### ISSUE TITLE
No rule to make target `libredex/PgoFiles.cpp',

### ISSUE THREAD

**Issue by desmond1121** [facebook/redex#102]
Hello, I meet this error message when executing `autoreconf -ivf && ./configure && make`.
```
Making install in .
make[1]: *** No rule to make target `libredex/PgoFiles.cpp', needed by `libredex/PgoFiles.lo'.  Stop.
make: *** [install-recursive] Error 1
```
os: osx 10.11.4
I've install dependencies & update submodule successfully.

**Comment by aiplay** [comment]
They has not modify makefile about PgoFiles while this file has been renamed, just search where use PgoFiles and modify to ConfigFiles.

**Comment by desmond1121** [comment]
@aiplay That's it, thank you:) Recent commits have done this rename.

**Comment by desmond1121** [comment]
@aiplay I've figure out the problem:

The commit `e266199` seems to forget change `PgoFiles.cpp` in Makefile, just change `PgoFiles.cpp` to `ConfigFiles.cpp` in `Makefile.am` and it would build success.

**Comment by tiffyangel89** [comment]
8179185498
