### ISSUE TITLE
redex-all is not found or is not executable

### ISSUE THREAD

**Issue by yang747046912** [facebook/redex#109]
I just run redex input.apk out.apk, and it gei me a log :redex-all is not found or is not executable

how can i fix it

**Comment by bunnyswe** [comment]
same problem ,on OSX

**Comment by 157688302** [comment]
same problem +1

**Comment by bertmaher** [comment]
Your command line should be: `redex input.apk -o out.apk`.

**Comment by vfaSonnt** [comment]
I run `./redex.py /Volumes/DATA/Desktop/input.apk -o /Volumes/DATA/Desktop/output.apk`

And same error redex-all is not found or is not executable

**Comment by justinjhendrick** [comment]
@vfaSonnt, could you please try `redex /Volumes/DATA/Desktop/input.apk -o /Volumes/DATA/Desktop/output.apk` and comment here if it doesn't work.
