### ISSUE TITLE
Is it possible to use this in Windows?

### ISSUE THREAD

**Issue by perphyyoung** [facebook/redex#11]

**Comment by mohamedmansour** [comment]
In Windows 10 you can :) It has Linux Subsystem for Linux!

**Comment by jp1017** [comment]
@mohamedmansour I used in Win10 preview, but I can't install it. 

![11](https://cloud.githubusercontent.com/assets/7868514/14484117/594134d6-0180-11e6-8ec6-0976595da68b.jpg)

>  subdirectory third-party/folly/folly not present

So, I run this command:
 `cd third-party/folly && mkdir folly`, 

and try again...

New error came to me:

![22](https://cloud.githubusercontent.com/assets/7868514/14484122/61b32106-0180-11e6-9bad-ea4c559fe816.jpg)

**Comment by bertmaher** [comment]
Try `git submodule update --init`  (you might need to revert your `mkdir folly`).  That said, best of luck getting this to work on Windows -- I'd love to merge PRs that help get us there, but we're only supporting Mac and (some) Linux platforms at the moment.

**Comment by jp1017** [comment]
@bertmaher I make it.
I install folly first and I send you PR.

**Comment by bertmaher** [comment]
Glad to hear it's somewhat working for you, but I don't want to advertise Windows support on our master branch.  We don't have the engineering resources to support it, nor do any of us run Windows, so it will likely break frequently.  We'll revisit this in the medium term if it's a *very* popular request.

**Comment by brian512** [comment]
we need it on windows,thx

**Comment by jjhesk** [comment]
We need it on windows thx. This is the only machine we got. Many thx

**Comment by juanmitr** [comment]
we need it on windows,thx

**Comment by migzisreallywewwhat** [comment]
some of us work in companies where they only provide windows machines. please consider adding windows support 👍  many thanks
