### ISSUE TITLE
error when make

### ISSUE THREAD

**Issue by wangchenghao** [facebook/redex#114]
/Applications/Xcode.app/Contents/Developer/usr/bin/make  libfollytestmain.la libgtest.la foreach_benchmark benchmark_test concurrent_skiplist_benchmark sorted_vector_types_test foreach_test hash_test timeout_queue_test conv_test range_test bits_test bit_iterator_test spin_lock_test small_locks_test packed_sync_ptr_test small_vector_test discriminated_ptr_test cpuid_test fbstring_test_using_jemalloc thread_cached_int_test thread_local_test fbvector_test dynamic_test json_test scope_guard_test endian_test rw_spinlock_test synchronized_test concurrent_skiplist_test histogram_test group_varint_test map_util_test string_test conditionally_existent_test producer_consumer_queue_test atomic_hash_array_test atomic_hash_map_test format_test fingerprint_test portability_test spooky_hash_v1_test spooky_hash_v2_test token_bucket_test thread_name_test indestructible_test futures_test function_test
make[4]: *** No rule to make target `gtest-1.7.0/src/gtest-all.cc', needed by `gtest-1.7.0/src/libfollytestmain_la-gtest-all.lo'.  Stop.
make[3]: *** [check-am] Error 2
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

**Comment by bertmaher** [comment]
Please show the exact sequence of commands you used to get to this point.

**Comment by wangchenghao** [comment]
@bertmaher Show these errors when I used the last command, "make check"

**Comment by FabianTerhorst** [comment]
Im getting a similar error when make 

```
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./configparser -I./include -I./liblocator -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/interdex -I./opt/local-dce -I./opt/peephole -I./opt/rebindrefs -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/unterface -I./third-party/folly -I./util --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/DexClass.lo -MD -MP -MF libredex/.deps/DexClass.Tpo -c libredex/DexClass.cpp  -fno-common -DPIC -o libredex/.libs/DexClass.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./configparser -I./include -I./liblocator -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/interdex -I./opt/local-dce -I./opt/peephole -I./opt/rebindrefs -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/unterface -I./third-party/folly -I./util --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/DexClass.lo -MD -MP -MF libredex/.deps/DexClass.Tpo -c libredex/DexClass.cpp -o libredex/DexClass.o >/dev/null 2>&1
make[2]: *** No rule to make target `libredex/DexDebugOpcode.cpp', needed by `libredex/DexDebugOpcode.lo'.  Stop.
make[1]: *** [all-recursive] 
```Error 1
make: *** [all] Error 2

**Comment by v1v** [comment]
Same error:
```bash
Making all in function_benchmark
make[5]: Nothing to be done for `all'.
Making all in .
make[2]: *** No rule to make target `libredex/DexDebugOpcode.cpp', needed by `libredex/DexDebugOpcode.lo'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Apparently `libredex/DexDebugOpcode.cpp` doesn't exist

**Comment by v1v** [comment]
Apparently it has been just fixed: 
da2850a

**Comment by FabianTerhorst** [comment]
yes the fix works

**Comment by bertmaher** [comment]
@wangchenghao , run `test/setup.sh` before running make check to get gtest.  Also note that you don't need to run `make check` to use redex.  It's mostly there for developers.
