### ISSUE TITLE
New error when building

### ISSUE THREAD

**Issue by shmuelr** [facebook/redex#115]
Hey,

Thanks for the prompt support and updates to this project.

I'm trying to use redex on a app that uses retrolamba so I pulled the latest source to build a new copy of redex now that the lamda bug was fixed.

When I run "autoreconf -ivf && ./configure && make && make install" I get this error:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./configparser -I./include -I./liblocator -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/interdex -I./opt/local-dce -I./opt/peephole -I./opt/rebindrefs -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/unterface -I./third-party/folly -I./util --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/DexClass.lo -MD -MP -MF libredex/.deps/DexClass.Tpo -c libredex/DexClass.cpp  -fno-common -DPIC -o libredex/.libs/DexClass.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./configparser -I./include -I./liblocator -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/interdex -I./opt/local-dce -I./opt/peephole -I./opt/rebindrefs -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/unterface -I./third-party/folly -I./util --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/DexClass.lo -MD -MP -MF libredex/.deps/DexClass.Tpo -c libredex/DexClass.cpp -o libredex/DexClass.o >/dev/null 2>&1
make[2]: *** No rule to make target `libredex/DexDebugOpcode.cpp', needed by `libredex/DexDebugOpcode.lo'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

OSX Yosemite 10.10.5
MacBook Pro Retina

**Comment by codeskraps** [comment]
I'm having the same issue on Ubunt 14.04 LTS

`make[2]: Entering directory `/opt/redex'
/bin/bash ./libtool  --tag=CXX   --mode=link g++ --std=gnu++11 -O3 -Wall -g -g -O2   -o libredex.la  configparser/keeprules.lo configparser/generated_files/parser.lo configparser/generated_files/tokenizer.lo liblocator/locator.lo libredex/ConfigFiles.lo libredex/Creators.lo libredex/Debug.lo libredex/DexAnnotation.lo libredex/DexClass.lo libredex/DexDebugOpcode.lo libredex/DexIdx.lo libredex/DexLoader.lo libredex/DexOpcode.lo libredex/DexOutput.lo libredex/DexUtil.lo libredex/JarLoader.lo libredex/PassManager.lo libredex/ProguardLoader.lo libredex/ProguardMap.lo libredex/ReachableClasses.lo libredex/RedexContext.lo libredex/RegAlloc.lo libredex/Resolver.lo libredex/Show.lo libredex/Trace.lo libredex/Transform.lo libredex/Vinfo.lo libredex/Warning.lo libredex/WorkQueue.lo libresource/FileMap.lo libresource/RedexResources.lo libresource/ResourceTypes.lo libresource/SharedBuffer.lo libresource/Static.lo libresource/String16.lo libresource/String8.lo libresource/TypeWrappers.lo libresource/Unicode.lo libresource/VectorImpl.lo opt/annoclasskill/AnnoClassKill.lo opt/annokill/AnnoKill.lo opt/bridge/Bridge.lo opt/delinit/DelInit.lo opt/delsuper/DelSuper.lo opt/final_inline/FinalInline.lo opt/interdex/InterDex.lo opt/local-dce/LocalDce.lo opt/peephole/Peephole.lo opt/rebindrefs/ReBindRefs.lo opt/remove_empty_classes/RemoveEmptyClasses.lo opt/renameclasses/RenameClasses.lo opt/shorten-srcstrings/Shorten.lo opt/simpleinline/Deleter.lo opt/simpleinline/Devirtualizer.lo opt/simpleinline/InlineHelper.lo opt/simpleinline/SimpleInline.lo opt/singleimpl/SingleImpl.lo opt/singleimpl/SingleImplAnalyze.lo opt/singleimpl/SingleImplOptimize.lo opt/singleimpl/SingleImplStats.lo opt/singleimpl/SingleImplUtil.lo opt/static-sink/StaticSink.lo opt/staticrelo/StaticRelo.lo opt/synth/Synth.lo opt/unterface/Unterface.lo opt/unterface/UnterfaceOpt.lo util/Sha1.lo -lboost_filesystem -lboost_system -lpthread third-party/folly/folly/libfolly.la -lz 
libtool: link: `libredex/DexDebugOpcode.lo' is not a valid libtool object
make[2]: *** [libredex.la] Error 1
make[2]: Leaving directory `/opt/redex'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/redex'
make: *** [all] Error 2
`

**Comment by SynteZZZ** [comment]
Same thing here.
Distributing product via master branch only is a bad idea. At least release branches/tags are required.

**Comment by v1v** [comment]
#114

**Comment by v1v** [comment]
Apparently it has been just fixed: 
https://github.com/facebook/redex/commit/da2850ae076151b7fa7d69103e261a411cbfa4a7

**Comment by shmuelr** [comment]
Bleeding edge... I love it 😄 

building now... will report back

**Comment by bertmaher** [comment]
So sorry about this -- I'm adding a precommit test to make sure the OSS build works before pushing an update.  Thanks for reporting it quickly.
