### ISSUE TITLE
Error opening method move file: No such file or directory

### ISSUE THREAD

**Issue by FabianTerhorst** [facebook/redex#116]
im getting Error opening method move file: No such file or directory when i try to redex path/apk.apk -o path/output.apk. I also tried absolute paths. The tests also fails 
```
mkdir -p synth-test-class
javac -d synth-test-class Alpha.java SynthTest.java
jar cf synth-test-class.jar -C synth-test-class .
dx --dex --output=synth-test-class.dex synth-test-class.jar
make[2]: dx: No such file or directory
make[2]: *** [synth-test-class.dex] Error 1
make[1]: *** [check-am] Error 2

```

**Comment by bertmaher** [comment]
Sorry about the method move thing, I just fixed that in [da2850a](https://github.com/facebook/redex/commit/da2850ae076151b7fa7d69103e261a411cbfa4a7), if you want to pull and try again.

For the `make check` thing, it looks like you don't have dx on your PATH.  If you want to run make check (you don't have to do that to use redex, it's mostly for developers), then add $ANDROID_SDK/build-tools/xx.y.z to your PATH.
