### ISSUE TITLE
autoreconf -ivf && ./configure && make error

### ISSUE THREAD

**Issue by MichaelLiu89** [facebook/redex#120]
when i execute autoreconf -ivf && ./configure && make，i got error:

./../folly/Malloc.h:138:36: error: expected body of lambda expression
  static const bool result = [] () FOLLY_MALLOC_NOINLINE noexcept {
                                   ^
./../folly/Malloc.h:121:31: note: expanded from macro 'FOLLY_MALLOC_NOINLINE'
#define FOLLY_MALLOC_NOINLINE __attribute__((__noinline__))

and my system is OS X Yosemite(version 10.10.5)
hope you can help me.

**Comment by bertmaher** [comment]
You probably need to upgrade Xcode to version >= 7.0
