### ISSUE TITLE
OSX compilation error: no matching constructor for initialization of 'ProguardMap'

### ISSUE THREAD

**Issue by bubbleguuum** [facebook/redex#121]
OSX El Capitan 10.11.4, latest Xcode, fresh git code as of today.

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./configparser -I./include -I./liblocator -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/interdex -I./opt/local-dce -I./opt/peephole -I./opt/rebindrefs -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/unterface -I./third-party/folly -I./util --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/ConfigFiles.lo -MD -MP -MF libredex/.deps/ConfigFiles.Tpo -c libredex/ConfigFiles.cpp  -fno-common -DPIC -o libredex/.libs/ConfigFiles.o
libredex/ConfigFiles.cpp:20:5: error: no matching constructor for initialization of 'ProguardMap'
    m_proguard_map(
    ^
./include/ProguardMap.h:34:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'fbstring' (aka 'basic_fbstring<char>') to 'ProguardMap' for 1st argument
struct ProguardMap {
       ^
./include/ProguardMap.h:34:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'fbstring' (aka 'basic_fbstring<char>') to 'const ProguardMap' for 1st argument
./include/ProguardMap.h:38:12: note: candidate constructor not viable: no known conversion from 'fbstring' (aka 'basic_fbstring<char>') to 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') for 1st
      argument
  explicit ProguardMap(const std::string& filename);
           ^
./include/ProguardMap.h:44:12: note: candidate constructor [with IStream = folly::basic_fbstring<char, std::__1::char_traits<char>, std::__1::allocator<char>, folly::fbstring_core<char> >] not viable: expects an l-value for 1st argument
  explicit ProguardMap(IStream& is) {
           ^

**Comment by bertmaher** [comment]
Ugh, sorry, someone broke our trunk.  Fix is pushing now.
