### ISSUE TITLE
Issue with: autoreconf -ivf && ./configure && make

### ISSUE THREAD

**Issue by squoraishee** [facebook/redex#122]
hecking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for clock_gettime... no
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for munmap... yes
checking for regcomp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating test/integ/Makefile
config.status: creating test/unit/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in third-party/folly/folly (/Users/foohs/Desktop/Tools/redex2/third-party/folly/folly)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
./configure: line 2248: config.log: Permission denied
./configure: line 2258: config.log: Permission denied
configure: error: ./configure failed for third-party/folly/folly

**This is part of the failure trace for when I run: [tried all variants - and with and without sudo]  Also tried running different combinations (separating) the  autoreconf, make and configure commands to no avail.**

sudo autoreconf -ivf && ./configure && make.

**Comment by bertmaher** [comment]
The only thing I can figure is that you used `sudo` when you grabbed folly with `git submodule update --init`, which you should not do.  Try deleting your repo and following the instructions in the README exactly, without adding sudo's where they aren't specified.
