### ISSUE TITLE
Running Redex error "Unknown secondary dex mode"

### ISSUE THREAD

**Issue by guochangmao** [facebook/redex#125]
I am using the redex on ubuntu 14.04.
executed command "redex XXX.apk -o XXX.apk ", some error happened,

Unknown secondary dex mode

Has anyone come with this error too??
Any comment will be appreciated.
Thanks.

**Comment by bertmaher** [comment]
Can you share the APK, or at least the output of `aapt list -v XXX.apk | grep dex`?  Redex has to know how to unpack all the dexes in an APK, which is usually a set of dexes in the root, but there are some other weird ways of packing.

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
