### ISSUE TITLE
java.lang.NoSuchMethodError after redex processing

### ISSUE THREAD

**Issue by smallfrogs** [facebook/redex#127]
HI

We are testing redex on some popular apps before using in our production environment.

We found some Google Play top apps have crashed after using redex, such as  https://play.google.com/store/apps/details?id=com.cleanmaster.mguard

Attached the logcat message:
05-03 09:47:34.132 17342 17359 E AndroidRuntime: Process: com.cleanmaster.mguard:service, PID: 17342
05-03 09:47:34.132 17342 17359 E AndroidRuntime: java.lang.NoSuchMethodError: No static method a(Lcom/cleanmaster/security/timewall/core/b;Lcom/cleanmaster/security/timewall/core/TimeWallDefine$EVENT_TYPE;Lcom/cleanmaster/security/timewall/core/e;ZJ)Z in class Llibcore/util/R; or its super classes (declaration of 'libcore.util.R' appears in /data/app/com.cleanmaster.mguard-1/base.apk:classes2.dex)
05-03 09:47:34.132 17342 17359 E AndroidRuntime:    at com.cleanmaster.security.scan.monitor.i.run(state1:39)
05-03 09:47:34.132 17342 17359 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
05-03 09:47:34.132 17342 17359 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
05-03 09:47:34.132 17342 17359 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:135)
05-03 09:47:34.132 17342 17359 E AndroidRuntime:    at android.os.HandlerThread.run(HandlerThread.java:61)

It is a bug in redex ?

**Comment by Iknewitbitch** [comment]
Oh really

**Comment by justinjhendrick** [comment]
Unfortunately, redex without any configuration often deletes or renames methods you needed. In general, you should try to specify "-keep" in your proguard config to tell redex not to delete or rename it.

closing due to age
