### ISSUE TITLE
autoreconf -ivf && ./configure && make && make install

### ISSUE THREAD

**Issue by williamsim** [facebook/redex#128]
Bits.cpp: Assembler messages:
Bits.cpp:48: Error: invalid instruction suffix for `popcnt'
Makefile:1424: recipe for target 'Bits.lo' failed
make[4]: *** [Bits.lo] Error 1
make[4]: Leaving directory '/home/tonlin/redex/third-party/folly/folly'
Makefile:1483: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/tonlin/redex/third-party/folly/folly'
Makefile:926: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/tonlin/redex/third-party/folly/folly'
Makefile:1255: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tonlin/redex'
Makefile:587: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bertmaher** [comment]
Strang, I've never seen something like that.  What's your compiler version (`g++ -v`).

**Comment by williamsim** [comment]
@bertmaher 
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)

**Comment by codeskraps** [comment]
I'm having the same similar issue:

> cp ./redex.py redex
> chmod +x redex
> make[2]: Leaving directory `/opt/redex'
> Making all in test
> make[2]: Entering directory `/opt/redex/test'
> Making all in .
> make[3]: Entering directory `/opt/redex/test'
> make[3]: Nothing to be done for `all-am'.
> make[3]: Leaving directory `/opt/redex/test'
> Making all in integ
> make[3]: Entering directory `/opt/redex/test/integ'
> make[3]: Nothing to be done for `all'.
> make[3]: Leaving directory `/opt/redex/test/integ'
> Making all in unit
> make[3]: Entering directory `/opt/redex/test/unit'
> make[3]: Nothing to be done for `all'.
> make[3]: Leaving directory `/opt/redex/test/unit'
> make[2]: Leaving directory `/opt/redex/test'
> make[1]: Leaving directory `/opt/redex'
> Making install in third-party/folly/folly
> make[1]: Entering directory `/opt/redex/third-party/folly/folly'
> Making install in .
> make[2]: Entering directory `/opt/redex/third-party/folly/folly'
> make[3]: Entering directory `/opt/redex/third-party/folly/folly'
>  /bin/mkdir -p '/usr/local/lib'
>  /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfolly.la libfollybenchmark.la '/usr/local/lib'
> libtool: install: /usr/bin/install -c .libs/libfolly.so.57.0.0 /usr/local/lib/libfolly.so.57.0.0
> /usr/bin/install: cannot remove '/usr/local/lib/libfolly.so.57.0.0': Permission denied
> make[3]: *** [install-libLTLIBRARIES] Error 1
> make[3]: Leaving directory `/opt/redex/third-party/folly/folly'
> make[2]: *** [install-am] Error 2
> make[2]: Leaving directory `/opt/redex/third-party/folly/folly'
> make[1]: *** [install-recursive] Error 1
> make[1]: Leaving directory `/opt/redex/third-party/folly/folly'
> make: *** [install-recursive] Error 1

Output of:

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by codeskraps** [comment]
Running:

$ autoreconf -ivf && ./configure && make && make install

as root solved the problem.

**Comment by bertmaher** [comment]
@codeskraps, that's a different problem; you have to `sudo make install` to install programs in /usr/local.  The other steps should ideally _not_ be run as root (it doesn't really hurt anything, it's just not necessary and makes permissions a bit more annoying).

**Comment by bertmaher** [comment]
Oh, I see the problem.  You're on a 32-bit OS.  It's not really a supported version right now, though it's plausible it could be in the future.
