### ISSUE TITLE
checking for main in -ldouble-conversion... no

### ISSUE THREAD

**Issue by hljwang3874149** [facebook/redex#13]
on mac 10.11.3
Warning: boost-1.58.0 already installed
Warning: double-conversion-1.1.5 already installed
Warning: gflags-2.1.2 already installed
Warning: glog-0.3.4 already installed
Warning: libevent-2.0.22 already installed

 i  download  double-conversion  in /usr/local/Cellar/double-conversion
but can't found it . why?

**Comment by JohnnyYin** [comment]
I've had the same problem.

**Comment by bertmaher** [comment]
To make sure you have double-conversion properly linked, can you do:
```
ls /usr/local/include/double-conversion 
ls /usr/local/lib/libdouble-conversion.a
```
and check that those actually exist?
If not try `brew link double-conversion`, or possible `brew link --force double-conversion`

**Comment by hljwang3874149** [comment]
actually exist
bignum.h		double-conversion.h	ieee.h
cached-powers.h		fast-dtoa.h		strtod.h
diy-fp.h		fixed-dtoa.h		utils.h
localhost:double-conversion wangxiaolong$ ls /usr/local/lib/libdouble-conversion.a
/usr/local/lib/libdouble-conversion.a

**Comment by bertmaher** [comment]
Ah, I think our configure check for double-conversion might be kinda broken even though it works on my dev box.  I'll push an update.
