### ISSUE TITLE
fatal error: folly/folly-config.h: No such file or directory

### ISSUE THREAD

**Issue by wkq87** [facebook/redex#131]
Hi 
   I try to compile redex 
`./test/setup.sh
cd test
make check`
and here is the error

> In file included from ../../third-party/folly/folly/Portability.h:23:0,
                 from ../../third-party/folly/folly/FBString.h:52,
                 from ../../third-party/folly/folly/dynamic.h:77,
                 from ../../third-party/folly/folly/json.h:45,
                 from SynthTest.cpp:18:
../../third-party/folly/folly/portability/Config.h:20:32: fatal error: folly/folly-config.h: No such file or directory
compilation terminated.

how to solute this problem?

**Comment by bertmaher** [comment]
Don't bother with make check; it's only for developers.
