### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by oscarHuang** [facebook/redex#132]
hi, after running the command, I got this error info:

Assertion failed: (intf_cls->get_ifields().size() == 0), function escape_with_sfields, file opt/singleimpl/SingleImplAnalyze.cpp, line 208.
0   redex-all                           0x000000010d140f94 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff8defcf1a _sigtramp + 26
2   ???                                 0x000000010df40a00 0x0 + 4529064448
3   libsystem_c.dylib                   0x00007fff9bb069ab abort + 129
4   libsystem_c.dylib                   0x00007fff9bacea91 basename + 0
5   redex-all                           0x000000010d1dc7bc _ZN12AnalysisImpl19escape_with_sfieldsEv + 236
6   redex-all                           0x000000010d1dc3c0 _ZN12AnalysisImpl18create_single_implERKNSt3__113unordered_mapIP7DexTypeS3_NS0_4hashIS3_EENS0_8equal_toIS3_EENS0_9allocatorINS0_4pairIKS3_S3_EEEEEERKNS0_13unordered_setIS3_S5_S7_NS8_IS3_EEEERK16SingleImplConfig + 240
7   redex-all                           0x000000010d1dd322 _ZN18SingleImplAnalysis7analyzeERKNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEER10DexClassesRKNS0_13unordered_mapIP7DexTypeSD_NS0_4hashISD_EENS0_8equal_toISD_EENS4_INS0_4pairIKSD_SD_EEEEEERKNS0_13unordered_setISD_SF_SH_NS4_ISD_EEEERK16SingleImplConfig + 82
8   redex-all                           0x000000010d1da2be _ZN14SingleImplPass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 558
9   redex-all                           0x000000010d16725a _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER11ConfigFiles + 378
10  redex-all                           0x000000010d13326b main + 2267
11  libdyld.dylib                       0x00007fff926d05c9 start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 788, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 744, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 115, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmp7147u10a.redex_extracted_apk --outdir /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex0/classes.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex1/classes2.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex2/classes3.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex3/classes4.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex4/classes5.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex5/classes6.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex6/classes7.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex7/classes8.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex8/classes9.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex9/classes10.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex10/classes11.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex11/classes12.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex12/classes13.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex13/classes14.dex /var/folders/r8/qrwwrvld6_d722lf4f9gsp000000gq/T/tmpftzwpgjs.redex_dexen/dex14/classes15.dex' returned non-zero exit status -6

any clue? Thanks a lot

**Comment by dariorussi** [comment]
that code was assuming no instance fields could be defined on an interface. And that is what the assert is.
Could you give us the "offending" java code? that would be the interface in question.

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
