### ISSUE TITLE
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir 

### ISSUE THREAD

**Issue by wisly33230** [facebook/redex#136]
please help!
wisly@wisly-ThinkPad-T440p:~/redex$ redex -o /home/wisly/app/appredex.apk -P /home/wisly/app/proguard-rules.pro /home/wisly/app/app.apk 
 on line 1 token 
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 788, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 744, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 115, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /tmp/tmp_bs86b5n.redex_extracted_apk --outdir /tmp/tmp8kard3sg.redex_dexen --proguard-config /home/wisly/app/proguard-rules.pro /tmp/tmp8kard3sg.redex_dexen/dex0/classes.dex' returned non-zero exit status 1

**Comment by wisly33230** [comment]
problem resolved ! the args for proguard-rules.pro is -p not -P ,then  it is OK

**Comment by int3** [comment]
Cool, looks like you figured it out
