### ISSUE TITLE
Size is not changed

### ISSUE THREAD

**Issue by jemshit** [facebook/redex#137]
It was 65.2mb and became 64.9mb. Other apk examples: 
19mb -> 18.6mb
8.5mb -> 8.3mb

I don't see obvious change on size. Is it normal?

**Comment by WizKid** [comment]
You should compare the dex files that are inside the APK. Those are the only files that get smaller

**Comment by int3** [comment]
Yup, what @WizKid said. The APK contains lots of non-DEX files too.
