### ISSUE TITLE
openssl/evp.h'  file not found

### ISSUE THREAD

**Issue by ijustyce** [facebook/redex#14]
i install python3.5.1 ,but build error, here is the error log

In file included from io/async/AsyncPipe.cpp:16:
In file included from ./../folly/io/async/AsyncPipe.h:18:
In file included from ./../folly/io/async/AsyncTransport.h:26:
./../folly/io/async/ssl/OpenSSLPtrTypes.h:20:10: fatal error: 'openssl/evp.h'
      file not found
#include <openssl/evp.h>
         ^
2 warnings and 1 error generated.
make[4]: *** [io/async/AsyncPipe.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

how to fix this, thanks

**Comment by bertmaher** [comment]
Looks like issue #7.  Try `brew install openssl && brew link --force openssl`

**Comment by ijustyce** [comment]
i solve it by sudo brew link openssl --force , but appears other error， here is the error log， and my os is mac 10.11.4

./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);
           ^
1 error generated.
make[4]: *** [portability/Malloc.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by bertmaher** [comment]
It looks like there's a bug in folly on OSX -- you can fix it by going to third-party/folly/folly/portability/Malloc.h and adding `#include <stddef.h>`.  I'll see if I can get folly patched tomorrow.

**Comment by ijustyce** [comment]
@bertmaher thank you，but when i run `redex app-android_test-debug.apk -o ./app-1.apk` in terminal , it tell me : Optimization warning: Pure abstract class passed to encode: 12 occurrences
Couldn't find zipalign.  Your APK may not be fully optimized.    how to fix 'Couldn't find zipalign' thanks in advance

**Comment by ratm** [comment]
@ijustyce zipalign is part for the build tools from the Android SDK, make sure it's in your PATH.

**Comment by bertmaher** [comment]
The "optimization warning" is no problem (it's more for us developers, I probably should have disabled it).  The zipalign thing is an optimization step that's usually done by the default toolchain -- you can fix that by adding zipalign to your path, so for example, I have my android SDK tools installed at `/opt/android_sdk/build-tools/23.0.3`, so I'd do:
```
export PATH=/opt/android_sdk/build-tools/23.0.3:$PATH
```
before running redex.

**Comment by ijustyce** [comment]
thanks, it make my app less 0.3M

**Comment by rekire** [comment]
IMHO this should not been closed since this is still broken
