### ISSUE TITLE
Out-of-bounds vector access in MethodTransform::sync_all()

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#143]
In MethodTransform::sync_all(), the following statement causes an error when the vector of transformations is empty: 

  wq.run_work_items(&workitems[0], (int)workitems.size());

Inserting a guard after populating 'transforms' solves the problem:

  if (transforms.size() == 0) {
    return;
  }

**Comment by satnam6502** [comment]
I've created an internal task for this.

**Comment by satnam6502** [comment]
Oh, and thank you very much for reporting this!

**Comment by satnam6502** [comment]
We're having problems trying to repo this. Can you provide a bit more context for a repo? Thanks.

**Comment by arnaudvenet** [comment]
The problem occurred when I disabled all optimization passes so as to test the code generation path 'Dex -> Internal Representation -> Dex'. I wanted to evaluate the sheer impact of going through the internal representation on the Dex file size.

**Comment by satnam6502** [comment]
That's interesting. I often run redex with an empty passes config (`passes = []`) and this has always worked for me. Did you disable the optimizations from the config file?

**Comment by arnaudvenet** [comment]
No, I disabled the passes manually in 'main.cpp'. Something I forgot to mention is that I compiled the tool using Clang.

**Comment by satnam6502** [comment]
Interesting. I debug using XCode which also compiled with Clang.

**Comment by arnaudvenet** [comment]
As a sanity check, I just tried it again and I get the same crash. I commented out the code building the default configuration in 'main.cpp'.

**Comment by bertmaher** [comment]
This has been fixed.
