### ISSUE TITLE
Installation error: Please install jsoncpp

### ISSUE THREAD

**Issue by sincerekamal** [facebook/redex#145]
Hi Team,
I'm trying to install Redex in my Mac OSX(El Captain) using the tutorial given in http://fbredex.com/ . But I get this error. 

<img width="528" alt="screen shot 2016-06-03 at 1 50 36 am" src="https://cloud.githubusercontent.com/assets/3885228/15759733/a6ab8454-292d-11e6-98b2-0f7af3601de5.png">

I tried installing 
````brew install jsoncpp````

It shows jsoncpp is already installed

**Comment by mlimb** [comment]
I'm having the same issue. Tried installing, but to no avail.

**Comment by dkmeteor** [comment]
+1

**Comment by Redapptz** [comment]
Same issue

**Comment by chicheng** [comment]
`sudo apt-get install libjsoncpp-dev` works for me on Ubuntu 14.04

**Comment by dkmeteor** [comment]
brew install jsoncpp
Warning: jsoncpp-0.10.5 already installed

---
jsoncpp is already installed.
OS X EI Capitan 10.11.2

**Comment by marukami** [comment]
Try `brew update && brew upgrade jsoncpp` the current version I get is `1.6.5`

**Comment by marukami** [comment]
Also, the jsoncpp is missing from the dependencies list on http://fbredex.com/

**Comment by dkmeteor** [comment]
@marukami 
https://github.com/open-source-parsers/jsoncpp
This one?
The latest version is 0.10.6.

I have tryed `brew upgrade jsoncpp `
`
git:(master) brew upgrade jsoncpp
Error: jsoncpp 0.10.5 already installed`

I think 0.10.5 maybe the latest release on brew.

Where can i get 1.6.5?

**Comment by pollux-** [comment]
droid-2:redex SPARK$ brew install jsoncpp
Warning: jsoncpp-1.6.5 already installed
same issue, how to solve this

**Comment by marukami** [comment]
That looks like it. The latest I found was `1.7.2` https://github.com/open-source-parsers/jsoncpp/tree/1.7.2. Brew tends to lag a bit. This is the `.rb` 

My setup is 
`brew info jsoncpp` gives https://github.com/Homebrew/homebrew-core/blob/master/Formula/jsoncpp.rb 
I'm using Homebrew `0.9.9`

Try `brew uninstall jsoncpp` and check `brew doctor` for any issue that might be there. Otherwise, you could clone and build from tag 1.6.5

**Comment by dkmeteor** [comment]
@marukami  
Thanks. 

My home brew version is 0.9.5

>  git:(master) brew info jsoncpp
>jsoncpp: stable 0.10.5 (bottled), HEAD
>Library for interacting with JSON
>https://github.com/open-source-parsers/jsoncpp
>/usr/local/Cellar/jsoncpp/0.10.5 (20 files, 640K) *
>  Poured from bottle
>From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jsoncpp.rb

After update brew to 0.9.9, brew can find jsoncpp:1.6.5.

> ➜  Documents brew info jsoncpp
jsoncpp: stable 1.6.5 (bottled), HEAD
Library for interacting with JSON
https://github.com/open-source-parsers/jsoncpp
/usr/local/Cellar/jsoncpp/0.10.5 (22 files, 583.2K)
  Poured from bottle on 2016-06-12 at 18:34:33
/usr/local/Cellar/jsoncpp/1.6.5 (22 files, 604.0K) *
  Poured from bottle on 2016-06-17 at 17:31:02
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jsoncpp.rb

**Comment by avsynaidu** [comment]
+1, same issue

**Comment by bertmaher** [comment]
Thanks for reporting, I updated fbredex.com to mirror the README in the repo.

**Comment by netfishx** [comment]
+1, same issue

**Comment by netfishx** [comment]
+1, same issue

**Comment by denversc** [comment]
I was able to fix this issue on Mac OS X El Capitan 10.11.4 by simply installing the Xcode command-line tools, as instructed in README.md:

    xcode-select --install

I had assumed that they were already installed so skipped this step in the setup.  After running the command the compilation completes successfully.

**Comment by sincerekamal** [comment]
@denversc  At last  your solution worked for me !! great !! 👍

**Comment by maniramezan** [comment]
@denversc worked for me on macOS Sierra and having both xcode 8 and 7.3.1

**Comment by xoder-me** [comment]
@denversc it‘s worked for me. THX 

macOS 10.12.1 & Xcode 8.0

**Comment by wangchauyan** [comment]
@denversc  thanks, it saves my day, and i found that this had been documented at README file as well.
