### ISSUE TITLE
Signedness issue in loop condition

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#146]
In file tools/redex-all/main.cpp, the command-line argument parsing loop is structured as follows:

```
char c;
...
while ((c = getopt_long(
            argc, argv, ":a:c:o:w:p:S::J::", &options[0], nullptr)) != -1) { ... }
```

If the compiler interprets the 'char' type as 'unsigned char' in its default settings, the user might be in for a very puzzling crash (I was). It would be safer to declare the variable 'c' as 'signed char'.

**Comment by bertmaher** [comment]
Thanks for reporting.  I think the issue is that getopt_long actually returns an int, not a char.  Fix incoming.

**Comment by arnaudvenet** [comment]
FYI, there's the same issue in 'RedexDump.cpp'.
