### ISSUE TITLE
./include/ConfigFiles.h:17:10: fatal error: 'json/json.h' file not found  

### ISSUE THREAD

**Issue by ajay2034** [facebook/redex#151]
After **autoreconf -ivf && ./configure && make** running  i am getting 

In file included from libredex/ConfigFiles.cpp:10:
./include/ConfigFiles.h:17:10: fatal error: 'json/json.h' file not found
#include <json/json.h>
         ^
1 error generated.
make[1]: *** [libredex/ConfigFiles.lo] Error 1
make: *** [install-recursive] Error 1

**Comment by 411805662** [comment]
same error

**Comment by int3** [comment]
Did you install libjson?

**Comment by bertmaher** [comment]
I've updated the README and the instructions on fbredex.com.

**Comment by damien5314** [comment]
Hmm.. I'm getting the same error on Mac OSX 10.12.5. I seem to already have jsoncpp-1.8.0 (probably from installing dependencies in the previous step).

```
~/GitHub/redex ᐅ brew install boost double-conversion gflags glog libevent jsoncpp

Warning: boost-1.64.0_1 already installed
Warning: double-conversion-1.1.5 already installed
Warning: gflags-2.2.0 already installed
Warning: glog-0.3.5_1 already installed
Warning: libevent-2.1.8 already installed
Warning: jsoncpp-1.8.0 already installed
```
Any idea?
