### ISSUE TITLE
AttributeError: 'module' object has no attribute 'which'

### ISSUE THREAD

**Issue by ShrutiSarraf** [facebook/redex#152]
On running the command:
python redex.py hello.apk -o hello_redex.apk

I'm getting the following issue:
Traceback (most recent call last):
  File "redex.py", line 797, in <module>
    run_redex(args)
  File "redex.py", line 752, in run_redex
    dexen)
  File "redex.py", line 77, in run_pass
    executable_path = shutil.which('redex-all')
AttributeError: 'module' object has no attribute 'which'

Any idea?

**Comment by int3** [comment]
https://docs.python.org/3/library/shutil.html#shutil.which was only introduced in python 3.3, so I'm fairly certain you're running an older version. Try upgrading your Python. Feel free to reopen if you're still stuck
