### ISSUE TITLE
Virtual classes without virtual destructors

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#155]
Classes PositionMapper (include/DexPosition.h) and Token (include/ProguardLexer.h) have virtual methods but do not declare a virtual destructor. In particular, the absence of a virtual destructor in Token causes a crash during cleanup in ProguardLexerTest.cpp (mismatch between the declared and actual size of the object in a delete operation).

**Comment by dcolascione** [comment]
How did that ever work?

**Comment by dcolascione** [comment]
Also, -Weff-c++?

**Comment by arnaudvenet** [comment]
Class DexDebugInstructionReader in 'tools/redexdump/DumpTable.cpp' has the same issue.

**Comment by int3** [comment]
PRs definitely welcome. (We should also set up a linter to catch these sorts of things...)

**Comment by bertmaher** [comment]
Huh, apparently clang (at least clang 7.3 on osx) doesn't include -Wnon-virtual-dtor in -Wall.  Blah.  Bummer.

**Comment by int3** [comment]
Closed by fc4bdca39cf8.
