### ISSUE TITLE
Issue with ShortenSrcStringsPass and Fabric (Crashlytics)

### ISSUE THREAD

**Issue by udbhav3000** [facebook/redex#156]
Because of filenames being changed by ShortenSrcStringsPass, the report for crashes shown in Fabric gets difficult to read.

PFA two screenshots for with and without ShortenSrcStringsPass. 

<img width="1109" alt="without shortensrcstringspass" src="https://cloud.githubusercontent.com/assets/1161811/16695306/abdd156e-455c-11e6-8d75-b5190f94613d.png">
**Without ShortenSrcStringsPass**

<img width="1098" alt="with shortensrcstringspass" src="https://cloud.githubusercontent.com/assets/1161811/16695305/abdd4d54-455c-11e6-8772-846937f379ae.png">
**With ShortenSrcStringsPass**

The generate filename_mappings.txt is correctly generated. Any way to import the generated filename_mappings.txt into Fabric so that it understands the crash reports? 

Also what would be impact to the app if ShortenSrcStringsPass is not used?

**Comment by int3** [comment]
No idea how Fabric works, but internally we have our own symbolicator / demangling code in our crash analyzer.

> Also what would be impact to the app if ShortenSrcStringsPass is not used?

You'll have more strings and therefore a larger APK.
