### ISSUE TITLE
[Testability] How to measure decreased installation / start time / cold start time?

### ISSUE THREAD

**Issue by tabishjaved03** [facebook/redex#158]
This is not an issue but rather a discussion request. I just didn't know where to ask, hence posting here.

I would just like to know how can we determine reduced installation/start time/cold start time.

So far i have come across two ways:
1) adb logcat -s ActivityManager:I | grep Displayed
2) Method Profiling Using Traceview

Is there any other way? Or which one of these is more accurate. What are you guys using?

Any help would be appreciated. Thanks:-)

**Comment by justinjhendrick** [comment]
We have some internal tools we use to measure all sorts of things.
