### ISSUE TITLE
Issue while compiling 

### ISSUE THREAD

**Issue by jeyaprakash** [facebook/redex#160]
When i execute the command **autoreconf -ivf && ./configure && make**  getting following error
with OS yosomite 10.10.5 . Could any one help me?

opt/rebindrefs/ReBindRefs.cpp:120:3: error: defaulted default constructor of 'RefStats' cannot
      be used by non-static data member initializer which appears before end of class
      definition
  Rebinder(Scope& scope) : m_scope(scope) {}
  ^
opt/rebindrefs/ReBindRefs.cpp:120:3: error: defaulted default constructor of 'RefStats' cannot
      be used by non-static data member initializer which appears before end of class
      definition
2 errors generated.
make[2]: *** [opt/rebindrefs/ReBindRefs.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by int3** [comment]
What compiler version are your using?

**Comment by jeyaprakash** [comment]
Hello int3,

Using 4.2.1 version

<img width="916" alt="screen shot 2016-07-18 at 09 47 50" src="https://cloud.githubusercontent.com/assets/5215595/16908550/dd0f90cc-4ccc-11e6-8369-226727df39bc.png">

**Comment by int3** [comment]
Try upgrading your compiler. Here's mine:

```
redex: gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by wanderingGuy** [comment]
have you sovled this problem,I meet the same problem now...

**Comment by bertmaher** [comment]
Check your compiler version -- we're on Apple LLVM 7.3.0

**Comment by bertmaher** [comment]
This is an issue with older (3.5.1 and before) LLVM versions.  Please upgrade to the latest Xcode.
