### ISSUE TITLE
Use std::string in ProguardLexer

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#161]
All uses of the type 'string' in Redex are fully qualified as 'std::string'. However, this is not the case in the files ProguardLexer.h and ProguardLexer.cpp. Would it be possible to qualify all instances of the 'string' type in those two files?

Background: We have our own implementation of strings alongside 'std::string' and this causes a compilation error ("reference to 'string' is ambiguous"). I have to manually qualify all occurrences of 'string' in those two files whenever I install a new version of Redex.

**Comment by int3** [comment]
Seems like a reasonable request. cc @satnam6502 -- I think he wrote most of that code

**Comment by arnaudvenet** [comment]
Thanks!!
