### ISSUE TITLE
Couldn`t find zipalign ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ishaan1995** [facebook/redex#168]
I am not able to execute the redex command due to the error:
Couldn't find zipalign. See README.md to resolve this
I have set zipalign in my path variable.Even tried the command
"ANDROID_SDK=/home/ishaan/Android/Sdk redex /home/ishaan/app-debug.apk -o /home/ishaan/facebook-redux/ " but same result
I have my android sdk at - /home/username/Android/Sdk and have working sdk commands.I am using ubuntu 16.04. Whats the issue?

**Comment by bertmaher** [comment]
Can you paste the output of `which zipalign` and `find /home/ishaan/Android/Sdk -name zipalign`?  Thanks.

**Comment by ishaan1995** [comment]
#Output
which zip align -> 
/home/ishaan/Android/Sdk/build-tools/23.0.3/zipalign

find /home/ishaan/Android/Sdk -name zipalign ->

/home/ishaan/Android/Sdk/build-tools/19.1.0/zipalign
/home/ishaan/Android/Sdk/build-tools/24.0.0/zipalign
/home/ishaan/Android/Sdk/build-tools/23.0.1/zipalign
/home/ishaan/Android/Sdk/build-tools/23.0.3/zipalign
/home/ishaan/Android/Sdk/build-tools/23.0.2/zipalign
/home/ishaan/Android/Sdk/build-tools/22.0.1/zipalign
/home/ishaan/Android/Sdk/build-tools/20.0.0/zipalign
/home/ishaan/Android/Sdk/build-tools/21.1.2/zipalign

**Comment by ishaan1995** [comment]
Sorry it was some problem with my bash, after some clean up updating, it worked flawlessly.
Thanks for the info btw!

**Comment by rantianhua** [comment]
I have the same problem, i want to know how you clean up your bash? I haven't solved it yet!
