### ISSUE TITLE
Can't find the pyredex module

### ISSUE THREAD

**Issue by qingye** [facebook/redex#169]
chris:Redex chris$ redex testapk/test.apk -o testapk/output.apk
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 30, in <module>
    import pyredex.unpacker as unpacker
ImportError: No module named 'pyredex'

**Comment by chicheng** [comment]
`export PYTHONPATH=.` on redex folder works for me.

**Comment by whenasmile** [comment]
楼上，是要配置python环境变量为redex目录吗？

**Comment by qingye** [comment]
@chicheng Thanks, I solve it.

**Comment by addelll** [comment]
how can i export in Mac?

**Comment by qingye** [comment]
@addelll 
open .bash_profile and add Env. below:
export PYTHONPATH=/Users/your username/Desktop/Facebook/Redex
export PATH=$PATH:${PYTHONPATH}
then will be ok!

**Comment by addelll** [comment]
the same "Traceback (most recent call last):
  File "/usr/local/bin/redex", line 30, in <module>
    import pyredex.unpacker as unpacker
ImportError: No module named 'pyredex'"
