### ISSUE TITLE
Bogus line encountered in proguard map:     java.lang.String ƒKEY_FILTER -> ƒKEY_FILTER

### ISSUE THREAD

**Issue by abhishesh-srivastava** [facebook/redex#172]
libredex/ProguardMap.cpp:135: void ProguardMap::parse_proguard_map(std::istream &): assertion `false' failed.
Bogus line encountered in proguard map:     java.lang.String ƒKEY_FILTER -> ƒKEY_FILTER

0   redex-all                           0x000000010ba69a94 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff8fc5f52a _sigtramp + 26
2   ???                                 0x000000010bca3800 0x0 + 4492769280
3   libsystem_c.dylib                   0x00007fff9abb637b abort + 129
4   redex-all                           0x000000010ba69a51 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x000000010ba9d8d8 _ZN11ProguardMap18parse_proguard_mapERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEE + 632
6   redex-all                           0x000000010ba9d456 _ZN11ProguardMapC2ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 646
7   redex-all                           0x000000010ba6859a _ZN11ConfigFilesC2ERKN4Json5ValueE + 106
8   redex-all                           0x000000010ba5e4af main + 4095
9   libdyld.dylib                       0x00007fff9916e5ad start + 1
10  ???                                 0x0000000000000008 0x0 + 8
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 490, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 438, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 107, in run_pass
    subprocess.check_call(args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 581, in check_call

redex fails with above mentioned logs

**Comment by abhishesh-srivastava** [comment]
proguard mapping contains following lines which causes problem
com.moengage.ActionMapperConstants -> com.moengage.ActionMapperConstants:
    java.lang.String ACTION_NAVIGATE -> ACTION_NAVIGATE
    java.lang.String ACTION_DISMISS -> ACTION_DISMISS
    java.lang.String ACTION_TRACK_ATTR -> ACTION_TRACK_ATTR
    java.lang.String ACTION_SHARE -> ACTION_SHARE
    java.lang.String ACTION_CALL -> ACTION_CALL
    java.lang.String ACTION_COPY -> ACTION_COPY
    java.lang.String ACTION_SET_ATTRIBUTE -> ACTION_SET_ATTRIBUTE
    java.lang.String ACTION_OPEN_IN_APP -> ACTION_OPEN_IN_APP
    java.lang.String ACTION_REMIND_EXACT -> ACTION_REMIND_EXACT
    java.lang.String ACTION_REMIND_INEXACT -> ACTION_REMIND_INEXACT
    java.lang.String KEY_VALUE -> KEY_VALUE
    java.lang.String KEY_VALUE_OF -> KEY_VALUE_OF
    **java.lang.String ƒKEY_FILTER -> ƒKEY_FILTER**
    java.lang.String KEY_MESSAGE -> KEY_MESSAGE
    java.lang.String KEY_EMAIL -> KEY_EMAIL
    java.lang.String KEY_SCREEN -> KEY_SCREEN
    java.lang.String KEY_EXTRA -> KEY_EXTRA
    java.lang.String KEY_CAMPAIGN_ID -> KEY_CAMPAIGN_ID
    java.lang.String KEY_TRACK -> KEY_TRACK
    java.lang.String KEY_URI -> KEY_URI
    java.lang.String KEY_GCM_ACTION -> KEY_GCM_ACTION
    java.lang.String KEY_ACTION_TAG -> KEY_ACTION_TAG
    java.lang.String KEY_ACTION_TITLE -> KEY_ACTION_TITLE
    java.lang.String KEY_ACTION_ICON -> KEY_ACTION_ICON
    java.lang.String KEY_ACTION_ID -> KEY_ACTION_ID
    java.lang.String KEY_ACTION_PAYLOAD -> KEY_ACTION_PAYLOAD
    java.lang.String KEY_VALUE_TYPE -> KEY_VALUE_TYPE
    java.lang.String KEY_CONTENT -> KEY_CONTENT
    java.lang.String KEY_SET -> KEY_SET
    java.lang.String ACTION_SNOOZE_TIME -> ACTION_SNOOZE_TIME
    java.lang.String ACTION_SNOOZE_TODAY -> ACTION_SNOOZE_TODAY
    java.lang.String ACTION_SNOOZE_TOMORROW -> ACTION_SNOOZE_TOMORROW
    java.lang.String KEY_RENOTIFY -> KEY_RENOTIFY
    java.lang.String IMG_ID -> IMG_ID
    java.lang.String IMG_URL -> IMG_URL
    java.lang.String IMG_ACTION_NEXT -> IMG_ACTION_NEXT
    java.lang.String IMG_ACTION_PREV -> IMG_ACTION_PREV
    java.lang.String IMG_INDEX -> IMG_INDEX
    java.lang.String CAROUSEL_AUTOSTART -> CAROUSEL_AUTOSTART

**Comment by kgsharma** [comment]
Hi abhishek, proguard map is not needed for operation of redex. So, there are two workarounds. First, not use unicode characters in fields, methods, etc if you want to use proguard map. Second, don't use proguard map at all.

**Comment by kgsharma** [comment]
Hi abhishek, proguard map is not needed for operation of redex. So, there are two workarounds. First, not use unicode characters in fields, methods, etc if you want to use proguard map. Second, don't use proguard map at all.

**Comment by dcolascione** [comment]
This report is about a real bug in the method parsing routines, which (after peeking at them just now) expect ASCII. (They could also be implemented much more succinctly with boost regex or something like that.) Leave the bug open if you want, but don't close it with a "you're holding it wrong" message. Java and Android support the full range of Unicode characters.

**Comment by kgsharma** [comment]
Okay, reopening this issue. But, this will be taken not in the near-term.

**Comment by bertmaher** [comment]
Should be fixed by https://github.com/facebook/redex/commit/d22646a232c3eb2d17ab6f73486d5db35b01b2dc, lmk if it's still a problem.
