### ISSUE TITLE
The '-s' command-line argument is not parsed

### ISSUE THREAD

**Issue by arnaudvenet** [facebook/redex#175]
In tools/redex-all/main.cpp:

```
  while ((c = getopt_long(
              argc, argv, ":a:c:o:w:p:S::J::", &options[0], nullptr)) != -1) 
```

The string argument is missing an entry for the '-s' option, which causes the program to abort when a seed file is passed on the command line.

**Comment by bertmaher** [comment]
Thanks for pointing this out!  I'll try to get this fixed today.  In the meantime as a workaround you can specify --seeds, since the long form arg should be parsed correctly.

**Comment by bertmaher** [comment]
Should be fixed by https://github.com/facebook/redex/commit/1da2d021012e1733287b507241f6c69db509a2a9, let me know if it's still broken.

**Comment by arnaudvenet** [comment]
Thanks a lot! Everything works fine.
