### ISSUE TITLE
problem with firebase

### ISSUE THREAD

**Issue by alexodus** [facebook/redex#178]
I've this runtimeException:

`10-06 13:58:42.867 E/AndroidRuntime(25200): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: com.google.firebase.auth.FirebaseAuth#getInstance has been removed by Proguard. Add keep rule to prevent it.
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.installProvider(ActivityThread.java:5216)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4808)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4748)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.os.Looper.loop(Looper.java:148)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.main(ActivityThread.java:5480)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at java.lang.reflect.Method.invoke(Native Method)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-06 13:58:42.867 E/AndroidRuntime(25200): Caused by: java.lang.IllegalStateException: com.google.firebase.auth.FirebaseAuth#getInstance has been removed by Proguard. Add keep rule to prevent it.
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.FirebaseApp.a(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.FirebaseApp.a(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.FirebaseApp.a(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.FirebaseApp.a(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
10-06 13:58:42.867 E/AndroidRuntime(25200):     at android.app.ActivityThread.installProvider(ActivityThread.java:5213)
10-06 13:58:42.867 E/AndroidRuntime(25200):     ... 10 more`

without redex, the release apk with proguard active, is working.

**Comment by newobj** [comment]
How are you running redex? Are you correctly pointing it at your proguard config?

**Comment by alexodus** [comment]
the problem appaered when my app has become multidex in release mode

```
buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro','proguard-rx.pro', 'proguard-smack.pro'
            signingConfig signingConfigs.release
        }
    ....
```
in proguard-rules.pro I have:
```
...
#firebase auth
# Recommended flags for Firebase Auth
-keepattributes Signature
-keepattributes *Annotation*
-keepclasseswithmembers class * {
    public static FirebaseAuth getInstance ();
}
...
```

my commandline are these:
`#redex -o app-release-redex.apk app-release.apk --sign -s ./xxxx.jks -a xxxx -p xxxx  -k keepme.txt -P proguard-rules.pro`

`#redex -o app-release-redex.apk app-release.apk --sign -s ./xxxx.jks -a xxxx -p xxxx  -k keepme.txt`

`#redex -o app-release-redex.apk app-release.apk --sign -s ./xxxx.jks -a xxxx -p xxxx `

my keepme.txt was that:
`com.google.firebase.auth.FirebaseAuth`

in the app-release-redex.apk there is the method getInstance() (see

![image](https://cloud.githubusercontent.com/assets/2721510/20521733/eb4bc6ee-b0ac-11e6-8534-8bf8d3060723.png)
)

In all tests:
- the app-release.apk is OK
- the app-release-redex.apk fails

**Comment by alexodus** [comment]
I'm using always the last commit of redex, like today:
```
commit 18fdc1a10602d1835eec1bad053ca8636bd95720
Author: Brian Long <blo@fb.com>
Date:   Mon Nov 21 15:06:41 2016 -0800
```

PS: I'm using redex in other project with success

**Comment by samyakjain** [comment]
I have the same issue

**Comment by samyakjain** [comment]
I added this in proguard  and it worked

```
-keepattributes Signature
-keepattributes *Annotation*
-keepclasseswithmembers class * {
    public static FirebaseAuth getInstance ();
}
-keep class com.google.firebase.auth.FirebaseAuth
```

and i am not doing this **-k keepme.txt** as well while generating redex apk

**Comment by alexodus** [comment]
no, even with your changes, the generated redex apk fails with the same exception

**Comment by juice77** [comment]
+1

**Comment by samyakjain** [comment]
Not working for me now. Anyone find solution for this, please paste it here.

**Comment by alexodus** [comment]
@samyakjain , is your app overflow the 64k methods?

**Comment by samyakjain** [comment]
No, but multiDexEnabled is true, because app overflow 64k methods in debug

**Comment by justinjhendrick** [comment]
Try adding `@DoNotStrip`. See the readme for details.

**Comment by ZacSweers** [comment]
@justinjhendrick this class is from a closed source external library, how can someone apply that annotation on code they didn't write?

**Comment by ZacSweers** [comment]
It appears that even with adding that to our config, it's not respecting that annotation (at least in the version of redex we're using). I'll talk with @awelc separately first to make sure I'm not missing something on our end

**Comment by justinjhendrick** [comment]
You can also add a proguard rule and pass the proguard file to redex with `-P`

**Comment by justinjhendrick** [comment]
If you weren't using a proguard file before this, adding a proguard file may enable some more optimizations.

To check which new optimizations will run, before you add `-P`, enable logging with `export TRACE=1` then look for prints like: 
```
"Pass not run because no ProGuard configuration was provided."
```

**Comment by NTillmann** [comment]
closing due to age
