### ISSUE TITLE
Support Windows build of ReDex

### ISSUE THREAD

**Issue by satnam6502** [facebook/redex#18]
Make sure we can reliably build and support ReDex for Windows 10. One approach might be to use the new native support for bash as suggested by @jp1017 in #17

**Comment by Orvid** [comment]
Alternatively, I'm doing significant work towards getting Folly building under MSVC, so you may soon be able to get away without needing bash on windows.

**Comment by hantsy** [comment]
if possible provide a ReDex Docker ready build environment for Windows user.

**Comment by necros2k7** [comment]
+1

**Comment by jjhesk** [comment]
+1, try it on docker + [this container](https://hub.docker.com/r/yongjhih/redex/)

**Comment by necros2k7** [comment]
yeah but docker requires lin. or mac

**Comment by WizKid** [comment]
https://docs.docker.com/docker-for-windows/ ?

**Comment by necros2k7** [comment]
my bad, thanx 8-)

**Comment by deephole** [comment]
This is really needed!!!

**Comment by minjang** [comment]
Heads-up: we (Facebook) also now have some demand running Redex on Windows. Unfortunately, this is still low priority. If one is extremely interesting, it's worthy to try with Visual Studio. E.g., create a command-line executable C++ project with all source code (except testing) and proper defines. You will see compile errors from Unix/Linux-only headers. So, it requires some work. A good news is that we recently updated code to be more C++ standard (e.g., not using pthread). While we can't give an ETA, it's not that far from supporting Windows.

**Comment by dphillipsprosper** [comment]
So, this issue's been open for a couple years now, I was wondering if there's any update?

Reading the docs, it appears Redex can be compiled for Windows, albeit it's in an "experimental" state. So I was wondering, what does "experimental" really mean here?

Is it that it'll compile, and it'll work but it's not thoroughly tested so it's "experimental"?
Or is it that compiling itself is still experimental?

**Comment by youssef212** [comment]
when building for windows i get a lot of compile errors and build fails tried with both cmake and msbuild

**Comment by necros2k7** [comment]
welcome to the club bud)

**Comment by youssef212** [comment]
is it worth the try ? like how much does it optimize? because i already wasted like day and a half on trying to build it

**Comment by necros2k7** [comment]
if you`ll succeed you`ll be worshipped to, 4 years no binary for people...

**Comment by agampe** [comment]
I've cleaned up Redex a bit with some known incompatibilities. The support is still experimental, but feedback is welcome. You no longer need MSVC or WSL, a pure OSS setup works. Thus it should thus work on older releases of Windows, too.

(There's a good chance the MSVC build works again, too, but that is untested.)

Follow the (light) instructions [here](https://fbredex.com/docs/installation#experimental-windows-64-bit-with-msys2) and [here](https://fbredex.com/docs/installation#experimental-windows-64-bit-with-msys2-1).

**Comment by agampe** [comment]
The MSYS-style build is now continuously tested on CircleCI.

**Comment by necros2k7** [comment]
Any link to the binary?

**Comment by agampe** [comment]
> Any link to the binary?

We do not provide binaries for any platform at this point, and there are no plans to. Please follow the quite simple instructions [here](https://fbredex.com/docs/installation) to build your own.

**Comment by youssef212** [comment]
is this even instructions? its just like every time i try to build it you put two or three instructions and we have to figure out everything on our own, the ones who would use this are mobile devs and we barely use this build tools so when you put instructions please be patient and add everything we should do

**Comment by agampe** [comment]
Since people have complained: I was *not* responsible for the structure of the installation document, which tries to keep common parts common but thus pulls the steps apart. The written-down steps are also IMO clearly explained. But let me try a more streamlined version here.

# Preparation

* Install MSYS2. The link is in the docs, or go [here](https://www.msys2.org/#installation).
* Install Python 3.6+ for Windows. The link is in the docs, or go [here](https://www.python.org/downloads/windows/).

# MSYS Compilation

The following steps do all need to be run in a "MingW64 Shell." Installing MSYS2 should have added this option to the Start Menu. Alternatively, run the MingW64 executable in `C:\msys2` (or wherever you installed MSYS2). (`#` denotes a comment, does not need to be typed/copied.)
```
# Possibly update MSYS and package caches
pacman -Syuu  # If this updates MSYS and tells you, close the shell and open a new one
# Install dependencies
pacman -Sy make mingw-w64-x86_64-boost mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-jsoncpp mingw-w64-x86_64-make git
# Download redex from Github
git clone https://github.com/facebook/redex.git
cd redex
# Prepare and build
mkdir build-cmake
cd build-cmake
cmake -G "MSYS Makefiles" ..
make -j4  # This typically needs 8GB of RAM. You may need to lower the number
```

# Collect All Files

At this point, the binary is created. Collect all the necessary things for redex from under the MSYS home folder (by default `C:\msys2\home\{USERNAME}\redex` (or in the MingW64 shell, typing `pwd -W` will give the Windows path). You need
```
redex.py
pyredex/*
build-cmake/redex-all.exe
```

Redex is invoked through the Python script nowadays, which will unpack an APK, invoke `redex-all`, and repack the APK. In a standard command prompt (MSYS is no longer required), run something like
```
python redex.py ...
```

**Comment by youssef212** [comment]
thanks for your replay i deleted my comment even before you reply cuz i felt i was bit unfair and my be tilted XD but i calmed down quickly , i know you probably saw the comment in email notification may be , i deleted it cuz i didnt want to be an idiot who just push false claim on some other dev without knowing all the facts so i am sorry about the earlier comment i amnt sure if you saw it or not actually but still i had to say this .

**Comment by youssef212** [comment]
btw make -j4 is still gives errors

**Comment by agampe** [comment]
> btw make -j4 is still gives errors

Can you open a new issue with the error you get?

**Comment by youssef212** [comment]
sure i will, thank you so much for your time

**Comment by necros2k7** [comment]
agampe, you say "The MSYS build is simple/easy, tested on CircleCI and works." can you please upload somewhere working build for community?

**Comment by agampe** [comment]
> agampe, you say "The MSYS build is simple/easy, tested on CircleCI and works." can you please upload somewhere working build for community? not all here are skillful compilers

I still feel strongly that the instructions cover a simple setup that is complete (and the CircleCI config gives an alternative starting from chocolatey). In general, in my opinion getting the redex configuration right is a way more complex task than getting the binary.

Anyways, I've submitted a [patch](https://github.com/facebook/redex/pull/573) that adds Windows to the nightly build on CircleCI and stores the binary as an "artifact."

Notes:
* This is totally inofficial. No guarantees, warrantees, etc, you use it at your own risk, it's nothing but a test artifact for us, you're still supposed to compile that for yourself. That said, if you find problems, file a Github issue.
* CircleCI stores artifacts for 30 days. If you want older binaries (maybe they were more stable or w/e), it's your job to keep copies. There's also only the build for `master`, no such thing for `stable`.
* Our CircleCI pipeline is [here](https://app.circleci.com/pipelines/github/facebook/redex). You have to select a nightly windows build and look into the artifacts tab. You should find a zip with the binary, the python files and the default config.
* It missed today's "nightly" build. You can check the build for the pull request test, its build number is 2273.

**Comment by necros2k7** [comment]
Can you confirm right syntax?
Z:\redex>redex-all z:\redex\1.apk -o z:\redex\2.apk
error: outdir is not a writable directory: z:\redex\2.apk

**Comment by agampe** [comment]
Obviously not. `redex-all` has not been the main driver in years, instead use `redex.py`. It's sketched in the install documentation at the end [here](https://fbredex.com/docs/installation#experimental-windows-64-bit-with-msys2-1). We'll update the main docs.

**Comment by necros2k7** [comment]
I took latest nightly - so what redex-all.exe for?

**Comment by agampe** [comment]
The comment seems to have been removed, I will still reply:

> so what redex-all.exe for?

`redex-all` is the ReDex optimizer implemented in C++. However, for a long time now `redex-all` has not been dealing with APKs, but unpacked dex files (as we now support multiple custom compression schemes that are hard to support in C++). `redex.py` is the "new" wrapper that deals with APKs, alignment, signing. `redex.py` will unpack the given APK, call `redex-all` (either with a default path, or the `--redex-binary` parameter), and repackage afterwards. You need Python3 for it (which is detailed in the installation instructions).
