### ISSUE TITLE
java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by drinkWaterForThirsty** [facebook/redex#182]
Caused by: de.greenrobot.dao.DaoException: Could not init DAOConfig
10-18 15:29:56.328 27896 27896 E AndroidRuntime:    at de.greenrobot.dao.internal.DaoConfig.<init>(￥:94)
10-18 15:29:56.328 27896 27896 E AndroidRuntime:    at de.greenrobot.dao.AbstractDaoMaster.registerDaoClass(￥:44)

Caused by: java.lang.NoSuchFieldException: TABLENAME
10-18 15:29:56.328 27896 27896 E AndroidRuntime:    at java.lang.Class.getField(Class.java:891)
10-18 15:29:56.328 27896 27896 E AndroidRuntime:    at de.greenrobot.dao.internal.DaoConfig.<init>(￥:56)
10-18 15:29:56.328 27896 27896 E AndroidRuntime:    ... 23 more

**Comment by drinkWaterForThirsty** [comment]
在做dex优化的时候把 const TABLENAME 给删除了。
但是我在混淆配置文件里面keep住了。

**Comment by drinkWaterForThirsty** [comment]
when optimize dex , Delete const TABLENAME
But I keep it in the proguard.pro

**Comment by justinjhendrick** [comment]
See my update to the README coming soon.
