### ISSUE TITLE
Unknown opcode ff

### ISSUE THREAD

**Issue by eagertofly** [facebook/redex#188]
I have one apk with multi-dex. The output report one such error and failed. Anyone can help me?

Unknown opcode ff
libredex/DexClass.cpp:304: static std::unique_ptr<DexCode> DexCode::get_dex_code(DexIdx *, uint32_t, DexString *): assertion `dop != nullptr' failed.
Failed to parse method at offset 0x00137b20
0   redex-all                           0x0000000106556954 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff935ae52a _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
3   libsystem_c.dylib                   0x00007fff8ab836e7 abort + 129
4   redex-all                           0x0000000106556911 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x000000010655c977 _ZN7DexCode12get_dex_codeEP6DexIdxjP9DexString + 1879
6   redex-all                           0x000000010655e93f _ZN8DexClass20load_class_data_itemEP6DexIdxjP20DexEncodedValueArray + 2671
7   redex-all                           0x0000000106560760 _ZN8DexClassC2EP6DexIdxP13dex_class_def + 496
8   redex-all                           0x000000010656627a _ZL10class_workPv + 58
9   redex-all                           0x00000001065d5505 _ZN9WorkQueue13worker_threadEPv + 69
10  libsystem_pthread.dylib             0x00007fff937d999d _pthread_body + 131
11  libsystem_pthread.dylib             0x00007fff937d991a _pthread_body + 0
12  libsystem_pthread.dylib             0x00007fff937d7351 thread_start + 13
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 500, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 444, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 117, in run_pass
    raise err
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/yr/934y0vk17r36cgbpb8t3yhdc0000gn/T/tmpoLbkJ6.redex_extracted_apk --outdir /var/folders/yr/934y0vk17r36cgbpb8t3yhdc0000gn/T/tmpZHIVZI.redex_dexen /var/folders/yr/934y0vk17r36cgbpb8t3yhdc0000gn/T/tmpZHIVZI.redex_dexen/dex0/classes.dex /var/folders/yr/934y0vk17r36cgbpb8t3yhdc0000gn/T/tmpZHIVZI.redex_dexen/dex1/classes2.dex /var/folders/yr/934y0vk17r36cgbpb8t3yhdc0000gn/T/tmpZHIVZI.redex_dexen/dex2/classes3.dex' returned non-zero exit status -6

**Comment by newobj** [comment]
Well, per the dex spec, 0xff is indeed an unused opcode. Is your input APK ok? It passes verification? It would be helpful to add some printf debugging to see which class/method it's trying to load, then post the bytecode of that method, per dexdump.

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
