### ISSUE TITLE
static analysis

### ISSUE THREAD

**Issue by necros2k7** [facebook/redex#189]
[configparser\generated_files\parser.cc:2026]: (error) Memory allocation size is negative.
[libredex\Creators.cpp:83]: (performance) Function parameter 'obj' should be passed by reference.
[libredex\Creators.cpp:119]: (performance) Function parameter 'obj' should be passed by reference.
[Cppcheck\redex-master\libredex\DexClass.h:361]: (performance) Variable 'm_list' is assigned in constructor body. Consider performing initialization in initialization list.
[Cppcheck\redex-master\libredex\DexClass.h:639]: (performance) Variable 'm_code' is assigned in constructor body. Consider performing initialization in initialization list.
[Cppcheck\redex-master\libredex\DexClass.h:475]: (performance) Function parameter 'pos' should be passed by reference.
[libredex\ProguardParser.cpp:778]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[libresource\ResourceTypes.cpp:6721]: (error) Uninitialized struct member: value.size
[libresource\ResourceTypes.cpp:6721]: (error) Uninitialized struct member: value.res0
[libresource\ResourceTypes.cpp:6721]: (error) Uninitialized struct member: value.dataType
[libresource\ResourceTypes.cpp:4101]: (error) Common realloc mistake: 'set' nulled but not freed upon failure

**Comment by newobj** [comment]
Thanks for this. Relaying to the team internally. Closing this task. Will definitely take a look at the ProguardParser.cpp ++/-- issue.
