### ISSUE TITLE
Crash when i try to redex kotlin apk

### ISSUE THREAD

**Issue by tagantroy** [facebook/redex#19]
`opt/bridge/Bridge.cpp:37: DexMethod *(anonymous namespace)::match_pattern(DexMethod *): assertion `code' failed.
Bridge method `public abstract kotlin.text.MatchGroupCollection.add(Ljava/lang/Object;)Z' doesn't contain code
0   redex-all                           0x0000000100e51fa4 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9ef9c52a _sigtramp + 26
2   ???                                 0x00007fff5edb6860 0x0 + 140734784825440
3   libsystem_c.dylib                   0x00007fff8cc116e7 abort + 129
4   redex-all                           0x0000000100e51f61 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000100eca51c _ZZN13BridgeRemover12find_bridgesEvENKUlP9DexMethodE_clES1_ + 1052
6   redex-all                           0x0000000100eca09c _Z12walk_methodsINSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEEZN13BridgeRemover12find_bridgesEvEUlP9DexMethodE_EvRKT_T0_ + 140
7   redex-all                           0x0000000100ec9c34 _ZN13BridgeRemover3runEv + 20
8   redex-all                           0x0000000100ec9ae2 _ZN10BridgePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER8PgoFiles + 114
9   redex-all                           0x0000000100e73928 _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEE + 312
10  redex-all                           0x0000000100f1cf38 main + 2168
11  libdyld.dylib                       0x00007fff8f8b45ad start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /var/folders/xl/htc7wt_x6px_rdy00h1sff8h0000gn/T/tmpnyoddlkf.redex_extracted_apk --outdir /var/folders/xl/htc7wt_x6px_rdy00h1sff8h0000gn/T/tmpkbg0gar4.redex_dexen /var/folders/xl/htc7wt_x6px_rdy00h1sff8h0000gn/T/tmpkbg0gar4.redex_dexen/dex0/classes.dex /var/folders/xl/htc7wt_x6px_rdy00h1sff8h0000gn/T/tmpkbg0gar4.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6`

multidex enabled.
compileSdkVersion 23
buildToolsVersion "23.0.3"
kotlin 1.0.1

**Comment by bertmaher** [comment]
It looks like there's an error with the BridgePass.  You can remove it by following the instructions in [docs/Config.md](https://github.com/facebook/redex/blob/master/docs/Config.md).  I'll hopefully fix this relatively soon.
