### ISSUE TITLE
cant make in macos 10.12

### ISSUE THREAD

**Issue by fanglajide** [facebook/redex#191]
is mac os 10.12 support?
Undefined symbols for architecture x86_64:
  "type_class(DexType const*)", referenced from:
      print_stats(std::__1::unordered_map<DexType*, SingleImplData, std::__1::hash<DexType*>, std::__1::equal_to<DexType*>, std::__1::allocator<std::__1::pair<DexType* const, SingleImplData> > >&) in SingleImplStats.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [redex-all] Error 1
make: *** [all-recursive] Error 1

**Comment by navyxliu** [comment]
type_class(const DexType*) is defined in head DexUtil.h
why can't you find the def symbol? it seems that it's related to your compiler and invocation.

**Comment by justinjhendrick** [comment]
closing due to age. If you still see this error on the newest version, please re-open or create new issue.
