### ISSUE TITLE
binary dist

### ISSUE THREAD

**Issue by wisechengyi** [facebook/redex#194]
Hi,

I think people may be interested directly getting the binary version this for different platforms, given the runtimes are available. 

I was also curious how fb internally consumes it? Probably not building it on the go right?

Thanks,
Yi

**Comment by justinjhendrick** [comment]
We do build it on the go (with clever caching). It works better with our continuous integration that way.

**Comment by wisechengyi** [comment]
hehe, only if c++'s build system as good as jvm's. thanks for sharing :D
