### ISSUE TITLE
interdex not working

### ISSUE THREAD

**Issue by yiwowang** [facebook/redex#195]
**redex/config/default.config :**

{
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "BridgePass",
      "SynthPass",
      "FinalInlinePass",
      "DelSuperPass",
      "SingleImplPass",
      "SimpleInlinePass",
      "StaticReloPass",
      "RemoveEmptyClassesPass",
      "ShortenSrcStringsPass"
    ]
  },
  "InterDexPass" : {
  "static_prune" : "0",
  "emit_canaries" : "1",
  "coldstart_classes"："list_of_classes.txt"
}
}

**redex/config/list_of_classes.txt:**
com.yiwowang.lulu.LoginActivity.class
com.yiwowang.lulu.MainActivity.class
com.yiwowang.lulu.Util.class
...........
...........

When I execute this command line:
ANDROID_SDK=/Users/yiwowang/Library/Android/sdk redex app-debug.apk -o output.apk

tip : Error writing mapping file: No such file or directory

but

ANDROID_SDK=/Users/yiwowang/Library/Android/sdk redex app-debug.apk -o output.apk -c config/default.config

tip:
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 506, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 428, in run_redex
    config_dict = json.load(config_file)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting : delimiter: line 19 column 22 (char 381)

What should I do?

**Comment by justinjhendrick** [comment]
Sorry for the extremely delayed reply,

I'm not sure why it failed to write the mapping file. Could you check `filename_mappings.txt` to see if it's write protected or something similar?

The second issue (failing to read the config) is caused by some bogus characters in your config.txt. Look at this hexdump

```
00000000  22 65 6d 69 74 5f 63 61  6e 61 72 69 65 73 22 20  |"emit_canaries" |
00000010  3a 20 22 31 22 2c 0a 22  63 6f 6c 64 73 74 61 72  |: "1",."coldstar|
00000020  74 5f 63 6c 61 73 73 65  73 22 ef bc 9a 22 6c 69  |t_classes"..."li|
00000030  73 74 5f 6f 66 5f 63 6c  61 73 73 65 73 2e 74 78  |st_of_classes.tx|
00000040  74 22 0a                                          |t".|
```

These bytes show a colon in the browser, but they aren't ascii `ef bc 9a`. You should use `3a` for `:`

**Comment by justinjhendrick** [comment]
See #185
