### ISSUE TITLE
multil dex cause :subprocess.CalledProcessError 

### ISSUE THREAD

**Issue by tim1004457** [facebook/redex#200]
My apk has tow dex file : classes.dex 、classes2.dex
when I use redex, I get this error:

./libredex/DexClass.h:331: void DexField::attach_annotation_set(DexAnnotationSet *): assertion `false' failed.
attach_annotation_set failed for field Lcom/tencent/tmsecurelite/commom/DataEntity;.CREATOR

0   redex-all                           0x000000010f71f254 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff8a29ef1a _sigtramp + 26
2   ???                                 0x0000000000000000 0x0 + 0
3   libsystem_c.dylib                   0x00007fff889bfb53 abort + 129
4   redex-all                           0x000000010f71f211 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x000000010f7299ec _ZN8DexClass22load_class_annotationsEP6DexIdxj + 684
6   redex-all                           0x000000010f72a1ab _ZN8DexClassC2EP6DexIdxP13dex_class_def + 443
7   redex-all                           0x000000010f72f9fa _ZL10class_workPv + 58
8   redex-all                           0x000000010f7b3701 _ZN9WorkQueue13worker_threadEPv + 65
9   libsystem_pthread.dylib             0x00007fff90e0c268 _pthread_body + 131
10  libsystem_pthread.dylib             0x00007fff90e0c1e5 _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff90e0a41d thread_start + 13
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 507, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 448, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 117, in run_pass
    raise err
subprocess.CalledProcessError: Command '/usr/local/bin/redex-all --apkdir /var/folders/bg/9dkd49fx2mg_j6l1ncvwskfm0000gn/T/tmpFBMukD.redex_extracted_apk --outdir /var/folders/bg/9dkd49fx2mg_j6l1ncvwskfm0000gn/T/tmpYKPDtQ.redex_dexen /var/folders/bg/9dkd49fx2mg_j6l1ncvwskfm0000gn/T/tmpYKPDtQ.redex_dexen/dex0/classes.dex /var/folders/bg/9dkd49fx2mg_j6l1ncvwskfm0000gn/T/tmpYKPDtQ.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6

Can u Help me ?

**Comment by Dwan-xie** [comment]
i have the same issue

**Comment by tushar7sharma** [comment]
I am having the same issue as well. Its running fine when I don't use Proguard, but with Proguard it gives the same error

**Comment by agampe** [comment]
Closing old issue. Reopen if this is still a problem.
