### ISSUE TITLE
Interest in bazel build?

### ISSUE THREAD

**Issue by kamalmarhubi** [facebook/redex#206]
For my own purposes, I have enough of a [bazel](https://bazel.build/) build set up to build `libredex` and the `redexdump` binary. I'm mostly interested in `libredex`, so I haven't filled out the optimizations or the `redex` binary / python wrapper. If it'd be welcome, I could contribute it here.

**Comment by kamalmarhubi** [comment]
This could either be actually bazel-ifying the build so that it works with [`http_archive`](https://bazel.build/versions/master/docs/be/workspace.html#http_archive), adding a `WORKSPACE` and `BUILD` files throughout. Alternatively, it could be something like `contrib/bazel` which contains rules to set up redex as a [`new_http_archive`](https://bazel.build/versions/master/docs/be/workspace.html#new_http_archive) external repository. The latter would keep changes to just a single directory, and more clearly suggests it's not an officially supported build system.

**Comment by minjang** [comment]
Thanks for the suggestion. Honestly speaking, I don't think we would add a bazel build support anytime soon. If we see a strong need in the future, we could consider it.

**Comment by kamalmarhubi** [comment]
No worries! I'd done the work, so just wanted to see if it was wanted upstream. :-)
