### ISSUE TITLE
Issue with jsonapp

### ISSUE THREAD

**Issue by augusting52** [facebook/redex#210]
hi, 
centos 7
build jsoncpp success , and test success
but run "autoreconf -ivf && ./configure && make" failed
config.log shows Please install jsoncpp

I want know how to config jsoncpp that let redex to find it ???

**Comment by augusting52** [comment]
I hope anybody can help me, thanks

**Comment by minjang** [comment]
It seems like you need to install `jsoncpp`. Please try `sudo yum install jsoncpp`.

**Comment by augusting52** [comment]
Thank you very much, this problem has been solved. @minjang
