### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by augusting52** [facebook/redex#211]
hello, 
env:
centos 7
redex : commit 4d06897
When I make redex, I get an error as followed.

[username@localhost redex-master]$ autoreconf -ivf && ./configure 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of gcc... (cached) gcc3
checking dependency style of g++... (cached) gcc3
checking for a Python interpreter with version >= 3.0... python
checking for python... /usr/bin/python
checking for python version... 3.6
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.6/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.6/site-packages
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for boostlib >= 1.54.0... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex-mt... yes
checking for adler32 in -lz... yes
checking for main in -ljsoncpp... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking for memory.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for off_t... yes
checking for pid_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for clock_gettime... yes
checking for gettimeofday... yes
checking for memmove... yes
checking for memset... yes
checking for munmap... yes
checking for regcomp... yes
checking for strchr... yes
checking for strdup... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating test/integ/Makefile
config.status: creating test/unit/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

[username@localhost redex-master]$ sudo make
Making all in .
make[1]: 进入目录“/home/username/util/redex-master”
/bin/sh ./libtool  --tag=CXX   --mode=link g++ --std=gnu++11 -O3 -Wall -g -g -O2   -o redex-all opt/annokill/AnnoKill.o opt/bridge/Bridge.o opt/constant_propagation/ConstantPropagation.o opt/delinit/DelInit.o opt/delsuper/DelSuper.o opt/final_inline/FinalInline.o opt/access-marking/AccessMarking.o opt/interdex/InterDex.o opt/local-dce/LocalDce.o opt/obfuscate/Obfuscate.o opt/obfuscate/ObfuscateUtils.o opt/obfuscate/VirtualRenamer.o opt/peephole/Peephole.o opt/rebindrefs/ReBindRefs.o opt/remove_empty_classes/RemoveEmptyClasses.o opt/remove-unreachable/RemoveUnreachable.o opt/renameclasses/RenameClasses.o opt/renameclasses/RenameClassesV2.o opt/shorten-srcstrings/Shorten.o opt/simpleinline/Deleter.o opt/simpleinline/InlineHelper.o opt/simpleinline/SimpleInline.o opt/singleimpl/SingleImpl.o opt/singleimpl/SingleImplAnalyze.o opt/singleimpl/SingleImplOptimize.o opt/singleimpl/SingleImplStats.o opt/singleimpl/SingleImplUtil.o opt/static-sink/StaticSink.o opt/staticrelo/StaticRelo.o opt/synth/Synth.o opt/track_resources/TrackResources.o opt/unterface/Unterface.o opt/unterface/UnterfaceOpt.o opt/verifier/Verifier.o opt/analysis_ref_graph/ReferenceGraphCreator.o tools/redex-all/main.o libredex.la -lboost_filesystem -lboost_system -lboost_regex-mt -lpthread -ljsoncpp -lz 
libtool: link: g++ --std=gnu++11 -O3 -Wall -g -g -O2 -o redex-all opt/annokill/AnnoKill.o opt/bridge/Bridge.o opt/constant_propagation/ConstantPropagation.o opt/delinit/DelInit.o opt/delsuper/DelSuper.o opt/final_inline/FinalInline.o opt/access-marking/AccessMarking.o opt/interdex/InterDex.o opt/local-dce/LocalDce.o opt/obfuscate/Obfuscate.o opt/obfuscate/ObfuscateUtils.o opt/obfuscate/VirtualRenamer.o opt/peephole/Peephole.o opt/rebindrefs/ReBindRefs.o opt/remove_empty_classes/RemoveEmptyClasses.o opt/remove-unreachable/RemoveUnreachable.o opt/renameclasses/RenameClasses.o opt/renameclasses/RenameClassesV2.o opt/shorten-srcstrings/Shorten.o opt/simpleinline/Deleter.o opt/simpleinline/InlineHelper.o opt/simpleinline/SimpleInline.o opt/singleimpl/SingleImpl.o opt/singleimpl/SingleImplAnalyze.o opt/singleimpl/SingleImplOptimize.o opt/singleimpl/SingleImplStats.o opt/singleimpl/SingleImplUtil.o opt/static-sink/StaticSink.o opt/staticrelo/StaticRelo.o opt/synth/Synth.o opt/track_resources/TrackResources.o opt/unterface/Unterface.o opt/unterface/UnterfaceOpt.o opt/verifier/Verifier.o opt/analysis_ref_graph/ReferenceGraphCreator.o tools/redex-all/main.o  ./.libs/libredex.a -lboost_filesystem -lboost_system -lboost_regex-mt -lpthread -ljsoncpp -lz
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1293: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1293: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::cpp_regex_traits_implementation<char>::error_string(boost::regex_constants::error_type) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:449: undefined reference to `boost::re_detail_106200::get_default_error_string(boost::regex_constants::error_type)'
./.libs/libredex.a(ProguardMatcher.o): In function `void boost::re_detail_106200::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type)':
/usr/local/include/boost/regex/pattern_except.hpp:75: undefined reference to `boost::re_detail_106200::raise_runtime_error(std::runtime_error const&)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::cpp_regex_traits_implementation<char>::error_string(boost::regex_constants::error_type) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:447: undefined reference to `boost::re_detail_106200::get_default_error_string(boost::regex_constants::error_type)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:223: undefined reference to `boost::re_detail_106200::get_mem_block()'
./.libs/libredex.a(ProguardMatcher.o): In function `save_state_init':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:107: undefined reference to `boost::re_detail_106200::get_mem_block()'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_imp()':
/usr/local/include/boost/regex/v4/perl_matcher_common.hpp:214: undefined reference to `boost::re_detail_106200::verify_options(unsigned int, boost::regex_constants::_match_flags)'
./.libs/libredex.a(ProguardMatcher.o): In function `~save_state_init':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
./.libs/libredex.a(ProguardMatcher.o): In function `perl_matcher':
/usr/local/include/boost/regex/v4/perl_matcher.hpp:382: undefined reference to `boost::re_detail_106200::perl_matcher<char const*, std::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:223: undefined reference to `boost::re_detail_106200::get_mem_block()'
./.libs/libredex.a(ProguardMatcher.o): In function `save_state_init':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:107: undefined reference to `boost::re_detail_106200::get_mem_block()'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::re_detail_106200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_imp()':
/usr/local/include/boost/regex/v4/perl_matcher_common.hpp:214: undefined reference to `boost::re_detail_106200::verify_options(unsigned int, boost::regex_constants::_match_flags)'
./.libs/libredex.a(ProguardMatcher.o): In function `~save_state_init':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail_106200::put_mem_block(void*)'
./.libs/libredex.a(ProguardMatcher.o): In function `perl_matcher':
/usr/local/include/boost/regex/v4/perl_matcher.hpp:382: undefined reference to `boost::re_detail_106200::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::cpp_regex_traits<char>::transform(char const*, char const*) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
./.libs/libredex.a(ProguardMatcher.o): In function `boost::cpp_regex_traits<char>::transform(char const*, char const*) const':
/usr/local/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_106200::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
collect2: error: ld returned 1 exit status
make[1]: *** [redex-all] error 1
make[1]: leave dir “/home/username/util/redex-master”
make: *** [all-recursive] error 1

Hope to reply! Thank you!

**Comment by toliuweijing** [comment]
I'm seeing the same issue.

**Comment by justinjhendrick** [comment]
It could be an issue with your boost libraries (version)?
```
undefined reference to boost::re_detail_106200::put_mem_block(void*) ...
```

**Comment by justinjhendrick** [comment]
I ran into a similar issue. The issue might be this: libboost_regex must be build with the same compiler that you're using.

So, if you're using `gcc` on a mac, you'll have to `brew uninstall boost && brew install boost --cc=gcc-4.9`
