### ISSUE TITLE
Library not loaded:...libevent-x.y.z.dylib

### ISSUE THREAD

**Issue by kebbbnnn** [facebook/redex#212]
I'm getting this error 

```
  Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/bin/redex-all
  Reason: image not found
```

while doing the `redex path/to/my.apk -o path/to/my_output.apk`

**Comment by justinjhendrick** [comment]
our dependencies list is probably out of date. Have you tried getting libevent from your package manager?

**Comment by bertmaher** [comment]
That's pretty weird - redex shouldn't depend on libevent (it was only needed because redex used folly, which used libevent, and we removed folly).

**Comment by kebbbnnn** [comment]
Hi there guys. Thanks for your responses they gave me hint. After minutes of digging it turns out there's already a local repo of redex(but outdated) in the machine that I'm using. So I just updated it and do the build process and everything is working fine now. Thanks! :)
