### ISSUE TITLE
Error occured when "autoreconf -ivf && ./configure && make"

### ISSUE THREAD

**Issue by 654277633** [facebook/redex#215]
Error occured when "autoreconf -ivf && ./configure && make"

Log:

Making all in .
make[1]: 正在进入目录 `/home/yangyong/redex'
depbase=`echo libredex/ControlFlow.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"redex\" -DPACKAGE_TARNAME=\"redex\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"redex\ 1.0\" -DPACKAGE_BUGREPORT=\"not-valid-yet@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_LIBZ=1 -DHAVE_LIBJSONCPP=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MUNMAP=1 -DHAVE_REGCOMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -I.  -I./liblocator -I./libredex -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annokill -I./opt/bridge -I./opt/constant_propagation -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/access-marking -I./opt/interdex -I./opt/local-dce -I./opt/obfuscate -I./opt/peephole -I./opt/rebindrefs -I./opt/remove-unreachable -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/track_resources -I./opt/unterface -I./opt/verifier -I./util -I./tools/common -I./tools/redexdump -I/usr/include/jsoncpp  --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/ControlFlow.lo -MD -MP -MF $depbase.Tpo -c -o libredex/ControlFlow.lo libredex/ControlFlow.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DPACKAGE_NAME=\"redex\" -DPACKAGE_TARNAME=\"redex\" -DPACKAGE_VERSION=\"1.0\" "-DPACKAGE_STRING=\"redex 1.0\"" -DPACKAGE_BUGREPORT=\"not-valid-yet@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_FILESYSTEM=/**/" "-DHAVE_BOOST_SYSTEM=/**/" "-DHAVE_BOOST_REGEX=/**/" -DHAVE_LIBZ=1 -DHAVE_LIBJSONCPP=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MUNMAP=1 -DHAVE_REGCOMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -I. -I./liblocator -I./libredex -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/annokill -I./opt/bridge -I./opt/constant_propagation -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/access-marking -I./opt/interdex -I./opt/local-dce -I./opt/obfuscate -I./opt/peephole -I./opt/rebindrefs -I./opt/remove-unreachable -I./opt/remove_empty_classes -I./opt/renameclasses -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/synth -I./opt/track_resources -I./opt/unterface -I./opt/verifier -I./util -I./tools/common -I./tools/redexdump -I/usr/include/jsoncpp --std=gnu++11 -O3 -Wall -g -g -O2 -MT libredex/ControlFlow.lo -MD -MP -MF libredex/.deps/ControlFlow.Tpo -c libredex/ControlFlow.cpp  -fPIC -DPIC -o libredex/.libs/ControlFlow.o
libredex/ControlFlow.cpp: In member function 'void ControlFlowGraph::remove_all_edges(Block*, Block*)':
libredex/ControlFlow.cpp:43:36: error: no matching function for call to 'std::vector<Block*>::erase(__gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >, std::vector<Block*>::const_iterator)'
                    p->succs().end());
                                    ^
libredex/ControlFlow.cpp:43:36: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/boost/detail/container_fwd.hpp:93,
                 from /usr/include/boost/functional/hash/extensions.hpp:17,
                 from /usr/include/boost/functional/hash/hash.hpp:529,
                 from /usr/include/boost/functional/hash.hpp:6,
                 from libredex/ControlFlow.h:12,
                 from libredex/ControlFlow.cpp:10:
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = Block*; _Alloc = std::allocator<Block*>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = Block**]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = Block*; _Alloc = std::allocator<Block*>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = Block**]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 2 from 'std::vector<Block*>::const_iterator {aka __gnu_cxx::__normal_iterator<Block* const*, std::vector<Block*> >}' to 'std::vector<Block*>::iterator {aka __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >}'
libredex/ControlFlow.cpp:47:36: error: no matching function for call to 'std::vector<Block*>::erase(__gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >, std::vector<Block*>::const_iterator)'
                    s->preds().end());
                                    ^
libredex/ControlFlow.cpp:47:36: note: candidates are:
In file included from /usr/include/c++/4.8/vector:69:0,
                 from /usr/include/boost/detail/container_fwd.hpp:93,
                 from /usr/include/boost/functional/hash/extensions.hpp:17,
                 from /usr/include/boost/functional/hash/hash.hpp:529,
                 from /usr/include/boost/functional/hash.hpp:6,
                 from libredex/ControlFlow.h:12,
                 from libredex/ControlFlow.cpp:10:
/usr/include/c++/4.8/bits/vector.tcc:134:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = Block*; _Alloc = std::allocator<Block*>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = Block**]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:134:5: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/vector.tcc:146:5: note: std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::iterator) [with _Tp = Block*; _Alloc = std::allocator<Block*>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = Block**]
     vector<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   no known conversion for argument 2 from 'std::vector<Block*>::const_iterator {aka __gnu_cxx::__normal_iterator<Block* const*, std::vector<Block*> >}' to 'std::vector<Block*>::iterator {aka __gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >}'
make[1]: *** [libredex/ControlFlow.lo] 错误 1
make[1]:正在离开目录 `/home/yangyong/redex'
make: *** [all-recursive] 错误 1

**Comment by thezhangwei** [comment]
Are you building on Ubuntu? What is your boost lib version?

**Comment by 654277633** [comment]
Version: 1.54.0.1ubuntu1

**Comment by justinjhendrick** [comment]
Try this

```
$ sudo apt-get install \
    g++ \
    automake \
    autoconf \
    autoconf-archive \
    libtool \
    libboost-all-dev \
    liblz4-dev \
    liblzma-dev \
    make \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    libiberty-dev \
    libjsoncpp-dev

$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by justinjhendrick** [comment]
If that doesn't work, make sure your compiler supports c++11.

```
error: no matching function for call to 'std::vector<Block*>::erase(__gnu_cxx::__normal_iterator<Block**, std::vector<Block*> >, std::vector<Block*>::const_iterator)'```

makes me think you may not have c++11 because that function was introduced in c++11.
