### ISSUE TITLE
libredex: Allow unregistering passes; do not require static initialization

### ISSUE THREAD

**Issue by kamalmarhubi** [facebook/redex#219]
I'm writing some DEX instrumentation and would like to dynamically construct and register passes. Inspecting the code, it seems I'm fine to do so providing I ensure the passes are outlive the call to `PassManager::run_passes()`. The only place the work queue is used seems to be in loading and writing. Am I missing some way in which this would be unsafe?

**Comment by int3** [comment]
It should be fine. We have no need for dynamically constructed pass at present, and the static initialization makes code cleaner to write, so I would rather not accept a PR that changes this behavior while making pass registration more verbose.
