### ISSUE TITLE
StripDebugInfoPass not stripping all info with specific options

### ISSUE THREAD

**Issue by deephole** [facebook/redex#220]
All debug info is stripped only if drop_all_dbg_info together with drop_src_files is enabled.
If only drop_line_numbers (or drop_local_variables) is enabled - no info is stripped

**Comment by int3** [comment]
StripDebugInfo isn't really production-ready; we haven't activated it internally either, so it's not surprising that it has some bugs. We'll be working on better debug info handling soon though.

**Comment by deephole** [comment]
Is there any information about which optimisations are production ready and which are not?

**Comment by int3** [comment]
https://github.com/facebook/redex/blob/master/config/default.config lists a subset of production-ready passes. We should update it at some point.

**Comment by deephole** [comment]
What about peephole, renaming, regalloc, debug info stripping, dead code elimination and so on ? I've tested those with quite few test cases and they seem to be quite stable. Also I believe you've quite more passes described here https://code.facebook.com/posts/1480969635539475/optimizing-android-bytecode-with-redex/ then you have in default.config

**Comment by justinjhendrick** [comment]
Peephole is pretty stable, renaming is stable (if you're careful about blacklisting things you need), regalloc is quite new and only mildly stable, DCE is stable.

I'll update default.config soon.
