### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by andyhaha** [facebook/redex#222]
after redex，the apk can not be installed

**Comment by wisechengyi** [comment]
What error did you see? From adb I assume?

**Comment by andyhaha** [comment]
how can I see the error when installing，it just prompt that the apk can not  be resolved

**Comment by wisechengyi** [comment]
`adb install <your apk>` wait for the error or success message

**Comment by andyhaha** [comment]
thanks a lot for your helep. I have resolved my problem. It seems that the apk must be signed,otherwise it could not be installed.

**Comment by justinjhendrick** [comment]
For any searchers later I will add another piece of advice. `adb logcat` will give you all of the logs from the phone.
