### ISSUE TITLE
Will crash when use proxy

### ISSUE THREAD

**Issue by LnsooXD** [facebook/redex#223]
When use the `java.reflect.Proxy` in app, redex will case `java.lang.ClassCastException: $Proxy2 cannot be cast to xxxx`.

The example code like this:
```java
// The interface:
public interface ITest {
    void test();
}

// The implement class:
public class TestImpl {
    void test() {
         // some code
    }
}

// The handler
public class Handler implement InvocationHandler {
   // some code
}

// The test code
TestImpl impl = new TestImpl();

// After redex, it will throw ClassCastException: $Proxy2 cannot be cast to  ITest
ITest proxy = (ITest) Proxy.newProxyInstance(impl.getClass().getClassLoader(), impl.getClass().getInterfaces(), new Handler());
```

**Comment by thezhangwei** [comment]
Might be worth to look at the post redex dex dump to see what's going on.

**Comment by LnsooXD** [comment]
@thezhangwei Use witch tool to dump the dex?

**Comment by justinjhendrick** [comment]
try adding `-keep class TestImpl { *; }` to your proguard config.

**Comment by LnsooXD** [comment]
@justinjhendrick No effect, You can test on this project: [https://github.com/crazycodeboy/TakePhoto](TakePhoto) , it will crash like "java.lang.ClassCastException: $Proxy2 cannot be cast to com/jph/takephoto/app/TakePhotoImpl.java" when select a image

**Comment by LnsooXD** [comment]
@justinjhendrick It look's like that, the code:
```java
ITest proxy = (ITest) Proxy.newProxyInstance(...);
```
may be optimized into:
```java
ITest proxy = (TestImpl) Proxy.newProxyInstance(...);
```

**Comment by LnsooXD** [comment]
@justinjhendrick  I change
```java
ITest proxy = (ITest) Proxy.newProxyInstance(impl.getClass().getClassLoader(), impl.getClass().getInterfaces(), new Handler());
```
to
 ```java
ITest proxy = (ITest) Proxy.newProxyInstance(impl.getClass().getClassLoader(), new Class[]{ITest.class}, new Handler());
```
and it was no longer crash. 😂

**Comment by justinjhendrick** [comment]
Sorry, I misread. Try putting `-keep class path.to.ITest { *; }` in your proguard config.

If that doesn't work, you can add an annotation to any class to make sure Redex will not delete it.

Redex probably deleted or renamed it. Redex is quite aggressive about deleting things it deems are unreachable. But, often Redex doesn't know about reflection or other complex ways an entity could be reached.

Here's how you ensure Redex will not delete or rename something:

Annotate any class, method, or field you want to keep with `@DoNotStrip`.

```
@DoNotStrip
class ITest {
  void test();
}
```

Add this to your redex config (at the uppermost level of the json) to prevent deletion:

```
"keep_annotations": [
  "Lcom/path/to/your/DoNotStrip;"
]
```

and add this to your config to prevent renaming:

```
"RenameClassesPassV2" : {
  "dont_rename_annotated": [
    "Lcom/path/to/your/DoNotStrip;"
  ]
}
```

and define `DoNotStrip`:

```
package com.path.to.your;
public @interface DoNotStrip {}
```

**Comment by LnsooXD** [comment]
@justinjhendrick  Ok, thank you.  I just increase the reference of class ITest and it work well, too. The code is: 
```java
//  Increase the reference of class ITest by using `new Class[]{ITest.class}`
ITest proxy = (ITest) Proxy.newProxyInstance(impl.getClass().getClassLoader(), 
new Class[]{ITest.class}, new Handler());
```

**Comment by justinjhendrick** [comment]
Yes. That works as well because Redex can see that you use `ITest.class`, so it knows not to delete it.

This seems resolved. Closing. Feel free to re-open if necessary.
