### ISSUE TITLE
regalloc throws exception on check_cast instruction

### ISSUE THREAD

**Issue by deephole** [facebook/redex#226]
Regalloc pass throws exception with following input : 
import java.util.ArrayList;
import java.util.List;

public class Main {
    private final List<byte[]> data = new ArrayList<byte[]>(4);

    public static void main(String [] args){
        Main it = new Main();
    }
    private byte[][] get() {
        byte[][] result = new byte[data.size()][];
        return data.toArray(result);
    }
}

Exception message:
 DexInstruction *IRInstruction::to_dex_instruction() const: assertion `dest() == src(0)' failed.

I think this is due to renumber_registers call. In fact there's another bug with interference graph. Interference graph ignores if statement scopes

**Comment by justinjhendrick** [comment]
cc @int3

**Comment by int3** [comment]
Again, not quite ready for public consumption. You should be able to get it to work by adding `"next_release_gate": true` in the JSON config.

> In fact there's another bug with interference graph. Interference graph ignores if statement scopes

Not sure what you mean by this, care to elaborate?

**Comment by deephole** [comment]
int3 thanks for response - changing next_release_gate to true helped me. As per my understanding the purpose of interference graph builder is to find potential register type conflicts. This is basically replication of what dexVerifier (AOSP) does. At the moment interference call ignores scopes. I hope my further example will explain my issue:
The issue with inteference graph:
cons-string v1, "someString" // v1 register type STRING
const-4 v2, #int 3
if-eqz v2, 0015 //
const-4 v1, #int 35 // v1 register type INT
0015:
invoke-static {v1}, LMain;->someMethod(I)V  // REGISTER v1 is STRING at this point, but interference graph thinks it's INT and doesn't complain

**Comment by int3** [comment]
RegAlloc assumes that the input code is correct to begin with. It doesn't try (beyond some very superficial checks) to verify that the input code verifies. For your example, at the line

> invoke-static {v1}, LMain;->someMethod(I)V

v1 could be either a string or an int there, so it doesn't make sense to pass it to someMethod. That code will not pass dexopt/dex2oat verification even before it is run through the register allocator.
