### ISSUE TITLE
build break

### ISSUE THREAD

**Issue by colinstonema** [facebook/redex#227]
In file included from ./libresource/androidfw/ResourceTypes.h:27:0,
                 from libredex/RedexResources.h:15,
                 from libredex/ReachableClasses.cpp:21:
./libresource/utils/Vector.h: In member function 'const android::Vector<T>& android::Vector<TYPE>::operator=(const android::Vector<TYPE>&) const':
./libresource/utils/Vector.h:251:64: error: no matching function for call to 'android::Vector<TYPE>::operator=(const android::VectorImpl&) const'
     VectorImpl::operator = (static_cast<const VectorImpl&>(rhs));
                                                                ^
In file included from ./libresource/utils/Vector.h:26:0,
                 from ./libresource/androidfw/ResourceTypes.h:27,
                 from libredex/RedexResources.h:15,
                 from libredex/ReachableClasses.cpp:21:
./libresource/utils/VectorImpl.h:56:29: note: candidate: android::VectorImpl& android::VectorImpl::operator=(const android::VectorImpl&) <near match>
             VectorImpl&     operator = (const VectorImpl& rhs);
                             ^~~~~~~~
./libresource/utils/VectorImpl.h:56:29: note:   passing 'const android::Vector<TYPE>*' as 'this' argument discards qualifiers

make[1]: *** [libredex/ReachableClasses.lo] Error 1

**Comment by wisechengyi** [comment]
looks similar to #221, have you tried gcc-4.9?

**Comment by colinstonema** [comment]
thx, gcc-4.9.4 work fine.
