### ISSUE TITLE
Installation fails after redex

### ISSUE THREAD

**Issue by VenomVendor** [facebook/redex#23]
Trying to install redexed app fails with `Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]`
Tried with both debug & release apk.

**Comment by bonnyfone** [comment]
You need to re-sign the APKs before install. 

You can sign the ouput APK automatically with **redex** by providing proper extra params:

>   --sign                Sign the apk after optimizing it
>   -s [KEYSTORE], --keystore [KEYSTORE]
>   -a [KEYALIAS], --keyalias [KEYALIAS]
>   -p [KEYPASS], --keypass [KEYPASS]

**Comment by chethann** [comment]
Follow this to sign the APK manually http://developer.android.com/tools/publishing/app-signing.html#signing-manually

**Comment by VenomVendor** [comment]
Auto signing with **redex** should be documented.

**Comment by bonnyfone** [comment]
Yep, it's not that obvious. I suggest to quote the output of 

`redex -h `

inside the README.md so you can get an idea of the possibile params.

**Comment by stephanenicolas** [comment]
Just to help those who arrive here to sign a debug apk and try redex : 
http://stackoverflow.com/a/16711281/693752

`jarsigner -verbose -keystore ~/.android/debug.keystore -storepass android -keypass android path/to/my.apk androiddebugkey`

**Comment by VenomVendor** [comment]
Ideal way of signing would be 
 > redex in.apk -o out.apk  --sign -s /path/to/secret.keystore -a `[KEYALIAS]`  -p `[KEYPASS]`

**Comment by bertmaher** [comment]
I've updated the README with your suggestions, thanks!
