### ISSUE TITLE
clang compile error

### ISSUE THREAD

**Issue by qhdwns123** [facebook/redex#230]
Hi.

I get an error when compiling with clang.

gcc does not generate an error.

Does not clang support?

```
opt/remove-builders/RemoveBuildersHelper.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
opt/remove-builders/RemoveBuildersHelper.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
./.libs/libredex.a(DexUtil.o): In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
./.libs/libredex.a(DexUtil.o): In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1206: recipe for target 'redex-all' failed
make[1]: *** [redex-all] Error 1
make[1]: Leaving directory '/home/oom/redex'
Makefile:1463: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Thanks.

**Comment by wisechengyi** [comment]
I got this error before, the issue was likely some stale boost version in the system.
If you do `brew uninstall boost`, then if there are still relevant result from `find /usr | grep boost`, you might want to remove them (make sure they actually belong to boost instead of some other system libraries)

Once cleaned up:
1. `brew install boost`
2. `git clean -fdx`
3. build as the readme

**Comment by wisechengyi** [comment]
or you can pass some flags to be explicit about where the boost libraries are https://github.com/facebook/redex/issues/193

**Comment by maxmg22** [comment]
Hello @wisechengyi, thanks for reporting this issue, I'll try to repro the build break and let you know when we have a fix.

**Comment by wisechengyi** [comment]
reporter is @qhdwns123 :)

**Comment by maxmg22** [comment]
Oh right, corrected :) thanks!

**Comment by maxmg22** [comment]
@qhdwns123 I couldn't repro the build break, @wisechengyi is right; this would occur only if you have a mismatching boost version in your system.  I did a clean build on the Mac and it worked, did a fresh install of all redex' dependencies and then cloned redex source from git and ran a build and worked.

**Comment by qhdwns123** [comment]
@maxmg22 @wisechengyi 

Hi.

Sorry.

I installed clean Ubuntu and solved the problem.

Thanks.
