### ISSUE TITLE
Segmentation fault when run redex-all

### ISSUE THREAD

**Issue by colinstonema** [facebook/redex#231]
help! what's wrong about this error? 
my env is:  ubuntu-14.04, gcc-4.9.4, libc-2.19.so
gdb info: 
#0  0x0000000000000000 in ?? ()
#1  0x000000000053218a in operator() (__args#0=<optimized out>, this=<optimized out>) at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/functional:2440
#2  operator() (a=<optimized out>, __closure=<optimized out>) at libredex/WorkQueue.h:119
#3  _ZNSt17_Function_handlerIFDnRS0_P15class_load_workEZ17workqueue_foreachIS3_E9WorkQueueIT_S0_S0_ESt8functionIFvS7_EEjEUlS1_S3_E_E9_M_invokeERKSt9_Any_dataS1_S3_ (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/functional:2025
#4  0x0000000000530830 in operator() (__args#1=0x1288d00, __args#0=@0x128a238: <error reading variable>, this=0x7ffdf4698f80)
    at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/functional:2440
#5  consume (task=0x1288d00, state=0x128a1c0, this=0x7ffdf4698f80) at libredex/WorkQueue.h:74
#6  operator() (__closure=<optimized out>, state_idx=<optimized out>, state=0x128a1c0) at libredex/WorkQueue.h:167
#7  _M_invoke<0ul, 1ul> (this=0x128ac18) at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/functional:1700
#8  operator() (this=0x128ac18) at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/functional:1688
#9  std::thread::_Impl<std::_Bind_simple<WorkQueue<Input, Data, Output>::run_all(const Output&) [with Input = class_load_work*; Data = std::nullptr_t; Output = std::nullptr_t]::<lambda((anonymous namespace)::WorkerState<class_load_work*, std::nullptr_t, std::nullptr_t>*, size_t)>((anonymous namespace)::WorkerState<class_load_work*, std::nullptr_t, std::nullptr_t>*, long unsigned int)> >::_M_run(void) (this=0x128ac00) at /home/colin/soft/gcc-4.9.4/release/include/c++/4.9.4/thread:115
#10 0x00007f8effe45e10 in std::execute_native_thread_routine (__p=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/thread.cc:84
#11 0x00007f8eff459184 in start_thread (arg=0x7f8efbd40700) at pthread_create.c:312
#12 0x00007f8efe830ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by maxmg22** [comment]
Hi @colinstonema, I'm taking a look at this, thanks for reporting.  Is there any chance for us to get a repro? In the meantime I'll ping the author of this code to look into it.

**Comment by justinjhendrick** [comment]
Should be fixed in https://github.com/facebook/redex/commit/195cf3c5c32c763e813996bb1b10ea174d92eeb4

**Comment by colinstonema** [comment]
@justinjhendrick  yes,the patch 195cf3c works fine! thank you~
