### ISSUE TITLE
class member mapping is need?

### ISSUE THREAD

**Issue by bunnyblue** [facebook/redex#233]
hello ,i dump dex after redex, redex change some method invoke,and add filed or delete field,like this
![image](https://user-images.githubusercontent.com/1221755/28063581-1e564f7e-6664-11e7-8cbc-acd37d21a832.png)

![image](https://user-images.githubusercontent.com/1221755/28063475-c70e28ea-6663-11e7-976e-ea0ec1809d7f.png)

but ,i not find any class mapping,  class mapping is need for retrace?

**Comment by justinjhendrick** [comment]
There should be a file named `redex-class-rename-map.txt` in the directory you ran `redex` from
