### ISSUE TITLE
Can't run redex when installed via Homebrew

### ISSUE THREAD

**Issue by erawhctim** [facebook/redex#234]
Mac OS 10.12.5, Homebrew v1.2.4

* Installed via `brew install redex`
* Ran `redex -o {output file} {input APK}`

Crash: 
```
dyld: Symbol not found: __ZN5boost16re_detail_10630012perl_matcherIPKcNSt3__19allocatorINS_9sub_matchIS3_EEEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14construct_initERKNS_11basic_regexIcSC_EENS_15regex_constants12_match_flagsE
  Referenced from: /tmp/redex.671dOS/redex-all
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /tmp/redex.671dOS/redex-all
Traceback (most recent call last):
  File "/tmp/redex.671dOS/redex.py", line 504, in <module>
    run_redex(args)
  File "/tmp/redex.671dOS/redex.py", line 445, in run_redex
    dexen)
  File "/tmp/redex.671dOS/redex.py", line 120, in run_pass
    raise err
subprocess.CalledProcessError: Command '/tmp/redex.671dOS/redex-all --apkdir /tmp/redex.671dOS/tmp2a3KIk.redex_extracted_apk --outdir /tmp/redex.671dOS/tmpBJcKPV.redex_dexen /tmp/redex.671dOS/tmpBJcKPV.redex_dexen/dex0/classes.dex /tmp/redex.671dOS/tmpBJcKPV.redex_dexen/dex1/classes2.dex /tmp/redex.671dOS/tmpBJcKPV.redex_dexen/dex2/classes3.dex' returned non-zero exit status -6
```

Let me know if there's some other info I can provide that helps

**Comment by justinjhendrick** [comment]
Which version of boost do you have? Where is it installed?

The brew formula is a bit out of date. If you want the most up to date version, follow the instructions in README.md

**Comment by erawhctim** [comment]
boost v1.64.0
/usr/local/Cellar/boost/1.64.0_1

**Comment by justinjhendrick** [comment]
Hmm... I have the same version of boost installed in the same place. So, I'm not sure of the issue. Could you try the most recent version `brew install redex --HEAD`, please?

We don't make regular releases, we just always build from master. So, if `brew install redex` could default to `brew install redex --HEAD`, that would be ideal.

**Comment by erawhctim** [comment]
That definitely made it work. Thanks! I'll update the brew formula

**Comment by jaredsburrows** [comment]
I had to do the following:
```
brew unlink redex
brew install redex --HEAD
```
