### ISSUE TITLE
dont_rename_packages and keep_packages

### ISSUE THREAD

**Issue by deephole** [facebook/redex#238]
Hello guys,
I'm wondering what's the difference between dont_rename_packages and keep_packages options?
e.g.
"keep_packages": [
  "Lcom/fasterxml/jackson/",
  "Lgenerated_rootmodule/",
  "Lsecondary/",
  "Lcom/google/dexmaker/mockito/",
  "Lcom/facebook/testing",
  "Lcom/facebook/react/",
  "Linjector_autorequire_modules/"
],

  "RenameClassesPassV2" : {
    "class_rename" : "redex-class-rename-map.txt",
    "dont_rename_packages" : [
      "android/",
      "junit/",
      "org/fest/",
      "org/hamcrest/",
      "org/junit/"
    ]
  },

**Comment by justinjhendrick** [comment]
"dont_rename_packages" applies specifically to the class renamer and tells it not to rename any class within the package.

Whereas "keep_packages" is global to all redex passes and tells redex that this package is reached via reflection.

Hope this helps!

**Comment by deephole** [comment]
Thanks, this definitely helps. Is in the reality keep_packages used anywhere else except renaming?

**Comment by justinjhendrick** [comment]
Yes "keep_packages" is used by any pass that wants to delete something. Everything inside the package is [marked](https://github.com/facebook/redex/blob/master/libredex/ReachableClasses.cpp#L310) reachable [by string](https://github.com/facebook/redex/blob/master/libredex/ReachableClasses.cpp#L45) and [by type](https://github.com/facebook/redex/blob/master/libredex/ReferencedState.h#L80). When a pass wants to delete something, it first calls [can_delete](https://github.com/facebook/redex/blob/master/libredex/ReferencedState.h#L50) which checks the `bytype` flag.

If you find a pass that doesn't seem to be honoring "keep_packages", let us know :)

**Comment by justinjhendrick** [comment]
Seems resolved. Closing. Please re-open if necessary.
