### ISSUE TITLE
test make check error

### ISSUE THREAD

**Issue by kele86838437** [facebook/redex#247]
Hi,
I can build source code for redex and redex-all. But when I run the tests, there are some errors. 
My configures:
  gcc version 6.3.0 20170406;
  ubuntu 17.04(64 bit);
  boost_version:1.62

errors:
Making check in .
make[1]: Entering directory '/home/chen/pra_code/dex_pra/redex/test'
make  libgtest_main.la
make[2]: Entering directory '/home/chen/pra_code/dex_pra/redex/test'
make[2]: 'libgtest_main.la' is up to date.
make[2]: Leaving directory '/home/chen/pra_code/dex_pra/redex/test'
make[1]: Leaving directory '/home/chen/pra_code/dex_pra/redex/test'
Making check in integ
make[1]: Entering directory '/home/chen/pra_code/dex_pra/redex/test/integ'
make  synth_test empty_classes_test propagation_test constant_propagation_test
make[2]: Entering directory '/home/chen/pra_code/dex_pra/redex/test/integ'
/bin/bash ../../libtool  --tag=CXX   --mode=link g++ --std=gnu++14    -o synth_test SynthTest.o ../../test/libgtest_main.la ../../libredex.la -ljsoncpp -lz 
libtool: link: g++ --std=gnu++14 -o synth_test SynthTest.o  ../../test/.libs/libgtest_main.a ../../.libs/libredex.a -lboost_filesystem -lboost_system -lboost_regex -lpthread -ljsoncpp -lz
SynthTest.o: In function `ReBindRefsPass::ReBindRefsPass()':
SynthTest.cpp:(.text._ZN14ReBindRefsPassC2Ev[_ZN14ReBindRefsPassC5Ev]+0x6d): undefined reference to `vtable for ReBindRefsPass'
SynthTest.o: In function `SynthPass::SynthPass()':
SynthTest.cpp:(.text._ZN9SynthPassC2Ev[_ZN9SynthPassC5Ev]+0x6d): undefined reference to `vtable for SynthPass'
SynthTest.o: In function `LocalDcePass::LocalDcePass()':
SynthTest.cpp:(.text._ZN12LocalDcePassC2Ev[_ZN12LocalDcePassC5Ev]+0x6d): undefined reference to `vtable for LocalDcePass'
collect2: error: ld returned 1 exit status
Makefile:645: recipe for target 'synth_test' failed
make[2]: *** [synth_test] Error 1
make[2]: Leaving directory '/home/chen/pra_code/dex_pra/redex/test/integ'
Makefile:956: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/chen/pra_code/dex_pra/redex/test/integ'
Makefile:486: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by justinjhendrick** [comment]
We have a different build system internally, so we often forget to keep the Makefiles up to date. I'll go update these soon.

**Comment by NTillmann** [comment]
Seems like the issues has been resolved. Closing for now. Feel free to re-open if appropriate.
