### ISSUE TITLE
Crash in obfuscate pass on Linux host

### ISSUE THREAD

**Issue by deephole** [facebook/redex#257]
Redex crashes (segmentation fault) when running "ObfuscatePass"
I've been debugging this issue for a while but I couldn't find what exactly causes the crash. This is the list of things I know:
    - Crashes only on Linux with "Release" build (you build it with optimization flags by default). I've tried to build with -O0 and it didn't crash.
    - Crashes during ObfuscatePass pass in rename_virtuals > ClassScopes(...) > build_signature_map > build_signature_map ... > build_signature_map
        I will attach stack trace.
    - Crashes with all apps I've been trying with
    - Crash occurs only if your app has any abstract classes/interfaces that are implemented
Also, I've been trying to debug with adress sanitizer. I've noticed you have a lot of memory leaks but that could be due the fact that you perform a lot of asynchronous tasks and adress sanitizer couldn't handle it.
Below are things I used to reproduce the crash:
    redex config:
    {
        "redex" : {
            "passes" : [
            "ObfuscatePass"
            ]
        }
    }
    proguard rules (just a palce holder that does not impact anything and makes obfuscator to rename everything):
        -keep public class * GoodbyeWorld { *; }
    Also, I've provided jar from android sdk:
        /home/Android/Sdk/platforms/android-26/android.jar
    Any apk is fine.

CrashTrace
(anonymous namespace)::build_signature_map(std::unordered_map<DexType const*, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> >, std::hash<DexType const*>, std::equal_to<DexType const*>, std::allocator<std::pair<DexType const* const, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> > > > > const&, DexType const*, std::map<DexString const*, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > >, dexstrings_comparator, std::allocator<std::pair<DexString const* const, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > > > > >&) 0x000000000089b561
(anonymous namespace)::build_signature_map(std::unordered_map<DexType const*, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> >, std::hash<DexType const*>, std::equal_to<DexType const*>, std::allocator<std::pair<DexType const* const, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> > > > > const&, DexType const*, std::map<DexString const*, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > >, dexstrings_comparator, std::allocator<std::pair<DexString const* const, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > > > > >&) 0x000000000089ab04
(anonymous namespace)::build_signature_map(std::unordered_map<DexType const*, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> >, std::hash<DexType const*>, std::equal_to<DexType const*>, std::allocator<std::pair<DexType const* const, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> > > > > const&, DexType const*, std::map<DexString const*, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > >, dexstrings_comparator, std::allocator<std::pair<DexString const* const, std::map<DexProto const*, std::vector<VirtualScope, std::allocator<VirtualScope> >, dexprotos_comparator, std::allocator<std::pair<DexProto const* const, std::vector<VirtualScope, std::allocator<VirtualScope> > > > > > > >&) 0x000000000089ab04
build_signature_map(std::unordered_map<DexType const*, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> >, std::hash<DexType const*>, std::equal_to<DexType const*>, std::allocator<std::pair<DexType const* const, std::set<DexType const*, dextypes_comparator, std::allocator<DexType const*> > > > > const&) 0x000000000089cd6e
ClassScopes::ClassScopes(std::vector<DexClass*, std::allocator<DexClass*> > const&) 0x000000000089d803
rename_virtuals(std::vector<DexClass*, std::allocator<DexClass*> >&) 0x00000000005a3c77
obfuscate(std::vector<DexClass*, std::allocator<DexClass*> >&, RenameStats&) 0x00000000005819f7
ObfuscatePass::run_pass(std::vector<DexStore, std::allocator<DexStore> >&, ConfigFiles&, PassManager&) 0x00000000005828fb
PassManager::run_passes(std::vector<DexStore, std::allocator<DexStore> >&, std::vector<DexClass*, std::allocator<DexClass*> > const&, ConfigFiles&) 0x0000000000783c77

**Comment by deephole** [comment]
Do you need any more information on this?

**Comment by justinjhendrick** [comment]
No thanks, this information is sufficient. Sorry for the delay, I haven't looked into it yet. We don't currently use this pass internally, so it's not very high priority at the moment.

**Comment by justinjhendrick** [comment]
Speaking of AddressSanitizer. Yes, we leak quite a bit, but we're actually not too worried about leaks because we're not a realtime long-running service. The more worrisome memory errors are invalid reads and writes. Does ASan report any invalid reads or writes with Obfuscate pass? Could you ignore leaks for now and show the output of ASan, please?

**Comment by minjang** [comment]
As @justinjhendrick mentioned, ObfuscatePass isn't top priority. It's really in an alpha phase. Meanwhile it's better for you to use ProGuard's obfuscation feature. But we will address this issue later. I can easily guess the bug (VirtualScope), but...
