### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by ASCE1885** [facebook/redex#26]
C02PC5C1FVH5:~ guhaoxin$ brew install boost double-conversion gflags glog libevent
Warning: boost-1.57.0 already installed
==> Installing double-conversion dependency: cmake
==> Downloading http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.2.2.tar.gz
==> Downloading http://www.cmake.org/gitweb?p=cmake.git;a=commitdiff_plain;h=2ec
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8
Actual: 86f228a5f05e2c3a69308bdbfc77141019d3077c28f3ca99a99dbe0a3172f1ba
Archive: /Library/Caches/Homebrew/cmake--patch-147854010874cd68289e3ca203399d5c149287167bca0b67f9c5677f0ee22eb8.git;a=commitdiff_plain;h=2ecf168f
To retry an incomplete download, remove the file above.

**Comment by bertmaher** [comment]
It looks like your homebrew setup is in an inconsistent state.  I can't really help with that since it's not related to redex, but you might try uninstalling cmake (`brew uninstall cmake`) and trying again.

**Comment by ASCE1885** [comment]
`brew update` solve the problem
