### ISSUE TITLE
App crashes on launch after redex compression 

### ISSUE THREAD

**Issue by chethann** [facebook/redex#27]
I did redex compression on the APK, signed and did zipAlign and installed on the device. The app crashes on launch. The logcat says `Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

I have `multiDexEnabled true`. Thank you!

**Comment by aectann** [comment]
Facing similar issue.

**Comment by shmuelr** [comment]
This may not work with Multidex...

**Comment by bertmaher** [comment]
I just fixed a serious bug with multidex support -- it should work now.  Thanks for reporting it!
