### ISSUE TITLE
Unable to create output APK on macOS running El capitan

### ISSUE THREAD

**Issue by sushilr** [facebook/redex#276]
I tried running the binary downloaded from the releases page on my APK and it failed with the following error:
```
./redex_macos_x86_64 debug.apk

dyld: Library not loaded: /usr/local/opt/jsoncpp/lib/libjsoncpp.11.dylib
  Referenced from: /tmp/redex.MMTKjR/redex-all
  Reason: image not found
Traceback (most recent call last):
  File "/tmp/redex.MMTKjR/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.MMTKjR/redex-all', '--apkdir', '/tmp/redex.MMTKjR/tmpt_en6rkj.redex_extracted_apk', '--outdir', '/tmp/redex.MMTKjR/tmps3sxsm0y.redex_dexen', '/tmp/redex.MMTKjR/tmps3sxsm0y.redex_dexen/dex0/classes.dex', '/tmp/redex.MMTKjR/tmps3sxsm0y.redex_dexen/dex1/classes2.dex', '/tmp/redex.MMTKjR/tmps3sxsm0y.redex_dexen/dex2/classes3.dex', '/tmp/redex.MMTKjR/tmps3sxsm0y.redex_dexen/dex3/classes4.dex']' died with <Signals.SIGTRAP: 5>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.MMTKjR/redex.py", line 640, in <module>
    run_redex(args)
  File "/tmp/redex.MMTKjR/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.MMTKjR/redex.py", line 165, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -5! You can re-run it under gdb by running /tmp/redex.MMTKjR/redex-gdb-b4enj9_i.sh or under lldb by running /tmp/redex.MMTKjR/redex-lldb-zd9n6r0_.sh
```

I tried building this from source before I decided to use the binary. I ran into issues when I did that too:
```
In file included from libredex/PluginRegistry.cpp:10:
./libredex/PluginRegistry.h:30:8: error: no type named 'vector' in namespace 'std'
  std::vector<std::unique_ptr<T>> create_plugins() {
  ~~~~~^
./libredex/PluginRegistry.h:30:14: error: expected member name or ';' after declaration specifiers
  std::vector<std::unique_ptr<T>> create_plugins() {
  ~~~~~~~~~~~^
./libredex/PluginRegistry.h:22:5: error: use of undeclared identifier 'm_creators'; did you mean 'creator'?
    m_creators[plugin_name] = std::move(creator);
    ^~~~~~~~~~
    creator
./libredex/PluginRegistry.h:21:66: note: 'creator' declared here
  void register_plugin(const std::string& plugin_name, Creator&& creator) {
                                                                 ^
./libredex/PluginRegistry.h:25:9: error: use of undeclared identifier 'm_creators'
    if (m_creators.count(plugin_name)) {
        ^
./libredex/PluginRegistry.h:26:33: error: use of undeclared identifier 'm_creators'
      return std::unique_ptr<T>(m_creators[plugin_name]());
                                ^
5 errors generated.
make[1]: *** [libredex/PluginRegistry.lo] Error 1
make: *** [all-recursive] Error 1
```

**Comment by justinjhendrick** [comment]
Sorry for the troubles getting redex to run! :/

Downloaded Binary:
I intended to link jsoncpp in statically, but it seems it's happening dynamically :(. I'll try to fix that later. But in the mean time, does `brew install jsoncpp` fix things?

From Source:
Which hash did you build from? On which branch? Which compiler are you using?
It looks like https://github.com/facebook/redex/commit/70a82b873da269e7dd46611c73cfcdf7f84efa1a might fix this issue?

**Comment by sushilr** [comment]
No worries!

> does brew install jsoncpp fix things
No it does not. I had that package installed before I ran this. 

> It looks like 70a82b8 might fix this issue?
Yes, that fixed it. Thank you!

**Comment by franciscofranco** [comment]
I have this exact same issue under High Sierra and I `jsoncpp`
Any hint? Thanks.

**Comment by justinjhendrick** [comment]
Where is libjsoncpp.11.dylib on your system?

Here's what mine looks like

```
$ locate jsoncpp.11.dylib
/usr/local/Cellar/jsoncpp/1.8.1/lib/libjsoncpp.11.dylib
/usr/local/lib/libjsoncpp.11.dylib
```

**Comment by franciscofranco** [comment]
/usr/local/Cellar/jsoncpp/1.8.1/lib/libjsoncpp.11.dylib
I added a symbolic link to /usr/local/lib/libjsoncpp.11.dylib and this particular error doesn't show up anymore, but now it's a new one:

dyld: Symbol not found: __ZN5boost16re_detail_10650012perl_matcherIPKcNSt3__19allocatorINS_9sub_matchIS3_EEEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE14construct_initERKNS_11basic_regexIcSC_EENS_15regex_constants12_match_flagsE
  Referenced from: /tmp/redex.g7MeZf/redex-all
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /tmp/redex.g7MeZf/redex-all
Traceback (most recent call last):
  File "/tmp/redex.g7MeZf/redex.py", line 152, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.g7MeZf/redex-all', '--apkdir', '/tmp/redex.g7MeZf/tmpg6oab306.redex_extracted_apk', '--outdir', '/tmp/redex.g7MeZf/tmp6s0dn91w.redex_dexen', '/tmp/redex.g7MeZf/tmp6s0dn91w.redex_dexen/dex0/classes.dex']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.g7MeZf/redex.py", line 641, in <module>
    run_redex(args)
  File "/tmp/redex.g7MeZf/redex.py", line 570, in run_redex
    debugger)
  File "/tmp/redex.g7MeZf/redex.py", line 165, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.g7MeZf/redex-gdb-5moplzrm.sh or under lldb by running /tmp/redex.g7MeZf/redex-lldb-hcz1tnxn.sh

I guess I'll just ln -s libboost too...

**Comment by franciscofranco** [comment]
I found the issue, I was using the default "GCC-4.2.1 Clang Edition" bullshit, installed gcc-4.9 through brew, made sure gcc --version showed 4.9.4, make clean, config everything again, make install, and voilá, everything works. I read the instructions beforehand, but I assumed I was already using a newer GCC.

**Comment by justinjhendrick** [comment]
Seems resolved. Closing
