### ISSUE TITLE
Couldn't find zipalign.  Your APK may not be fully optimized.

### ISSUE THREAD

**Issue by kirussell** [facebook/redex#28]
$ANDROID_SDK environment variable is set to "/Users/<username>/Library/Android/sdk"
where build-tools/22.0.1 and build-tools/23.0.2 are available, both have zipalign file
Also tried to put zipalign to directories with target apks

**Comment by VenomVendor** [comment]
Add this to your `$PATH`
`export PATH=$PATH:/Users//Library/Android/sdk/build-tools/23.0.2`

**Comment by kirussell** [comment]
Sorry, my  bad, all works fine, $ANDROID_SDK var were reseted to another value.
