### ISSUE TITLE
Wrong command in build instructions for windows

### ISSUE THREAD

**Issue by diegoflassa** [facebook/redex#283]
In the file [README.md](https://github.com/facebook/redex/blob/master/README.md)
In the section [Experimental: CMake for Mac, Linux, and Windows](https://github.com/facebook/redex#experimental-cmake-for-mac-linux-and-windows)
there is the command

<pre>
cmake .. -G "Visual Studio 15 2017 Win64"` -DVCPKG_TARGET_TRIPLET=x64-windows-static` -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
</pre>

Trying to use it result iun the error

<pre>CMake Error: Could not create named generator Visual Studio 15 2017 Win64`</pre>

The cause is the ` character, next to  "Win64" and "x64-windows-static"
To fix, just remove them as in example below

<pre>
cmake .. -G "Visual Studio 15 2017 Win64" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE="C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
</pre>

**Comment by justinjhendrick** [comment]
cc @minjang

**Comment by minjang** [comment]
@diegoflassa Thanks for reporting. This backtick is for line separation in PowerShell. So, it depends on your environment. But it's good to remove to prevent any confusion. Thanks!
