### ISSUE TITLE
Inliner gen_callee_reg_map() does not respect ushort limits

### ISSUE THREAD

**Issue by mvolkus** [facebook/redex#294]
Register map generator in `gen_callee_reg_map() ` creates a map by incrementing registers from caller reg size:
`reg_map->emplace(i, callee_reg_start + i);`

If `callee_reg_start + i` is higher than USHRT_MAX, overflow happens, which invalidates the code and results in errors like Type violation later during regalloc pass.

**Comment by justinjhendrick** [comment]
You're right, it could overflow. But the max register for dalvik is 2**16 anyway. Do you have a method with more than 2**15 registers? That's huge! Does running it through redex send it over the top? If so, could you send me the apk as an example?

**Comment by mvolkus** [comment]
This happens only when I try to merge multiple large methods using inliner. I believe the 65535 register limit is only applicable when printing out the dex, IR representation may be able to hold larger values since these will be reduced during instruction lowering step.
I guess a solution in my case would be running instruction lowering manually in between inlining.

**Comment by justinjhendrick** [comment]
enhancement: allow more registers in IR
