### ISSUE TITLE
[Makefile:1844: all-recursive] Error 1

### ISSUE THREAD

**Issue by blacpythoz** [facebook/redex#298]
All the make log output after
`autoreconf -ivf && ./configure && make -j4`

[https://pastebin.com/ZfvfSrq2](url)

I had also tried with cmake and got the error.
`cmake ..`
[https://pastebin.com/kSMwtR7T](url)

I am currently on arch linux

**Comment by justinjhendrick** [comment]
Which compiler are you using? And what version? If I'm reading the logs right, it's gcc-7.3. Try again with gcc6 and see if that works?

libresource is something we've included (and made changes to) from the AOSP project. It looks like there is an issue compiling AOSP with gcc7: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853312

See discussion of a similar report here: https://github.com/facebook/redex/issues/286
