### ISSUE TITLE
m_virtual = true before cls->remove will cause assert(erased)

### ISSUE THREAD

**Issue by plasta** [facebook/redex#299]
https://github.com/facebook/redex/blob/5c7e8239ad34c0446c67393a9eda0b4d8cb0faee/libredex/DexClass.cpp#L569

"m_virtual = true" should be moved after "cls->remove_method(this);"

**Comment by justinjhendrick** [comment]
Good catch!

I can see why it would be correct to move the write to `m_virtual` until after we've actually taken it out of the list of direct methods. It violates an invariant (all methods in the `dmethods` vector are not virtual) when `remove_method()` is called.

Would you like to submit a pull request to fix this bug? To merge the pull request, you would need to sign this: https://code.facebook.com/cla

If you don't want to submit a PR, we can fix it internally as well.

**Comment by plasta** [comment]
Hi,
Feel free to fix it internally, thanks
