### ISSUE TITLE
Can't insert DBG_SET_PROLOGUE_END and DBG_START_LOCAL instructions

### ISSUE THREAD

**Issue by ltmarys** [facebook/redex#301]
Is there any way to create and insert new DBG_SET_PROLOGUE_END and DBG_START_LOCAL instructions into the IRCode?

**Comment by justinjhendrick** [comment]
What is your high-level goal? I'm happy to help :)

`MFLOW_POSITION` entries correspond to the `std::unique_ptr<DexPosition> pos` value of the union, not the `IRInstruction* insn` value. An `MFLOW_POSITION` with an opcode isn't a well formed `MethodItemEntry`.

If you'd prefer to have the help discussion on a less public setting, feel free to email me, justinjhendrick@gmail.com

**Comment by ltmarys** [comment]
I've changed my question regarding the insertion.

**Comment by justinjhendrick** [comment]
You'll want to use `MFLOW_DEBUG` instead of `MFLOW_POSITION`. Here's a small code example.

```
  auto dbg = std::make_unique<DexDebugInstruction>(DBG_SET_PROLOGUE_END);
  auto mie = new MethodItemEntry(std::move(dbg));
  code->push_back(mie); // or insert_before, insert_after, etc.
```

Also see https://github.com/facebook/redex/blob/master/libredex/DexDebugInstruction.h and https://github.com/facebook/redex/blob/master/shared/DexDefs.h#L148-L160
