### ISSUE TITLE
Issue while building redex on MacOS 10.13.3

### ISSUE THREAD

**Issue by monil1334** [facebook/redex#303]
Getting this error on MacOS while building redex. I tried running 
sudo autoreconf -ivf && ./configure && make -j4 and also without sudo.

depbase=`echo tools/common/DexCommon.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	g++ -DPACKAGE_NAME=\"redex\" -DPACKAGE_TARNAME=\"redex\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"redex\ 1.0\" -DPACKAGE_BUGREPORT=\"not-valid-yet@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_FILESYSTEM=/\*\*/ -DHAVE_BOOST_SYSTEM=/\*\*/ -DHAVE_BOOST_REGEX=/\*\*/ -DHAVE_BOOST_PROGRAM_OPTIONS=/\*\*/ -DHAVE_BOOST_IOSTREAMS=/\*\*/ -DHAVE_BOOST_THREAD=/\*\*/ -DHAVE_LIBZ=1 -DHAVE_LIBJSONCPP=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MUNMAP=1 -DHAVE_REGCOMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -I.  -I./liblocator -I./libredex -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/access-marking -I./opt/add_redex_txt_to_apk -I./opt/analysis_ref_graph -I./opt/annoclasskill -I./opt/annokill -I./opt/bridge -I./opt/check_breadcrumbs -I./opt/constant-propagation -I./opt/dedup_blocks -I./opt/delinit -I./opt/delsuper -I./opt/final_inline -I./opt/hotness-score -I./opt/inlineinit -I./opt/interdex -I./opt/local-dce -I./opt/obfuscate -I./opt/original_name -I./opt/outliner -I./opt/peephole -I./opt/print-members -I./opt/rebindrefs -I./opt/redundant_move_elimination -I./opt/regalloc -I./opt/remove-builders -I./opt/remove-unreachable -I./opt/remove_empty_classes -I./opt/remove_gotos -I./opt/renameclasses -I./opt/reorder-interfaces -I./opt/shorten-srcstrings -I./opt/simpleinline -I./opt/singleimpl -I./opt/static-sink -I./opt/staticrelo -I./opt/string_simplification -I./opt/strip-debug-info -I./opt/synth -I./opt/test_cfg -I./opt/track_resources -I./opt/unreferenced_interfaces -I./opt/unterface -I./opt/verifier -I./opt/virtual_scope -I./shared -I./tools/common -I./tools/redexdump -I./util -I/usr/include/jsoncpp  --std=gnu++14 -O3 -Wall -g  -MT tools/common/DexCommon.o -MD -MP -MF $depbase.Tpo -c -o tools/common/DexCommon.o tools/common/DexCommon.cpp &&\
	mv -f $depbase.Tpo $depbase.Po

error: error opening 'tools/redexdump/.deps/PrintUtil.Tpo': Permission denied
1 error generated.
make[1]: *** [tools/redexdump/PrintUtil.o] Error 1
make[1]: *** Waiting for unfinished jobs....
error: error opening 'tools/common/.deps/DexCommon.Tpo': Permission denied
1 error generated.
make[1]: *** [tools/common/DexCommon.o] Error 1
error: error opening 'tools/redexdump/.deps/RedexDump.Tpo': Permission denied
1 error generated.
make[1]: *** [tools/redexdump/RedexDump.o] Error 1
error: error opening 'tools/redexdump/.deps/DumpTables.Tpo': Permission denied
1 error generated.
make[1]: *** [tools/redexdump/DumpTables.o] Error 1
make: *** [all-recursive] Error 1

**Comment by justinjhendrick** [comment]
Hmmm... I wonder if running `autoreconf` as `root` the first time created the directories owned by root, the next run may not fully clean out those directories owned by root

If you check out a fresh copy of redex (or delete all untracked files and directories with`git clean -xfd`), then run `autoreconf -ivf && ./configure && make -j4`, will that work?

**Comment by monil1334** [comment]
sudo git clean -xfd  solved the issue!

**Comment by monil1334** [comment]
while building from redex got another issue...

redex path/to/test.apk -o path/to/new.apk

yld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/bin/redex-all
  Reason: image not found
Traceback (most recent call last):
  File "/tmp/redex.8XeVnT/redex.py", line 173, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/redex-all', '--apkdir', '/tmp/redex.8XeVnT/tmpdk83wsls.redex_extracted_apk', '--outdir', '/tmp/redex.8XeVnT/tmpjvaezsa6.redex_dexen', '/tmp/redex.8XeVnT/tmpjvaezsa6.redex_dexen/dex0/classes.dex', '/tmp/redex.8XeVnT/tmpjvaezsa6.redex_dexen/dex1/classes2.dex']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.8XeVnT/redex.py", line 687, in <module>
    run_redex(args)
  File "/tmp/redex.8XeVnT/redex.py", line 605, in run_redex
    debugger)
  File "/tmp/redex.8XeVnT/redex.py", line 186, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.8XeVnT/redex-gdb-6mj1ufyn.sh or under lldb by running /tmp/redex.8XeVnT/redex-lldb-n44l6aey.sh

**Comment by justinjhendrick** [comment]
I didn't know we depended on libevent... Huh.

Does `brew install libevent` fix it?

**Comment by monil1334** [comment]
@justinjhendrick It is already installed but i have version libevent 2.1.8 and it is expecting 2.0.5

**Comment by justinjhendrick** [comment]
Hmmm... I'm unable to repro. I just built on a 10.13.3 macOS with libevent 2.1.6 installed. So it's not an issue of backwards compatibility between 2.1.x and 2.0.x.

**Comment by justinjhendrick** [comment]
Lets see if we can get some more logging. Could you enable trace

```
$ export TRACE=1;
```

And paste the logs please?

**Comment by justinjhendrick** [comment]
Does this help https://apple.stackexchange.com/questions/127186/installing-tmux-but-getting-dyld-library-not-loaded-referenced-from-usr ?

**Comment by monil1334** [comment]
Libevent was installed fine although i did relink it. Logs after trace

Using config (default)
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 0.40 seconds
Running redex-all on 2 dex files
Running redex binary at /usr/local/bin/redex-all
dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.0.5.dylib
  Referenced from: /usr/local/bin/redex-all
  Reason: image not found
Traceback (most recent call last):
  File "/tmp/redex.XpmSty/redex.py", line 173, in run_pass
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/redex-all', '--apkdir', '/tmp/redex.XpmSty/tmp635jzuv5.redex_extracted_apk', '--outdir', '/tmp/redex.XpmSty/tmp1u9xqti_.redex_dexen', '/tmp/redex.XpmSty/tmp1u9xqti_.redex_dexen/dex0/classes.dex', '/tmp/redex.XpmSty/tmp1u9xqti_.redex_dexen/dex1/classes2.dex']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.XpmSty/redex.py", line 687, in <module>
    run_redex(args)
  File "/tmp/redex.XpmSty/redex.py", line 605, in run_redex
    debugger)
  File "/tmp/redex.XpmSty/redex.py", line 186, in run_pass
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.XpmSty/redex-gdb-_oh6jq49.sh or under lldb by running /tmp/redex.XpmSty/redex-lldb-5nk712ov.sh

**Comment by justinjhendrick** [comment]
Someone found a workaround to a similar issue here: https://github.com/amberframework/micrate/issues/17

Not ideal, but maybe it'll work.

**Comment by monil1334** [comment]
@justinjhendrick  thanks, will give it a shot!
