### ISSUE TITLE
Obfuscate pass sets wrong DexMethodRef in instructions

### ISSUE THREAD

**Issue by mvolkus** [facebook/redex#306]
`Obfuscate::update_refs` modifies IRInstructions with new method refs. In some cases, it may set ref to parent class' method instead of the actual one. This causes problems in further analysis.

Example (attached): If parent class has a private method and derived class has public virtual method with the same prototype, some calls to derived class method will hold reference to base class method after Obfuscate pass. In this case, virtual call to `DerivedCls2::pan()` in `DerivedCls2::n()` will turn to call to `BaseCls::pan()`.
Running SimpleInlinePass after Obfuscate turns base class private method into static, causing changed instructions that have wrong method reference to be invalid (INVOKE_VIRTUAL to a static method):

> IRTypeChecker.cpp:654: void irtc_impl::TypeInference::analyze_instruction(IRInstruction *, TypeEnvironment *) const: assertion `insn->arg_word_count() > src_idx' failed.
> invalid insn INVOKE_VIRTUAL v0, Lcom/example/mvolkus/testrepro/BaseCls;.B:(Lcom/example/mvolkus/testrepro/BaseCls;)V

(`pan` has been renamed to B in this case)

I've attached class sources and config files for repro. I can't attach apk file as the type isn't supported.

[BaseCls.txt](https://github.com/facebook/redex/files/1819686/BaseCls.txt)
[DerivedCls.txt](https://github.com/facebook/redex/files/1819687/DerivedCls.txt)
[DerivedCls2.txt](https://github.com/facebook/redex/files/1819688/DerivedCls2.txt)
[MainActivity.txt](https://github.com/facebook/redex/files/1819689/MainActivity.txt)
[proguard.txt](https://github.com/facebook/redex/files/1819690/proguard.txt)
[cfg.txt](https://github.com/facebook/redex/files/1819693/cfg.txt)

The command line I'm running:

> redex -c cfg.json -P proguard.txt -j "/path/to/Library/Android/sdk/platforms/android-26/android.jar" app-debug.apk -o output.apk

**Comment by justinjhendrick** [comment]
I can repro this crash. I'm working on it. Thanks for the detailed report!

**Comment by justinjhendrick** [comment]
I have a fix and it's in code review now
