### ISSUE TITLE
Issue compiling - recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by 0x2f0713** [facebook/redex#307]
I have tried the `autoreconf -ivf && ./configure && make -j4` command and received the error: `Makefile:1894: recipe for target "all" failed`. Please help me to solve this problem.

**Comment by justinjhendrick** [comment]
I suspect some other error occurred before `recipe for target "all" failed` but it's hard to find because the error log is interleaved with the other three building threads. Could you rerun it with a single thread?

Try running `make` instead of `make -j4` and paste the full error log here, please

**Comment by 0x2f0713** [comment]
![Imgur](https://i.imgur.com/E7ENnln.png)
`In file included from ./libresource/androidfw/ResourceTypes.h:27:0,
                 from libredex/RedexResources.h:17,
                 from libredex/ReachableClasses.cpp:23:
./libresource/utils/Vector.h: In member function ‘const android::Vector<T>& android::Vector<TYPE>::operator=(const android::Vector<TYPE>&) const’:
./libresource/utils/Vector.h:255:64: error: no matching function for call to ‘android::Vector<TYPE>::operator=(const android::VectorImpl&) const’
     VectorImpl::operator = (static_cast<const VectorImpl&>(rhs));
                                                                ^
In file included from ./libresource/utils/Vector.h:30:0,
                 from ./libresource/androidfw/ResourceTypes.h:27,
                 from libredex/RedexResources.h:17,
                 from libredex/ReachableClasses.cpp:23:
./libresource/utils/VectorImpl.h:56:29: note: candidate: android::VectorImpl& android::VectorImpl::operator=(const android::VectorImpl&) <near match>
             VectorImpl&     operator = (const VectorImpl& rhs);
                             ^~~~~~~~
./libresource/utils/VectorImpl.h:56:29: note:   passing ‘const android::Vector<TYPE>*’ as ‘this’ argument discards qualifiers
Makefile:1866: recipe for target 'libredex/ReachableClasses.lo' failed
make[1]: *** [libredex/ReachableClasses.lo] Error 1
make[1]: Leaving directory '/home/admin/redex'
Makefile:1894: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`
Here is the error which I have received.

**Comment by justinjhendrick** [comment]
Thanks for the full report log :)

This looks like the same error as #298 which came up while investigating #286 as well. 

Please see the discussion on those issues and let me know if those workaround help.

I'm going to see if deleting the `operator=(...) const` method will fix this.

**Comment by justinjhendrick** [comment]
does rebasing past 253b771 fix things for you? If so, feel free to close this issue

**Comment by 0x2f0713** [comment]
I think this issue has been solved, thank you so much.!
![Imgur](https://i.imgur.com/FoFQeoo.png)

**Comment by 0x2f0713** [comment]
How to convert the dex.zxs file to original .dex file?

**Comment by justinjhendrick** [comment]
For the zipalign issue, see the readme: https://github.com/facebook/redex/#im-getting-couldnt-find-zipalign-see-readmemd-to-resolve-this

I think a `.xzs` file is multiple files concatenated together then compressed with `xz`. `redex -u example.apk` should unpack an apk and its `xzs` files for you and print the directory it unpacked into.

**Comment by 0x2f0713** [comment]
Thank you so much. I am closing these issues now.

**Comment by huaixiaohuai** [comment]
> I think this issue has been solved, thank you so much.!
> ![Imgur](https://camo.githubusercontent.com/d26d7407fd30ee5ff7e5ec213f37e7d116efdbee/68747470733a2f2f692e696d6775722e636f6d2f466f4651656f6f2e706e67)

How did solve this issue? I'm tracked with the same problem as you. Could you give some tips?
