### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by paijwar** [facebook/redex#31]
Platform is OSX

./../folly/SingletonThreadLocal.h:33:36: warning: initialized lambda captures are a C++14 extension
      [-Wc++14-extensions]
          return new ThreadLocalT([createFunc =
                                   ^
In file included from io/async/AsyncPipe.cpp:16:
In file included from ./../folly/io/async/AsyncPipe.h:18:
In file included from ./../folly/io/async/AsyncTransport.h:26:
./../folly/io/async/ssl/OpenSSLPtrTypes.h:20:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
2 warnings and 1 error generated.
make[4]: *** [io/async/AsyncPipe.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by sealskej** [comment]
Solution is mentioned in #7 but it leads to another issue.

**Comment by paijwar** [comment]
Code is still not compilable how can this be closed?
only error changed due to #7 
Now error logs come as below

libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT portability/Malloc.lo -MD -MP -MF portability/.deps/Malloc.Tpo -c portability/Malloc.cpp  -fno-common -DPIC -o portability/.libs/Malloc.o
In file included from portability/Malloc.cpp:17:
./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);
           ^
1 error generated.
make[4]: *** [portability/Malloc.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
