### ISSUE TITLE
ApkManager.cpp:17 control may reach end of non-void function

### ISSUE THREAD

**Issue by JoeLoser** [facebook/redex#312]
`libredex/ApkManager.cpp:17:1: warning: control may reach end of non-void function [-Wreturn-type]`

**Problem**:
`check_directory` does not return a bool in every possible code path. See [here](https://github.com/facebook/redex/blob/master/libredex/ApkManager.cpp#L11).

**Solution**:
Simply return true at the end of the function.

**Comment**: the function `check_directory` should probably take its argument by const reference to denote that it is not changing the original parameter.

**Comment by justinjhendrick** [comment]
Agreed. A fix is in the works and will be committed soon.
