### ISSUE TITLE
Output dex file size of 16mb can be exceeded

### ISSUE THREAD

**Issue by deephole** [facebook/redex#315]
Output dex file size of 16 MB can be exceeded if there's many long strings in the APK.

`$ ./redex.py app-debug.apk 
0   redex-all                           0x000000010f5b3994 _ZN12_GLOBAL__N_115crash_backtraceEv + 52
1   redex-all                           0x000000010f5b3930 _Z23crash_backtrace_handleri + 16
2   libsystem_platform.dylib            0x00007fff547f2f5a _sigtramp + 26
3   ???                                 0x00007ffee06f3528 0x0 + 140732663805224
4   redex-all                           0x000000010f6965ba _ZN9DexString6encodeEPh + 74
5   redex-all                           0x000000010f695fd1 _ZN9DexOutput20generate_string_dataE8SortMode + 3137
6   redex-all                           0x000000010f6aa63f _ZN9DexOutput7prepareE8SortModeRKNSt3__16vectorIS0_NS1_9allocatorIS0_EEEE + 79
7   redex-all                           0x000000010f6abcf5 _Z20write_classes_to_dexNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEPNS_6vectorIP8DexClassNS3_IS8_EEEEPNS_13unordered_mapIP9DexStringN8facebook7LocatorENS_4hashISE_EENS_8equal_toISE_EENS3_INS_4pairIKSE_SG_EEEEEEmR11ConfigFilesRKN4Json5ValueEP14PositionMapper + 5317
8   redex-all                           0x00000001103b6a22 main + 23634
9   libdyld.dylib                       0x00007fff54571115 start + 1
10  ???                                 0x0000000000000006 0x0 + 6`

[dex-size-limit.zip](https://github.com/facebook/redex/files/1919440/dex-size-limit.zip)

DexOutput.cpp has constant "constexpr uint32_t k_max_dex_size = 16 * 1024 * 1024;".  I didn't find in DEX specification any mention of this file size, could you point to any reference?

**Comment by justinjhendrick** [comment]
The only max size I can find in the spec is 2^32 bytes. 16M may have been chosen for convenience sake. We haven't hit this error before because we're usually constrained by MethodRefs per dex. What happens if you double it? Does that unblock you? Have you considered moving those strings out of the dex and into the resources?

**Comment by deephole** [comment]
Doubling it solves the issue. I was concerned about increasing this constant as I didn't realise where this number coming from. Looks like it is OK to double it. Thanks!

**Comment by justinjhendrick** [comment]
Yeah, I've found quite a few arbitrary sizes like that in DexOutput. It was written in a C style without much use of dynamically sized memory. Seems solved for now. Closing.
