### ISSUE TITLE
PC stuck when running dump_classes_from_hprof.py

### ISSUE THREAD

**Issue by liush55** [facebook/redex#319]
after running command line 
/local/opensource/redex/tools/hprof/dump_classes_from_hprof.py --hprof my.hprof > list_of_classes.txt
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/array
from: can't read /var/mail/collections
...

**Comment by liush55** [comment]
[myapp.hprof.tar.gz](https://github.com/facebook/redex/files/1987250/myapp.hprof.tar.gz)
![screenshot](https://user-images.githubusercontent.com/19220129/39808170-d01cdc7a-53b0-11e8-809e-e1b5bf14a58c.png)

**Comment by justinjhendrick** [comment]
https://stackoverflow.com/questions/16069816/getting-python-error-from-cant-read-var-mail-bio

We didn't include a `#!/usr/bin/env python`, so you'll have to invoke it with `python dump_classes_from_hprof.py ...`. If you'd like, you could send a pull request to add the `#!/usr/bin/env python` at the top of the file.
