### ISSUE TITLE
PC stuck when running redex/tools/hprof/dump_classes_from_hprof.py

### ISSUE THREAD

**Issue by liush55** [facebook/redex#320]
[myapp.hprof.tar.gz](https://github.com/facebook/redex/files/1990078/myapp.hprof.tar.gz)
![screenshot from 2018-05-10 10 20 22](https://user-images.githubusercontent.com/19220129/39848832-e6a157b0-543b-11e8-8931-3bcc5761909a.png)

**Comment by liush55** [comment]
add #!/usr/bin/env python3 in python file resolved this issue

**Comment by justinjhendrick** [comment]
duplicate of #319
