### ISSUE TITLE
Problems with RemoveGotos pass

### ISSUE THREAD

**Issue by awelc** [facebook/redex#321]
It seems like there are some problems with the RemoveGotos pass that prevent it from running correctly on fairly simple programs. There seems to be two distinct problems:

1. The `ControlFlowGraph::merge_blocks` method updates neither `m_entry_block` nor `m_exit_block`. While I am not 100% certain that the latter is problematic, not updating `m_entry_block` when it is the block being removed during merge may result in `ControlFlowGraph::remove_unreachable_succ_edges` method to start visiting blocks starting with the block that has just been removed which may in turn result in the entire control flow graph being erased.

2. The RemoveGotos transformation appears to be performed based solely on the information about structure of the CFG and the resulting transformed code may differ semantically from the original one due to data dependencies being violated.

Here is a sample Java program that should help understand how these problems manifest themselves (it is clearly not thread safe - it has been simplified for presentation purposes):
```java
public class Test {
    private static Foo bar;
    public static Foo get() {
        for (;;) {
            Foo f = bar;
            if (f != null)
                return f;
            bar = new Foo();
        }
    }

    private static class Foo {
        int i = 42;
    }

    public static void main(String[] args) {
        System.out.println(get().i);
    }
}
```

Below are the steps to create a dex file that can be processed by Redex. I used the most recent version of Redex (commit sha eac37422930b5080c6596fb1b7de740484420f39), the most recent version of d8 (commit sha 22034387245cd8befc20b606af9606ef1e46bbeb), and the following Redex config file:
```
{
  "redex" : {
    "passes" : [
      "RemoveGotosPass"
    ]
  }
}
```
Please assume that the test file is called Test.java and has been placed in ~/test directory (which also contains Redex config file called stripped_config), r8 has been built in the ~/r8 directory, and Android SDK (including files for API 27) is located in the android-sdk directory:
```
cd ~/test
javac Test.java
jar cvf test.jar *.class
mkdir out_d8
java -jar ~/r8/build/libs/d8.jar --classpath ~/android-sdk/platforms/android-27/android.jar --output out_d8/ test.jar
cd out_d8/
zip classes.apk classes.dex
```

The following Redex invocation (in ~/test directory) will crash, which represents the first problem described above:
`TRACE=RMGOTO:6 redex out_d8/classes.apk -c stripped.config`

As a side note, I disabled multi-threading in Redex using the following diff (though there is probably a better way but I could not find it):
```diff
diff --git a/libredex/Walkers.h b/libredex/Walkers.h
index dd9b753..dc6dae8 100644
--- a/libredex/Walkers.h
+++ b/libredex/Walkers.h
@@ -567,7 +567,7 @@ class walk {
      * default.
      */
     static unsigned int default_num_threads() {
-      unsigned int threads = std::thread::hardware_concurrency() / 2;
+      unsigned int threads = 1; //std::thread::hardware_concurrency() / 2;
       return std::max(1u, threads);
     }
```

The relevant fragment of the stack trace representing the crash looks as follows:
```
0   redex-all                           0x00000001033ae7a2 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff75c5ef5a _sigtramp + 26
2   redex-all                           0x00000001031990b3 _ZNSt3__116__pad_and_outputIcNS_11char_traitsIcEEEENS_19ostreambuf_iteratorIT_T0_EES6_PKS4_S8_S8_RNS_8ios_baseES4_ + 211
3   redex-all                           0x00000001033a23cb _ZN3cfg16ControlFlowGraph29remove_unreachable_succ_edgesEv + 75
4   redex-all                           0x00000001033a45c9 _ZN3cfg16ControlFlowGraph25remove_unreachable_blocksEv + 25
5   redex-all                           0x00000001033a1d7a _ZN3cfg16ControlFlowGraph8simplifyEv + 42
6   redex-all                           0x00000001033a6455 _ZN3cfg16ControlFlowGraph9linearizeEv + 149
7   redex-all                           0x00000001034052d9 _ZN6IRCode9clear_cfgEv + 41
8   redex-all                           0x00000001032e2c99 _ZN12_GLOBAL__N_111RemoveGotos14process_methodEP9DexMethod + 2409
```

This crash is, as far as I can tell, a result of `visited` set in `ControlFlowGraph::remove_unreachable_succ_edges` method being populated with the removed block whose ID==0, as this set is initialized with `m_entry_block` that has not been updated during block merge.

In order to illustrate the second problem described above, here is the CFG representing `Test.get` method after it has been processed by RemoveGotos pass:
```
 Block B1:
   preds: (goto B2)
   [0x7fd8ef300270] POSITION: Test.java:9
   [0x7fd8ede00590] OPCODE: RETURN_OBJECT v0
   succs:
 Block B2:
   preds: (branch B2)
   [0x7fd8ef300290] POSITION: Test.java:11
   [0x7fd8ede005f0] OPCODE: NEW_INSTANCE LTest$Foo;
   [0x7fd8ef300130] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
   [0x7fd8ede00650] OPCODE: CONST v1, 0
   [0x7fd8ede006b0] OPCODE: INVOKE_DIRECT v0, v1, LTest$Foo;.<init>:(LTest$1;)V
   [0x7fd8ede00710] OPCODE: SPUT_OBJECT v0, LTest;.bar:LTest$Foo;
   [0x7fd8ef3002b0] POSITION: Test.java:12
   [0x7fd8ef300230] POSITION: Test.java:7
   [0x7fd8ede004d0] OPCODE: SGET_OBJECT LTest;.bar:LTest$Foo;
   [0x7fd8ef300000] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
   [0x7fd8ef300250] POSITION: Test.java:8
   [0x7fd8ede00530] OPCODE: IF_EQZ v0
   succs: (branch B2) (goto B1)
```

Even if this CFG would be linearized correctly (after the first problem is fixed) it does not seem to represent a method that is semantically equivalent to the original one. My attempt to reconstruct a source program from this CFG results in the following:
```
    public static Foo get() {
        for (;;) {
            bar = new Foo();
            Foo f = bar;
            if (f != null) {
                return f;
            }
        }
    }
```
Please note that while the original program permits an existing value of `bar` to flow into the `get` method and be returned, the modified one always overwrites `bar` at the beginning of the loop.

**Comment by justinjhendrick** [comment]
You're right. That is broken. A fix is in the works.

Thanks for flagging!
