### ISSUE TITLE
What happened to OptimizeResourcesPass in redex?

### ISSUE THREAD

**Issue by kageiit** [facebook/redex#322]
Saw the talk at SF Droidcon last year: https://droidcon-server.herokuapp.com/showSession/111638

It mentioned a pass in redex to optimize `resources.arsc` and remove unused resources.

There seem to be some references to this in redex (https://github.com/facebook/redex/commit/62dd8ed022b4112570cdffc0eb56105c2c53b95a) but no ability to actually use it. Is this something that is possible or is it a work in progress?

cc @tophyr

**Comment by wsanville** [comment]
OptimizeResourcesPass in its current form isn't self contained and requires another tool (not open sourced) to fully do the job of eliminating unused things. We'd like to open source it, but it will need some cleanup first.

**Comment by andreasnomikos** [comment]
bump @wsanville @justinjhendrick

**Comment by wsanville** [comment]
The pass is now here https://github.com/facebook/redex/tree/main/opt/optimize_resources and we've recently pushed several other passes that also can reduce the amount of resource metadata in other ways.

For a while we've wanted to get to this, i.e. clean up the passes, make them self contained and open source. But it wasn't until more recently that we blew off the dust, removed internal dependencies, and updated the code for newer file formats. Dead resource elimination and other resource passes also work against app bundle input files too.
