### ISSUE TITLE
Retrolambda android library probable issue.

### ISSUE THREAD

**Issue by jmodrako** [facebook/redex#33]
Probably redex does not work with Retrolambda:

./redex old.apk -o ~/new.apk
opt/bridge/Bridge.cpp:292: void BridgeRemover::delete_unused_bridgees(): assertion `bridge->is_virtual()' failed.
bridge: private private com.example.ExpandableListAdapter.lambda$onBindViewHolder$129(Lpl/example/android/common/ExpandableListAdapter$Group;Landroid/view/View;)V
bridgee: private private com.example.ExpandableListAdapter.refreshList(Lpl/example/android/common/ExpandableListAdapter$Group;)V
  annotations:type:Ldalvik/annotation/Signature; visibility:system annotations:value:( Lpl/example/android/common/ExpandableListAdapter$Group < Lpl/example/android/festival/breweries/FestivalBrewery; Lpl/example/android/festival/breweries/FestivalBeer; >;)V
0   redex-all                           0x000000010973ba14 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9187052a _sigtramp + 26
2   ???                                 0x00007fff60e39552 0x0 + 140734818915666
3   libsystem_c.dylib                   0x00007fff83c586e7 abort + 129
4   redex-all                           0x000000010973b9d1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x00000001097b3a17 _ZN13BridgeRemover22delete_unused_bridgeesEv + 215
6   redex-all                           0x00000001097b36ec _ZN13BridgeRemover3runEv + 92
7   redex-all                           0x00000001097b3552 _ZN10BridgePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER8PgoFiles + 114
8   redex-all                           0x000000010975d398 _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEE + 312
9   redex-all                           0x0000000109804eb8 main + 2168
10  libdyld.dylib                       0x00007fff874495ad start + 1
11  ???                                 0x0000000000000006 0x0 + 6
Traceback (most recent call last):
  File "./redex", line 779, in <module>
    run_redex(args)
  File "./redex", line 735, in run_redex
    dexen)
  File "./redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /var/folders/fl/x0_3ssc93zvf9kn4d4p2___00000gn/T/tmpoqze1ul4.redex_extracted_apk --outdir /var/folders/fl/x0_3ssc93zvf9kn4d4p2___00000gn/T/tmpenvbqlvi.redex_dexen /var/folders/fl/x0_3ssc93zvf9kn4d4p2___00000gn/T/tmpenvbqlvi.redex_dexen/dex0/classes.dex' returned non-zero exit status -6

**Comment by yelinaung** [comment]
I can assure that happens in one of the apps using [gradle-retrolambda](https://github.com/evant/gradle-retrolambda) as well. 

Here are some logs

```
yla:redex ~ redex /Users/yelinaung/..../app-release.apk -o /Users/yelinaung/Downloads/output.apk
opt/bridge/Bridge.cpp:292: void BridgeRemover::delete_unused_bridgees(): assertion `bridge->is_virtual()' failed.
bridge: private com.example.MainActivity.lambda$promptDialog$6(Ljava/lang/String;Landroid/content/DialogInterface;I)V
bridgee: private com.example.MainActivity.lambda.promptDialog(Ljava/lang/String;)V
0   redex-all                           0x0000000104fca5a4 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff843a452a _sigtramp + 26
2   libsystem_malloc.dylib              0x00007fff8668572d szone_free_definite_size + 943
3   libsystem_c.dylib                   0x00007fff8761c6e7 abort + 129
4   redex-all                           0x0000000104fca561 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000105033b07 _ZN13BridgeRemover22delete_unused_bridgeesEv + 215
6   redex-all                           0x00000001050337dc _ZN13BridgeRemover3runEv + 92
7   redex-all                           0x0000000105033642 _ZN10BridgePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER8PgoFiles + 114
8   redex-all                           0x0000000104fe8778 _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEE + 312
9   redex-all                           0x0000000104fbe048 main + 2168
10  libdyld.dylib                       0x00007fff8e5775ad start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /var/folders/rt/d1qtftnx74q2y14n3x8027080000gn/T/tmpz1y7c5sv.redex_extracted_apk --outdir /var/folders/rt/d1qtftnx74q2y14n3x8027080000gn/T/tmpmd_q7z1o.redex_dexen /var/folders/rt/d1qtftnx74q2y14n3x8027080000gn/T/tmpmd_q7z1o.redex_dexen/dex0/classes.dex /var/folders/rt/d1qtftnx74q2y14n3x8027080000gn/T/tmpmd_q7z1o.redex_dexen/dex1/classes2.dex' returned non-zero exit status -6
```

**Comment by kingty** [comment]
i think so
```
opt/bridge/Bridge.cpp:292: void BridgeRemover::delete_unused_bridgees(): assertion `bridge->is_virtual()' failed.
bridge: private com.p1.mobile.putong.ui.profile.MediaReorderCard.lambda$uploadStart$1111(Lcom/p1/mobile/putong/data/Picture;)V
bridgee: private com.p1.mobile.putong.ui.profile.MediaReorderCard.handleSuccessfulMediaUpload(Lcom/p1/mobile/putong/data/Picture;)V
0   redex-all                           0x0000000103f5e534 _Z15crash_backtracei + 52
1   libsystem_platform.dylib            0x00007fff9043252a _sigtramp + 26
2   ???                                 0x00007fff6a854552 0x0 + 140734980506962
3   libsystem_c.dylib                   0x00007fff9ac6b6e7 abort + 129
4   redex-all                           0x0000000103f5e4f1 _Z11assert_failPKcS0_jS0_S0_z + 177
5   redex-all                           0x0000000103fd6b57 _ZN13BridgeRemover22delete_unused_bridgeesEv + 215
6   redex-all                           0x0000000103fd682c _ZN13BridgeRemover3runEv + 92
7   redex-all                           0x0000000103fd6692 _ZN10BridgePass8run_passERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEER8PgoFiles + 114
8   redex-all                           0x0000000103f7feb8 _ZN11PassManager10run_passesERNSt3__16vectorI10DexClassesNS0_9allocatorIS2_EEEE + 312
9   redex-all                           0x0000000104029b08 main + 2168
10  libdyld.dylib                       0x00007fff91e845ad start + 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /var/folders/_7/7rsl3sbj2v95j77_k9d84f3m0000gn/T/tmp8nhj4two.redex_extracted_apk --outdir /var/folders/_7/7rsl3sbj2v95j77_k9d84f3m0000gn/T/tmpoxq69omc.redex_dexen /var/folders/_7/7rsl3sbj2v95j77_k9d84f3m0000gn/T/tmpoxq69omc.redex_dexen/dex0/classes.dex' returned non-zero exit status -6
```

**Comment by bertmaher** [comment]
You can disable BridgePass using a config file, as described in docs/Config.md.  I'll get to a fix very soon.
