### ISSUE TITLE
BUCK + Redex: configure proguard properties & jars

### ISSUE THREAD

**Issue by tapthaker** [facebook/redex#330]
Using redex with BUCK has already been answered as a part of https://github.com/facebook/redex/issues/179 , I am wondering as to how do we add arguments such as 
- **PROGUARD_CONFIGS** ( the merged proguard file generated as a part of APK generation process )
- **JARPATHS**

**Comment by justinjhendrick** [comment]
I'm not positive this works. I would suggest trying this and printing out the invocation to redex to make sure all the arguments made it through.

```
android_binary(
    name = "my_app_redex",
    package_type = "release",
    proguard_config = "relative/path/to/proguard/config.pro",
    redex = True,
    redex_config = "relative/path/to/redex.config",
    skip_proguard = True, # or False, up to you (redex reads the proguard config either way)
    no_dx = [], # this should be jarpaths
    redex_extra_args = [], # this is always a fallback if the other options fail
    # ...
    # whatever else your android binary needs
)
```

More documentation on [the buck android_binary page](https://buckbuild.com/rule/android_binary.html)

**Comment by tapthaker** [comment]
Interesting, I was assuming that the proguard_config file for redex would be the merged config file of all the dependencies not just the proguard_config of `android_binary`.

For e.g. `recyclerview-v7-25.3.1.aar` contains the following proguard configuration inside it's proguard.txt file
```
-keep public class * extends android.support.v7.widget.RecyclerView$LayoutManager {
    public <init>(...);
}
```
As the dex file would also contain classes for **android.support.v7.widget.RecyclerView** we would need redex to consider this configuration as well. 

Am I mistaken ?

**Comment by justinjhendrick** [comment]
You're right. You need all the proguard files. It would be nice if it were automatic but I don't think it is.

I looked some more and it seems we have a python script (and associated buck rules) that combines all the proguard files into one, you might want to do something similar.

**Comment by tapthaker** [comment]
Thanks, this clears my understanding. Closing this issue.
