### ISSUE TITLE
Statically link libjsoncpp.11.dylib

### ISSUE THREAD

**Issue by tapthaker** [facebook/redex#332]
Currently while downloading the binary from Releases for macosx, it crashes with the following error: 

```bash
dyld: Library not loaded: /usr/local/opt/jsoncpp/lib/libjsoncpp.11.dylib
Reason: image not found
```
while it might somehow still be possible to install this it is cumbersome and requires and additional step. 

So, can be statically link the libjsoncpp with the binary ?

**Comment by int3** [comment]
Would be happy to take a PR that added an option for static linking to the makefile.

**Comment by tapthaker** [comment]
Awesome, will send out a PR soon

**Comment by tapthaker** [comment]
@int3 Looking into how we can statically link boost libs & jsoncpp statically. Please let me know if you have any ideas.

Tried looking at static runtime using [boost.m4](https://github.com/tsuna/boost.m4)

> Thus you can invoke BOOST_GRAPH (for instance) or BOOST_THREAD([mt-d]).
The optional argument is made of one or more of the following letters:
  sgdpn (in that order)
where:
  s = static runtime
  d = debug build
  g = debug/diagnostic runtime
  p = STLPort build
  n = (unsure) STLPort build without iostreams from STLPort
      (it looks like `n' must always be used along with `p').
Additionally, it can start with `mt-' to indicate that there is a preference
for multi-thread builds.

**Comment by tapthaker** [comment]
Bump !!

**Comment by tapthaker** [comment]
I think we can close the issue with the caveat that this is only fixed for `CMake`
