### ISSUE TITLE
How deobfuscate the Android APK crash logs

### ISSUE THREAD

**Issue by tapthaker** [facebook/redex#334]
Proguard has just 1 proguard mapping file to deobfuscate the code. However **ReDex**  generates the following files.

- redex-bytecode-offset-map.txt
- redex-class-rename-map.txt
- redex-line-number-map-v2
- redex-src-strings-map.txt

**Question**: Is using the `redex-class-rename-map.txt` to deobfuscate the crash sufficient ? Or is something else necessary ?

**Comment by minjang** [comment]
Correct. `redex-class-rename-map.txt` is enough to deobfuscate the symbols. Please note that we have RenameClassesV2Pass (it renames classes) and ObfuscatePass (it renames fields and members).
