### ISSUE TITLE
InterDex pass error

### ISSUE THREAD

**Issue by awelc** [facebook/redex#339]
I have been playing with the InterDex pass for a while and after recently updating to the newest version or ReDex sources I encountered the following error (running with `TRACE=4`) which I have never seen before:

```
Emitting the mixed mode dex after the interdex order.
error: not a writable directory: /tmp/redex.pNa5WH/tmp_r90p8nn.redex_extracted_apk/assets/secondary-program-dex-jars/
Traceback (most recent call last):
  File "/tmp/redex.pNa5WH/redex.py", line 176, in run_pass
    subprocess.check_call(args, env=env)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
```

I have narrowed down the problem to a specific commit (https://github.com/facebook/redex/commit/65a7f062d06f130da36d87580784a8a8aa2272c1)  but it's not immediately obvious to me what's happening here and I was hoping that someone could provide some insight...

**Comment by awelc** [comment]
It seems like the problem is related to the following piece of code in `emit_mixed_mode_classes` function (InterDex.cpp):

```java
  // Flush the mixed mode classes
  if (det.outs.size()) {
    flush_out_mixed_mode_dex(pass, apk_manager, det, outdex);
  }
```
As it appears, the error happens when trying to flush mixed mode classes, but from the log (in the previous message) it seems like no classes are actually emitted (as classes being emitted "event" is traced at `TRACE` level 2 and the last thing you see in the log is "Emitting the mixed mode dex after the interdex order").

It then seems that perhaps flushing should not happen since no classes are being emitted (but a wrong condition for the `if` statement is used?). But is the case of no classes being emitted here even correct?

**Comment by awelc** [comment]
Thank you for a super-quick - it's working now! My ReDex config is super simple:
```
{
  "redex" : {
    "passes" : [
      "InterDexPass"
    ]
  },
  "InterDexPass" : {
    "normal_primary_dex" : "false"
  },
  "coldstart_classes" : "shamu_5.1_classlist.txt"
}
```

I also dug in a bit more into the problem and I think that the error is generated by the following line in `flush_out_mix_mode_dex` function (InterDex.cpp:254 in the current head):

```java
  auto mix_mode = apk_manager.new_asset_file("mixed_mode.txt");
```
I suspect that the assets directory does not exist at this time, but I am not sure how would this work with actual mixed mode classes (what are they, btw.?) being present - it does not look like emitting a class has anything to do to with disk IO (e.g. creating files or directories).

**Comment by emma0303** [comment]
Glad it works now. The problem before was related to the structure of coldstart_classes. With the small fix though, that will not be taken into account anymore.

As a side note, you will want to add `RegAllocPass` in your config as you start adding other passes.

//I suspect that the assets directory does not exist at this time//
I am not sure why it doesn't work for you .. It seems like not all the directories are created in the output folder? To investigate this further, can you grab the temporary folder and check what was created there? (this happens from `redex.py`) Thanks

//actual mixed mode classes (what are they, btw.?)//
Those aren't currently used.
