### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [facebook/redex#34]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [ByteBucketArray](https://github.com/facebook/redex/blob/51e5fa6288b223bd7cf6f6aa9ebdf410d220563a/libresource/androidfw/ByteBucketArray.h#L37 "Destructor for ByteBucketArray")
* [DexLoader](https://github.com/facebook/redex/blob/51e5fa6288b223bd7cf6f6aa9ebdf410d220563a/libredex/DexLoader.cpp#L33 "Destructor for DexLoader")

**Comment by bertmaher** [comment]
Thanks you are correct (though it's more unnecessary than actively harmful).  I don't want to change code in libresource (ByteBucketArray is third-party code), but I'll change the case in DexLoader.
