### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'escape_summaries'

### ISSUE THREAD

**Issue by hoangnam973** [facebook/redex#340]
redex /Users/hoangnam/Documents/work/project_android/SurePortalAndroid/app/release/app-release.apk -o /Users/hoangnam/Documents/work/project_android/SurePortalAndroid/app/release/app-release1.apk
Using config (default)
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 0.92 seconds
Traceback (most recent call last):
  File "/tmp/redex.Vfkyyd/redex.py", line 738, in <module>
    run_redex(args)
  File "/tmp/redex.Vfkyyd/redex.py", line 720, in run_redex
    state = prepare_redex(args)
  File "/tmp/redex.Vfkyyd/redex.py", line 611, in prepare_redex
    if args.escape_summaries is not None:
AttributeError: 'Namespace' object has no attribute 'escape_summaries'

Can i help you ? Thanks you !

**Comment by justinjhendrick** [comment]
cc @int3
