### ISSUE TITLE
statically link libstdc++ in static build mode

### ISSUE THREAD

**Issue by neyguvj** [facebook/redex#352]
I used this commands to build redex
```
mkdir build && cd build
cmake ..
make redex
cmake .. -G Ninja -DBUILD_TYPE=Static
cmake --build .
```
```
Running redex on browser/app/build/outputs/apk/armCanaryApi21Local/release/app-arm-canary-api21-local-release-before-redex.apk
 /browser/buildSrc/src/scripts/redex/redex_linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by browser/buildSrc/src/scripts/redex/redex_linux)
 /browser/buildSrc/src/scripts/redex/redex_linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by browser/buildSrc/src/scripts/redex/redex_linux)
 /browser/buildSrc/src/scripts/redex/redex_linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by browser/buildSrc/src/scripts/redex/redex_linux)
 /browser/buildSrc/src/scripts/redex/redex_linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by browser/buildSrc/src/scripts/redex/redex_linux)
 :app:packageArmCanaryApi21LocalRelease FAILED
 
 FAILURE: Build failed with an exception.
```

redex works correctly on my computer, but it doesn't work on CI server because another libstdc++ version installed on the server.
it's difficult to install libraries on each build agent with different Linux version and environment.

I think static linking means REALLY static linking and redex shouldn't require any external libraries :-)

**Comment by minjang** [comment]
`redex-all` has been compiled successfully, and the errors are from your missing .so. Could you double check whether you installed the correct toolchains? Possible SO article: https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx

**Comment by neyguvj** [comment]
I'm speaking about static veriosn of redex.
I think libstdc++ should be linked statically.
So redex shouldn't require any external libraries inclidung libstdc++.

why I shold have any external .so if I build Redex statically ?

**Comment by neyguvj** [comment]
redex works correctly on my computer, but it doesn't work on CI server because another libstdc++ version installed on the server.
it's difficult to install libraries on each build agent with different Linux version and environment.

**Comment by minjang** [comment]
Understood the problem. Unfortunately, as we don't use internally CMake, I don't have a freecycle to fix this issue. Actually, @tapthaker implemented static linking in https://github.com/facebook/redex/pull/346. @tapthaker, could you take a look at this issue? In your PR, libc++ (not libstc++) was still dynamically linked. Can you also make them statically linked? I would appreciate if you provide us a help.

**Comment by neyguvj** [comment]
we already have this fix in our old fork https://github.com/igor-eremeev/redex/blob/custom/CMakeLists.txt#L75

we implemented static linking in our fork 2 or 3 months ago.
now we want to update our fork and use your official static linking.

**Comment by tapthaker** [comment]
Sure, I will get a PR out sometime today. 

Thanks 👍

**Comment by minjang** [comment]
Thanks. But libstc++ is not available everywhere. So I don't think we could easily put it into our CMake. If there is a general solution that picks libc++ or libstd++, we'd love to take it. Otherwise, a local patch would be better.

**Comment by neyguvj** [comment]
but how redex works without libstdc++ ?

**Comment by minjang** [comment]
My bad. libstdc++ is for GNU toolchains, while libc++ is for LLVM's. On Macs, it is now with libc++ only.

**Comment by tapthaker** [comment]
> So I don't think we could easily put it into our CMake. If there is a general solution that picks libc++ or libstd++, we'd love to take it

The PR #355 only fixes this problem for g++ (Linux). I am not sure what flags would work for clang (macOS). 
I think normally you won't face any problems by keeping libc++ dynamically linked in macOS
