### ISSUE TITLE
Use apksigner to sign APKs

### ISSUE THREAD

**Issue by neyguvj** [facebook/redex#353]
Redex uses jarsigner to sign APKs.
Google recommends to use their new tools apksigner
https://developer.android.com/studio/command-line/apksigner
Google added new signature schemes that are not supported in jarsigner
https://source.android.com/security/apksigning/v2
https://source.android.com/security/apksigning/v3

You need to use apksigner to support new sugnature schemes.

**Comment by franciscofranco** [comment]
This would be nice to have.
