### ISSUE TITLE
Analysis 

### ISSUE THREAD

**Issue by juanduarte1927** [facebook/redex#357]
Hello, I want get analysis of the problems or bugs in my app... I run the command redex /example/xx.apk -o /example/yy.apk and create the new APK. But i dont know the issues that resolving. 

I see that Infer indicate leaks and other problems, with the line of code... Its possible obtain this information with Redex? 

Thank you

**Comment by justinjhendrick** [comment]
Redex is an optimizer, not a bug finder.

I'd recommend the tools in this article for bug finding: https://medium.com/mindorks/static-code-analysis-for-android-using-findbugs-pmd-and-checkstyle-3a2861834c6a

If you wanted to build your own code analyzer, you could do so on top of redex as a library, `libredex`.
