### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [facebook/redex#36]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/facebook/redex/blob/2a1b9609f48ebd64def6260e2018b3d476c2d9f0/configure.ac#L23 "Configuration checks")?

**Comment by bertmaher** [comment]
Probably!  I'm pretty much a n00b at autoconf, so if you know how to do it, I'd love to see a PR.
