### ISSUE TITLE
Run command redex an error occurred

### ISSUE THREAD

**Issue by lycfr** [facebook/redex#360]
Run command：redex path/to/your.apk -o path/to/output.apk
Result：Running error，Error is as follows：
`/tmp/redex.Ji1GqM/redex-all: error while loading shared libraries: libboost_iostreams.so.1.64.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/tmp/redex.Ji1GqM/redex.py", line 205, in run_redex_binary
    subprocess.check_call(args, env=env)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/redex.Ji1GqM/redex-all', '--apkdir', '/tmp/redex.Ji1GqM/tmph_vv4rjh.redex_extracted_apk', '--outdir', '/tmp/redex.Ji1GqM/tmpv4mbqjhx.redex_dexen', '/tmp/redex.Ji1GqM/tmpv4mbqjhx.redex_dexen/dex0/classes.dex', '/tmp/redex.Ji1GqM/tmpv4mbqjhx.redex_dexen/dex1/classes2.dex', '/tmp/redex.Ji1GqM/tmpv4mbqjhx.redex_dexen/dex2/classes3.dex', '/tmp/redex.Ji1GqM/tmpv4mbqjhx.redex_dexen/dex3/classes4.dex']' returned non-zero exit status 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/redex.Ji1GqM/redex.py", line 885, in <module>
    run_redex(args)
  File "/tmp/redex.Ji1GqM/redex.py", line 862, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.Ji1GqM/redex.py", line 218, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code 127! You can re-run it under gdb by running /tmp/redex.Ji1GqM/redex-gdb-38hzijjs.sh or under lldb by running /tmp/redex.Ji1GqM/redex-lldb-npr7h1gf.sh
`
I tried a lot of methods and couldn't solve it.

**Comment by lycfr** [comment]
![image](https://user-images.githubusercontent.com/29672247/48831366-a94a1900-edb1-11e8-9d60-e0585c28f86d.png)

**Comment by Feng23** [comment]
It seems that the binary can not find the boost shared library, so just want to make sure you have tried the following things: (1) Installed boost libraries on your machine  Or (2) set LD_LIBRARY_PATH environment variable to the boost library path (If the boost libraries are not available in the system library path) ?
