### ISSUE TITLE
Podcast about Redex on Inside Facebook Mobile!

### ISSUE THREAD

**Issue by justinjhendrick** [facebook/redex#366]
@emma0303 recently went on the Inside Facebook Mobile podcast to talk about Redex. She gave a great overview of Redex and answered a bunch of frequently asked questions.

Here's the link: https://play.google.com/music/m/Dfajhf6uql4fthj3fxspkrq3zki?t=9_Android_Bytecode_Optimisation_with_Emma-Inside_Facebook_Mobile

**Comment by andreasnomikos** [comment]
Noice!
