### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [facebook/redex#37]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocaction") ⇒ [extract_jar_entry](https://github.com/facebook/redex/blob/51e5fa6288b223bd7cf6f6aa9ebdf410d220563a/libredex/JarLoader.cpp#L559)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [WorkQueue constructor](https://github.com/facebook/redex/blob/51e5fa6288b223bd7cf6f6aa9ebdf410d220563a/libredex/WorkQueue.cpp#L91)

**Comment by bertmaher** [comment]
Seems like a reasonable idea but not a priority for me at the moment.  I'd happily consider a pull request to check those cases though!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?
