### ISSUE TITLE
SynthPass generates invalid bytecode in rare cases, truncating the register number.

### ISSUE THREAD

**Issue by igor-eremeev** [facebook/redex#370]
Condition: a method that gets result of access-method invocation from a register with a high number, at least v16.
For example: `invoke-static/range {v22}, SomeClass;.access$100:(SomeSignature)`
invoke-static has 16 bits in its opcode to address the source register, so it's a valid code (see https://source.android.com/devices/tech/dalvik/dalvik-bytecode)

What happens: SynthPass tries to replace it with iget-object, that has only 4 bits for source register. v22 gets its high bits cut down and becomes v6, resulting in invalid bytecode (`java.lang.VerifyError instance field access on object that has non-reference type Undefined`).

Possible fix (rough draft) - just skip them high registers:
```
opt/synth/Synth.cpp:
@@ -570,20 +570,24 @@ void replace_wrappers(const ClassHierarchy& ch,
       if (found_get != ssms.getters.end()) {
         auto next_it = std::next(it);
         auto const move_result = next_it->insn;
         if (!is_move_result(move_result->opcode())) {
           ssms.keepers.emplace(callee);
           continue;
         }
+        if (insn->arg_word_count() && insn->src(0) >= 16) {
+          ssms.keepers.emplace(callee);
+          continue;
+        }
         auto field = found_get->second;
         getter_calls.emplace_back(insn, move_result, field);
         continue;
       }
...
       auto const found_get = ssms.getters.find(callee);
       if (found_get != ssms.getters.end()) {
         auto next_it = std::next(it);
         auto const move_result = next_it->insn;
         if (!is_move_result(move_result->opcode())) {
           ssms.keepers.emplace(callee);
           continue;
         }
+        if (insn->arg_word_count() && insn->src(0) >= 16) {
+          ssms.keepers.emplace(callee);
+          continue;
+        }
         auto field = found_get->second;
         getter_calls.emplace_back(insn, move_result, field);
         continue;
       }
 ```

**Comment by justinjhendrick** [comment]
Good catch!

Though I'm not exactly sure this is the right place to fix that bug. We have an Intermediate representation (IR) which shouldn't have the 4 bit restriction on any register (see [this comment](https://github.com/facebook/redex/blob/master/libredex/IRInstruction.h#L17)). It sounds like there might be a problem allocating registers and lowering the IR down to Dex bytecode.

Are you passing a config to redex? If so, is `RegAllocPass` in the list of passes?

**Comment by igor-eremeev** [comment]
I didn't know that, thanks for pointing out! No, RegAllocPass is disabled. So, it turns out that there are dependency relations between passes?
My current config is:
```
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "SynthPass",
      "DelSuperPass",
      "InterDexPass"
    ]
  },
  "coldstart_classes" : "<...>"
```
The idea was "only include things that give huge dexcount, size or speed profit" :)

**Comment by justinjhendrick** [comment]
Yes, there are dependencies but unfortunately we haven't surfaced that information anywhere :/

`RegAllocPass` is a required pass. And it should be put at (or near) the end of the passes list.

**Comment by igor-eremeev** [comment]
Thank you for your answers, adding RegAlloc solves the problem.
I believe this can be closed now.
