### ISSUE TITLE
ReDex not parsing the keep rule regex correctly

### ISSUE THREAD

**Issue by tapthaker** [facebook/redex#372]
### Issue

- I want to keep all classes that start with `Animal_`. To ensure this I have added the following proguard-rule

```
-keep class **Animal_** { *; }
```
Even after adding this rule ReDex removes the class.

### Steps to Reproduce

I have created a sample apk with the repro steps in this [repository](https://github.com/tapthaker/redex-sample/). Just clone and execute the `run_redex.sh` script.

### Analysis of the issue

- The `**Animal_**` regex generates the `boost::regex` 
```regex
L(?:[^\/]+(?:\/[^\/]+)*)Animal_(?:[^\/]+(?:\/[^\/]+)*);
``` 
which does not match the class `Lcom/example/redexsampleapp/Animal_Cat;`. You can validate this using online regex tester [here](https://regex101.com/r/RHz4Ee/1).

May be changing 
```regex
L(?:[^\/]+(?:\/[^\/]+)*)Animal_(?:[^\/]+(?:\/[^\/]+)*);
```
 to 
```regex
L(?:[^\/]+(?:\/[^\/]*)*)Animal_(?:[^\/]+(?:\/[^\/]*)*);
``` 
could fix this issue. But I am not sure on what considerations you folks made while creating this regex so not sure.  ¯\\_(ツ)_/¯

**Comment by justinjhendrick** [comment]
Good catch. Definitely seems wrong. Though, I'm wondering if we should just broaden it even further to something like this

```
L.*Animal.*;
```

Because the new regex you've suggested doesn't match "LAnimal_Cat;", but I think `**Animal_**` should match that string.

**Comment by tapthaker** [comment]
- Broadening the regex makes sense.  From the Proguard [documentation](https://www.guardsquare.com/en/products/proguard/manual/usage#classspecification)
```
** | matches any part of a class name, possibly containing any number of package separators.
```

- I will submit a PR to fix regex based on what we discussed.

**Comment by justinjhendrick** [comment]
Don't worry about the PR. I'm already writing the fix.

**Comment by justinjhendrick** [comment]
I think `.*` is too broad, because it would match an array type, but it's not supposed to.

**Comment by tapthaker** [comment]
If we can assume that every class name would have at least 1 path separator we could still use the initial regex I suggested.

**Comment by justinjhendrick** [comment]
I don't think we can assume that. The spec says `**` matches **any** part of a class name, so I think someone could write this the config:

```
com/foobar/**
``` 

and that should match `com/foobar/Cat` even though `Cat` doesn't have any separators in it.

The revisions I just commited (https://github.com/facebook/redex/commit/655d2e75c80196a7259d9f2e85d4206cbfa535d1) converts `**` to `[^\\[]*`, so basically everything except for the array marker.

**Comment by tapthaker** [comment]
Thanks 👍
