### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [facebook/redex#38]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/facebook/redex/blob/51e5fa6288b223bd7cf6f6aa9ebdf410d220563a/tools/redex-all/main.cpp#L282 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by bertmaher** [comment]
Thanks for the feedback!  I don't feel strongly about catching exceptions in redex's main(), to be honest.  If an exception somehow bubbled up to main, we're just going to die anyways, and we don't have any resources that need to be released that won't be freed by the OS.  Maybe we could provide a nice message, but we're not at that level of polish yet.

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](https://stackoverflow.com/questions/5557555/raii-and-stack-unwinding "RAII and Stack unwinding")?
