### ISSUE TITLE
run dump_classes_from_hprof.py KeyError

### ISSUE THREAD

**Issue by levianye** [facebook/redex#387]
when I run dump_classes_from_hprof.py,wrong error as below
my python version is 2.7.15, os is macOS 10.14.2
and that is my command :**python2 dump_classes_from_hprof.py --hprof mydump.hprof > list_of_classes.txt**
what is this issue? anyone can help?
Traceback (most recent call last):
  File "dump_classes_from_hprof.py", line 1265, in <module>
    hp = parse_filename(args.hprof)
  File "dump_classes_from_hprof.py", line 57, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "dump_classes_from_hprof.py", line 49, in parse_hprof_dump
    hprof_data.resolve()
  File "dump_classes_from_hprof.py", line 889, in resolve
    root.resolve(self)
  File "dump_classes_from_hprof.py", line 304, in resolve
    self.obj = hprof_data.object_id_dict[self.object_id]
KeyError: 328084648
and here is the my dump file
[lenderdump.hprof.zip](https://github.com/facebook/redex/files/2995275/lenderdump.hprof.zip)

**Comment by wsanville** [comment]
Hello, I apologize but it looks like this script has not been maintained or kept up to date. Therefore, it's unlikely to work on heap dumps from modern OS versions. We're likely to remove this soon, since we haven't been using it.

**Comment by levianye** [comment]
@wsanville my android phone is xiaomi mix2 ,android version 8.0,is cause of android version ?

**Comment by justinjhendrick** [comment]
Yeah, the script doesn't support android 8. I think the script was written back when most android phones were 4.x. So it's pretty out of date.

**Comment by levianye** [comment]
@justinjhendrick Is that interdex option also worked at modern version? if I dump from lower version like 5.x or 4.x version ,analyzed by this script also worked at android 8.0?

**Comment by levianye** [comment]
I dump from 5.1.1 also run error
`Traceback (most recent call last):
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 1265, in <module>
    hp = parse_filename(args.hprof)
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 57, in parse_filename
    return parse_hprof_dump(open(filename, 'rb'))
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 49, in parse_hprof_dump
    hprof_data.resolve()
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 866, in resolve
    clazz.resolve(self)
  File "redex/tools/hprof/dump_classes_from_hprof.py", line 551, in resolve
    static_field.value = hprof_data.object_id_dict[static_field.value]
KeyError: 6619237`
5.1.1 also not work?

**Comment by justinjhendrick** [comment]
Interdex should work okay on any android version. A dump from an older phone should still work on a newer phone (though, I doubt the optimal order is the same across many OS versions).

I'm not sure where that script works. My guess is that it might only work on 4.x devices.

**Comment by levianye** [comment]
I gave up Interdex cause I can't handle it ,doc seems very simple I can't generate a dump classes for interdex config ,do you have any sample? it seem compatibility not very well,now I can only use default config for redex

**Comment by benjaminRomano** [comment]
What do you recommend to use as a replacement for this script? @justinjhendrick @wsanville

**Comment by justinjhendrick** [comment]
I'd recommend building an instrumented version of your app that logs which classes are loaded (and in what order). Then you can use that data to generate a class list for interdex.

**Comment by emma0303** [comment]
We haven't updated this script, nor do we use it for a long time now. 
But, when this was created, it was written for Android 4 heapdumps.
