### ISSUE TITLE
crashed with exit code -11

### ISSUE THREAD

**Issue by levianye** [facebook/redex#389]
when I use aggressive.config run error
Traceback (most recent call last):
  File "/tmp/redex.zObEJ9/redex.py", line 895, in <module>
    run_redex(args)
  File "/tmp/redex.zObEJ9/redex.py", line 872, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.zObEJ9/redex.py", line 222, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -11! You can re-run it under gdb by running /tmp/redex.zObEJ9/redex-gdb-rAYQz9.sh or under lldb by running /tmp/redex.zObEJ9/redex-lldb-59Nsfe.sh

**Comment by justinjhendrick** [comment]
This doesn't give us enough information to debug the issue. Could you run `redex` under gdb (either by running the script in the error message or adding `--gdb` to your command)? (lldb works too). When you reach the crash, print out the backtrace

**Comment by levianye** [comment]
@justinjhendrick is that command 'redex  -c redex/config/aggressive.config  app.apk -o aggressive.apk --gdb'
it shows 
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 0.92 seconds
Running redex-all on 6 dex files 
Running redex binary at /tmp/redex.JaonoL/redex-all
Traceback (most recent call last):
  File "/tmp/redex.JaonoL/redex.py", line 895, in <module>
    run_redex(args)
  File "/tmp/redex.JaonoL/redex.py", line 872, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.JaonoL/redex.py", line 215, in run_redex_binary
    raise err
OSError: [Errno 2] No such file or directory

**Comment by levianye** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Current executable set to '/tmp/redex.FYbh3d/redex-all' (x86_64).
(lldb) settings set -- target.run-args  "--apkdir" "/tmp/redex.FYbh3d/tmpc7w9Nb.redex_extracted_apk" "--outdir" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen" "--config" "/Users/ppd-03020213/android-project/redex/config/aggressive.config" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex0/classes.dex" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex1/classes2.dex" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex2/classes3.dex" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex3/classes4.dex" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex4/classes5.dex" "/tmp/redex.FYbh3d/tmpXa6AQc.redex_dexen/dex5/classes6.dex"

**Comment by justinjhendrick** [comment]
Did you run (with the `run` command) the program inside lldb? I don't see the backtrace here

**Comment by levianye** [comment]
@justinjhendrick may I ask is that config aggressive.config is usable？How can I use it?
here is my env
mac os 10.14.2 
Apple LLVM version 10.0.0
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by justinjhendrick** [comment]
I haven't tested the aggressive config since I wrote it a while ago. So, I make no promises about how stable it is. I'd recommend starting with the automatic config (defined inside `main.cpp`) and add passes one at a time, using aggressive.config as a guide

**Comment by justinjhendrick** [comment]
I'd also recommend enabling the bash env variable `TRACE` with `export TRACE=1` to get logging to stdout. You can also redirect it to a file with `export TRACEFILE=~/tmp/trace.txt`

**Comment by justinjhendrick** [comment]
TRACE can also take on more nuanced values. For example `$ export TRACE=0,TIME:1` disables most logging except for the timers. You can see a full list of the possible trace sub-options in libredex/Trace.h

**Comment by agampe** [comment]
No feedback, closing.
