### ISSUE TITLE
 https://fbredex.com can't open 

### ISSUE THREAD

**Issue by liuzhao2007** [facebook/redex#396]
This website can't open, is there anything wrong !

**Comment by justinjhendrick** [comment]
Huh. That's odd. I can still access the website. Is it still down for you?

**Comment by liuzhao2007** [comment]
Yes, I still can't access it

**Comment by justinjhendrick** [comment]
I think it may be an issue with your browser or your internet connection? [downforeveryoneorjustme.com shows that it's up](https://downforeveryoneorjustme.com/fbredex.com)

**Comment by yuxuanchen1997** [comment]
Unfortunately this website [seems to be blocked in China](http://www.chinafirewalltest.com/?siteurl=fbredex.com).

**Comment by justinjhendrick** [comment]
O, that's surprising. I wonder why it's blocked...

Most of the information on the website is also here: https://github.com/facebook/redex/tree/master/docs
