### ISSUE TITLE
help me validate_dex_header fail

### ISSUE THREAD

**Issue by JuneLeo** [facebook/redex#398]
I set minSdkVersion = 25

/tmp/redex.O2FnbH/redex-all[0xae2fc8]
/tmp/redex.O2FnbH/redex-all(_Z11assert_failPKcS0_jS0_10RedexErrorS0_z+0xf4)[0xae3344]
/tmp/redex.O2FnbH/redex-all(_ZN9DexLoader8load_dexEPKcP11dex_stats_tb+0x5a3)[0xaffcd3]
/tmp/redex.O2FnbH/redex-all(_Z21load_classes_from_dexPKcP11dex_stats_tbb+0x9d)[0xb006cd]
/tmp/redex.O2FnbH/redex-all(main+0x14c7)[0x7161e7]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4e7d0dd830]
/tmp/redex.O2FnbH/redex-all(_start+0x29)[0x71c5f9]
terminate called after throwing an instance of 'RedexException'
  what():  libredex/DexLoader.cpp:56: void validate_dex_header(const dex_header*, size_t, bool): assertion `false' failed.
Bad v35 dex magic dex
037

/tmp/redex.O2FnbH/redex-all[0xae2fc8]
/tmp/redex.O2FnbH/redex-all(_Z23crash_backtrace_handleri+0x8)[0xae3008]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f4e7d0f24b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f4e7d0f2428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f4e7d0f402a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x16d)[0x7f4e7da3584d]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d6b6)[0x7f4e7da336b6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d701)[0x7f4e7da33701]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8d919)[0x7f4e7da33919]
/tmp/redex.O2FnbH/redex-all(_Z11assert_failPKcS0_jS0_10RedexErrorS0_z+0x161)[0xae33b1]
/tmp/redex.O2FnbH/redex-all(_ZN9DexLoader8load_dexEPKcP11dex_stats_tb+0x5a3)[0xaffcd3]
/tmp/redex.O2FnbH/redex-all(_Z21load_classes_from_dexPKcP11dex_stats_tbb+0x9d)[0xb006cd]
/tmp/redex.O2FnbH/redex-all(main+0x14c7)[0x7161e7]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4e7d0dd830]
/tmp/redex.O2FnbH/redex-all(_start+0x29)[0x71c5f9]
Traceback (most recent call last):
  File "/tmp/redex.O2FnbH/redex.py", line 931, in <module>
    run_redex(args)
  File "/tmp/redex.O2FnbH/redex.py", line 908, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.O2FnbH/redex.py", line 222, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.O2FnbH/redex-gdb-B9x6bX.sh or under lldb by running /tmp/redex.O2FnbH/redex-lldb-5bm0eH.sh

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by JuneLeo** [comment]
help me,help me

**Comment by yuxuanchen1997** [comment]
Thank you for being patient. It's out of our regular work hours.

We are sorry if the error messages didn't make sense to you. It's finding dex v37 format magic number while it's expecting v35.

I have checked it for you and v37 support is not enabled in redex-all at this moment.

**Comment by JuneLeo** [comment]
Thank you. How can I solve this problem?

> Thank you for being patient. It's out of our regular work hours.
> 
> We are sorry if the error messages didn't make sense to you. It's finding dex v37 format magic number while it's expecting v35.
> 
> I have checked it for you and v37 support is not enabled in redex-all at this moment.

Thank you. How can I solve this problem?

**Comment by JuneLeo** [comment]
> Thank you for being patient. It's out of our regular work hours.
> 
> We are sorry if the error messages didn't make sense to you. It's finding dex v37 format magic number while it's expecting v35.
> 
> I have checked it for you and v37 support is not enabled in redex-all at this moment.

thanks, I know how to solve this problem

**Comment by justinjhendrick** [comment]
As an additional note: We do plan on supporting higher dex versions in the future, but it's not ready yet.
