### ISSUE TITLE
Interdex:  Class won't fit current dex

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#399]
**Background**
We saw the following error during the Interdex pass:
```
[warning]: Class won't fit current dex since it will go over the field refs limit: 65535 >= 65535: Landroid/support/v7/app/AppCompatActivity;
```
which will eventually cause Interdex to fail since this will trigger the creation of a second priamry dex.

**Workaround**
This error message is slightly strange for two reasons:
1. The max method count is `65536`
2. The comparison should be done with `>` instead of `>=` afaict

We've made the following patches to the `DexStructure.cpp` to workaround this issue and it has been working for us in production for a couple months now.

```cpp
// Line 37
-constexpr unsigned MAX_METHOD_REFS = (1 << 16) - 1;
-constexpr unsigned MAX_FIELD_REFS = (1 << 16) - 1;
+constexpr unsigned MAX_METHOD_REFS = (1 << 16);
+constexpr unsigned MAX_FIELD_REFS = (1 << 16);

// Line 204
-  if (m_frefs.size() + extra_frefs.size() >= MAX_FIELD_REFS) {
+  if (m_frefs.size() + extra_frefs.size() > MAX_FIELD_REFS) {
```

Please let me know if this seems reasonable. I suspect you may not have ran into this issue since your primary dex is small based on what I saw from the team's recent F8 talk (which was great btw). Additionally, it would be helpful if you could provide some more context on what the motivation is for keeping that file so small (my assumption is that its to delay incurring the cost of loading further dex files?)

**Comment by justinjhendrick** [comment]
I'm not sure where the boundary should actually be, but this does seem fishy. There have been some refactors of this file, so it's not easy to find the original commit that put the limit there. It sounds like the app works okay with a lower limit. Maybe we should upstream this change. Feel free to put up a pull request and we can test it too and see what happens.

**Comment by NTillmann** [comment]
This should not happen anymore.
