### ISSUE TITLE
Warning: Optimization warning: Pure abstract class passed to encode: 86 occurrences

### ISSUE THREAD

**Issue by loretoparisi** [facebook/redex#40]
What does this warning mean?
I see a very small difference in my apk after optimization:

```shell
-rwxr-xr-x@ 1 admin  staff  19101808 13 Apr 16:59 myapp_arm-v7a.apk
-rw-r--r--  1 admin  staff  18849654 13 Apr 18:08 myapp_arm-v7a_redex.apk
```

not sure if it's related to this warning.

**Comment by shanenay** [comment]
"Optimization Warning" means:  We're probably leaving something on the table.  In this case, we've stripped 86 classes of all of their useful bits.  More than likely, we shouldn't be outputting the classes at all.  We tag cases like this which are below the threshold of worthwhile to do.  (That way if they ever get big on some app then we'll take the time to handle them)  In terms of optimization, it's generally better to measure the difference between the size of the dex before and after.

**Comment by bertmaher** [comment]
I've squashed the optimization warnings from the default output since they're confusing.  Thanks for bringing this up.

**Comment by loretoparisi** [comment]
@bertmaher you're welcome!
