### ISSUE TITLE
file opened but not checked.

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/redex#404]
file 'fd' is opened here:
https://github.com/facebook/redex/blob/c987dfc7a598c384fdfe3e5e9c345000bba62d87/shared/QuickData.cpp#L135

and is used here:
https://github.com/facebook/redex/blob/c987dfc7a598c384fdfe3e5e9c345000bba62d87/shared/QuickData.cpp#L141

file 'fp' is used without checking.

**Comment by justinjhendrick** [comment]
`fileno` will return -1 on an invalid location. What exactly is the problem with that?
