### ISSUE TITLE
DebugMetadata might cause output non-determinism

### ISSUE THREAD

**Issue by mvolkus** [facebook/redex#408]
DebugMetadata struct has uninitialized fields, which will get random value if not set. For example, `generate_debug_instructions` may not set `line_start` field in some cases.

**Comment by justinjhendrick** [comment]
Sounds like a problem to me. Do you want to put up a pull request that adds default values?

**Comment by mvolkus** [comment]
It would be best if you fixed it. Due to legal issues getting pull request through would take way too much time for such a small fix.

**Comment by mvolkus** [comment]
Thanks. Does stable branch eventually gets merged into master?

**Comment by justinjhendrick** [comment]
Yeah, about every 3 months. I can promote this up now though if you need it

**Comment by mvolkus** [comment]
No, it's fine.
