### ISSUE TITLE
Add Redex to Homebrew

### ISSUE THREAD

**Issue by jaredsburrows** [facebook/redex#41]
For convenience, it would be nice to simply do:

`brew install redex`

**Comment by almesh** [comment]
https://github.com/facebook/redex/issues/43

**Comment by kageiit** [comment]
Addressed in https://github.com/Homebrew/homebrew-core/pull/5196

It would be good to have a stable release at this point for brew to create bottles.

**Comment by kageiit** [comment]
It seems they do not accept head only formula

Can we get a tag so this can actually happen?

**Comment by kageiit** [comment]
@bertmaher bump!

**Comment by bertmaher** [comment]
This is definitely a good idea, especially now that we're through the initial wave of bug reports.  I'll get some feedback from my team at FB and try to cut a stable version Real Soon Now :)

**Comment by kageiit** [comment]
@bertmaher any updates on the release?

**Comment by bertmaher** [comment]
I've got general agreement that we should do it, and a tentative plan to have it sync up with FB's internal releases (so stability should be relatively good).  I should be able to do this in the next week or so.

**Comment by bertmaher** [comment]
At long last, we have a stable release: https://github.com/facebook/redex/tree/release-2016.10.10 :-)

**Comment by kageiit** [comment]
@bertmaher can we please tag this release branch so it shows up as a release tag?

**Comment by bertmaher** [comment]
Yep, tagged now.

**Comment by kageiit** [comment]
@bertmaher Can you comment on https://github.com/Homebrew/homebrew-core/pull/5948#issuecomment-254137216?

It seems brew is failing audit when creating the redex formula due to how redex is being packaged

**Comment by bertmaher** [comment]
I'm out on paternity leave but I will try to take a look in between diaper changes ;-)

On Nov 10, 2016, at 10:07 AM, Gautam Korlam <notifications@github.com<mailto:notifications@github.com>> wrote:


@bertmaher<https://github.com/bertmaher> Can you comment on Homebrew/homebrew-core#5948 (comment)<https://github.com/Homebrew/homebrew-core/pull/5948#issuecomment-254137216>?

It seems brew is failing audit when creating the redex formula due to how redex is being packaged

-

**Comment by kageiit** [comment]
@bertmaher can someone else comment while you are away?

**Comment by bertmaher** [comment]
Back from leave, finally, and I've changed the way redex is packaged so it is a single binary to be installed.  This *should* be cool from homebrew's perspective.

**Comment by jaredsburrows** [comment]
`brew install redex` works. Closing.

**Comment by justinjhendrick** [comment]
`brew install redex` defaults to a rather old release. `brew install redex --HEAD` will get you the newest version.
