### ISSUE TITLE
No-inline annotations?

### ISSUE THREAD

**Issue by awelc** [facebook/redex#410]
I am trying to figure out how to prevent a method from being inlined using MethodInlinePass without using the black lists (these, I believe do not work when ProGuard obfuscation is enabled as they compare names of obfuscated methods and thus would require specifying obfuscated method name in the config file).

I have found some info in the code on no-inline annotations and it seems like a list of these have to be specified in the config file but it's difficult to figure out how they work exactly. I would really appreciate some help here.

**Comment by justinjhendrick** [comment]
I think you're looking for `no_inline_annos`. Here's a little example:

```
"inliner": {
  "no_inline_annos" : [
    "Lcom/foo/DoNotInline;",
  ],
}
```

note that the "inliner" section was recently renamed from "MethodInlinePass". The reason is that multiple different passes use the inliner infrastructure and we wanted common configuration for all of them.
