### ISSUE TITLE
redex my.apk -o output.apk crashed with exit code -6

### ISSUE THREAD

**Issue by flydht** [facebook/redex#411]
redex -c interdex.config -o output.apk app.apk 
WARNING: keep annotation Lcom/google/common/annotations/VisibleForTesting; not found
WARNING: Unable to find RequiresApi annotation. It's either unused (okay) or been deleted (not okay)
terminate called after throwing an instance of 'RedexException'
  what():  opt/rebindrefs/ReBindRefs.cpp:138: {anonymous}::Rebinder::rewrite_refs()::<lambda(DexMethod*, IRInstruction*)>: assertion `is_resolved(insn)' failed.
[rebind] Unresolved method reference in INVOKE_STATIC v0, v12, v7, Landroid/support/v7/internal/widget/ActionBarContextView;.next:(IIZ)I

/tmp/redex.jAlH4e/redex-all(+0x77566b)[0x556ec8de066b]
/tmp/redex.jAlH4e/redex-all(_Z23crash_backtrace_handleri+0x8)[0x556ec8de06a8]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f66fd62af20]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f66fd62ae97]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f66fd62c801]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c957)[0x7f66fe01f957]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ab6)[0x7f66fe025ab6]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92af1)[0x7f66fe025af1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d24)[0x7f66fe025d24]
/tmp/redex.jAlH4e/redex-all(_Z11assert_failPKcS0_jS0_10RedexErrorS0_z+0x15b)[0x556ec8de0a2b]
/tmp/redex.jAlH4e/redex-all(+0x538069)[0x556ec8ba3069]
/tmp/redex.jAlH4e/redex-all(_ZN20editable_cfg_adapter7iterateIZZN4walk15iterate_opcodesEPK8DexClassRKSt8functionIFbP9DexMethodEERKS5_IFvS7_P13IRInstructionEEENKUlS7_R6IRCodeE_clES7_SJ_EUlR15MethodItemEntryE_EEvPSI_T_+0x94)[0x556ec89979e4]
/tmp/redex.jAlH4e/redex-all(_ZNSt17_Function_handlerIFvP9DexMethodR6IRCodeEZN4walk15iterate_opcodesEPK8DexClassRKSt8functionIFbS1_EERKS9_IFvS1_P13IRInstructionEEEUlS1_S3_E_E9_M_invokeERKSt9_Any_dataOS1_S3_+0x2c)[0x556ec8997bcc]
/tmp/redex.jAlH4e/redex-all(_ZNSt17_Function_handlerIFvP9DexMethodEZN4walk12iterate_codeEPK8DexClassRKSt8functionIFbS1_EERKS7_IFvS1_R6IRCodeEEEUlS1_E_E9_M_invokeERKSt9_Any_dataOS1_+0x5e)[0x556ec898ffce]
/tmp/redex.jAlH4e/redex-all(_ZN14ReBindRefsPass8run_passERSt6vectorI8DexStoreSaIS1_EER11ConfigFilesR11PassManager+0xec9)[0x556ec8ba2219]
/tmp/redex.jAlH4e/redex-all(_ZN11PassManager10run_passesERSt6vectorI8DexStoreSaIS1_EER11ConfigFiles+0x8f3)[0x556ec8e94f33]
/tmp/redex.jAlH4e/redex-all(main+0x369)[0x556ec8983919]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f66fd60db97]
/tmp/redex.jAlH4e/redex-all(_start+0x2a)[0x556ec898b2ca]
Traceback (most recent call last):
  File "/tmp/redex.jAlH4e/redex.py", line 785, in <module>
    run_redex(args)
  File "/tmp/redex.jAlH4e/redex.py", line 762, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.jAlH4e/redex.py", line 224, in run_redex_binary
    'by running %(lldb_script_name)s') % script_filenames)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.jAlH4e/redex-gdb-2agKzT.sh or under lldb by running /tmp/redex.jAlH4e/redex-lldb-6hR7wg.sh

**Comment by emma0303** [comment]
Looking. Sorry for the delayed reply. A recent change might have caused this.

For our context, can you post the interdex.config? Thanks

**Comment by emma0303** [comment]
https://github.com/facebook/redex/commit/76cf90cefb599c0f5a7397d67502c5e018c7ed4a should have solved it. Please comment back if it didn't. Thanks
