### ISSUE TITLE
Unclear usage: should we use proguard and redex together?

### ISSUE THREAD

**Issue by slavasav** [facebook/redex#414]
It is not clear from documentation whether we should run the full release build with proguard and then run redex on the apk, or whether we should skip the proguard step and only feed the proguard rules to it. Please clarify :)

**Comment by justinjhendrick** [comment]
Either one works. It's up to you to decide which is best for you. Redex can do a lot (but not all) of the optimizations that proguard can, but you need to fiddle with your redex config to enable all the right  optimizations for that. (which admittedly isn't easy and isn't documented well...)

You should definitely feed the proguard rules into redex though. It tell Redex where the roots of the reachability graph are.

**Comment by slavasav** [comment]
I see, thank you.
