### ISSUE TITLE
i get a java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by microsoftBoy** [facebook/redex#422]
java.lang.NoSuchMethodError: No static method setTimeout(Lorg/apache/http/params/AbstractHttpParams;J)V in class Lorg/apache/http/conn/params/ConnManagerParams; or its super classes (declaration of 'org.apache.http.conn.params.ConnManagerParams' appears in /system/framework/org.apache.http.legacy.boot.jar)

but,the byteCode about ConnManagerParams  in classes.dex :

.method public static setTimeout(Lorg/apache/http/params/AbstractHttpParams;J)V
    .registers 3

    .line 8
    new-instance p1, Ljava/lang/RuntimeException;

    const-string p0, "Stub!"

    invoke-direct {p1, p0}, Ljava/lang/RuntimeException;-><init>(Ljava/lang/String;)V

    throw p1
.end method

**Comment by emma0303** [comment]
//'org.apache.http.conn.params.ConnManagerParams' appears in /system/framework/org.apache.http.legacy.boot.jar)//
It seems the method was searched in `/system/framework/org.apache.http.legacy.boot.jar`, while your code is from within your app (I assume) - given the Runtime Error that would be thrown there, if used.

`setTimeout` was deprecated. Based on https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/params/ConnManagerParams.html, `HttpConnectionParams.setConnectionTimeout(HttpParams, int)` is advised to be used.

**Comment by microsoftBoy** [comment]
thank you
