### ISSUE TITLE
redex: command not found

### ISSUE THREAD

**Issue by ltym2016** [facebook/redex#423]
My OS is macOS，I installed and compiled according to this document, but the prompt “-bash: redex: command not found”  The following is my installation steps：

1 `xcode-select--install` 
2` brew install autoconf automake libtool python3` 
` brew install boost jsoncpp` 
3` git clone https://github.com/facebook/redex.git` 
` cd redex` 
4 ` autoreconf -ivf && ./configure && make -j4
sudo make install` 

but，When I run the "redex path/to/your.apk -o path/to/output.apk" command, I get "-bash: redex: command not found".I need help because I can't find the reason, thank you very much.

**Comment by justinjhendrick** [comment]
I think you're missing another ` && ` between `make -j4` and `sudo make install`. Those are separate commands.
```
autoreconf -ivf && ./configure && make -j4 && sudo make install
```

**Comment by ltym2016** [comment]
`lysdeMacBook-Pro:~ lys$ git clone https://github.com/facebook/redex.git`
`Cloning into redex...`
`remote: Enumerating objects: 512, done.`
`remote: Counting objects: 100% (512/512), done.`
`remote: Compressing objects: 100% (400/400), done.`
`remote: Total 29180 (delta 230), reused 247 (delta 109), pack-reused 28668`
`Receiving objects: 100% (29180/29180), 13.24 MiB | 4.36 MiB/s, done.`
`Resolving deltas: 100% (21845/21845), done.`
`lysdeMacBook-Pro:~ lys$ cd redex`
`lysdeMacBook-Pro:redex lys$ autoreconf -ivf && ./configure && make -j4 && sudo make install`

I ran the command "autoreconf -ivf && ./configure && make -j4 && sudo make install" but still prompted the following message：

`lysdeMacBook-Pro:redex lys$ redex /Users/lys/DeskTop/app-release.apk -o /Users/lys/Desktop/out.apk
-bash: redex: command not found`

I found the following error message in the log, I don't know if it has any effect, how should I solve it?


`In file included from /usr/local/include/boost/variant/apply_visitor.hpp:16:`
`/usr/local/include/boost/variant/detail/apply_visitor_unary.hpp:98:33: error: no
      matching function for call to object of type '(lambda at
      ./sparta/include/DisjointUnionAbstractDomain.h:91:26)'
        typedef decltype(true ? boost::declval< Visitor& >()( boost::decl...
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
`

**Comment by emma0303** [comment]
Sorry for the long delay, missed the follow up here. 

It seems there was a compile error for redex. That should be solved by now. Did you end uo retrying? Thanks

**Comment by emma0303** [comment]
Closing the issue as it should be solved. Feel free to open a different issue if you find a different type of problem / same when retrying. Thanks
