### ISSUE TITLE
 configure error

### ISSUE THREAD

**Issue by Guolei1130** [facebook/redex#430]
autoreconf -ivf && ./configure --with-boost=/usr/local/Cellar/boost/1.71.0 --with-boost-libdir=/usr/local/Cellar/boost/1.71.0/lib --host=arm && make -j4

checking for boostlib >= 1.58.0... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... no
checking for exit in -lboost_filesystem... (cached) no
checking for exit in -lboost_filesystem-mt... no
checking for exit in -lboost_filesystem-mt... (cached) no
configure: error: Could not link against boost_filesystem-mt !

**Comment by rackamx** [comment]
Odd, it's not able to link with your boost_filesystem lib (but if found the headers). Can you check the config.log, see what the error is in there ?
