### ISSUE TITLE
Announcement: Upgrading Required Boost Version (1.58 -> 1.66)

### ISSUE THREAD

**Issue by justinjhendrick** [facebook/redex#436]
As of 82b8cb6f0fb7e4454444384d58f83722102e21d3, Boost 1.66 is required to build redex (upgraded from 1.58).

If boost 1.66 is not available in your system's package-manager, you can use `get_boost.sh` to download boost and install it.

**Comment by beyondckw** [comment]
I have run the cmd of "sudo ./get_boost.sh", but still have an error of  "configure: error: Please install boost >= 1.66 (including filesystem)". so, what 's the problem?
