### ISSUE TITLE
 git submodule update --init

### ISSUE THREAD

**Issue by Sadmansamee** [facebook/redex#44]
when I'm trying to run 
`git submodule update --init` it says "fatal: Not a git repository (or any of the parent directories): .git"

**Comment by jaredsburrows** [comment]
You have to `cd` into `redex`.

**Comment by Sadmansamee** [comment]
Thanks now i'm getting "configure: error: Please install double-conversion library" and also redex can not be found

**Comment by kageiit** [comment]
I am also getting "configure: error: Please install double-conversion library"

**Comment by bertmaher** [comment]
The double-conversion thing is #15 , please see comments there for the solution.
