### ISSUE TITLE
'DexDefs.h' file not found

### ISSUE THREAD

**Issue by Enzo-Fight** [facebook/redex#447]
../../libredex/DexClass.h:24:10: fatal error: 'DexDefs.h' file not found
../../libredex/DexDebugInstruction.h:12:10: fatal error: 'DexDefs.h' file not found

**Comment by budmonde** [comment]
Hi, what were you trying to do when you had this error? As is, we can't really investigate the issue.

**Comment by budmonde** [comment]
Feel free to re-open with additional context!

**Comment by joychic** [comment]
It appeared when I  run the unit test suite too. But I can find DexDebugInstruction.h in libredex

./test/setup.sh
cd test
make check

**Comment by HeroAm4Kobe** [comment]
mv -f $depbase.Tpo $depbase.Po
In file included from SynthTest.cpp:18:
In file included from ../../libredex/ControlFlow.h:16:
In file included from ../../libredex/IRCode.h:16:
In file included from ../../libredex/DexClass.h:23:
../../libredex/DexDebugInstruction.h:12:10: fatal error: 'DexDefs.h' file not found
#include "DexDefs.h"
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [SynthTest.o] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1


me,too
It appeared when I run the unit test suite too. But I can find DexDebugInstruction.h in libredex

./test/setup.sh
cd test
make check
