### ISSUE TITLE
How can I output a dex file instead a apk file ?

### ISSUE THREAD

**Issue by JasonWu1111** [facebook/redex#448]
I am developing SDK which is in aar format, I want to compress the class.jar file into a dex file by redex. But redex only accepts apk file, how can I handle it?

**Comment by yuxuanchen1997** [comment]
The `redex-all` binary accepts dex files. If you want to convert jar files to dex, `dx` or `d8` should be the tool you are looking for. You can run redex to optimize the dex files generated by `dx` or `d8` if you wish.
