### ISSUE TITLE
https://fbredex.com/docs/synth

### ISSUE THREAD

**Issue by popoaichuiniu** [facebook/redex#452]
The example you show, don‘t have a correct problem？： change the access of the field？

**Comment by agampe** [comment]
Can you maybe reformulate your question? It's not clear what you mean.

The docs state:

> To make the access of the alpha field legal for the Dalvik VM we have mutated the access permissions for this field:

So Redex does change the access flags of the field to allow inlining/replacing the synthetic method.

**Comment by popoaichuiniu** [comment]
if some one can‘t access the field, but you change the flag of the field.  At now, it can access the field.

**Comment by yuxuanchen1997** [comment]
We do change access flags of class members if an optimization pass finds it necessary. This should not cause problems for the app.

**Comment by agampe** [comment]
Redex is a whole-program optimizer. It expects the input to be correct, i.e., there is no code trying to access the field without access rights. In that case, it does not change program behavior to make a field public.
