### ISSUE TITLE
Ability to provide jsoncpp path

### ISSUE THREAD

**Issue by igas** [facebook/redex#457]
Hi 👋 

I'm trying to upgrade `jsoncpp` in [homebrew](https://brew.sh). https://github.com/Homebrew/homebrew-core/pull/49702

We test dependencies, redex is one of them and does not build anymore. It fails to locate it as path is hardcoded to `/usr/include/jsoncpp`. Is there a way to overwrite it?

I assume that macOS instructions will have the same problem, as homebrew installs it to `/usr/local`.

**Comment by justinjhendrick** [comment]
Does your `$PATH` include the directory where jsoncpp is?

Could you add a symlink to fix the issue?

**Comment by agampe** [comment]
You can use `CPPFLAGS` and `LDFLAGS` to point to a "non-standard" jsoncpp install path (we don't have that as an explicit `configure` parameter, only for boost). Something like:
```
export CPPFLAGS="$CPPFLAGS -I/path/to/jsoncpp/include"
export LDFLAGS="$LDFLAGS -L/path/to/jsoncpp/lib"
autoreconf -i
./configure
make
```
