### ISSUE TITLE
How to use DedupStringsPass?

### ISSUE THREAD

**Issue by woshitangebupasui** [facebook/redex#460]
When I use the "DedupStringsPass" configuration of redex, redex prompts me that the number of registers exceeds the limit. But when I added "RegAllocPass" after "DedupStringsPass", it reminded me again 'Trying to encode too many method refs in dex 2: 65540 (limit: 65536)'. How can I resolve these issues?
My config.file：
{
  "redex" : {
    "passes" : [
      "MakePublicPass",
      "DedupStringsPass",
      "RegAllocPass"
    ]
  }
}

**Comment by newobj** [comment]
` 'Trying to encode too many method refs in dex 2: 65540 (limit: 65536)'`.

This message has nothing to do with DedupStringsPass. Every dex is limited to 64k method refs (and other dex items like type refs, classes, etc). 

It looks like you have a multidex application, correct? You must run the Interdex pass if you have a multidex application. I would recommend starting with the `config/aggressive.config` Redex config, which includes Interdex, and adding or removing passes as needed from there.

**Comment by newobj** [comment]
Feel free to reopen the task if you need further assistance.
