### ISSUE TITLE
Failed to execute zipalign, strerror: Exec format error

### ISSUE THREAD

**Issue by 30sunling** [facebook/redex#461]

**Comment by 30sunling** [comment]
ubuntu 18

**Comment by agampe** [comment]
When filing an issue, please give more details. Give the full process output, at minimum

Redex does not package `zipalign`. Please ensure that you have the right version for your OS. What is the output of:
```
file `which zipalign`
```
and
```
uname -a
```
or
```
cat /proc/cpuinfo
```
