### ISSUE TITLE
Can`t find pure/safe method

### ISSUE THREAD

**Issue by Cregrant** [facebook/redex#471]
I see a lot of messages during running LocalDcePass/CommonSubexpressionEliminationPass like
```
[get_pure_methods]: Could not find pure method Ljava/lang/Math;.expm1:(D)D
[get_pure_methods]: Could not find pure method Ljava/lang/Math;.floorDiv:(II)I
```
```
[CSE]: Could not find safe method Ljava/lang/Math;.addExact:(JJ)J
[CSE]: Could not find safe method Ljava/lang/Math;.decrementExact:(J)J
```
Can it broke my apk? As an example - "implementing interface method which is not public" error (in logcat)?

**Comment by yuxuanchen1997** [comment]
Hello,

Can you share the command you used to run Redex? It's likely that you are missing a `-j /path/to/android_sdk/android.jar`. `Ljava/lang/Math;` is part of the Java library and we expect to find them in the support library jar. 

> Can it broke my apk?

In this particular problem, it may not. But it's hard to tell what may go wrong when you don't pass redex your support library jar.

Thanks.

**Comment by Cregrant** [comment]
> you are missing a `-j /path/to/android_sdk/android.jar`

You`re absolutely right. The "libandroid-23-java" fix most of errors (looks like others are unimportant)

> Can it broke my apk?

Yes!

By the way, who can update some info to FAQ at https://fbredex.com? Redex requires boost version >= 1.71, not 1.58
I spent a lot of time because **`sudo apt-get install libboost-all-dev`** command install an old 1.65 one. So fix is very simple but not clear: run `git clone https://github.com/facebook/redex.git`   `cd redex` and **then** `sudo ./get_boost.sh`
