### ISSUE TITLE
Found use without def when processing

### ISSUE THREAD

**Issue by Cregrant** [facebook/redex#479]
`Running RegAllocPass...
Failed to allocate Le/c/a/g;.l:()V: service/dataflow/LiveRange.cpp:92: {anonymous}::UDChains {anonymous}::calculate_ud_chains(const cfg::ControlFlowGraph&): 
assertion ``!defs.is_top() && defs.size() > 0' failed.
Found use without def when processing [0x7f490e9478d0]MONITOR_ENTER v0
`

Looks like an old error https://github.com/facebook/redex/issues/362 that was fixed but.. i am lucky. Any suggestions?

**Comment by agampe** [comment]
No suggestion from a report without much information content. :-(

In the code dump, if you manually trace, was the analysis correct (and the `monitor-enter` is reachable without `v0` being defined)? If you run with `-J ir_type_checker.run_after_each_pass=true`, does it fail somewhere?

If so, can you figure out (bisect the passes, use after-pass dumps [e.g., the CFG dumper] and compare manually) where it starts going wrong?

(Remote diagnosing isn't really possible here, so if you need help you will have to share a [minimal] reproducer with us...)

**Comment by Cregrant** [comment]
> ir_type_checker.run_after_each_pass=true

You`re right i should use this to check a code before question.
