### ISSUE TITLE
 fatal error: InstructionSequenceOutliner.h: No such file or directory

### ISSUE THREAD

**Issue by zhangkevd** [facebook/redex#480]
system：Ubuntu 20

when i build ReDex using autoconf and make. get this
autoreconf -ivf && ./configure && make -j4
![TIM截图20200509153509](https://user-images.githubusercontent.com/3618002/81467359-bc051780-920a-11ea-9bbd-06f172735b8c.png)

**Comment by Zane96** [comment]
+1

**Comment by justinjhendrick** [comment]
@NTillmann, did you forget to update a makefile when you landed the `InstructionSequenceOutliner`?

**Comment by justinjhendrick** [comment]
Same error on Travis here: https://travis-ci.org/github/facebook/redex/builds/684483861

**Comment by justinjhendrick** [comment]
As a workaround, you can checkout https://github.com/facebook/redex/commit/15de5e5792d9a060984a908eaa3c12eaaa85e6e1 and build from there

**Comment by Zane96** [comment]
It works~ Thanks!!

**Comment by justinjhendrick** [comment]
Travis passed on https://github.com/facebook/redex/commit/8ec9be2330c6451988aa38b4d71e0f9b5822612b. Closing
