### ISSUE TITLE
Instrumenting ClassLoader and viewing DEX file access

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#481]
In a previous issue, it was mentioned that FB is instrumenting the classloader to get the cold start classlist instead of using the `dump_classes_from_hprof`. Are there any code references you can share on how you do this process?

Additionally, the visual from [Scaling Android with Redex tech talk](https://www.facebook.com/watch/?v=1960349394238155) is very interesting. Do you have any pointers on how to setup this sort of instrumentation? 
<img width="714" alt="Screen Shot 2020-05-12 at 12 30 28 PM" src="https://user-images.githubusercontent.com/9221137/81737177-8d767f00-944c-11ea-8cfc-732b840d63d6.png">

**Comment by zhangkevd** [comment]
Which issue?
so dump_classes_from_hprof.py is out of date？

**Comment by benjaminRomano** [comment]
The `dump_classes_from_hprof.py` crashes on a lot of cases when given heap dumps from new OS versions. I've personally patched a lot of the holes here. Based on feedback from Redex maintainer, insturmenting the app may be a better option: https://github.com/facebook/redex/issues/387#issuecomment-489268289

**Comment by zhangkevd** [comment]
> The `dump_classes_from_hprof.py` crashes on a lot of cases when given heap dumps from new OS versions. I've personally patched a lot of the holes here. Based on feedback from Redex maintainer, insturmenting the app may be a better option: [#387 (comment)](https://github.com/facebook/redex/issues/387#issuecomment-489268289)

insturmenting the app may be no easy.

**Comment by shanenay** [comment]
WRT the visualization:  The source instrumentation was the names of classes that were loaded gathered via instrumentation in the class-loader.  Then the A case was a projection of the dex-layout using default ordering and the B case was a projection of the ordered output.  All real data, the only thing synthetic was I made assumptions about how large individual methods would be (just size / N st N is the number of methods)  Then a script that implemented a model of the kernel's fault handler.  I used a simpler model than what you'd find in a modern version of Android.  Basically X amount of page-cache, X "read-ahead", with a simulation of the LRU lists used in the kernel for active and inactive pages.  I modeled the hash-table lookups in dex as random (which they just about are ;) ).

We have done several "real" fault tracing though which lines up with the above simulation/model.  I didn't do them so I don't know the exact instrumentation used, I think one time someone just wrote it, and another they may have used perf counters?  Not sure.

Now, modern versions of Linux are a little different, they do pre-fetch without taking a hard-fault for sequential-ish faulting applications.  But proximally the behavior is still similar, it's just slightly more optimal from a systems perspective than the model above.

**Comment by benjaminRomano** [comment]
thanks for the detailed response. That's a very cool approach :)

I was also able to find a way to instrument the class loaders. FWIW, it didn't show much improvement over collecting classes from heap dumps based on our performance testing.
