### ISSUE TITLE
InterDexPass Invaild !! Help

### ISSUE THREAD

**Issue by LessTalk** [facebook/redex#488]
this is order  
redex -c /my-path/Redex/redex/config/default.config -o hello.apk /my-path/apk/debug/app-debug.apk
and this is my default.config but function is not effective
{
    "redex" : {
        "passes" : [
            "ReBindRefsPass",
            "BridgePass",
            "ResultPropagationPass",
            "FinalInlinePassV2",
            "DelSuperPass",
            "CommonSubexpressionEliminationPass",
            "MethodInlinePass",
            "PeepholePass",
            "ConstantPropagationPass",
            "LocalDcePass",
            "RemoveUnreachablePass",
            "RemoveGotosPass",
            "DedupBlocksPass",
            "UpCodeMotionPass",
            "SingleImplPass",
            "ReorderInterfacesPass",
            "RemoveEmptyClassesPass",
            "ShortenSrcStringsPass",
            "CommonSubexpressionEliminationPass",
            "RegAllocPass",
            "CopyPropagationPass",
            "LocalDcePass",
            "InterDexPass",
            "ReduceGotosPass"
        ]
    },
    "ir_type_checker": {
        "run_after_each_pass": true
    },
    "InterDexPass" : {
        "coldstart_classes":[
            "org/less/abtest/TestActivity.class"
        ]
    },

**Comment by agampe** [comment]
> [...] is not effective

What does that mean, exactly?

**Comment by LessTalk** [comment]
> > [...] is not effective
> 
> What does that mean, exactly?

invalid default.config invalid

**Comment by LessTalk** [comment]
> > > [...] is not effective
> > 
> > 
> > What does that mean, exactly?
> 
> invalid default.config invalid

How to configure it to make it effective？

**Comment by yuxuanchen1997** [comment]
Are you sure you are using the provided `default.config`? I see you have an extra semicolon at the end of the config.

**Comment by LessTalk** [comment]
> Are you sure you are using the provided `default.config`? I see you have an extra semicolon at the end of the config.

{
  "redex" : {
    "passes" : [
      "ReBindRefsPass",
      "BridgePass",
      "ResultPropagationPass",
      "FinalInlinePassV2",
      "DelSuperPass",
      "CommonSubexpressionEliminationPass",
      "MethodInlinePass",
      "PeepholePass",
      "ConstantPropagationPass",
      "LocalDcePass",
      "RemoveUnreachablePass",
      "RemoveGotosPass",
      "DedupBlocksPass",
      "UpCodeMotionPass",
      "SingleImplPass",
      "ReorderInterfacesPass",
      "RemoveEmptyClassesPass",
      "ShortenSrcStringsPass",
      "CommonSubexpressionEliminationPass",
      "RegAllocPass",
      "CopyPropagationPass",
      "LocalDcePass",
      "InterDexPass",
      "ReduceGotosPass"
    ]
  },
  "ir_type_checker": {
    "run_after_each_pass": true
  },
  "InterDexPass" : {
    "coldstart_classes": "~/redex/config/list_of_classes.txt" 
  },
  "FinalInlinePass" : {
    "propagate_static_finals": true,
    "replace_encodable_clinits": true
  },
  "MethodInlinePass": {
    "throws": true,
    "multiple_callers": true,
    "black_list": []
  },
  "RegAllocPass" : {
    "live_range_splitting": false
  },
  "CopyPropagationPass" : {
    "eliminate_const_literals": false,
    "full_method_analysis": true
  },
  "PeepholePass" : {
    "disabled_peepholes": [
      "Replace_PutGet",
      "Replace_PutGetWide",
      "Replace_PutGetObject",
      "Replace_PutGetShort",
      "Replace_PutGetChar",
      "Replace_PutGetByte",
      "Replace_PutGetBoolean"
    ]
  },
  "keep_packages": [
    "Lcom/fasterxml/jackson/",
    "Lcom/google/dexmaker/mockito/"
  ],
  "debug_info_kind": "no_custom_symbolication",
  "method_move_map" : "redex-moved-methods-map.txt",
  "string_sort_mode" : "class_order",
  "bytecode_sort_mode" : "class_order",
  "ir_type_checker": {
    "run_after_each_pass" : false,
    "verify_moves" : false
  }
}
This is complete,but function invaild so whether to provide effective demo

**Comment by yuxuanchen1997** [comment]
What do you mean by "function invalid"? Do you see an error message? What does it say?
