### ISSUE TITLE
Turn off input checking with `-J ir_type_checker.run_on_input=false` not work

### ISSUE THREAD

**Issue by shixinzhang** [facebook/redex#489]
Hi I'm trying to use interdex but an error has occurred. Here is my input :

```
admin$ /Users/simon/Documents/code/redex/redex -c ./interdex.config -o output.apk -P proguard.rule -J ir_type_checker.run_on_input_ignore_access=true -J ir_type_checker.run_on_input=false aweme_aweGW_v11.3.0_b5b6cb6.apk 
```

Result is:

```
Inconsistency found in Dex code for Lcom/ss/android/ugc/aweme/story/shootvideo/textrecord/TextStickerTextWrap;.writeToParcel:(Landroid/os/Parcel;I)V
 Type error in method Lcom/ss/android/ugc/aweme/story/shootvideo/textrecord/TextStickerTextWrap;.writeToParcel:(Landroid/os/Parcel;I)V at instruction 'INVOKE_INTERFACE v0, Ljava/util/Map$Entry;.getKey:()Ljava/lang/Object;' @ 0x7f9ca7b4acc0 for : Ljava/lang/Object; is not assignable to Ljava/util/Map$Entry;
//...
If you are confident that this does not matter, turn off input checking with `-J ir_type_checker.run_on_input=false`.
```

The question is I follow the advice "If you are confident that this does not matter, turn off input checking with `-J ir_type_checker.run_on_input=false`", add  `-J ir_type_checker.run_on_input=false`  but get the same result.

And here is my config:

```
{
  "redex": {
    "passes": [
      "InterDexPass",
      "RegAllocPass",
      "MakePublicPass"
    ]
  },
  "InterDexPass": {
    "minimize_cross_dex_refs": true
  },
  "stats_output": "redex-stats.txt",
  "coldstart_classes": "dy-class-list.txt"
}
```

**I just want turn off input checking, Thanks for your help.**

**Comment by shixinzhang** [comment]
Finally I find answer in source code. 

![image](https://user-images.githubusercontent.com/17017832/85408568-43c69b80-b597-11ea-9156-97b9b5de694f.png)

Need use `` -J ir_type_checker.run_on_input=false -J ir_type_checker.run_after_each_pass=false`` together.

**Comment by yuxuanchen1997** [comment]
You can add this section to your config.

```JSON
"ir_type_checker": {
    "run_after_each_pass": false,
    "run_on_input": false
},
```

**Comment by agampe** [comment]
Please note that incorrect input bytecode can easily lead to miscompilations. It would be beneficial if you figured out what's going wrong.

> 'INVOKE_INTERFACE v0, Ljava/util/Map$Entry;.getKey:()Ljava/lang/Object;' @ 0x7f9ca7b4acc0 for : Ljava/lang/Object; is not assignable to Ljava/util/Map$Entry;

The type checker should let that pass, as it's an interface, and classes are always assignable. Maybe you are missing the Android SDK definitions so the type checker does not know that `Map.Entry` is an interface?

**Comment by shixinzhang** [comment]
> Please note that incorrect input bytecode can easily lead to miscompilations. It would be beneficial if you figured out what's going wrong.
> 
> > 'INVOKE_INTERFACE v0, Ljava/util/Map$Entry;.getKey:()Ljava/lang/Object;' @ 0x7f9ca7b4acc0 for : Ljava/lang/Object; is not assignable to Ljava/util/Map$Entry;
> 
> The type checker should let that pass, as it's an interface, and classes are always assignable. Maybe you are missing the Android SDK definitions so the type checker does not know that `Map.Entry` is an interface?

I have configured Android SDK path in .bash_profile, should I add the path in redex config? I didn't see the redex document about that.

**Comment by agampe** [comment]
> I have configured Android SDK path in .bash_profile, should I add the path in redex config? I didn't see the redex document about that.
