### ISSUE TITLE
Mac build error:  error: possibly undefined macro: AC_MSG_ERROR

### ISSUE THREAD

**Issue by rossbacher** [facebook/redex#49]
I get this error while trying to build:

```
configure.ac:21: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

The internet suggests to install `pkg-config`, which I did, also installed `python3` which the error seems to be about to no avail.

**Comment by bertmaher** [comment]
If you're using homebrew, you might try `brew upgrade autoconf automake`.  I'm using autoconf-2.69/automake-1.15 on my Mac.

**Comment by rossbacher** [comment]
I just installed them today so I already had the latest versions:

```
brew upgrade autoconf automake
Error: autoconf 2.69 already installed
Error: automake 1.15 already installed
```

Still same error.
