### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by geyy472** [facebook/redex#490]
ubuntu16.04
redex code commitId : 1a7cb8b11bb6b72eac9c4141d0a3e2e9fcb507dd
When running after installation，An error occurred：
  File "/tmp/redex.avc56r/redex.py", line 253
    print(f"{line}")
                  ^
SyntaxError: invalid syntax

**Comment by kuganv** [comment]
Could you please let me know what version of Python are you using? You need a recent Python for this. Please also provide the exact command you are using to reproduce.

**Comment by agampe** [comment]
@kuganv We will have to remove f-strings. 16.04 only comes with Python 3.5... :-(

@geyy472 Is there a reason you are stuck with Ubuntu 16.04? Could you use 18.04?
