### ISSUE TITLE
RuntimeError: redex-all crashed with exit code 1! 

### ISSUE THREAD

**Issue by wang0420** [facebook/redex#492]
If you are confident that this does not matter (e.g., because you are using MakePublicPass), turn off accessibility checking on input with `-J ir_type_checker.run_on_input_ignore_access=true`.
 You may turn off all input checking with `-J ir_type_checker.run_on_input=false`.
Traceback (most recent call last):
  File "/tmp/redex.XmiF5L/redex.py", line 1049, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.XmiF5L/pyredex/utils.py", line 56, in with_temp_cleanup
    fn()
  File "/tmp/redex.XmiF5L/redex.py", line 1049, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.XmiF5L/redex.py", line 1028, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.XmiF5L/redex.py", line 494, in run_redex_binary
    if run():
  File "/tmp/redex.XmiF5L/redex.py", line 479, in run
    ).format(returncode, gdb_script_name, lldb_script_name)
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.XmiF5L/redex-gdb-5jlzg8y9.sh or under lldb by running /tmp/redex.XmiF5L/redex-lldb-6hseqmxg.sh

**Comment by agampe** [comment]
Your input code does not type-check. Specifically, the code accesses inaccessible members. The first sentence describes what you can do to work around the crash, but really you should be fixing your inputs to be correct (as otherwise redex can make no guarantees that any optimization is correct).

**Comment by rybalkinsd** [comment]
Hey @wang0420, could you please give more details about your input?

Please also have a look at #489 for some ideas.
