### ISSUE TITLE
Can't find zipalign if preview exists. 

### ISSUE THREAD

**Issue by VenomVendor** [facebook/redex#51]
Trying to find `zipalign` fails if preview version of build tool exists.

**Comment by Gavin1989** [comment]
`zipalign` is an optimization step that is bundled with the Android SDK. You need to tell `redex` where to find it. For example, if you installed the SDK at `/path/to/android/sdk`, try:

`ANDROID_SDK=/path/to/android/sdk redex [... arguments ...]`
You can alternatively add `zipalign` to your `PATH`, for example:

`PATH=/path/to/android/sdk/build-tools/xx.y.zz:$PATH redex [... arguments ...]`

**Comment by bertmaher** [comment]
Thanks for the PR!  I've merged it in.
