### ISSUE TITLE
Interdex fails when `apk_dir` is not specified.

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#517]
Interdex fails with `error: not a writable directory: ` if `apk_dir` is not defined in the configuration. This could be fixed by adding a check for empty string [here](https://github.com/facebook/redex/blob/master/libredex/ApkManager.cpp#L32).

**Comment by kuganv** [comment]
Thanks for reporting. I am testing a patch along what you have suggested and will commit that soon.
