### ISSUE TITLE
AccessMarkingPass privatizing methods defined in proguard rules

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#518]
Configuration:
```
   "passes": [
     "AccessMarkingPass",
     "MethodDevirtualizationPass",
     "ReBindRefsPass",
     "BridgePass",
     "ResultPropagationPass",
     "SynthPass",
     "FinalInlinePassV2",
     "DelSuperPass",
     "UnreferencedInterfacesPass",
     "SingleImplPass",
     "CommonSubexpressionEliminationPass",
     "MethodInlinePass",
     "PeepholePass",
     "ConstantPropagationPass",
     "LocalDcePass",
     "AnnoKillPass",
     "ReorderInterfacesPass",
     "RemoveEmptyClassesPass",
     "SingleImplPass",
     "InterDexPass",
     "CommonSubexpressionEliminationPass",
     "RemoveGotosPass",
     "DedupBlocksPass",
     "RemoveRedundantCheckCastsPass",
     "UpCodeMotionPass",
     "RegAllocPass",
     "CopyPropagationPass",
     "LocalDcePass",
     "DedupBlocksPass",
     "ReduceGotosPass"
   ]
 },
```

I have the following proguard rule:
```
-keepclassmembers,allowobfuscation class * extends com.google.gson.TypeAdapter {
  public <init>(com.google.gson.Gson);
  public void write(...);
  public *** read(...);
}
```
which I would expect to preserve the access modifiers of the following methods. However, the `init` method was getting modified to be private. I suspect this is due to `AccessMarkingPass`. I can patch these up by running `MakePublicPass`, but it was unexpected that I would need both. Is this behavior possibly intended to aid in later optimization passes?

**Comment by kuganv** [comment]
Thanks for reporting. Proguard rule you provide has allowobfuscation so AccessMarkingPass by design will consider those methods for making them private. It is guarded with can_rename() and it will be true when allowobfuscation.

**Comment by benjaminRomano** [comment]
thanks for the clarification
