### ISSUE TITLE
Is FB Patent abusive or just unclear ?

### ISSUE THREAD

**Issue by stephanenicolas** [facebook/redex#52]
The patent file says : 
> A "Patent Assertion" is any lawsuit or other action alleging direct, indirect,
or contributory infringement or inducement to infringe any patent, including a
cross-claim or counterclaim.

There is something logical in the patent file : a protection for FB not being possibly sued for using this stuff. Which seems logical, and I would believe the apache licence or other licences already have provisions for this. 

Though, the claim here is broader : it is not possible to sue FB on **any** patent and this include counter patent assertion. So a logical reading of the patent file is : "if your company has patents, and use redex, and FB violates the company's patent, then the company cannot sue FB because the company uses redex." I believe this reading is not expected, it would probably be abusive as no one can bargain the right to go against the law. The patent assertion is probably missing : 
>  A "Patent Assertion" is any lawsuit or other action alleging direct, indirect,
or contributory infringement or inducement to infringe any patent **regarding the Software**, 
including a cross-claim or counterclaim.

Can this be clarified ?

**Comment by bootstraponline** [comment]
context: https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/

**Comment by stephanenicolas** [comment]
Thx for the context, but still, I think there is something strange regarding what I introduced initially.

**Comment by bertmaher** [comment]
Thanks for your concerns, but this is our standard license/patent grant text.  None of us are lawyers and as such are not qualified to comment or take any action on this.

**Comment by stephanenicolas** [comment]
is it possible to send it to the legal department ? I am not a lawyer neither but I think it's a concern some devs would have. At least do I.. :)

**Comment by stephanenicolas** [comment]
@bertmaher some action should definitely be taken here, you can't just wipe out this kind of question. If you add a licence you must find a way to answer questions about it..

**Comment by bertmaher** [comment]
I will reopen this and pass your question on to legal.

**Comment by stephanenicolas** [comment]
Thx @bertmaher

**Comment by bertmaher** [comment]
Hey @stephanenicolas, I checked with our lawyer, and I'm afraid I still can't give you much here, since we can't give legal advice via GitHub issues.  But, thanks for your feedback on the license -- we do listen to feedback, as this is actually v2 of our standard license.  You can read some community discussion of it here: https://news.ycombinator.com/item?id=9356508.  Beyond that, you'd need to speak with your own lawyer.

**Comment by stephanenicolas** [comment]
Lol. I was not aware I had to take a lawyer to code OSS ;)

Thx for asking though.
