### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by gaoyangcr7** [facebook/redex#521]
$redex -c config/default.config -o /Users/xxx/Desktop/output.apk /Users/xxx/Documents/app-debug.apk
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
        Load classes from dexes completed in 1.9 seconds
        Deobfuscating dex elements completed in 0.1 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 0.0 seconds
        No Optimizations Rules completed in 3.3 seconds
            Mark keep-methods completed in 0.0 seconds
            Computing XML reachability completed in 0.0 seconds
            Computing native reachability completed in 0.0 seconds
            Analyzing reflection completed in 0.3 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 0.3 seconds
    Redex_frontend completed in 5.6 seconds
        API Level Checker completed in 0.0 seconds
Evaluating ReBindRefsPass...
        ReBindRefsPass (eval) completed in 0.0 seconds
Evaluating BridgePass...
        BridgePass (eval) completed in 0.0 seconds
Evaluating ResultPropagationPass...
        ResultPropagationPass (eval) completed in 0.0 seconds
Evaluating FinalInlinePassV2...
        FinalInlinePassV2 (eval) completed in 0.0 seconds
Evaluating DelSuperPass...
        DelSuperPass (eval) completed in 0.0 seconds
Evaluating CommonSubexpressionEliminationPass...
        CommonSubexpressionEliminationPass (eval) completed in 0.0 seconds
Evaluating MethodInlinePass...
        MethodInlinePass (eval) completed in 0.0 seconds
Evaluating PeepholePass...
        PeepholePass (eval) completed in 0.0 seconds
Evaluating ConstantPropagationPass...
        ConstantPropagationPass (eval) completed in 0.0 seconds
Evaluating LocalDcePass...
        LocalDcePass (eval) completed in 0.0 seconds
Evaluating RemoveUnreachablePass...
        RemoveUnreachablePass (eval) completed in 0.0 seconds
Evaluating RemoveGotosPass...
        RemoveGotosPass (eval) completed in 0.0 seconds
Evaluating DedupBlocksPass...
        DedupBlocksPass (eval) completed in 0.0 seconds
Evaluating UpCodeMotionPass...
        UpCodeMotionPass (eval) completed in 0.0 seconds
Evaluating SingleImplPass...
        SingleImplPass (eval) completed in 0.0 seconds
Evaluating ReorderInterfacesPass...
        ReorderInterfacesPass (eval) completed in 0.0 seconds
Evaluating RemoveEmptyClassesPass...
        RemoveEmptyClassesPass (eval) completed in 0.0 seconds
Evaluating ShortenSrcStringsPass...
        ShortenSrcStringsPass (eval) completed in 0.0 seconds
Evaluating CommonSubexpressionEliminationPass...
        CommonSubexpressionEliminationPass (eval) completed in 0.0 seconds
Evaluating RegAllocPass...
        RegAllocPass (eval) completed in 0.0 seconds
Evaluating CopyPropagationPass...
        CopyPropagationPass (eval) completed in 0.0 seconds
Evaluating LocalDcePass...
        LocalDcePass (eval) completed in 0.0 seconds
Evaluating ReduceGotosPass...
        ReduceGotosPass (eval) completed in 0.0 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 5.5 seconds
        Hasher completed in 0.3 seconds
Running ReBindRefsPass...
            Hasher completed in 0.2 seconds
        ReBindRefsPass (run) completed in 0.5 seconds
Running BridgePass...
            Hasher completed in 0.2 seconds
        BridgePass (run) completed in 0.2 seconds
Running ResultPropagationPass...
            Building method override graph completed in 0.1 seconds
            Hasher completed in 0.3 seconds
        ResultPropagationPass (run) completed in 6.8 seconds
Running FinalInlinePassV2...
            Hasher completed in 0.3 seconds
        FinalInlinePassV2 (run) completed in 0.3 seconds
Running DelSuperPass...
            Hasher completed in 0.3 seconds
        DelSuperPass (run) completed in 0.6 seconds
Running CommonSubexpressionEliminationPass...
            Building method override graph completed in 0.1 seconds
            compute_conditionally_pure_methods completed in 0.3 seconds
            init_method_barriers completed in 0.3 seconds
            Hasher completed in 0.4 seconds
        CommonSubexpressionEliminationPass (run) completed in 21.2 seconds
Running MethodInlinePass...
            Hasher completed in 0.3 seconds
        MethodInlinePass (run) completed in 0.3 seconds
Running PeepholePass...
            Hasher completed in 0.3 seconds
        PeepholePass (run) completed in 3.8 seconds
Running ConstantPropagationPass...
            Hasher completed in 0.3 seconds
        ConstantPropagationPass (run) completed in 12.6 seconds
Running LocalDcePass...
            Building method override graph completed in 0.1 seconds
            compute_no_side_effects_methods completed in 0.3 seconds
            Hasher completed in 0.3 seconds
        LocalDcePass (run) completed in 6.3 seconds
Running RemoveUnreachablePass...
            Hasher completed in 0.3 seconds
        RemoveUnreachablePass (run) completed in 0.3 seconds
Running RemoveGotosPass...
            Hasher completed in 0.2 seconds
        RemoveGotosPass (run) completed in 1.7 seconds
Running DedupBlocksPass...
            Hasher completed in 0.3 seconds
        DedupBlocksPass (run) completed in 13.2 seconds
Running UpCodeMotionPass...
            Hasher completed in 0.3 seconds
        UpCodeMotionPass (run) completed in 2.4 seconds
Running SingleImplPass...
            Iteration 1 completed in 1.1 seconds
            Iteration 2 completed in 0.3 seconds
            Iteration 3 completed in 0.3 seconds
            Iteration 4 completed in 0.3 seconds
            Hasher completed in 0.2 seconds
        SingleImplPass (run) completed in 2.3 seconds
Running ReorderInterfacesPass...
            Hasher completed in 0.2 seconds
        ReorderInterfacesPass (run) completed in 0.4 seconds
Running RemoveEmptyClassesPass...
            Hasher completed in 0.3 seconds
        RemoveEmptyClassesPass (run) completed in 0.3 seconds
Running ShortenSrcStringsPass...
            Hasher completed in 0.2 seconds
        ShortenSrcStringsPass (run) completed in 0.4 seconds
Running CommonSubexpressionEliminationPass...
            Building method override graph completed in 0.1 seconds
            compute_conditionally_pure_methods completed in 0.3 seconds
            init_method_barriers completed in 0.3 seconds
            Hasher completed in 0.3 seconds
        CommonSubexpressionEliminationPass (run) completed in 8.7 seconds
Running RegAllocPass...
            Hasher completed in 0.3 seconds
        RegAllocPass (run) completed in 14.1 seconds
Running CopyPropagationPass...
            Hasher completed in 0.4 seconds
        CopyPropagationPass (run) completed in 12.5 seconds
Running LocalDcePass...
            Building method override graph completed in 0.2 seconds
            compute_no_side_effects_methods completed in 0.4 seconds
            Hasher completed in 0.3 seconds
        LocalDcePass (run) completed in 6.7 seconds
Running ReduceGotosPass...
            Hasher completed in 0.3 seconds
        ReduceGotosPass (run) completed in 2.2 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 6.3 seconds
    Running optimization passes completed in 130.0 seconds
        Instruction lowering completed in 2.3 seconds
        Writing optimized dexes completed in 5.6 seconds
        Writing opt decisions data completed in 0.0 seconds
        Writing stats completed in 0.0 seconds
    Redex_backend completed in 7.8 seconds
    Freeing global memory completed in 1.5 seconds
redex-all main() completed in 144.9 seconds
Traceback (most recent call last):
  File "/tmp/redex.Z2NeA0/redex.py", line 1058, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.Z2NeA0/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/tmp/redex.Z2NeA0/redex.py", line 1058, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.Z2NeA0/redex.py", line 1043, in run_redex
    finalize_redex(state)
  File "/tmp/redex.Z2NeA0/redex.py", line 1011, in finalize_redex
    state.args.page_align_libs,
  File "/tmp/redex.Z2NeA0/redex.py", line 553, in align_and_sign_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
  File "/tmp/redex.Z2NeA0/redex.py", line 513, in zipalign
    p = subprocess.Popen(zipalign, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1465, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 810, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by finchatticus** [comment]
have the same error

**Comment by finchatticus** [comment]
`./redex -o ./app-release-redex.apk ./app-release.apk -P ./proguard-rules.pro`

`redex-all main() completed in 4.5 seconds
Traceback (most recent call last):
  File "/tmp/redex.9FN34a/redex.py", line 1074, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.9FN34a/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/tmp/redex.9FN34a/redex.py", line 1074, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.9FN34a/redex.py", line 1059, in run_redex
    finalize_redex(state)
  File "/tmp/redex.9FN34a/redex.py", line 1027, in finalize_redex
    state.args.page_align_libs,
  File "/tmp/redex.9FN34a/redex.py", line 569, in align_and_sign_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
  File "/tmp/redex.9FN34a/redex.py", line 529, in zipalign
    p = subprocess.Popen(zipalign, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by finchatticus** [comment]
redex-all main() completed in 4.5 seconds
Traceback (most recent call last):
  File "/tmp/redex.9FN34a/redex.py", line 1074, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.9FN34a/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/tmp/redex.9FN34a/redex.py", line 1074, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.9FN34a/redex.py", line 1059, in run_redex
    finalize_redex(state)
  File "/tmp/redex.9FN34a/redex.py", line 1027, in finalize_redex
    state.args.page_align_libs,
  File "/tmp/redex.9FN34a/redex.py", line 569, in align_and_sign_output_apk
    zipalign(unaligned_apk_path, output_apk_path, ignore_zipalign, page_align)
  File "/tmp/redex.9FN34a/redex.py", line 529, in zipalign
    p = subprocess.Popen(zipalign, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1436, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by agampe** [comment]
You are missing `zipalign` for repacking the APK. Ensure that `ANDROID_SDK` is set and pointing to the Android SDK, or `PATH` includes a path to `zipalign` (in the SDK it's under `build-tools/APILEVEL`).
