### ISSUE TITLE
libredex/ReadMaybeMapped.cpp:70:19: error: use of undeclared identifier

### ISSUE THREAD

**Issue by chenrongfa** [facebook/redex#526]
On Mac :autoreconf -ivf && ./configure && make
libtool: compile:  g++ -DPACKAGE_NAME=\"redex\" -DPACKAGE_TARNAME=\"redex\" -DPACKAGE_VERSION=\"1.0\" "-DPACKAGE_STRING=\"redex 1.0\"" -DPACKAGE_BUGREPORT=\"not-valid-yet@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"redex\" -DVERSION=\"1.0\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_FILESYSTEM=/**/" "-DHAVE_BOOST_SYSTEM=/**/" "-DHAVE_BOOST_REGEX=/**/" "-DHAVE_BOOST_PROGRAM_OPTIONS=/**/" "-DHAVE_BOOST_IOSTREAMS=/**/" "-DHAVE_BOOST_THREAD=/**/" -DHAVE_LIBZ=1 -DHAVE_LIBJSONCPP=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MUNMAP=1 -DHAVE_REGCOMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -I. -I./analysis/max-depth -I./analysis/ip-reflection-analysis -I./liblocator -I./libredex -I./libresource -I./libresource/android -I./libresource/androidfw -I./libresource/cutils -I./libresource/system -I./libresource/utils -I./opt -I./opt/access-marking -I./opt/add_redex_txt_to_apk -I./opt/annoclasskill -I./opt/annokill -I./opt/basic-block -I./opt/builder_pattern -I./opt/branch-prefix-hoisting -I./opt/bridge -I./opt/check_breadcrumbs -I./opt/class-merging -I./opt/class-splitting -I./opt/constant-propagation -I./opt/copy-propagation -I./opt/cse -I./opt/dedup_blocks -I./opt/dedup-strings -I./opt/delinit -I./opt/delsuper -I./opt/evaluate_type_checks -I./opt/final_inline -I./opt/instrument -I./opt/interdex -I./opt/local-dce -I./opt/layout-reachability -I./opt/merge_interface -I./opt/obfuscate -I./opt/object-sensitive-dce -I./opt/optimize_enums -I./opt/original_name -I./opt/peephole -I./opt/print-members -I./opt/rebindrefs -I./opt/redundant_move_elimination -I./opt/regalloc -I./opt/remove-apilevel-checks -I./opt/remove-builders -I./opt/remove-interfaces -I./opt/remove-recursive-locks -I./opt/remove_redundant_check_casts -I./opt/remove-uninstantiables -I./opt/remove-unreachable -I./opt/remove_empty_classes -I./opt/remove_gotos -I./opt/remove-unused-args -I./opt/renameclasses -I./opt/reorder-interfaces -I./opt/reduce-array-literals -I./opt/reduce-gotos -I./opt/resolve-refs -I./opt/result-propagation -I./opt/stringbuilder-outliner -I./opt/shorten-srcstrings -I./opt/make-public -I./opt/methodinline -I./opt/outliner -I./opt/singleimpl -I./opt/split_huge_switches -I./opt/static-sink -I./opt/staticrelo -I./opt/string_concatenator -I./opt/strip-debug-info -I./opt/synth -I./opt/test_cfg -I./opt/throw-propagation -I./opt/track_resources -I./opt/type-analysis -I./opt/unreferenced_interfaces -I./opt/unmark_proguard_keep -I./opt/unterface -I./opt/up-code-motion -I./opt/verifier -I./opt/vertical_merging -I./opt/virtual_merging -I./opt/virtual_scope -I./service/api-levels -I./service/class-init -I./service/class-merging -I./service/constant-propagation -I./service/copy-propagation -I./service/cse -I./service/dataflow -I./service/dedup-blocks -I./service/escape-analysis -I./service/field-ops -I./service/local-dce -I./service/method-dedup -I./service/method-inliner -I./service/method-merger -I./service/reference-update -I./service/switch-dispatch -I./service/switch-partitioning -I./service/type-analysis -I./service/type-string-rewriter -I./shared -I./sparta/include -I./tools/common -I./tools/redexdump -I./util -I/usr/include/jsoncpp --std=gnu++14 -O3 -Wall -g -MT libredex/ReadMaybeMapped.lo -MD -MP -MF libredex/.deps/ReadMaybeMapped.Tpo -c libredex/ReadMaybeMapped.cpp  -fno-common -DPIC -o libredex/.libs/ReadMaybeMapped.o
libredex/ReadMaybeMapped.cpp:70:19: error: use of undeclared identifier
      'TEMP_FAILURE_RETRY'
      ssize_t n = TEMP_FAILURE_RETRY(read(fd, data, remaining));
                  ^
1 error generated.
make[1]: *** [libredex/ReadMaybeMapped.lo] Error 1
make: *** [all-recursive] Error 1

**Comment by agampe** [comment]
Try at tip-of-tree, after 1e2e32a3.

**Comment by chenrongfa** [comment]
> Try at tip-of-tree, after [1e2e32a](https://github.com/facebook/redex/commit/1e2e32a35d684a142a55c927073ebecdc1f3ce86).

Thanks
