### ISSUE TITLE
libredex/Transform.cpp:1677: bool MethodTransform::try_sync(): assertion `active_try == nullptr' failed.

### ISSUE THREAD

**Issue by huaihong1986** [facebook/redex#527]
When I run ANDROID_SDK=/Users/pingguo/Library/Android/sdk redex  ~/Desktop/shihuimiao.apk  -o ~/Desktop/app-release.apk using the master branch code. I get the following error:
libredex/Transform.cpp:1677: bool MethodTransform::try_sync(): assertion `active_try == nullptr' failed.

0   redex-all                           0x00000001000948a2 _Z15crash_backtracei + 50
1   libsystem_platform.dylib            0x00007fff6a80b5fd _sigtramp + 29
2   ???                                 0x0000000000000400 0x0 + 1024
3   libsystem_c.dylib                   0x00007fff6a6e1808 abort + 120
4   redex-all                           0x000000010009486d _Z11assert_failPKcS0_jS0_S0_z + 173
5   redex-all                           0x00000001001308ac _ZN15MethodTransform8try_syncEv + 4156
6   redex-all                           0x000000010012f728 _ZN15MethodTransform4syncEv + 24
7   redex-all                           0x0000000100073eb4 _Z16replace_wrappersP9DexMethodR7DexCodeR14WrapperMethods + 5204
8   redex-all                           0x0000000100074fbd _Z9transformRKNSt3__16vectorIP8DexClassNS_9allocatorIS2_EEEER14WrapperMethodsRK11SynthConfig + 365
9   redex-all                           0x0000000100075787 _ZN9SynthPass8run_passERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFilesR11PassManager + 119
10  redex-all                           0x00000001000c2a4d _ZN11PassManager10run_passesERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFiles + 2109
11  redex-all                           0x000000010008727c main + 5740
12  libdyld.dylib                       0x00007fff6a612cc9 start + 1
13  ???                                 0x0000000000000008 0x0 + 8
Traceback (most recent call last):
  File "/tmp/redex.jQv004/redex.py", line 1074, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.jQv004/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/tmp/redex.jQv004/redex.py", line 1074, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.jQv004/redex.py", line 1053, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.jQv004/redex.py", line 512, in run_redex_binary
    if run():
  File "/tmp/redex.jQv004/redex.py", line 493, in run
    raise RuntimeError(
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.jQv004/redex-gdb-4qew_9ds.sh or under lldb by running /tmp/redex.jQv004/redex-lldb-z52agjsq.sh.  
You can download our apk from the following link:
https://shop-internal.oss-cn-beijing.aliyuncs.com/shm-app-builds/index.html?branch=master

**Comment by Feng23** [comment]
Hi I could not repro the error on master with the apk from the link. It's possible that the apk in the link has changed.

**Comment by Feng23** [comment]
Not able to repro. Please reopen the issue if needed.
