### ISSUE TITLE
Question about dump_classes_from_hprof.py

### ISSUE THREAD

**Issue by misbahkhan** [facebook/redex#534]
[This commit](https://github.com/facebook/redex/commit/f1dd13fed3c4f87ee2c035a4832db60b54fafaac) added sorting based on class serial number to `tools/hprof/dump_classes_from_hprof.py`.  

In the PR description it says:
> Sadly we don't have a guarantee that this will sort in classload order on Art, but I think it's valuable to include in the script

In the code comments it says:
> On Dalvik these serial numbers correspond to classload order, so it's useful to sort by them.

I'm wondering what the distinction is here, and if anyone can point me to any more info about what the lack of guarantee may be referring to in this case.

**Comment by agampe** [comment]
Class load order can be used for optimizations that:
* attempt to lay out the dex in a way to reduce I/O (e.g., keep classes that are loaded together together)
* fetch things at runtime in an appropriate order

In ART, the "ID" is the "current location" in the heap (see [here](https://cs.android.com/android/platform/superproject/+/master:art/runtime/hprof/hprof.cc?q=hprof.cc)). Allocation is not necessarily linear, and ART has a moving GC, so the ID isn't even stable.

There is a possible alternative (turn on allocation tracking with a large enough buffer, and use the stack trace serial, as that is insertion-ordered). It is just not something we have explored, as allocation tracking adds serious overhead.
