### ISSUE TITLE
Typo in DexOutput error message when referring to `reserved_trefs` InterdexPass Config option

### ISSUE THREAD

**Issue by benjaminRomano** [facebook/redex#536]
**Background**
On the [following line](https://github.com/facebook/redex/blob/1fb6cefe501e584ba472929a7f9a9addcd7962c0/libredex/DexOutput.cpp#L796), the error message suggests to modify `reserve_trefs` to fix issues with too many type refs being encoded in a single DEX file:
```
"Trying to encode too many type refs in dex %lu: %lu (limit: %lu).\n"
"NOTE: Please check InterDexPass config flags and set: "
"`reserve_trefs: %lu` (or larger, until the issue goes away)",
```
**Solution**
The proper field should actually be `reserved_trefs`. Unfortunately, I can't put up a PR yet as I need to get approval to sign CLA.

**Comment by yuxuanchen1997** [comment]
Thanks. Will make the change.

**Comment by yuxuanchen1997** [comment]
#537
