### ISSUE TITLE
check-cast problem

### ISSUE THREAD

**Issue by EXZAID** [facebook/redex#551]
in some cases, the dexcode is like below:
```
invoke-interface {v5}, Ljava/util/Iterator;.next:()Ljava/lang/Object;
move-result-object v0
invoke-interface {v0}, Ljava/util/Map$Entry;.getKey:()Ljava/lang/Object;
move-result-object v2
```
the type of v0 is java/lang/Object, and there is no `getKey` in java/lang/Object.
so if the `-J ir_type_checker.run_on_input=false` is not configured, redex will report the error

I think a `check_cast` should be added after the `move-result-object v0`, like this
```
check-cast v0, Ljava/util/Map$Entry;
```

and I write a demo to verify my assumption
```
public static void main(String args[]) {
    HashMap<Integer, String> m = new HashMap<>();
    m.put(1, "aaa");
    m.put(2, "bbb");

    for (Map.Entry a : m.entrySet()) {
        System.out.println(a.getKey());
        System.out.println(a.getValue());
    }
}
```
the part of dexcode is generated, like this:
```
invoke-interface {v2}, Ljava/util/Iterator;.next:()Ljava/lang/Object;
move-result-object v0
check-cast v0, Ljava/util/Map$Entry; -----> check-cast
sget-object v3, Ljava/lang/System;.out:Ljava/io/PrintStream;
invoke-interface {v0}, Ljava/util/Map$Entry;.getKey:()Ljava/lang/Object;
move-result-object v4
```
so is it necessary to add a pass to handle this problem? like AddCheckCastPass?

**Comment by emma0303** [comment]
Where does the initial input come from? Do we (redex) remove the check cast or do you have other optimizations running beforehand?

**Comment by agampe** [comment]
There is no such `check-cast` problem. Android has always followed the older JVM model where interface-related operations do not statically require the interface type. As such, the code you posted is correct on Android (but the equivalent Java bytecode would not be on a modern JVM), and an up-to-date version of Redex will not complain about it.

**Comment by EXZAID** [comment]
@emma0303 @agampe 
thanks for answering my questions～

@emma0303 
redex dose not remove the `check-cast`, I think.
and I try again use redex to optimize my applicaton, and no error is reported. so I cannot reproduce the problem, sorry
@agampe 
you mean without option '-J ir_type_checker.run_on_input=false', the latest version of redex will not complain about this problem?

**Comment by agampe** [comment]
Even with `run_on_input=true` the type checker should let the code above pass.

What version/commit of Redex are you using. What is the exact error message?
