### ISSUE TITLE
Inconsistent behavior for accessing deobfuscated members

### ISSUE THREAD

**Issue by Myles1** [facebook/redex#552]
Calling `apply_deobfuscated_names(dexen, proguard_map)` allows type access through `DexType::get_type("LMyDeobfuscatedClassName;")` but doesn't allow field access via `DexField::get_field("LDeobContainer;.deobFieldName:LDeobType;")` or method access via `DexMethod::get_method("LDeobContainer;.deobMethodName:()V")`.

The current behavior makes sense based on the field/method lookup code, but I'm having trouble figuring out the preferred way to access deobfuscated fields/methods without needing to iterate over a class & call strcmp for each possibility.
(I'm sure there's something that I'm missing).

**Comment by emma0303** [comment]
Thanks for reporting this. It looks like we are saving the mapping from deobfsucated names to DexClasses, but not the same for fields and methods. We can look into adding this functionality. Will ping back once that is landed.

In the meantime, I can't think of a better solution than the one you mentioned also, where you are getting the class from the field/ method string and then iterating over its members.

On the other had, it looks like you are using Proguard first and then running redex? Have you tried disabling Proguard renaming and using the renaming functionality in Redex?

**Comment by Myles1** [comment]
Thanks for the response!
Your solution is actually exactly what I ended up doing, and it works great but I have to go back to the strcmp method when I'm profiling an optimized version of my apk.
