### ISSUE TITLE
Windows: problem finding zipalign and apksigner

### ISSUE THREAD

**Issue by pashamcr** [facebook/redex#556]
To work properly, I added the system variable
ANDROID_SDK
and path
%ANDROID_SDK%\build-tools
The scripts redex.py and utils.py need to search for zipalign.exe and apksigner.bat, respectively.
My suggestions:
redex.py
`find_android_build_tool ("zipalign" if os.name == 'posix' else "zipalign.exe"),`
utils.py
`return find_android_build_tool ("apksigner" if os.name == 'posix' else "apksigner.bat")`
or
`find_android_build_tool ("zipalign.exe" if platform.system() == 'Windows' else "zipalign"),`
`return find_android_build_tool ("apksigner.bat" if platform.system() == 'Windows' else "apksigner")`
please change it somehow

**Comment by agampe** [comment]
Can you create a pull request?
