### ISSUE TITLE
Interdex documentation mentions python2, looks outdated

### ISSUE THREAD

**Issue by slavasav** [facebook/redex#567]
The docs at https://fbredex.com/docs/interdex have "// Note that the script needs python 2". However:

python2 tools/hprof/dump_classes_from_hprof.py
  File "tools/hprof/dump_classes_from_hprof.py", line 1011
    raise RuntimeError(f"No object for {obj_id:x}")
                                                 ^
SyntaxError: invalid syntax

python3 tools/hprof/dump_classes_from_hprof.py
usage: dump_classes_from_hprof.py [-h] --hprof HPROF [--allow_missing_ids]
dump_classes_from_hprof.py: error: the following arguments are required: --hprof

**Comment by yuxuanchen1997** [comment]
Thanks for noticing! We will fix the documentation.
