### ISSUE TITLE
can not make install success

### ISSUE THREAD

**Issue by hschenzhimin** [facebook/redex#57]
/usr/bin/install: cannot create regular file '/usr/local/lib/libfolly.so.57.0.0': Permission denied
Makefile:980: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
Makefile:1783: recipe for target 'install-am' failed
Makefile:1483: recipe for target 'install-recursive' failed

**Comment by hschenzhimin** [comment]
IN Ubuntu

**Comment by bertmaher** [comment]
Try `sudo make install`.  I'll update the README
