### ISSUE TITLE
Inconsistency found in Dex code for Lcom/huawei/updatesdk/b/f/b;.a:()V

### ISSUE THREAD

**Issue by PerceiverDo** [facebook/redex#572]
Thanks for your answer to question #570.  @amnn 

But we have another problem~
 
Mine config is:
`

> {
>   "redex" : {
>     "passes" : [
>       "InterDexPass",
>       "RegAllocPass"
>     ]
>   },
>   "InterDexPass" : {
>       "normal_primary_dex": true
>   },
>   "coldstart_classes":"multidex-config.txt",
>   "debug_info_kind": "no_custom_symbolication",
>   "method_move_map" : "redex-moved-methods-map.txt",
>   "string_sort_mode" : "class_order",
>   "bytecode_sort_mode" : ["method_similarity_order", "class_order"],
>   "ir_type_checker": {
>     "run_after_each_pass" : false,
>     "check_no_overwrite_this" : false,
>     "verify_moves" : false,
>     "run_on_input" : false
>   }
> }

`

The issue is:
`
...
> [hasher] ==== hashing class Lt/i0/v/d/k0/k/b/g0/e;
> [hasher] ==== hashing class Lt/i0/v/d/k0/b/d1/i0$b;
> [hasher] ==== hashing class Lt/i0/v/d/k0/m/h1/a;
> [hasher] ==== hashing class Lt/k0/x;
> [hasher] ==== hashing class Lcom/xingin/xhs/v2/generalsettings/GeneralSettingsActivityV2;
> [hasher] ==== hashing class Lf0/q/f/r/y;
>             Hasher completed in 0.8 seconds
> After processing unresolved lines: MethodProfiles successfully parsed 0 rows; 0 unresolved lines
>         InterDexPass 1 (run) completed in 4.9 seconds
> Running IRTypeChecker...
> Inconsistency found in Dex code for Lcom/huawei/updatesdk/b/f/b;.a:()V
>  Use of uninitialized variable NEW_INSTANCE Ljava/lang/Thread; detected at [0x7fb7623c5e20] OPCODE: INVOKE_VIRTUAL v2, v0, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V in 
> CFG:
>  Block B0: entry
>    preds:
>    [0x7fb7623c4e20] OPCODE: NEW_INSTANCE Ljava/lang/Thread;
>    [0x7fb7623c5fc0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
>    [0x7fb7623c4e40] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$c;
>    [0x7fb7623c6020] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
>    [0x7fb7623c57a0] OPCODE: CONST v0, 0
>    [0x7fb7623c57c0] OPCODE: INVOKE_DIRECT v1, v0, Lcom/huawei/updatesdk/b/f/b$c;.<init>:(Lcom/huawei/updatesdk/b/f/b$a;)V
>    [0x7fb7623c58c0] OPCODE: CONST_STRING "a/b/f/b/updatesdk/huawei/com"
>    [0x7fb7623c60c0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
>    [0x7fb7623c58e0] OPCODE: INVOKE_STATIC v1, v0, Lp/f0/p1/i/f/c;.a:(Ljava/lang/Runnable;Ljava/lang/String;)Ljava/lang/Thread;
>    [0x7fb7623c59e0] OPCODE: MOVE_RESULT_OBJECT v1
>    [0x7fb7623c5a00] OPCODE: CONST_STRING "delete market file task"
>    [0x7fb737f43ea0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
>    [0x7fb7623c4ec0] OPCODE: INVOKE_VIRTUAL v1, v0, Ljava/lang/Thread;.setName:(Ljava/lang/String;)V
>    [0x7fb7623c4ee0] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$a;
>    [0x7fb737f43f90] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
>    [0x7fb7623c5dc0] OPCODE: INVOKE_DIRECT v0, Lcom/huawei/updatesdk/b/f/b$a;.<init>:()V
>    [0x7fb7623c5e20] OPCODE: INVOKE_VIRTUAL v2, v0, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V
>    [0x7fb7623c5e80] OPCODE: INVOKE_VIRTUAL v2, Ljava/lang/Thread;.start:()V
>    [0x7fb7623c5ee0] OPCODE: RETURN_VOID 
>    succs:
> 
> Code:
> [0x7fb7623c4e20] OPCODE: NEW_INSTANCE Ljava/lang/Thread;
> [0x7fb7623c5fc0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
> [0x7fb7623c4e40] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$c;
> [0x7fb7623c6020] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
> [0x7fb7623c57a0] OPCODE: CONST v0, 0
> [0x7fb7623c57c0] OPCODE: INVOKE_DIRECT v1, v0, Lcom/huawei/updatesdk/b/f/b$c;.<init>:(Lcom/huawei/updatesdk/b/f/b$a;)V
> [0x7fb7623c58c0] OPCODE: CONST_STRING "a/b/f/b/updatesdk/huawei/com"
> [0x7fb7623c60c0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
> [0x7fb7623c58e0] OPCODE: INVOKE_STATIC v1, v0, Lp/f0/p1/i/f/c;.a:(Ljava/lang/Runnable;Ljava/lang/String;)Ljava/lang/Thread;
> [0x7fb7623c59e0] OPCODE: MOVE_RESULT_OBJECT v1
> [0x7fb7623c5a00] OPCODE: CONST_STRING "delete market file task"
> [0x7fb737f43ea0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
> [0x7fb7623c4ec0] OPCODE: INVOKE_VIRTUAL v1, v0, Ljava/lang/Thread;.setName:(Ljava/lang/String;)V
> [0x7fb7623c4ee0] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$a;
> [0x7fb737f43f90] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
> [0x7fb7623c5dc0] OPCODE: INVOKE_DIRECT v0, Lcom/huawei/updatesdk/b/f/b$a;.<init>:()V
> [0x7fb7623c5e20] OPCODE: INVOKE_VIRTUAL v2, v0, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V
> [0x7fb7623c5e80] OPCODE: INVOKE_VIRTUAL v2, Ljava/lang/Thread;.start:()V
> [0x7fb7623c5ee0] OPCODE: RETURN_VOID 
> 
> (3 more issues!)
> Traceback (most recent call last):
>   File "/tmp/redex.BV15np/redex.py", line 1091, in <module>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/private/tmp/redex.BV15np/pyredex/utils.py", line 57, in with_temp_cleanup
>     fn()
>   File "/tmp/redex.BV15np/redex.py", line 1091, in <lambda>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/tmp/redex.BV15np/redex.py", line 1070, in run_redex
>     run_redex_binary(state, term_handler)
>   File "/tmp/redex.BV15np/redex.py", line 508, in run_redex_binary
>     if run():
>   File "/tmp/redex.BV15np/redex.py", line 489, in run
>     raise RuntimeError(
> RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.BV15np/redex-gdb-pw8f89hh.sh or under lldb by running /tmp/redex.BV15np/redex-lldb-rqnk3lcn.sh
`

This code is from `huawei` library, so there's no way to solve it at the code level.

Is there any configuration to add the white list of checkers？Or there are other ways to solve this problem？

**Comment by PerceiverDo** [comment]
The code is like this:
![image](https://user-images.githubusercontent.com/6870548/100707446-a2653080-33e5-11eb-84b6-594836428f19.png)
 
It doesn't look like a problem.

**Comment by thezhangwei** [comment]
It's complaining that there's no <init> ctor call on the new instance of `j/l/Thread;` before the invoke-virtual.

**Comment by amnn** [comment]
Here's how the bytecode from the error you posted (roughly) disassembles to:

```java
Thread v2 = new Thread();

p.f0.p1.i.f.c.a(new f.b.c(null), "a/b/f/b/updatesdk/huawei/com")
  .setName("delete market file task");

v2.setUncaughtExceptionHandler(new f.b.a());
v2.start();
```

I've taken some liberties with this disassembly.  In our intermediate representation, a `new` expression is decomposed into three parts: the `new-instance`, the `move-result-pseudo-object` and then an `invoke-direct` to a constructor, whose name we expect to be `<init>`, but:
* In the bytecode in the error, there are no calls to `<init>` methods, there are calls to a `.` method which seem to take their place, for `f.b.c` and `f.b.a`.
* For `v2`, the register holding the instance that the error is complaining about, we don't even have that.  Given how `setName` is being called on the result of the static method call to `p.f0.p1.i.f.c.a`, it seems like this is somehow doing the initialisation of the newly created `Thread`.

Note that this is quite different from the disassembly in your screenshot -- some new strings have been introduced, names have been changed around, etc, which suggest something is changing the dex code before it reaches Redex, and that can be tweaked without editing the code.

**Here are some things to try:**

- Could you provide the bytecode for the method in the `.class` file directly, rather than the disassembly?  That will help verify that the disassembly in your screenshot is not hiding any details that I picked up in the dex.
- The error is currently happening after running `InterDex`, it is unlikely that `InterDex` would introduce these kinds of problems, but to double check, can you run Redex with `"run_on_input" : true` in the `"ir_type_checker"` part of the config? It is currently set to `false`.  It should fail on the input.
- Could you detail what steps the `.class` or `.jar` files in your build go through before they reach the APK?  Do you use Proguard?  Do you use R8, D8, or DX?  If you use R8, try D8, if you use Proguard, try disabling that in your toolchain.

For reference, the slightly cleaned up bytecode I worked from:

```
new-instance              LThread;
move-result-pseudo-object v2
new-instance              Lf/b$c;
move-result-pseudo-object v1
const                     v0, 0
invoke-direct             v1, v0, Lf/b$c;.:(Lf/b$a;)V
const-string              "a/b/f/b/updatesdk/huawei/com"
move-result-pseudo-object v0
invoke-static             v1, v0, Lp/f0/p1/i/f/c;.a:(LRunnable;LString;)LThread;
move-result-object        v1
const-string              "delete market file task"
move-result-pseudo-object v0
invoke-virtual            v1, v0, LThread;.setName:(LString;)V
new-instance              Lf/b$a;
move-result-pseudo-object v0
invoke-direct             v0, Lf/b$a;.:()V
invoke-virtual            v2, v0, LThread;.setUncaughtExceptionHandler:(LThread$UncaughtExceptionHandler;)V
invoke-virtual            v2, LThread;.start:()V
return-void
```

**Comment by agampe** [comment]
Just for some clarification:

> For v2, the register holding the instance that the error is complaining about, we don't even have that. Given how setName is being called on the result of the static method call to p.f0.p1.i.f.c.a, it seems like this is somehow doing the initialisation of the newly created Thread.

This code is illegal, period, and correctly flagged (not clear why it doesn't fail for the `v1` object first, but...).

The Java and Android verifier disallow accesses to uninitialized objects (see [here](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.10.1.2), the previous section describing the type system, and the following sections describing instruction semantics; for Android, these are explicitly mentioned in constraints B5 and B6 [here](https://source.android.com/devices/tech/dalvik/constraints#struct-constraints)). Only `<init>` can be called. This code may be minimally "structurally" legal, but should fail with a `VerifyError` when executed (i.e., loaded and initialized).

**Comment by PerceiverDo** [comment]
According to your suggestion：

- .class file is :
[classes.jar.zip](https://github.com/facebook/redex/files/5626542/classes.jar.zip)

And, i used the `Android Studio Plugin` to make `.class` to `ByteCode`,which has call `<init>`.Like this:
![image](https://user-images.githubusercontent.com/6870548/100819868-ff192780-3487-11eb-9f6e-37289879e381.png)

- setting the config `"run_on_input"` : true in the `"ir_type_checker"`, but we get the error messgae:
`
> Redex_frontend completed in 9.5 seconds
> WARNING: Unable to find RequiresApi annotation. It's either unused (okay) or been deleted (not okay)
>         API Level Checker completed in 0.2 seconds
> WARNING: No inliner config
> Evaluating InterDexPass...
>         InterDexPass (eval) completed in 0.0 seconds
> Evaluating RegAllocPass...
>         RegAllocPass (eval) completed in 0.0 seconds
> Running IRTypeChecker...
>         IRTypeChecker completed in 9.3 seconds
> Inconsistency found in Dex code for Lcom/huawei/updatesdk/b/f/b;.a:()V
>  Use of uninitialized variable NEW_INSTANCE Ljava/lang/Thread; detected at [0x7fe79912c390] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V in 
> CFG:
>  Block B0: entry
>    preds:
>    [0x7fe7ac0f03b0] OPCODE: NEW_INSTANCE Ljava/lang/Thread;
>    [0x7fe7ac0c0640] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
>    [0x7fe7ac0f03d0] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$c;
>    [0x7fe79912c530] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
>    [0x7fe79912bd10] OPCODE: CONST v2, 0
>    [0x7fe79912bd30] OPCODE: INVOKE_DIRECT v1, v2, Lcom/huawei/updatesdk/b/f/b$c;.<init>:(Lcom/huawei/updatesdk/b/f/b$a;)V
>    [0x7fe79912be30] OPCODE: CONST_STRING "a/b/f/b/updatesdk/huawei/com"
>    [0x7fe7ac0c06e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
>    [0x7fe79912be50] OPCODE: INVOKE_STATIC v1, v2, Lp/f0/p1/i/f/c;.a:(Ljava/lang/Runnable;Ljava/lang/String;)Ljava/lang/Thread;
>    [0x7fe79912bf50] OPCODE: MOVE_RESULT_OBJECT v1
>    [0x7fe79912bf70] OPCODE: CONST_STRING "delete market file task"
>    [0x7fe7ac0c05e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
>    [0x7fe7ac0a2630] OPCODE: INVOKE_VIRTUAL v1, v2, Ljava/lang/Thread;.setName:(Ljava/lang/String;)V
>    [0x7fe7ac0a2650] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$a;
>    [0x7fe79912c5d0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
>    [0x7fe79912c330] OPCODE: INVOKE_DIRECT v1, Lcom/huawei/updatesdk/b/f/b$a;.<init>:()V
>    [0x7fe79912c390] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V
>    [0x7fe79912c3f0] OPCODE: INVOKE_VIRTUAL v0, Ljava/lang/Thread;.start:()V
>    [0x7fe79912c450] OPCODE: RETURN_VOID 
>    succs:
> 
> Code:
> [0x7fe7ac0f03b0] OPCODE: NEW_INSTANCE Ljava/lang/Thread;
> [0x7fe7ac0c0640] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
> [0x7fe7ac0f03d0] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$c;
> [0x7fe79912c530] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
> [0x7fe79912bd10] OPCODE: CONST v2, 0
> [0x7fe79912bd30] OPCODE: INVOKE_DIRECT v1, v2, Lcom/huawei/updatesdk/b/f/b$c;.<init>:(Lcom/huawei/updatesdk/b/f/b$a;)V
> [0x7fe79912be30] OPCODE: CONST_STRING "a/b/f/b/updatesdk/huawei/com"
> [0x7fe7ac0c06e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
> [0x7fe79912be50] OPCODE: INVOKE_STATIC v1, v2, Lp/f0/p1/i/f/c;.a:(Ljava/lang/Runnable;Ljava/lang/String;)Ljava/lang/Thread;
> [0x7fe79912bf50] OPCODE: MOVE_RESULT_OBJECT v1
> [0x7fe79912bf70] OPCODE: CONST_STRING "delete market file task"
> [0x7fe7ac0c05e0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
> [0x7fe7ac0a2630] OPCODE: INVOKE_VIRTUAL v1, v2, Ljava/lang/Thread;.setName:(Ljava/lang/String;)V
> [0x7fe7ac0a2650] OPCODE: NEW_INSTANCE Lcom/huawei/updatesdk/b/f/b$a;
> [0x7fe79912c5d0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
> [0x7fe79912c330] OPCODE: INVOKE_DIRECT v1, Lcom/huawei/updatesdk/b/f/b$a;.<init>:()V
> [0x7fe79912c390] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/lang/Thread;.setUncaughtExceptionHandler:(Ljava/lang/Thread$UncaughtExceptionHandler;)V
> [0x7fe79912c3f0] OPCODE: INVOKE_VIRTUAL v0, Ljava/lang/Thread;.start:()V
> [0x7fe79912c450] OPCODE: RETURN_VOID 
> 
>  If you are confident that this does not matter (e.g., because you are using MakePublicPass), turn off accessibility checking on input with `-J ir_type_checker.run_on_input_ignore_access=true`.
>  You may turn off all input checking with `-J ir_type_checker.run_on_input=false`.
> Traceback (most recent call last):
>   File "/tmp/redex.vaC37G/redex.py", line 1091, in <module>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/private/tmp/redex.vaC37G/pyredex/utils.py", line 57, in with_temp_cleanup
>     fn()
>   File "/tmp/redex.vaC37G/redex.py", line 1091, in <lambda>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/tmp/redex.vaC37G/redex.py", line 1070, in run_redex
>     run_redex_binary(state, term_handler)
>   File "/tmp/redex.vaC37G/redex.py", line 508, in run_redex_binary
>     if run():
>   File "/tmp/redex.vaC37G/redex.py", line 489, in run
>     raise RuntimeError(
> RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.vaC37G/redex-gdb-45nqecrr.sh or under lldb by running /tmp/redex.vaC37G/redex-lldb-js5db6ed.sh

`

- Mine Build has use R8, i will try it again.

**Comment by amnn** [comment]
Thanks for all the follow-ups @PerceiverDo, this really helps narrow things down.

> Then, i check the APK Dex about this class.used the Android Studio Plugin to make .class to ByteCode,which has call `<init>`.

Note that in this example, the constructor call for `Thread` is not present in the dex, so something.  If R8 is the only thing sitting between the JAR and Redex, I recommend replacing it with D8 and seeing if the problems are still present -- I expect it should go away.  It seems strange for R8 to introduce a spec-breaking change, but it may be a bug.  It could be that the entire initialisation of `Thread` should be outlined into the static method, resulting in:

```
new-instance              Lf/b$c;
move-result-pseudo-object v1
const                     v0, 0
invoke-direct             v1, v0, Lf/b$c;.:(Lf/b$a;)V
const-string              "a/b/f/b/updatesdk/huawei/com"
move-result-pseudo-object v0
invoke-static             v1, v0, Lp/f0/p1/i/f/c;.a:(LRunnable;LString;)LThread;
move-result-object        v1
const-string              "delete market file task"
move-result-pseudo-object v0
invoke-virtual            v1, v0, LThread;.setName:(LString;)V
new-instance              Lf/b$a;
move-result-pseudo-object v0
invoke-direct             v0, Lf/b$a;.:()V
invoke-virtual            v1, v0, LThread;.setUncaughtExceptionHandler:(LThread$UncaughtExceptionHandler;)V
invoke-virtual            v1, LThread;.start:()V
return-void
```

**Comment by PerceiverDo** [comment]
Wow,Thanks.

When i disable `R8`,the`InterDexPass` has work.
But ,i have some problem for the `optimized.apk`

**Comment by amnn** [comment]
Hey @PerceiverDo, glad to hear your initial problem was resolved.  I'll close this issue as a result.  If you find that the problem in `optimized.apk` is due to Redex, please raise a new issue and we'd be happy to take a look!
