### ISSUE TITLE
Some questions about optimization products!

### ISSUE THREAD

**Issue by PerceiverDo** [facebook/redex#574]
Firstly, my current profile content is：
`
> {
>   "redex" : {
>     "passes" : [
>       "InterDexPass",
>       "RegAllocPass"
>     ]
>   },
>   "InterDexPass" : {
>       "normal_primary_dex": true
>   },
>   "coldstart_classes":"multidex-config.txt",
>   "debug_info_kind": "no_custom_symbolication",
>   "method_move_map" : "redex-moved-methods-map.txt",
>   "string_sort_mode" : "class_order",
>   "bytecode_sort_mode" : ["method_similarity_order", "class_order"],
>   "ir_type_checker": {
>     "run_after_each_pass" : false,
>     "check_no_overwrite_this" : false,
>     "verify_moves" : false,
>     "run_on_input" : true
>   }
> }
`
The questions are:

- Why the size of APK increased nearly 2m?
![image](https://user-images.githubusercontent.com/6870548/101006738-32e57180-359c-11eb-852c-c044c8c5b75c.png)
![image](https://user-images.githubusercontent.com/6870548/101006955-42fd5100-359c-11eb-8aec-ee89bc8ec0b5.png)

- The `InterDexPass` content about some classes has not packaged into the apk.
-- some content about `class lists`:
![image](https://user-images.githubusercontent.com/6870548/101008368-a7b8ab80-359c-11eb-8985-6069ec8f06fe.png)
-- the optimized primary dex:
![image](https://user-images.githubusercontent.com/6870548/101009009-d9317700-359c-11eb-8d61-cb4c34951efe.png)

In my opinion, are there any options that have not been opened, or other problems that have caused these problems?

**Comment by amnn** [comment]
Hi (again) @PerceiverDo!  Your current config is quite barebones.  It instructs Redex to repackage your dexes, but it doesn't really run any optimisations.  Please have a look at the following configs that come with Redex and try merging them with your existing config to enable optimisations:

 - [config/default.config](https://github.com/facebook/redex/blob/master/config/default.config)
 - [config/aggressive.config](https://github.com/facebook/redex/blob/master/config/aggressive.config)
