### ISSUE TITLE
redex-all: not found

### ISSUE THREAD

**Issue by SuhairZain** [facebook/redex#58]
I followed the installation steps and when I try to run redex, I get the following error:

`/bin/sh: 1: redex-all: not found
Traceback (most recent call last):
  File "./redex.py", line 779, in <module>
    run_redex(args)
  File "./redex.py", line 735, in run_redex
    dexen)
  File "./redex.py", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /tmp/tmpzislfiuc.redex_extracted_apk --outdir /tmp/tmpft6dps10.redex_dexen /tmp/tmpft6dps10.redex_dexen/dex0/classes.dex' returned non-zero exit status 127
`

What might be the issue? I'm running elementary freya (Ubuntu 14.04).

**Comment by ratm** [comment]
Make sure to add the redex directory in your PATH, you can do so locally by launching redex with the following command:

PATH=.:$PATH ./redex

**Comment by bertmaher** [comment]
@ratm, thanks for the answer!  I've pushed a change to look for redex-all in the same directory as redex, so PATH modifications should not be needed in the future.
