### ISSUE TITLE
MYSYS2 cmake project failed

### ISSUE THREAD

**Issue by Desonye** [facebook/redex#581]
When I try to cmake this project on path ../redex/build-cmake, I get this result:

![image](https://user-images.githubusercontent.com/61608825/103125871-79c01600-46c7-11eb-9269-e18b7594cf1e.png)

Is any tools I dismissed?

**Comment by Desonye** [comment]
INFO:root:Compressing as tar.xz
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_14.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_15.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_16.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_17.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_18.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_19.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_21.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_23.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_25.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_26.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_27.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_28.txt
INFO:root:Adding D:/Tools/MYSYS2/home/y00378280/redex/service/api-levels/framework_classes_api_29.txt
Traceback (most recent call last):
  File "D:/Tools/MYSYS2/home/y00378280/redex/gen_packed_apilevels.py", line 175, in <module>
    main()
  File "D:/Tools/MYSYS2/home/y00378280/redex/gen_packed_apilevels.py", line 170, in main
    write_py_wrapper(base64_blob, args.output, args.tarxz)
  File "D:/Tools/MYSYS2/home/y00378280/redex/gen_packed_apilevels.py", line 157, in write_py_wrapper
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/:/Tools/MYSYS2/home/y00378280/redex/build-cmake/generated_apilevels.py'
make[2]: *** [CMakeFiles/generated_apilevels.dir/build.make:93: generated_apilevels.py] Error 1
make[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/generated_apilevels.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by sisco0** [comment]
Have a good day, it seems that _CMake_ under _MSYS2_ uses paths such as the ones you are getting (with slashes instead of backslashes, what could made `os.path.realpath` argument of the _Python_ application think this is a _Linux_ path, deleting the drive letter right here 

```
FileNotFoundError: [Errno 2] No such file or directory: '/:/Tools/MYSYS2/home/y00378280/redex/build-cmake/generated_apilevels.py'
```

**Comment by Desonye** [comment]
> Have a good day, it seems that _CMake_ under _MSYS2_ uses paths such as the ones you are getting (with slashes instead of backslashes), what could made `os.path.realpath` argument of the _Python_ application think this is a _Linux_ path, deleting the drive letter right here
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/:/Tools/MYSYS2/home/y00378280/redex/build-cmake/generated_apilevels.py'
> ```
> 
> It seems like a bad idea to pass the `${CMAKE_CURRENT_BINARY_DIR}` as an argument to the _Python_ argument parser, instead of that, it could be erased without any problem. I add a PR in order for you to test if the expected behaviour is had.

It works on your pull request. Thanks a lot!
