### ISSUE TITLE
DexEncodedValue::vencode overflow, size 4329

### ISSUE THREAD

**Issue by PerceiverDo** [facebook/redex#583]
When i `redex` my apk again, i have this issue, like this:
`

> Evaluating InterDexPass...
>         InterDexPass (eval) completed in 0.0 seconds
> Evaluating RegAllocPass...
>         RegAllocPass (eval) completed in 0.0 seconds
> Running IRTypeChecker...
>         IRTypeChecker completed in 10.1 seconds
>         Hasher completed in 0.5 seconds
> Running InterDexPass...
>             Hasher completed in 0.4 seconds
>         InterDexPass 1 (run) completed in 5.4 seconds
> Running RegAllocPass...
>             Hasher completed in 0.4 seconds
>         RegAllocPass 1 (run) completed in 20.3 seconds
> Running IRTypeChecker...
>         IRTypeChecker completed in 12.9 seconds
>     Running optimization passes completed in 49.4 seconds
>         Instruction lowering completed in 3.6 seconds
> libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::error_info_injector<RedexException>: libredex/DexAnnotation.cpp:273: void DexEncodedValue::vencode(DexOutputIdx *, std::vector<uint8_t> &): assertion `pend - buffer <= (4096)' failed.
> DexEncodedValue::vencode overflow, size 4141
> 
> 0   redex-all                           0x000000010de6c872 _Z23crash_backtrace_handleri + 50
> 1   libsystem_platform.dylib            0x00007fff20384d7d _sigtramp + 29
> 2   ???                                 0x00007fff00000400 0x0 + 140733193389056
> 3   libsystem_c.dylib                   0x00007fff20293720 abort + 120
> 4   libc++abi.dylib                     0x00007fff20305418 abort_message + 231
> 5   libc++abi.dylib                     0x00007fff202f6a65 _ZL28demangling_terminate_handlerv + 242
> 6   libobjc.A.dylib                     0x00007fff201ec9b9 _ZL15_objc_terminatev + 104
> 7   libc++abi.dylib                     0x00007fff20304847 _ZSt11__terminatePFvvE + 8
> 8   libc++abi.dylib                     0x00007fff20307167 __cxa_get_exception_ptr + 0
> 9   libc++abi.dylib                     0x00007fff2030712e _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
> 10  redex-all                           0x000000010de6ce4e _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 894
> 11  redex-all                           0x000000010de7f932 _ZN15DexEncodedValue7vencodeEP12DexOutputIdxRNSt3__16vectorIhNS2_9allocatorIhEEEE + 434
> 12  redex-all                           0x000000010de845d5 _ZN13DexAnnotation7vencodeEP12DexOutputIdxRNSt3__16vectorIhNS2_9allocatorIhEEEE + 373
> 13  redex-all                           0x000000010dec0d46 _ZN9DexOutput18unique_annotationsERNSt3__13mapIP13DexAnnotationjNS0_4lessIS3_EENS0_9allocatorINS0_4pairIKS3_jEEEEEERNS0_6vectorIS3_NS6_IS3_EEEE + 230
> 14  redex-all                           0x000000010dec263f _ZN9DexOutput20generate_annotationsEv + 943
> 15  redex-all                           0x000000010dec6086 _ZN9DexOutput7prepareE8SortModeRKNSt3__16vectorIS0_NS1_9allocatorIS0_EEEER11ConfigFilesRKNS1_12basic_stringIcNS1_11char_traitsIcEENS3_IcEEEE + 870
> 16  redex-all                           0x000000010dec88d7 _Z20write_classes_to_dexRK12RedexOptionsRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEPNS2_6vectorIP8DexClassNS6_ISD_EEEEPNS2_13unordered_mapIP9DexStringN8facebook7LocatorENS2_4hashISJ_EENS2_8equal_toISJ_EENS6_INS2_4pairIKSJ_SL_EEEEEEmmR11ConfigFilesP14PositionMapperPNSH_IP9DexMethodyNSM_IS11_EENSO_IS11_EENS6_INSQ_IKS11_yEEEEEEPNSH_IP7DexCodeNSB_I13DebugLineItemNS6_IS1B_EEEENSM_IS1A_EENSO_IS1A_EENS6_INSQ_IKS1A_S1D_EEEEEEP12IODIMetadataSA_PK12PostLoweringib + 2887
> 17  redex-all                           0x000000010de1044f _ZN12_GLOBAL__N_113redex_backendER11ConfigFilesR11PassManagerRNSt3__16vectorI8DexStoreNS4_9allocatorIS6_EEEERN4Json5ValueE + 3039
> 18  redex-all                           0x000000010de095c6 main + 8086
> 19  libdyld.dylib                       0x00007fff2035b631 start + 1
> 20  ???                                 0x0000000000000012 0x0 + 18
> Traceback (most recent call last):
>   File "/tmp/redex.5KViSD/redex.py", line 1091, in <module>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/private/tmp/redex.5KViSD/pyredex/utils.py", line 57, in with_temp_cleanup
>     fn()
>   File "/tmp/redex.5KViSD/redex.py", line 1091, in <lambda>
>     with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
>   File "/tmp/redex.5KViSD/redex.py", line 1070, in run_redex
>     run_redex_binary(state, term_handler)
>   File "/tmp/redex.5KViSD/redex.py", line 508, in run_redex_binary
>     if run():
>   File "/tmp/redex.5KViSD/redex.py", line 489, in run
>     raise RuntimeError(
> RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.5KViSD/redex-gdb-bzy9u2_4.sh or under lldb by running /tmp/redex.5KViSD/redex-lldb-_sz9e176.sh

`

**Comment by agampe** [comment]
Ugh, this seems to be a large value or something. The code is not very robust for speed purposes, and it's overflowing an internal buffer.

Can you apply this patch and run again? That should give us some interesting information:
```
--- a/libredex/DexAnnotation.cpp
+++ b/libredex/DexAnnotation.cpp
@@ -269,8 +269,8 @@
   uint8_t* pend = buffer;
   encode(dodx, pend);
   always_assert_log(pend - buffer <= MAX_BUFFER_SIZE,
-                    "DexEncodedValue::vencode overflow, size %d\n",
-                    (int)(pend - buffer));
+                    "DexEncodedValue::vencode overflow, size %d. value=%s",
+                    (int)(pend - buffer), show().c_str());
   for (uint8_t* p = buffer; p < pend; p++) {
     bytes.push_back(*p);
   }
```
