### ISSUE TITLE
A problem with handling MOVE_WIDE in CopyPropagationPass

### ISSUE THREAD

**Issue by fengruisd** [facebook/redex#585]
I am running redex and get an error
here is the config
> {
  "redex": {
    "passes": [
        "CopyPropagationPass",
        "RegAllocPass"
    ]
  },
  "CopyPropagationPass" : {
    "debug": true,
    "eliminate_const_strings": false
  },
 // ...
}

And I got an error after running CopyPropagationPass

> Inconsistency in Dex code. Type error in method .... @ 0x7fdf7f4f18d0 for register v3: expected type (LONG1, LONG2), but found (LONG1, LONG1) instead

I print the cfg and the IRCode
the cfg before CopyPropagationPass is
> **Block B6:**
   ...
   [0x7fc7b96fdd40] OPCODE: MOVE_WIDE v4, v3
   ...
   succs: (branch B9) (goto B7)
**Block B7:**
   preds: (goto B6)
   ...
   [0x7fc7b96e63e0] OPCODE: MOVE_WIDE v3, v4
   [0x7fc7b96e64c0] OPCODE: INVOKE_STATIC v0, v1, v2, v3, v5, v7, Lcom/.....

CopyPropagationPass remove the instruction `[0x7fc7b96e63e0] OPCODE: MOVE_WIDE v3, v4` and TypeChecker report the error

Maybe there is something wrong with CopyPropagationPass when handling `MOVE_WIDE vN, vN+1` ?

**Comment by agampe** [comment]
Thank you for the report! You are right, the overlapping case of `move-wide` is not correctly handled here. Fix coming soon.
