### ISSUE TITLE
Inconsistency found in Dex code for Landroidx/appcompat/app/AlertController$3;.run:()V

### ISSUE THREAD

**Issue by excitedhaha** [facebook/redex#586]
**A problem appeared when redex my apk. The log is :**
IRTypeChecker completed in 2.9 seconds
Inconsistency found in Dex code for Landroidx/appcompat/app/AlertController$3;.run:()V
 Type error in method Landroidx/appcompat/app/AlertController$3;.run:()V at instruction 'INVOKE_STATIC v0, v1, v2, Landroidx/appcompat/app/AlertController;.manageScrollIndicators:(Landroid/view/View;Landroid/view/View;Landroid/view/View;)V' @ 0x7fb086f537a0 for : Landroidx/core/widget/NestedScrollView; is not assignable to Landroid/view/View;

Code:
[0x7fb086f53460] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v3
[0x7fb086f4a3d0] POSITION: Landroidx/appcompat/app/AlertController$3;.run:()V(SourceFile:603)
[0x7fb086f53230] OPCODE: IGET_OBJECT v3, Landroidx/appcompat/app/AlertController$3;.this$0:Landroidx/appcompat/app/AlertController;
[0x7fb086f4a290] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fb086f53630] OPCODE: IGET_OBJECT v0, Landroidx/appcompat/app/AlertController;.mScrollView:Landroidx/core/widget/NestedScrollView;
[0x7fb086f53950] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fb086faf360] OPCODE: IGET_OBJECT v3, Landroidx/appcompat/app/AlertController$3;.val$top:Landroid/view/View;
[0x7fb086f53990] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7fb086f71240] OPCODE: IGET_OBJECT v3, Landroidx/appcompat/app/AlertController$3;.val$bottom:Landroid/view/View;
[0x7fb086f4a330] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v2
[0x7fb086f537a0] OPCODE: INVOKE_STATIC v0, v1, v2, Landroidx/appcompat/app/AlertController;.manageScrollIndicators:(Landroid/view/View;Landroid/view/View;Landroid/view/View;)V
[0x7fb086f4a250] OPCODE: RETURN_VOID

 If you are confident that this does not matter (e.g., because you are using MakePublicPass), turn off accessibility checking on input with `-J ir_type_checker.run_on_input_ignore_access=true`.
 You may turn off all input checking with `-J ir_type_checker.run_on_input=false`.
Traceback (most recent call last):
  File "/tmp/redex.eFpaLy/redex.py", line 1091, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.eFpaLy/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/tmp/redex.eFpaLy/redex.py", line 1091, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.eFpaLy/redex.py", line 1070, in run_redex
    run_redex_binary(state, term_handler)
  File "/tmp/redex.eFpaLy/redex.py", line 508, in run_redex_binary
    if run():
  File "/tmp/redex.eFpaLy/redex.py", line 489, in run
    raise RuntimeError(
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.eFpaLy/redex-gdb-_rg9bugz.sh or under lldb by running /tmp/redex.eFpaLy/redex-lldb-4a8fahy8.sh

**Then I add MakePlublicClass to the config and add "-J ir_type_checker.run_on_input=false" to the command, but they not work.**
And it's strange that AlertController is a subclass of View, It should be ok for the function to run.

**Comment by kuganv** [comment]
Thanks for reporting. Is it possible provide a test case to reproduce this.  As you said,  Landroidx/appcompat/app/AlertController; is asubclass of Landroid/view/View. so this should work.

**Comment by agampe** [comment]
It is not complaining that `AlertController` is not a `View`. It is saying that `NestedControlView` is not, but is used as such in an `AlertController` method.

I think we had this issue reported before, and when I looked at the APK, that error was correct. For some reason the class was broken. That is the first thing you should confirm on your input.

**Comment by excitedhaha** [comment]
> It is not complaining that `AlertController` is not a `View`. It is saying that `NestedControlView` is not, but is used as such in an `AlertController` method.
> 
> I think we had this issue reported before, and when I looked at the APK, that error was correct. For some reason the class was broken. That is the first thing you should confirm on your input.

Yes, I said was wrong,  NestedControlView is a View Actually. How can I find the error, the log's information is not enough.

**Comment by agampe** [comment]
> > It is not complaining that `AlertController` is not a `View`. It is saying that `NestedControlView` is not, but is used as such in an `AlertController` method.
> > I think we had this issue reported before, and when I looked at the APK, that error was correct. For some reason the class was broken. That is the first thing you should confirm on your input.
> 
> Yes, I said was wrong, NestedControlView is a View Actually. How can I find the error, the log's information is not enough.

We do not currently give that information. You can find it manually by running `dexdump` from the Android SDK over your dex files. It will disassemble the bytecode. You can search for the class definition (starts with `Class descriptor:`), and it will note the superclass.

**Comment by agampe** [comment]
Note: issue #566 is one of the similar things, where `androidx` seems to have been reduced to incorrect code.

**Comment by excitedhaha** [comment]
> > > It is not complaining that `AlertController` is not a `View`. It is saying that `NestedControlView` is not, but is used as such in an `AlertController` method.
> > > I think we had this issue reported before, and when I looked at the APK, that error was correct. For some reason the class was broken. That is the first thing you should confirm on your input.
> > 
> > 
> > Yes, I said was wrong, NestedControlView is a View Actually. How can I find the error, the log's information is not enough.
> 
> We do not currently give that information. You can find it manually by running `dexdump` from the Android SDK over your dex files. It will disassemble the bytecode. You can search for the class definition (starts with `Class descriptor:`), and it will note the superclass.

I decompiled the dex, and find that NestedControlView extends from 'android.widget.FrameLayout',

**Comment by excitedhaha** [comment]
> > > It is not complaining that `AlertController` is not a `View`. It is saying that `NestedControlView` is not, but is used as such in an `AlertController` method.
> > > I think we had this issue reported before, and when I looked at the APK, that error was correct. For some reason the class was broken. That is the first thing you should confirm on your input.
> > 
> > 
> > Yes, I said was wrong, NestedControlView is a View Actually. How can I find the error, the log's information is not enough.
> 
> We do not currently give that information. You can find it manually by running `dexdump` from the Android SDK over your dex files. It will disassemble the bytecode. You can search for the class definition (starts with `Class descriptor:`), and it will note the superclass.

I decompiled the dex, and find that NestedControlView extends from 'android.widget.FrameLayout', it seems right

**Comment by agampe** [comment]
That would indicate that you do not have the Android SDK available, if Redex does not know the `FrameLayout extends ViewGroup extends View`.

What "version" of Redex are you using? When was it compiled?

**Comment by excitedhaha** [comment]
I use the Android SDK same with the path in 'local.properties'. The command is 'python3 redex.py ~/StudioProjects/expressdriver-android/app/build/outputs/apk/servOnline/release/app-servOnline-release.apk --android-sdk-path ~/Library/Android/sdk -o a.apk -J ir_type_checker.run_on_input=false'
I'm in the master branch and I recompiled just today.

**Comment by agampe** [comment]
I think we do not have this documented well, and our internal setup uses proguard files for this, so a rewrite is compliced.

What you're missing is to add the `android.jar` from the SDK as a classpath. The `--android-sdk-path` sadly is only there to pick up build tools.

I'll try to come up with a scheme, but for now, you have to manually add something like
```
-j ~/Library/Android/sdk/platforms/android-30/android.jar
```

**Comment by excitedhaha** [comment]
A new error happened:
python3 redex.py ~/StudioProjects/expressdriver-android/app/build/outputs/apk/servOnline/release/app-servOnline-release.apk -j /Users/didi/Library/Android/sdk/platforms/android-30/android.jar -o a.apk -J ir_type_checker.run_on_input=false
WARNING:root:No android_sdk_api_XX_file parameters found!
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
        Load classes from dexes completed in 1.1 seconds
libc++abi.dylib: terminating with uncaught exception of type RedexException: RedexError: 4 with message: Found duplicate class in two different files. with extra info: ("class", "Landroid/view/View$OnGenericMotionListener;") ("dex", "/var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpa1uln6op.redex_dexen/dex0/classes.dex") ("jar", "/Users/didi/Library/Android/sdk/platforms/android-30/android.jar")
0   redex-all                           0x0000000110276422 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff674165fd _sigtramp + 29
2   ???                                 0x0000000000000400 0x0 + 1024
3   libsystem_c.dylib                   0x00007fff672ec808 abort + 120
4   libc++abi.dylib                     0x00007fff6454b458 abort_message + 231
5   libc++abi.dylib                     0x00007fff6453c8a7 _ZL28demangling_terminate_handlerv + 238
6   libobjc.A.dylib                     0x00007fff660775b1 _ZL15_objc_terminatev + 104
7   libc++abi.dylib                     0x00007fff6454a887 _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff6454d1a2 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff6454d169 _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
10  redex-all                           0x000000011036c0e9 _Z11parse_classPhPNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEENS0_8functionIFvN5boost7variantIP8DexFieldJP9DexMethodEEEPKcS_EEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS4_IcEEEE + 6057
11  redex-all                           0x000000011036d4e3 _Z11process_jarPKcPKhlPNSt3__16vectorIP8DexClassNS3_9allocatorIS6_EEEERKNS3_8functionIFvN5boost7variantIP8DexFieldJP9DexMethodEEES0_PhEEE + 1443
12  redex-all                           0x000000011036d81c _Z13load_jar_filePKcPNSt3__16vectorIP8DexClassNS1_9allocatorIS4_EEEERKNS1_8functionIFvN5boost7variantIP8DexFieldJP9DexMethodEEES0_PhEEE + 124
13  redex-all                           0x0000000110217dff _ZN12_GLOBAL__N_114redex_frontendER11ConfigFilesRNS_9ArgumentsERN10keep_rules21ProguardConfigurationERNSt3__16vectorI8DexStoreNS7_9allocatorIS9_EEEERN4Json5ValueE + 2847
14  redex-all                           0x000000011021162d main + 1501
15  libdyld.dylib                       0x00007fff6721dcc9 start + 1
16  ???                                 0x0000000000000019 0x0 + 25
Traceback (most recent call last):
  File "/Users/didi/AndroidStudioProjects/redex/redex.py", line 1158, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/Users/didi/AndroidStudioProjects/redex/pyredex/utils.py", line 57, in with_temp_cleanup
    fn()
  File "/Users/didi/AndroidStudioProjects/redex/redex.py", line 1158, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/Users/didi/AndroidStudioProjects/redex/redex.py", line 1137, in run_redex
    run_redex_binary(state, term_handler, exception_formatter)
  File "/Users/didi/AndroidStudioProjects/redex/redex.py", line 520, in run_redex_binary
    if run():
  File "/Users/didi/AndroidStudioProjects/redex/redex.py", line 506, in run
    raise RuntimeError(msg)
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/redex-gdb-8w49h2fj.sh or under lldb by running /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/redex-lldb-q66nlc2x.sh

**Comment by agampe** [comment]
That is a problem with your build process. You must not copy Android classes into your APK.
