### ISSUE TITLE
'make' command cause  'Undefined symbols for architecture x86_64' in Mac 

### ISSUE THREAD

**Issue by doulala1986** [facebook/redex#59]
I get blow message when I command ‘‘make’’  Redex    in Mac of version 10.11.2~~ thanks for your advices。

  ```
  libtool: link: g++ -std=gnu++0x -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o -Wl,-bind_at_load  ./.libs/libfollybase.a -lboost_context-mt -lboost_program_options-mt -lboost_thread-mt -lboost_filesystem -lboost_system -lboost_regex-mt -lpthread -llzma -levent -lssl -lgflags -lglog -ldouble-conversion -lz
Undefined symbols for architecture x86_64:
  "double_conversion::StringToDoubleConverter::StringToIeee(char const*, int, int*, bool) const", referenced from:
      folly::detail::str_to_float(folly::Range<char const*>*) in libfollybase.a(Conv.o)
      folly::detail::str_to_double(folly::Range<char const*>*) in libfollybase.a(Conv.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [generate_fingerprint_tables] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by shmuelr** [comment]
I'm getting this error also
I posted here https://stackoverflow.com/questions/36607316/cimpiling-facebook-redex-on-osx-yosemite

**Comment by bertmaher** [comment]
I've just pushed a bunch of build system fixes.  Can you pull the latest master and try `autoreconf -i && ./configure && make` again?  Thanks.

**Comment by shmuelr** [comment]
Thank you!

I pulled the latest  changes but now I get a new error - 

39 warnings generated.
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT futures/ThreadWheelTimekeeper.lo -MD -MP -MF futures/.deps/ThreadWheelTimekeeper.Tpo -c futures/ThreadWheelTimekeeper.cpp -o futures/ThreadWheelTimekeeper.o >/dev/null 2>&1
depbase=`echo detail/ThreadLocalDetail.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I./.. -pthread -I/usr/local/include   -std=gnu++0x -g -O2 -MT detail/ThreadLocalDetail.lo -MD -MP -MF $depbase.Tpo -c -o detail/ThreadLocalDetail.lo detail/ThreadLocalDetail.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT detail/ThreadLocalDetail.lo -MD -MP -MF detail/.deps/ThreadLocalDetail.Tpo -c detail/ThreadLocalDetail.cpp  -fno-common -DPIC -o detail/.libs/ThreadLocalDetail.o
detail/ThreadLocalDetail.cpp:39:3: error: no matching function for call to 'pthread_setspecific'
  pthread_setspecific(meta.pthreadKey_, threadEntry);
  ^~~~~~~~~~~~~~~~~~~
/usr/include/pthread.h:456:5: note: candidate function not viable: no known conversion from 'std::unique_ptr<ThreadEntry>' to 'const void *' for 2nd argument; take the address of
      the argument with &
int pthread_setspecific(pthread_key_t , const void *);
    ^
1 error generated.
make[4]: *** [detail/ThreadLocalDetail.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by doulala1986** [comment]
i pull the lastest masters,but still get error message:

```
libtool: link: g++ -std=gnu++0x -g -O2 -o generate_fingerprint_tables build/GenerateFingerprintTables.o -Wl,-bind_at_load  ./.libs/libfollybase.a -lboost_context-mt -lboost_program_options-mt -lboost_thread-mt -lboost_filesystem -lboost_system -lboost_regex-mt -lpthread -llzma -levent -ldouble-conversion -lssl -lglog -lgflags -lz
Undefined symbols for architecture x86_64:
  "double_conversion::StringToDoubleConverter::StringToIeee(char const*, int, int*, bool) const", referenced from:
      folly::detail::str_to_float(folly::Range<char const*>*) in libfollybase.a(Conv.o)
      folly::detail::str_to_double(folly::Range<char const*>*) in libfollybase.a(Conv.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [generate_fingerprint_tables] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by bertmaher** [comment]
It seems like your system can't find the double-conversion library.  Find libdouble-conversion.a (it *should* be in /usr/local/lib/libdouble-conversion.a), and invoke configure with `./configure 'LDFLAGS=-L/usr/local/lib'` (or whatever the correct path is).
