### ISSUE TITLE
Bug: Windows, No SDK jar found

### ISSUE THREAD

**Issue by pashamcr** [facebook/redex#598]
Windows, the SDK is installed, and is located in the standard installation path using Android Studio:
`C:\Users\user\AppData\Local\Android\Sdk`
This path is set in the ANDROID_SDK environment variables.
SDKs installed for platforms 30,28,21,19, i.e. there are folders: `%ANDROID_SDK%\platforms\android-XX`
When using redex, I get:
```
WARNING:root:No SDK jar found, attempting to find one. If the detection is wrong, add `--suppress-android-jar-check`.
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
        Load classes from dexes completed in 0.5 seconds
error: cannot open jar file: C
error: cannot open jar file: /C
error: library jar could not be loaded: C
Traceback (most recent call last):
  File "d:\WORK\redex\redex.py", line 1260, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "d:\WORK\redex\pyredex\utils.py", line 58, in with_temp_cleanup
    fn()
  File "d:\WORK\redex\redex.py", line 1260, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "d:\WORK\redex\redex.py", line 1239, in run_redex
    run_redex_binary(state, term_handler, exception_formatter)
  File "d:\WORK\redex\redex.py", line 521, in run_redex_binary
    if run():
  File "d:\WORK\redex\redex.py", line 496, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 1!
```
With the `--suppress-android-jar-check flag`, redex works,
tried without it and with flags:
```
--jarpath C:\Users\user\AppData\Local\Android\Sdk\platforms\android-30
--android-sdk-path C:\Users\user\AppData\Local\Android\Sdk
```
doesn't work how to set path to android.jar?

**Comment by agampe** [comment]
Ugh. So we handle `jarpath` like a standard Unix list, see [here](https://github.com/facebook/redex/blob/e87fe7d9b17da9ae5cc75c584d6b50847bcd117e/tools/redex-all/main.cpp#L856). We'll need to make that dependent on the operating system.

**Comment by agampe** [comment]
Can you try with e92aaaa8?

**Comment by pashamcr** [comment]
> Can you try with [e92aaaa](https://github.com/facebook/redex/commit/e92aaaa8830a2f9bb53e63fd0d4864593b4db5d1)?

Works with --jarpath flag, no warnings.
Without the --jarpath flag, it also works (finds android.jar automatically?), But the warning remains:
WARNING:root:No SDK jar found, attempting to find one. If the detection is wrong, add `--suppress-android-jar-check`.

**Comment by agampe** [comment]
That is expected. It could be an `INFO` message, but by default we only log warnings.
