### ISSUE TITLE
InterDex not worked

### ISSUE THREAD

**Issue by excitedhaha** [facebook/redex#600]
I using redex for optimizing launch time, so I only use the interdex pass. But after processing the apk, I find that the launch time not reduced, and I checked the dexes in two apk, it seems that t**he class distribution not changed**.

My command is :python3 redex.py ~/StudioProjects/expressdriver-android/app/build/outputs/apk/servOnline/release/app-servOnline-release.apk  -j /Users/didi/Library/Android/sdk/platforms/android-30/android.jar -s ~/StudioProjects/expressdriver-android/keystore/didichuxing.keystore -a xjkj.keystore -p xjkj3628077870116911 -o outputs/freight.apk --sign -c config/my.config -m ~/StudioProjects/expressdriver-android/app/build/outputs/mapping/servOnlineRelease/mapping.txt -P ~/StudioProjects/expressdriver-android/app/proguard-rules.pro

And the trace:
Using config config/my.config
Using binary (default)
Extracting apk...
Detected dex mode Api21DexMode
Unpacking dex files
Detecting Application Modules
Unpacking APK finished in 1.29 seconds
WARNING:root:No android_sdk_api_XX_file parameters found!
Running redex-all on 5 dex files
Running redex binary at /Users/didi/AndroidStudioProjects/redex/redex-all
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
    Parsing proguard map completed in 3.2 seconds
Unimplemented command (skipping): -dontskipnonpubliclibraryclassmembers at line 27
Unimplemented command (skipping): -useuniqueclassmembernames at line 31
Unimplemented command (skipping): -renamesourcefileattribute at line 32
Unimplemented command (skipping): -ignorewarnings at line 403
        Parsed ProGuard config file completed in 0.0 seconds
dup_class_allowlist: {
  Lcom/facebook/soloader/MergedSoMapping;
  Ljunit/framework/TestSuite;
  L$r8$java8methods$utility
  Ljava/util/stream/Stream$-
}
Loading classes from dex from /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpttn9n5ei.redex_dexen/dex0/classes.dex
Loading classes from dex from /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpttn9n5ei.redex_dexen/dex1/classes2.dex
Loading classes from dex from /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpttn9n5ei.redex_dexen/dex2/classes3.dex
Loading classes from dex from /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpttn9n5ei.redex_dexen/dex3/classes4.dex
Loading classes from dex from /var/folders/8g/hhwx3zb903l2dxpzpd1t2q980000gn/T/tmpttn9n5ei.redex_dexen/dex4/classes5.dex
        Load classes from dexes completed in 1.2 seconds
LIBRARY JAR: /Users/didi/Library/Android/sdk/platforms/android-30/android.jar
        Load library jars completed in 0.4 seconds
        Deobfuscating dex elements completed in 0.5 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 1.1 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 1.1 seconds
        No Optimizations Rules completed in 1.4 seconds
            Mark keep-methods completed in 0.0 seconds
            Computing XML reachability completed in 0.1 seconds
            Computing native reachability completed in 0.2 seconds
            Analyzing reflection completed in 0.1 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 0.3 seconds
    Redex_frontend completed in 5.0 seconds
        API Level Checker completed in 0.0 seconds
WARNING: No inliner config
Evaluating InterDexPass...
        InterDexPass (eval) completed in 0.0 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 3.9 seconds
        Hasher completed in 0.2 seconds
Running InterDexPass...
VmHWM for InterDexPass was 0.00 B (0.00 B over start).
            Hasher completed in 0.2 seconds
Running IRTypeChecker...
            IRTypeChecker completed in 4.6 seconds
After processing unresolved lines: MethodProfiles successfully parsed 0 rows; 0 unresolved lines
        InterDexPass 1 (run) completed in 6.1 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 4.9 seconds
    Running optimization passes completed in 15.2 seconds
        Instruction lowering completed in 1.4 seconds
Writing out new DexClasses...
found 9641 strings from types, 1230 from strings in init methods, 22370 total strings
found 3362 strings from types, 613 from strings in init methods, 7082 total strings
found 5056 strings from types, 736 from strings in init methods, 9740 total strings
found 6115 strings from types, 2224 from strings in init methods, 15077 total strings
found 9252 strings from types, 1350 from strings in init methods, 21067 total strings
        Writing optimized dexes completed in 10.1 seconds
        Writing opt decisions data completed in 0.0 seconds
        Writing stats completed in 0.0 seconds
    Redex_backend completed in 11.5 seconds
    Freeing global memory completed in 2.5 seconds
redex-all main() completed in 38.9 seconds
Done.
Memory stats: VmPeak=0.00 B VmHWM=0.00 B
Dex processing finished in 39.10 seconds
Repacking dex files
Emit Locator Strings: None
Creating output apk
Creating output APK finished in 7.38 seconds
Copying all redex generated artifacts redex-class-rename-map.txt map to output dir
WARNING:root:Copying all redex generated artifacts redex-class-rename-map.txt map to output_dir: /Users/didi/AndroidStudioProjects/redex/outputs/redex-class-rename-map.txt
Copying all redex generated artifacts redex-unused-keep-rules.txt map to output dir
WARNING:root:Copying all redex generated artifacts redex-unused-keep-rules.txt map to output_dir: /Users/didi/AndroidStudioProjects/redex/outputs/redex-unused-keep-rules.txt
Copying all redex generated artifacts redex-full-rename-map.txt map to output dir
WARNING:root:Copying all redex generated artifacts redex-full-rename-map.txt map to output_dir: /Users/didi/AndroidStudioProjects/redex/outputs/redex-full-rename-map.txt
Copying all redex generated artifacts redex-stats.txt map to output dir
WARNING:root:Copying all redex generated artifacts redex-stats.txt map to output_dir: /Users/didi/AndroidStudioProjects/redex/outputs/redex-stats.txt
Copying all redex generated artifacts redex-bytecode-offset-map.txt map to output dir
WARNING:root:Copying all redex generated artifacts redex-bytecode-offset-map.txt map to output_dir: /Users/didi/AndroidStudioProjects/redex/outputs/redex-bytecode-offset-map.txt

**Comment by excitedhaha** [comment]
The problem is clear after I searched other persons' config, I move the "coldstart_classes" section to the outer scope, the output dexes changed,  such as classes2.dex. But the first dex(classes.dex) is the same as the dex without interdex, and the launch time does not go down. The meminfo shows that .dex mmap go down, but the total even go up.
So why the first dex not changed, it should be the main dex, the apk contains 5 dex.

**Comment by emma0303** [comment]
Thanks for reaching out and providing the second comment with what you tried. 

>  the output dexes changed,

Great.

> But the first dex(classes.dex) is the same as the dex without interdex

That makes sense as we treat first dex differently .. By default, we don't add / remove anything from the first dex (this is useful in case of multidex, when native support is not provided, like on Android 4 and below.). If you don't have this limitation, please feel free to enable the feature of adding / removing / reordering primary dex via this option: 

 "InterDexPass": {
    "normal_primary_dex": true
    // +/- other configs that you might set here.
  }
  
  Also, feel free to share your configuration here. 
  
  As a side note, in order for this to improve performance, we expect that you have 1) a good strategy for how you compute that order and 2) the file is correctly formatted (which sounds like it is, since the 2+ dexes got changed).

**Comment by excitedhaha** [comment]
Thanks for your reply.
Unfortunately, it not works. Actually, I tried this option yesterday after I saw others' configs.
Here is my config:
{
  "redex" : {
    "passes":[
    "InterDexPass"
    ]
  },
  "InterDexPass" : {
    "normal_primary_dex": true
   },
   "coldstart_classes": "list_of_classes.txt"
}

**Comment by emma0303** [comment]
The config seems in order. 

This config probably doesn't do what you thought first. This change still keeps the classes in the primary dex, but keeps adding to it. So the order won't change .. We don't have a flag for that now. Can try to set something up soon.

**Comment by excitedhaha** [comment]
Sad to hear it

**Comment by excitedhaha** [comment]
> The config seems in order.
> 
> This config probably doesn't do what you (and I) thought first. This change still keeps the classes in the primary dex, but keeps adding to it. So the order won't change .. We don't have a flag for that now. Can try to set something up soon.

Any progress for it?

**Comment by emma0303** [comment]
Sorry, I was out for a while after this initial request and forgot to ping here with the newly added flag.

The change should be to set https://github.com/facebook/redex/blob/master/opt/interdex/InterDexPass.cpp#L44 flag to false.

{
  "redex" : {
    "passes":[
      "InterDexPass"
    ]
  },
  "InterDexPass" : {
    "normal_primary_dex": true,
    "keep_primary_order": false
  },
  "coldstart_classes": "list_of_classes.txt"
}

Please let me know if this works for your use case. Thanks!

**Comment by emma0303** [comment]
This issue should be fixed now. Please reach out if you don't find that to be the case. Thank you!
