### ISSUE TITLE
ProguardMap.file_name_from_method_string() requires class package

### ISSUE THREAD

**Issue by kbabcockuf** [facebook/redex#603]
`ProguardMap.file_name_from_method_string()`requires the given method's containing class to have a package specified.  The assert at https://github.com/facebook/redex/blob/master/libredex/ProguardMap.cpp#L356 fails if no package is present (e.g. no forward slash is found in the method's DexString.

**Comment by NTillmann** [comment]
A few lines later at https://github.com/facebook/redex/blob/master/libredex/ProguardMap.cpp#L358 it tries to explicitly deal with the case without a forward slash.

Do you have a more concrete test case that shows on what input what goes wrong?

**Comment by NTillmann** [comment]
Closing for now, feel free to reopen if you have more information.

**Comment by kbabcockuf** [comment]
Ah, my fault, our internal fork is out of date.  This is definitely fixed on current master.
