### ISSUE TITLE
Method invoked by native code is removed by inline pass

### ISSUE THREAD

**Issue by fengruisd** [facebook/redex#604]
Hi

I was optimizing my app with IntraDexInlinePass, a method invoked by native code and java code at the same times was removed.
I add a log in `Deleter.cpp delete_methods()` and enable the trace by `export TRACE=1,PGR:3`, then I got the log like this
```
...
native_lib: Lcom/xxx/ClassA;
...
Running IntraDexInlinePass...
No shrinker forest: 
            MultiMethodInliner construction completed in 0.4 seconds
            compute_callee_constant_arguments completed in 2.5 seconds
            compute_caller_nonrecursive_callees_by_stack_depth completed in 0.3 seconds
// the log I added in delete_methods ..
print by delete_methods:
            method: Lcom/xxx/ClassA.methodA(), method's rstate is: 10011000
...
```
rstate is 10011000, it means the method can be deleted.
I checked the code `ReachableClasses.cpp mark_reachable_by_native()` and `ReferencedState.h set_keepnames()`, and I found that `set_keepnames` invoke `set_allowshrinking()`.
what I can't understand is: if a method/class is reachable by native, why it would be set 'allowshrinking', the action may cause the method deleted.

Kindly let me know how this can be resolved.

**Comment by yuxuanchen1997** [comment]
keepnames allows the method to be removed if it's not necessary. You need to `-keep` or `@DoNotStrip` your native entry points.
