### ISSUE TITLE
Documentation for Passes

### ISSUE THREAD

**Issue by euzada** [facebook/redex#605]
Hi,

I tried to learn the passes via the official website https://fbredex.com/docs/passes, it is outdated and way more passes has been implemented.

Is there is any way from Github that I can see these passes and have some idea what they do?

Thank you.

**Comment by yuxuanchen1997** [comment]
My apologies that we didn't add the pass documentation. Usually there will be comment blocks in the source code of each pass under [`opt`](https://github.com/facebook/redex/tree/master/opt). I hope this helps.
