### ISSUE TITLE
BridgePass only inline private bridgee method, why?

### ISSUE THREAD

**Issue by bill-lia** [facebook/redex#612]
if (it->insn->opcode() != OPCODE_INVOKE_DIRECT &&
      it->insn->opcode() != OPCODE_INVOKE_STATIC) {
    TRACE(BRIDGE, 5, "Rejecting unhandled pattern: `%s'", SHOW(bridge));
    return nullptr;
}
most Generic generate bridge invoke-virtual, so cannot inline... only private bridgee can inline, why?

**Comment by NTillmann** [comment]
I think you indeed found some interesting quirk in this Redex pass. Indeed, it doesn't handle virtual bridgees at all right now, even though it seems that there is some ancient dead code that was meant to deal with it. I'll see if we can do better, but we'd also certainly welcome a contribution :-)

**Comment by NTillmann** [comment]
I've found that you can run the MethodDevirtualizationPass before the BridgePass to effectively deal with virtual bridge methods.
