### ISSUE TITLE
Incorrect stack trace line number for iodi(2) debug info kind

### ISSUE THREAD

**Issue by ParisZhang11** [facebook/redex#615]
I am trying redex on my demo application and I set debug_info_kind as iodi2. However, when there is an error in my demo, the stack trace output (after remap) is incorrect.

For example, here is my demo application with a bug at line 21
```
public class DemoApplication extends Application {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        debugTest();
    }

    public void debugTest() {
        String a = null;
        Log.e("test", String.valueOf(a.length()));       // Line 21
    }
}
```

Running the demo, the initial stack trace showed
```
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.bytedance.android.redexplugin.demo.DemoApplication.debugTest(:1)
        at com.bytedance.android.redexplugin.demo.DemoApplication.attachBaseContext(:3)
```

I read the issue [386](https://github.com/facebook/redex/issues/386#issuecomment-473449618), and used the command
`$ cat stacktrace.txt | remap redex-line-number-map-v2` to try to recover the original stack trace. However, the result was
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at android.support.v4.app.INotificationSideChannel$Stub$Proxy.<init>(INotificationSideChannel.java:97)
        at android.support.v4.app.INotificationSideChannel$Stub$Proxy.asBinder(INotificationSideChannel.java:102)
```
And I found that `android.support.v4.app.INotificationSideChannel$Stub$Proxy.<init>(INotificationSideChannel.java:97)` is actually the first line of my redex-line-number-map-v2 (after running linemapdump), and `android.support.v4.app.INotificationSideChannel$Stub$Proxy.asBinder(INotificationSideChannel.java:102` is the third line of the redex-line-number-map-v2.

It seems like there is a map missing that maps the error method and the initial line number in the stack trace to the line number in the redex-line-number-map-v2, which will indicate the true stack trace line number. 

I would be very grateful for any suggestions on how to handle this. Please let me know if any other information is needed.

**Comment by yuxuanchen1997** [comment]
Hello @ParisZhang11,

I don't think the the symbolicator you are using supports IODI. Can you try to symbolicate with [`tools/python/symbolicator/symbolicator.py`](https://github.com/facebook/redex/blob/master/tools/python/symbolicator/symbolicator.py)?

**Comment by ParisZhang11** [comment]
> Hello @ParisZhang11,
> 
> I don't think the the symbolicator you are using supports IODI. Can you try to symbolicate with [`tools/python/symbolicator/symbolicator.py`](https://github.com/facebook/redex/blob/master/tools/python/symbolicator/symbolicator.py)?

Yes, I was able to recover the stack trace information using the symbolicator you mentioned. Thank you very much!
