### ISSUE TITLE
Configuring thirdparty folly won't find double-conversion despite LDFLAGS and CPPFLAGS being set properly

### ISSUE THREAD

**Issue by fred777** [facebook/redex#62]
I'm passing LDFLAGS and CPPFLAGS to configure, pointing to double-conversion path. 

Configuring redex works fine, but when it steps over to thirdparty/folly, configure fails:

    === configuring in third-party/folly/folly (/home/fred777/src/redex/third-party/folly/folly)
    configure: running /bin/sh ./configure --disable-option-checking '--prefix=/home/fred777/.local'  'LDFLAGS=-L/home/fred777/src/double-conversion/' 'CPPFLAGS=-I/home/fred777/src/double-conversion/' --cache-file=/dev/null --srcdir=.
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether make supports nested variables... yes
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/home/fred777/src/redex/third-party/folly/folly':
    configure: error: cannot run C compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details
    configure: error: ./configure failed for third-party/folly/folly

According to thirdparty/folly/folly/config.log, this is because libdouble-conversion.1.so is not found.

If I configure folly directly within folder thirdparty/folly/folly/ using the very same LDFLAGS and CPPFLAGS, it works fine.

Hence, LDFLAGS and CPPFLAGS are not passed properly to folly-configure, but I don't have a clue why :-( Strangely, both variables do appear in above configure line

**Build system: Archlinux AMD64, autoconf 2.69, gcc 5.3.0**

**Comment by bertmaher** [comment]
If you have double-conversion installed in a non-standard location, you need to set LD_LIBRARY_PATH appropriately.  Probably `export LD_LIBRARY_PATH=/home/fred777/src/double-conversion` before configuring will work.
