### ISSUE TITLE
OptimizeEnumsPass: assertion error for a candidate_enum array type

### ISSUE THREAD

**Issue by ParisZhang11** [facebook/redex#620]
Hi! I am trying OptimizeEnumsPass on my application and I encountered a crash. After adding some log, I found out where the problem might be, and I wrote a demo to reproduce it.

```
  public static TestEnum[] useEnum() {
      Object result = TestEnum.values();
      StringBuilder stringBuilder = new StringBuilder();
      stringBuilder.append("test");
      stringBuilder.append(result);
      return (TestEnum[]) result;
  }
```

In `optimize_enums::reject_unsafe_enums(m_scope, &config);` in the function `replace_enum_with_int`, when we run the function `process_instruction` in EnumUpcastAnalysis.cpp, if we see an instruction with a candidate_enum array type, we don't reject that candidate_enum as long as the two array types involved in the cast instruction are consistent.

However, later when we run the function `update_instructions` in EnumTransformer.cpp, in the case of `OPCODE_CHECK_CAST`, we don't consider the possibility that the possibe_src_types is a candidate_enum array type in  `extract_candidate_enum_type(possible_src_types)`. Therefore, we cannot find the correct candidate_enum type inside the array and `candidate_type` will be nullptr, so the following always_assert will crash.

The similar error occurs in the function `add_substitute_of_stringvalueof`, where the parameter enum_type is only treated as a candidate_enum type, but may actually be a candidate_enum array type.

I guess there may be other places where a candidate_enum array type should be taken care of. I would be very grateful if you could have a look at it. Please let me know if any other information is needed.

**Comment by amnn** [comment]
Hi @ParisZhang11, thanks for the detailed report!  I'm taking a look and will let you know if we need more information.

Also, cc @Feng23 who is familiar with the pass.

**Comment by Feng23** [comment]
Thank you for reporting the error with analysis details and code example! I am working on the fix.

**Comment by Feng23** [comment]
Feel free to re-open the issue if the fix doesn't help. Thank you again for reporting the error!
