### ISSUE TITLE
OptimizeEnumsPass: java VerifyError for enum->int conversion

### ISSUE THREAD

**Issue by ParisZhang11** [facebook/redex#621]
Hi! Thank you for fixing the assertion error in OptimizeEnumsPass for #620. Now I am able to apply this pass on my app, but later the app runs with a java.lang.VerifyError. Again, I wrote a demo to reproduce it.

```
public enum DemoEnum {

    A("a"),
    B("b");

    String string;

    DemoEnum(String s) {
        string = s;
    }

    final String getString() {
        return string;
    }
}
```

After running redex, the bytecode of `getString()` becomes:
```
# virtual methods
.method final getString()Ljava/lang/String;
    .registers 2

    .prologue
    invoke-static {p0}, LDemoEnum;->redex$OE$get_string(Ljava/lang/Integer;)Ljava/lang/String;

    move-result-object v0

    return-object v0

.end method
```
While p0 (this) is an instance of DemoEnum, it is taken in as an Integer for `redex$OE$get_string`, which causes the java verifyError. I would be very grateful if you could have a look at it. Please let me know if any other information is needed.

**Comment by ParisZhang11** [comment]
> Thanks for reporting. invoke-static is a static call and hence does not take the "this" parameter. The error you are seeing should be elsewhere. Could you please provide the full dexdump.

Sorry, maybe I didn't describe the error clearly.

As a reference, the bytecode of getString() before running redex is:
```
.method final getString()Ljava/lang/String;
    .registers 2

    .prologue
    iget-object v0, p0, Lcom/bytedance/android/redexplugin/demo/OptimizeDemoEnum;->string:Ljava/lang/String;

    return-object v0

.end method
```
Here, p0 is an instance of DemoEnum (i.e. DemoEnum.A or DemoEnum.B). Even though the static method `redex$OE$get_string` does not have "this" itself, the bytecode after redex suggests that the transformed `getString` calls `redex$OE$get_string` with p0, an instance of DemoEnum (which I called "this").

It shows in the bytecode that p0 is treated as an Integer in `getString()`, but p0 is clearly not. That's why I believe the error is here.

**Comment by Feng23** [comment]
The bytecode looks unexpected and I can not repro.

The virtual method `getString()` should be changed to static method who accepts an integer parameter.
```
# virtual methods
.method final getString()Ljava/lang/String;
    .registers 2

    .prologue
    invoke-static {p0}, LDemoEnum;->redex$OE$get_string(Ljava/lang/Integer;)Ljava/lang/String;

    move-result-object v0

    return-object v0

.end method
```

What's the branch and commit you are using? And can you also share your Redex config and the verify error log?

**Comment by Feng23** [comment]
I see how it happens. The OptimizeEnumsPass relies on RemoveUnreachablePass to delete unused methods, when `RemoveUnreachablePass` is missing, the enum pass may leave unused code untransformed. We should fix that.
You can also try to add RemoveUnreachablePass, that requires proper ProGuard rules (e.g. all the reflected usages are properly kept).
