### ISSUE TITLE
configure: error: Please install double-conversion library

### ISSUE THREAD

**Issue by waynell** [facebook/redex#63]
comile redex failed, it shows the follwing errors, but I has already install all dependences

`checking for ceil in -ldouble-conversion... no`
`Please install double-conversion library `

**OS:** ubuntu 14.04.3 LTS

**Comment by githubdoramon** [comment]
Duplicate #15

**Comment by bertmaher** [comment]
try `xcode-select --install`.  I'm updating the readme today.
