### ISSUE TITLE
with_temp_cleanup:redex-all crashed with exit code -6!

### ISSUE THREAD

**Issue by houser0323** [facebook/redex#633]
Hi:
When i run cmd with below for my example app ,  I got some errors.
### **cmd**
`./redex.py -o /home/qiucheng/qiuchenglib/develop-hub/redex/output.apk /home/qiucheng/qiuchenglib/develop-hub/redex/app-debug.apk`
### **errors**
ERROR:root:expected str, bytes or os.PathLike object, not NoneType
WARNING:root:Could not find an SDK jar: Could not find SDK path, searched Env, Buck
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
  what():  libredex/DexLoader.cpp:49: void validate_dex_header(const dex_header*, size_t, int): assertion `supported' failed.
Bad dex magic dex
039 for support_dex_version 35

/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z23crash_backtrace_handleri+0x46)[0x563b0dac93a6]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7ff6f0080210]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7ff6f008018b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7ff6f005f859]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911)[0x7ff6f0436911]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7ff6f044238c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7)[0x7ff6f04423f7]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9)[0x7ff6f04426a9]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0x470beb)[0x563b0d4b1beb]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xae02e0)[0x563b0db212e0]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z21load_classes_from_dexPKcP11dex_stats_tbi+0x69)[0x563b0db22759]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_ZN5redex36load_classes_from_dexes_and_metadataERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERS0_I8DexStoreSaISB_EER11dex_stats_tRS0_ISF_SaISF_EE+0xc20)[0x563b0da5b660]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xa2241a)[0x563b0da6341a]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z27run_rethrow_first_aggregateRKSt8functionIFvvEE+0x2c)[0x563b0dc591ac]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xa26117)[0x563b0da67117]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(main+0x44c)[0x563b0d5194bc]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7ff6f00610b3]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_start+0x2e)[0x563b0d52d42e]

/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z23crash_backtrace_handleri+0x46)[0x563b0dac93a6]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0x470beb)[0x563b0d4b1beb]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xae02e0)[0x563b0db212e0]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z21load_classes_from_dexPKcP11dex_stats_tbi+0x69)[0x563b0db22759]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_ZN5redex36load_classes_from_dexes_and_metadataERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERS0_I8DexStoreSaISB_EER11dex_stats_tRS0_ISF_SaISF_EE+0xc20)[0x563b0da5b660]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xa2241a)[0x563b0da6341a]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_Z27run_rethrow_first_aggregateRKSt8functionIFvvEE+0x2c)[0x563b0dc591ac]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(+0xa26117)[0x563b0da67117]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(main+0x44c)[0x563b0d5194bc]
/home/qiucheng/qiuchenglib/github/redex-master/redex-all(_start+0x2e)[0x563b0d52d42e]

Traceback (most recent call last):
  File "./redex.py", line 1236, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/home/qiucheng/qiuchenglib/github/redex-master/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "./redex.py", line 1236, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "./redex.py", line 1215, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "./redex.py", line 364, in run_redex_binary
    run()
  File "./redex.py", line 357, in run
    raise RuntimeError(msg)
RuntimeError: redex-all crashed with exit code -6!
 terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
   what():  libredex/DexLoader.cpp:49: void validate_dex_header(const dex_header*, size_t, int): assertion `supported' failed.
 Bad dex magic dex
 039 for support_dex_version 35 You can re-run it under gdb by running /tmp/redex-gdb-0c7w57ay.sh or under lldb by running /tmp/redex-lldb-wfafliiz.sh

Could anyone help me to solve this problem? Thanks very much.

**Comment by houser0323** [comment]
i get it
https://github.com/facebook/redex/issues/592

**Comment by kuganv** [comment]
If this is resolved, please close the task.

**Comment by houser0323** [comment]
> If this is resolved, please close the task.

ok
