### ISSUE TITLE
Flatten packages pass

### ISSUE THREAD

**Issue by pgp** [facebook/redex#642]
Is there any pass which is able to flatten the package hierarchy in an apk file, similarly to what `RenameClassesPassV2` would do, but bringing all the classes to the root level (essentially, the same that ProGuard would do starting by the source code, when the option `-flattenpackagehierarchy` is provided)?

**Comment by NTillmann** [comment]
No. But sounds like it could be a fun pass to write :-)

Can I ask why you'd want that? Some compromise of debugability and size?
