### ISSUE TITLE
Why we didn't consider about use SSA IR to opt the dex ?

### ISSUE THREAD

**Issue by lfkdsk** [facebook/redex#648]
Most of the optimization solutions for programming languages use SSA IR.
I would like to know why we don't support it at the moment.

**Comment by yuxuanchen1997** [comment]
Current passes don't support it. You can write your own analysis (maybe on top of build CFG) to implement the Phi nodes.
It depends on what analysis you would like to perform. Liveness analysis and/or Reaching Definitions should give you the information you would get from an SSA IR.
