### ISSUE TITLE
Inconsistency found in Dex code for Landroidx/media/AudioAttributesCompatParcelizer;

### ISSUE THREAD

**Issue by jklwan** [facebook/redex#654]
WARNING:root:No embedded files, please add manually!
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
        Load classes from dexes completed in 1.7 seconds
        Load library jars completed in 0.8 seconds
        Deobfuscating dex elements completed in 0.5 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 0.1 seconds
        No Optimizations Rules completed in 0.0 seconds
            Mark keep-methods completed in 0.0 seconds
            Computing XML reachability completed in 0.7 seconds
            Computing native reachability completed in 0.4 seconds
            Analyzing reflection completed in 0.1 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 1.3 seconds
    Redex_frontend completed in 4.4 seconds
        API Level Checker completed in 0.1 seconds
WARNING: No inliner config
Evaluating StripDebugInfoPass...
        StripDebugInfoPass (eval) completed in 0.0 seconds
Evaluating InterDexPass...
        InterDexPass (eval) completed in 0.0 seconds
Evaluating RegAllocPass...
        RegAllocPass (eval) completed in 0.0 seconds
Evaluating MakePublicPass...
        MakePublicPass (eval) completed in 0.0 seconds
Running IRTypeChecker...
terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
  what():  D:/Android/git/redex/libredex/PassManager.cpp:277: static boost::optional<std::__cxx11::basic_string<char> > {anonymous}::CheckerConfig::run_verifier(const Scope&, bool, bool, bo
ol, bool, bool): assertion `!exit_on_fail' failed.
Inconsistency found in Dex code for Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V
 Type error in method Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V at instruction
 'IGET_OBJECT v1, Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;' @ 0x1bb6e97a810 for
illegal access to package-private Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;
 from Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V
Code:
[0x1bb6e97a930] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v1
[0x1bb6e97a7b0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v2
[0x1bb6e97a480] OPCODE: CONST v0, 0
[0x1bb6e97a1e0] POSITION: Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V(AudioAttri
butesCompatParcelizer.java:17)
[0x1bb6e97a750] OPCODE: INVOKE_VIRTUAL v2, v0, v0, Landroidx/versionedparcelable/VersionedParcel;.setSerializationFlags:(ZZ)V
[0x1bb6e97ab10] POSITION: Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V(AudioAttri
butesCompatParcelizer.java:18)
[0x1bb6e97a810] OPCODE: IGET_OBJECT v1, Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;
[0x1bb6e97a2a0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x1bb6e97a510] OPCODE: CONST v0, 1
[0x1bb6e97a540] OPCODE: INVOKE_VIRTUAL v2, v1, v0, Landroidx/versionedparcelable/VersionedParcel;.writeVersionedParcelable:(Landroidx/versionedparcelable/VersionedParcelable;I)V
[0x1bb6e97a8d0] OPCODE: RETURN_VOID

(5 more issues!)
Traceback (most recent call last):
  File "redex.py", line 1251, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "D:\Android\git\redex\pyredex\utils.py", line 62, in with_temp_cleanup
    fn()
  File "redex.py", line 1251, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "redex.py", line 1230, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "redex.py", line 372, in run_redex_binary
    run()
  File "redex.py", line 354, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 3!

config file

```json
{
    "redex" : {
        "passes" : [
            "StripDebugInfoPass",
            "InterDexPass",
            "RegAllocPass",
            "MakePublicPass"
        ]
    },
    "StripDebugInfoPass" : {
        "drop_all_dbg_info" : false,
        "drop_local_variables" : true,
        "drop_line_numbers" : false,
        "drop_src_files" : false,
        "use_whitelist" : false,
        "cls_whitelist" : [],
        "method_whitelist" : [],
        "drop_prologue_end" : true,
        "drop_epilogue_begin" : true,
        "drop_all_dbg_info_if_empty" : true
    },
    "InterDexPass" : {
        "minimize_cross_dex_refs": true,
        "minimize_cross_dex_refs_method_ref_weight": 100,
        "minimize_cross_dex_refs_field_ref_weight": 90,
        "minimize_cross_dex_refs_type_ref_weight": 100,
        "minimize_cross_dex_refs_string_ref_weight": 90
    },
    "RegAllocPass" : {
        "live_range_splitting": false
    }
}

```

![image](https://user-images.githubusercontent.com/8316090/143201411-d8262427-029f-4307-8034-88376b96ab64.png)

**Comment by thezhangwei** [comment]
Hi, do you need help understanding the error reported by type checker or are you implying the access validation is done incorrect? Thanks,

**Comment by jklwan** [comment]
I add this section，redex run success
```json
"ir_type_checker": {
    "run_on_input": false
}
```
thanks
