### ISSUE TITLE
Imprecise Whole program callgraph

### ISSUE THREAD

**Issue by ufarooq** [facebook/redex#656]
Hi,

Redex provides several passes that rely on callgraph such as RemoveUnreachablePass, however, I noticed that the current callgraph does not model the Android framework and ends with missing out lifecycle callbacks and event handlers as well. Please note that these callbacks are usually sources for many other calls. I think, there is a need to improve callgraph based on techniques described in research papers [1,2]. 

Currently, is there any work-in-progress in this direction? If not, what would be a good starting point to achieve this? 

Bests,
Umar

[1] Arzt, Steven, et al. "Flowdroid: Precise context, flow, field, object-sensitive and lifecycle-aware taint analysis for android apps." ACM SIGPLAN Notices 49.6 (2014): 259-269.
[2] Blackshear, Sam, Alexandra Gendreau, and Bor-Yuh Evan Chang. "Droidel: A general approach to Android framework modeling." Proceedings of the 4th ACM SIGPLAN International Workshop on State of the Art in Program Analysis. 2015.

**Comment by agampe** [comment]
Thank you for your question. We welcome contributions to Redex!

There is no WIP in this direction.

As can be seen, Redex currently follows the style established by Proguard, manually marking entrypoints to the app as something that is a root. *(There is some helper code that can scan the manifest and resources for names, as well as native libraries for strings that look like class names.)* In general, Android framework calls are singular enough that things like IPCP do not matter (much), or the optimizations are written such that roots are not optimized. On the other hand, there are sources like native that neither models at all, and that are in our experience a more severe source of code flow.

Both Flowdroid and Droidel are limited to the Android release they have established their "model" over. That is a nontrivial limitation. The Redex team does not currently have the resources to update this every year or more often.

As a starting point, you may want to check how the SDK is currently read and integrated. Replacing it with Droidel's "model" may be the simplest approach.
