### ISSUE TITLE
Bad dex magic dex 039 and support_dex_version is 35

### ISSUE THREAD

**Issue by 123zhangmiao** [facebook/redex#660]
Do you know how to change dex magic version by changing android sdk version.

**Comment by yuxuanchen1997** [comment]
Redex currently doesn't support dex039. You need to change the android SDK version in the manifest. See https://developer.android.com/guide/topics/manifest/uses-sdk-element

**Comment by 123zhangmiao** [comment]
@yuxuanchen1997  Thanks for your answer very much.Can you tell me the relationship between dex magic version and  android sdk version?Which one should I change of minsdkversion、targetsdkversion、maxsdkversion.How to make dex magic 35 rather than 39.

**Comment by yuxuanchen1997** [comment]
What's your current minSdkVersion? Turning that down should make dex version older. Can you try API level 21 (Android 5+)?

**Comment by 123zhangmiao** [comment]
My current minSdkVersion is 17 and current targetSdkVersion is 28.When I change targetSdkVersion to 24,error:Bad dex magic dex 037 and support_dex_version is 35 will be show.Can you please tell me the relationship between  minSdkVersion、targetSdkVersion and magic dex?

**Comment by yuxuanchen1997** [comment]
dex037 is still too new for Redex. Can you use API level 21?

**Comment by 123zhangmiao** [comment]
Do you mean redex  not support above android 5.0?or Redex supports building apps for all android versions?

**Comment by yuxuanchen1997** [comment]
Newer Android versions will have backwards compatibility for apps that work on Android 5.0.

**Comment by 123zhangmiao** [comment]
If my targetSdkVersion is above android 5.0,how to resolve the problem such as'Bad dex magic dex 037 and support_dex_version is 35'.

**Comment by yuxuanchen1997** [comment]
How are you building your apps? Is it with gradle or some other build systems? If you invoke `d8` on your own there should be a `--min-api` flag.

**Comment by yuxuanchen1997** [comment]
Sorry I think I confused you. When I said the manifest, I really should say gradle (or other build system) config files.

**Comment by 123zhangmiao** [comment]
Hi,
   My app builds with gradle.Can you tell me how to config when my targetsdkversion is above 21?

**Comment by yuxuanchen1997** [comment]
I don't understand why you get dex037 or 039 with gradle when minSdkVersion is 17. There has to be some mis-setup should Gradle be in control of `d8` invocation.

**Comment by 123zhangmiao** [comment]
Hi,What cammand or config should me do to get dex35 with gradle when minSdkVersion is 17?And what's the meaning of mis-setup.Can you explain this in detail?Thanks a lot.

**Comment by yuxuanchen1997** [comment]
The parameter for `--min-api` is Android API level, not dex version. You probably should pass `--min-api 17` to d8.

**Comment by Xinmeng322** [comment]
I met this problem, please tell me , how to solve this at  last , 3Q

**Comment by yuxuanchen1997** [comment]
> I met this problem, please tell me , how to solve this at last , 3Q

If you are using Gradle to build your app, lower your minSdkVersion. If you are invoking D8 from another build system, pass `--min-api` flag.

**Comment by 123zhangmiao** [comment]
> I met this problem, please tell me , how to solve this at last , 3Q



> I met this problem, please tell me , how to solve this at last , 3Q

Have you resolve this problem?

**Comment by yuxuanchen1997** [comment]
@123zhangmiao If you are using Gradle to build your app, lower your `minSdkVersion`. If you are invoking D8 from another build system, pass `--min-api` flag.

**Comment by 123zhangmiao** [comment]
I use Gradle to build my app.My gradle config is as follows.
                 compileSdkVersion  : 30
               , buildToolsVersion: "27.0.3"
               , minSdkVersion    : 17
               , targetSdkVersion : 29
How to resolve the the problem such as'Bad dex magic dex 039(or 037).
