### ISSUE TITLE
Bad dex magic dex 039 and support_dex_version is 35

### ISSUE THREAD

**Issue by 123zhangmiao** [facebook/redex#667]
I use Gradle to build my app.My gradle config is as follows.
compileSdkVersion : 30
, buildToolsVersion: "27.0.3"
, minSdkVersion : 17
, targetSdkVersion : 29
How to resolve the the problem such as'Bad dex magic dex 039(or 037).

**Comment by agampe** [comment]
You may want to ask that question on the Gradle forums. The Redex team does not use Gradle.

(Also please do not double-post, this was discussed in #660)

**Comment by 123zhangmiao** [comment]
https://github.com/facebook/redex/issues/592#issuecomment-772063564
Dex 39 is not supported?
