### ISSUE TITLE
redex-all crashed with exit code 1!

### ISSUE THREAD

**Issue by zhangxiaojin770** [facebook/redex#673]
**I encountered this problem when using instructions, but I don't know how to deal with it，The following is the relevant error message**

user@userdeMacBook-Pro redex -c /Users/user/redex/config/default.config  -o /Users/user/Downloads/LTest_redex.apk /Users/user/Downloads/LTest.apk 
ERROR:root:Expecting value: line 6 column 32 (char 108)
WARNING:root:Could not find an SDK jar: Could not find SDK path, searched Env, Buck
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
        Load classes from dexes completed in 2.6 seconds
        Deobfuscating dex elements completed in 0.6 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 0.1 seconds
        No Optimizations Rules completed in 0.0 seconds
            Mark keep-methods completed in 0.1 seconds
            Computing XML reachability completed in 0.1 seconds
            Computing native reachability completed in 0.3 seconds
            Analyzing reflection completed in 0.2 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 0.8 seconds
    Redex_frontend completed in 4.2 seconds
        API Level Checker completed in 0.2 seconds
Evaluating ReBindRefsPass...
        ReBindRefsPass (eval) completed in 0.0 seconds
Evaluating BridgePass...
        BridgePass (eval) completed in 0.0 seconds
Evaluating ResultPropagationPass...
        ResultPropagationPass (eval) completed in 0.0 seconds
Evaluating FinalInlinePassV2...
        FinalInlinePassV2 (eval) completed in 0.0 seconds
Evaluating DelSuperPass...
        DelSuperPass (eval) completed in 0.0 seconds
Evaluating CommonSubexpressionEliminationPass...
        CommonSubexpressionEliminationPass (eval) completed in 0.0 seconds
Evaluating MethodInlinePass...
        MethodInlinePass (eval) completed in 0.0 seconds
Evaluating PeepholePass...
        PeepholePass (eval) completed in 0.0 seconds
Evaluating ConstantPropagationPass...
        ConstantPropagationPass (eval) completed in 0.0 seconds
Evaluating LocalDcePass...
        LocalDcePass (eval) completed in 0.0 seconds
Evaluating RemoveUnreachablePass...
        RemoveUnreachablePass (eval) completed in 0.0 seconds
Evaluating RemoveGotosPass...
        RemoveGotosPass (eval) completed in 0.0 seconds
Evaluating DedupBlocksPass...
        DedupBlocksPass (eval) completed in 0.0 seconds
Evaluating UpCodeMotionPass...
        UpCodeMotionPass (eval) completed in 0.0 seconds
Evaluating SingleImplPass...
        SingleImplPass (eval) completed in 0.0 seconds
Evaluating ReorderInterfacesDeclPass...
        ReorderInterfacesDeclPass (eval) completed in 0.0 seconds
Evaluating RemoveEmptyClassesPass...
        RemoveEmptyClassesPass (eval) completed in 0.0 seconds
Evaluating ShortenSrcStringsPass...
        ShortenSrcStringsPass (eval) completed in 0.0 seconds
Evaluating CommonSubexpressionEliminationPass...
        CommonSubexpressionEliminationPass (eval) completed in 0.0 seconds
Evaluating RegAllocPass...
        RegAllocPass (eval) completed in 0.0 seconds
Evaluating CopyPropagationPass...
        CopyPropagationPass (eval) completed in 0.0 seconds
Evaluating LocalDcePass...
        LocalDcePass (eval) completed in 0.0 seconds
Evaluating ReduceGotosPass...
        ReduceGotosPass (eval) completed in 0.0 seconds
Running IRTypeChecker...
        IRTypeChecker completed in 15.1 seconds
Inconsistency found in Dex code for Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V
 Type error in method Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V at instruction 'IGET_OBJECT v1, Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;' @ 0x7ff5138f1d50 for 
illegal access to package-private Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;
 from Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V
Code:
[0x7ff5138f1780] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v1
[0x7ff5138f17a0] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v2
[0x7ff5138f1cd0] OPCODE: CONST v0, 0
[0x7ff517f7fa20] POSITION: Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V(AudioAttributesCompatParcelizer.java:17)
[0x7ff517f80080] OPCODE: INVOKE_VIRTUAL v2, v0, v0, Landroidx/versionedparcelable/VersionedParcel;.setSerializationFlags:(ZZ)V
[0x7ff5138f2010] POSITION: Landroidx/media/AudioAttributesCompatParcelizer;.write:(Landroid/support/v4/media/AudioAttributesCompat;Landroidx/versionedparcelable/VersionedParcel;)V(AudioAttributesCompatParcelizer.java:18)
[0x7ff5138f1d50] OPCODE: IGET_OBJECT v1, Landroid/support/v4/media/AudioAttributesCompat;.mImpl:Landroid/support/v4/media/AudioAttributesImpl;
[0x7ff5138f1f10] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7ff5138f1d70] OPCODE: CONST v0, 1
[0x7ff5138f1d90] OPCODE: INVOKE_VIRTUAL v2, v1, v0, Landroidx/versionedparcelable/VersionedParcel;.writeVersionedParcelable:(Landroidx/versionedparcelable/VersionedParcelable;I)V
[0x7ff517f800a0] OPCODE: RETURN_VOID 

(5 more issues!)
 If you are confident that this does not matter (e.g., because you are using MakePublicPass), turn off accessibility checking on input with `-J ir_type_checker.run_on_input_ignore_access=true`.
 You may turn off all input checking with `-J ir_type_checker.run_on_input=false`.
Traceback (most recent call last):
  File "/tmp/redex.drOAdR/redex.py", line 1262, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/private/tmp/redex.drOAdR/pyredex/utils.py", line 62, in with_temp_cleanup
    fn()
  File "/tmp/redex.drOAdR/redex.py", line 1262, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/tmp/redex.drOAdR/redex.py", line 1241, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/tmp/redex.drOAdR/redex.py", line 374, in run_redex_binary
    run()
  File "/tmp/redex.drOAdR/redex.py", line 367, in run
    raise RuntimeError(msg)
RuntimeError: redex-all crashed with exit code 1! You can re-run it under gdb by running /tmp/redex.drOAdR/redex-gdb-074_h8az.sh or under lldb by running /tmp/redex.drOAdR/redex-lldb-nof9jvd7.sh

**Comment by agampe** [comment]
Are you using another optimizer before Redex? E.g., `r8` or something?

The code sequence here is illegal, it violates Java restrictions. This check is on the code flowing *into* Redex - whatever your build pipeline creates without Redex.

To work around the issue (*not recommended*, please fix your build pipeline), you can add `MakePublicPass` as the very first pass in your pass list, and turn of that part of input checking with the mentioned command line switch
```
-J ir_type_checker.run_on_input_ignore_access=true
```

**Comment by zhangxiaojin770** [comment]
I just used jekins to pack the release package

**Comment by zhangxiaojin770** [comment]
This problem also occurs when I use Android studio build to package.

**Comment by zhangxiaojin770** [comment]
**The relevant configurations are as follows:**
 zipAlignEnabled false
 shrinkResources false
 minifyEnabled false
 debuggable false

> This problem also occurs when I use Android studio build to package.

**Comment by agampe** [comment]
It's possible your aars are broken or something. This is an issue in your build pipeline that we cannot diagnose.

Use the switch mentioned above and hope for the best.
