### ISSUE TITLE
RuntimeError: redex-all crashed with exit code 3!

### ISSUE THREAD

**Issue by androidsihai1** [facebook/redex#678]
python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/keystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/stripdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Administrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/build-tools/29.0.3

Traceback (most recent call last):
  File "redex.py", line 1262, in <module>
    with_temp_cleanup(lambda: run_redex(args), arg
  File "C:\msys64\home\pengsihai\redex\pyredex\uti
    fn()
  File "redex.py", line 1262, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), arg
  File "redex.py", line 1241, in run_redex
    run_redex_binary(state, exception_formatter, o
  File "redex.py", line 374, in run_redex_binary
    run()
  File "redex.py", line 356, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 3!

**Comment by agampe** [comment]
This seems to be missing the actual redex crash. Can you give complete logs?

**Comment by androidsihai1** [comment]
C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/keystore/debug
.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/stripdebuginfo.c
onfig -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Administrator/Down
loads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/o
utputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/build-tools/2
9.0.3
usage: redex.py [-h] [-o [OUT]] [-j JARPATHS] [--redex-binary [REDEX_BINARY]] [-c CONFIG] [--sign] [-s [KEYSTORE]]
                [-a [KEYALIAS]] [-p [KEYPASS]] [-u] [--unpack-dest UNPACK_DEST] [-w [WARN]] [-d] [--dev]
                [-m [PROGUARD_MAP]] [--printseeds [PRINTSEEDS]] [--used-js-assets USED_JS_ASSETS]
                [-P PROGUARD_CONFIGS] [-k [KEEP]] [-A [ARCH]] [-S PASSTHRU] [-J PASSTHRU_JSON] [--lldb] [--gdb]
                [--ignore-zipalign] [--verify-none-mode] [--enable-instrument-pass] [--is-art-build] [--redacted]
                [--disable-dex-hasher] [--page-align-libs] [--side-effect-summaries SIDE_EFFECT_SUMMARIES]
                [--escape-summaries ESCAPE_SUMMARIES] [--stop-pass STOP_PASS] [--output-ir OUTPUT_IR]
                [--debug-source-root [DEBUG_SOURCE_ROOT]] [--always-clean-up] [--cmd-prefix CMD_PREFIX]
                [--reset-zip-timestamps] [-q] [--android-sdk-path ANDROID_SDK_PATH] [--suppress-android-jar-check]
                [--log-level LOG_LEVEL] [--packed-profiles PACKED_PROFILES] [--jni-summary JNI_SUMMARY]
                [--outdir OUTDIR] [--dex-files DEX_FILES [DEX_FILES ...]]
                [input_apk]
redex.py: error: unrecognized arguments: redex.py C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/ou
tputs/apk/debug/ReDexSample-debug.apk

C:\msys64\home\pengsihai\redex>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/keystore/debug
.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/stripdebuginfo.c
onfig -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Administrator/Down
loads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/o
utputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/build-tools/2
9.0.3
usage: redex.py [-h] [-o [OUT]] [-j JARPATHS] [--redex-binary [REDEX_BINARY]] [-c CONFIG] [--sign] [-s [KEYSTORE]]
                [-a [KEYALIAS]] [-p [KEYPASS]] [-u] [--unpack-dest UNPACK_DEST] [-w [WARN]] [-d] [--dev]
                [-m [PROGUARD_MAP]] [--printseeds [PRINTSEEDS]] [--used-js-assets USED_JS_ASSETS]
                [-P PROGUARD_CONFIGS] [-k [KEEP]] [-A [ARCH]] [-S PASSTHRU] [-J PASSTHRU_JSON] [--lldb] [--gdb]
                [--ignore-zipalign] [--verify-none-mode] [--enable-instrument-pass] [--is-art-build] [--redacted]
                [--disable-dex-hasher] [--page-align-libs] [--side-effect-summaries SIDE_EFFECT_SUMMARIES]
                [--escape-summaries ESCAPE_SUMMARIES] [--stop-pass STOP_PASS] [--output-ir OUTPUT_IR]
                [--debug-source-root [DEBUG_SOURCE_ROOT]] [--always-clean-up] [--cmd-prefix CMD_PREFIX]
                [--reset-zip-timestamps] [-q] [--android-sdk-path ANDROID_SDK_PATH] [--suppress-android-jar-check]
                [--log-level LOG_LEVEL] [--packed-profiles PACKED_PROFILES] [--jni-summary JNI_SUMMARY]
                [--outdir OUTDIR] [--dex-files DEX_FILES [DEX_FILES ...]]
                [input_apk]
redex.py: error: unrecognized arguments: redex.py C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/ou
tputs/apk/debug/ReDexSample-debug.apk

C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3
WARNING:root:No embedded files, please add manually!
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
Unimplemented command (skipping): -ignorewarnings at line 27
        Parsed ProGuard config file completed in 0.0 seconds
        Load classes from dexes completed in 0.3 seconds
        Load library jars completed in 0.4 seconds
        Deobfuscating dex elements completed in 0.0 seconds
            Process keep for whyareyoukeeping completed in 0.0 seconds
            Process keep for classes and members completed in 0.0 seconds
            Process keep for assumenosideeffects completed in 0.0 seconds
        Processing proguard rules completed in 0.0 seconds
        No Optimizations Rules completed in 0.0 seconds
            Mark keep-methods completed in 0.0 seconds
            Computing XML reachability completed in 0.0 seconds
            Computing native reachability completed in 0.0 seconds
            Analyzing reflection completed in 0.0 seconds
            Analyzing Serializable completed in 0.0 seconds
            Initializing for json serde completed in 0.0 seconds
        Initializing reachable classes completed in 0.1 seconds
    Redex_frontend completed in 0.8 seconds
terminate called after throwing an instance of 'Json::LogicError'
  what():  Value is not convertible to bool.
Traceback (most recent call last):
  File "redex.py", line 1262, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "C:\msys64\home\pengsihai\redex\pyredex\utils.py", line 62, in with_temp_cleanup
    fn()
  File "redex.py", line 1262, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "redex.py", line 1241, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "redex.py", line 374, in run_redex_binary
    run()
  File "redex.py", line 356, in run
    raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 3!

**Comment by androidsihai1** [comment]
> This seems to be missing the actual redex crash. Can you give complete logs?
C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/keystore/debug
.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/stripdebuginfo.c
onfig -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Administrator/Down
loads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/o
utputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/build-tools/2
9.0.3
usage: redex.py [-h] [-o [OUT]] [-j JARPATHS] [--redex-binary [REDEX_BINARY]] [-c CONFIG] [--sign] [-s [KEYSTORE]]
[-a [KEYALIAS]] [-p [KEYPASS]] [-u] [--unpack-dest UNPACK_DEST] [-w [WARN]] [-d] [--dev]
[-m [PROGUARD_MAP]] [--printseeds [PRINTSEEDS]] [--used-js-assets USED_JS_ASSETS]
[-P PROGUARD_CONFIGS] [-k [KEEP]] [-A [ARCH]] [-S PASSTHRU] [-J PASSTHRU_JSON] [--lldb] [--gdb]
[--ignore-zipalign] [--verify-none-mode] [--enable-instrument-pass] [--is-art-build] [--redacted]
[--disable-dex-hasher] [--page-align-libs] [--side-effect-summaries SIDE_EFFECT_SUMMARIES]
[--escape-summaries ESCAPE_SUMMARIES] [--stop-pass STOP_PASS] [--output-ir OUTPUT_IR]
[--debug-source-root [DEBUG_SOURCE_ROOT]] [--always-clean-up] [--cmd-prefix CMD_PREFIX]
[--reset-zip-timestamps] [-q] [--android-sdk-path ANDROID_SDK_PATH] [--suppress-android-jar-check]
[--log-level LOG_LEVEL] [--packed-profiles PACKED_PROFILES] [--jni-summary JNI_SUMMARY]
[--outdir OUTDIR] [--dex-files DEX_FILES [DEX_FILES ...]]
[input_apk]
redex.py: error: unrecognized arguments: redex.py C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/ou
tputs/apk/debug/ReDexSample-debug.apk

C:\msys64\home\pengsihai\redex>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

exit()

C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/keystore/debug
.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/stripdebuginfo.c
onfig -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Administrator/Down
loads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/o
utputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/build-tools/2
9.0.3
usage: redex.py [-h] [-o [OUT]] [-j JARPATHS] [--redex-binary [REDEX_BINARY]] [-c CONFIG] [--sign] [-s [KEYSTORE]]
[-a [KEYALIAS]] [-p [KEYPASS]] [-u] [--unpack-dest UNPACK_DEST] [-w [WARN]] [-d] [--dev]
[-m [PROGUARD_MAP]] [--printseeds [PRINTSEEDS]] [--used-js-assets USED_JS_ASSETS]
[-P PROGUARD_CONFIGS] [-k [KEEP]] [-A [ARCH]] [-S PASSTHRU] [-J PASSTHRU_JSON] [--lldb] [--gdb]
[--ignore-zipalign] [--verify-none-mode] [--enable-instrument-pass] [--is-art-build] [--redacted]
[--disable-dex-hasher] [--page-align-libs] [--side-effect-summaries SIDE_EFFECT_SUMMARIES]
[--escape-summaries ESCAPE_SUMMARIES] [--stop-pass STOP_PASS] [--output-ir OUTPUT_IR]
[--debug-source-root [DEBUG_SOURCE_ROOT]] [--always-clean-up] [--cmd-prefix CMD_PREFIX]
[--reset-zip-timestamps] [-q] [--android-sdk-path ANDROID_SDK_PATH] [--suppress-android-jar-check]
[--log-level LOG_LEVEL] [--packed-profiles PACKED_PROFILES] [--jni-summary JNI_SUMMARY]
[--outdir OUTDIR] [--dex-files DEX_FILES [DEX_FILES ...]]
[input_apk]
redex.py: error: unrecognized arguments: redex.py C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/build/ou
tputs/apk/debug/ReDexSample-debug.apk

C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k
eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str
ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin
istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS
ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/
build-tools/29.0.3
WARNING:root:No embedded files, please add manually!
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
Unimplemented command (skipping): -ignorewarnings at line 27
Parsed ProGuard config file completed in 0.0 seconds
Load classes from dexes completed in 0.3 seconds
Load library jars completed in 0.4 seconds
Deobfuscating dex elements completed in 0.0 seconds
Process keep for whyareyoukeeping completed in 0.0 seconds
Process keep for classes and members completed in 0.0 seconds
Process keep for assumenosideeffects completed in 0.0 seconds
Processing proguard rules completed in 0.0 seconds
No Optimizations Rules completed in 0.0 seconds
Mark keep-methods completed in 0.0 seconds
Computing XML reachability completed in 0.0 seconds
Computing native reachability completed in 0.0 seconds
Analyzing reflection completed in 0.0 seconds
Analyzing Serializable completed in 0.0 seconds
Initializing for json serde completed in 0.0 seconds
Initializing reachable classes completed in 0.1 seconds
Redex_frontend completed in 0.8 seconds
terminate called after throwing an instance of 'Json::LogicError'
what(): Value is not convertible to bool.
Traceback (most recent call last):
File "redex.py", line 1262, in
with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
File "C:\msys64\home\pengsihai\redex\pyredex\utils.py", line 62, in with_temp_cleanup
fn()
File "redex.py", line 1262, in
with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
File "redex.py", line 1241, in run_redex
run_redex_binary(state, exception_formatter, output_line_handler)
File "redex.py", line 374, in run_redex_binary
run()
File "redex.py", line 356, in run
raise RuntimeError(default_error_msg)
RuntimeError: redex-all crashed with exit code 3!

**Comment by NTillmann** [comment]
closing due to age

**Comment by Coniferousforest** [comment]
> > This seems to be missing the actual redex crash. Can you give complete logs?
> 
> C:\msys64\home\pengsihai\redex>python redex.py --sign -s C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/k eystore/debug.keystore -a androiddebugkey -p android -c C:/Users/Administrator/Downloads/Chapter22-master/redex-test/str ipdebuginfo.config -P C:/Users/Administrator/Downloads/Chapter22-master/ReDexSample/proguard-rules.pro -o C:/Users/Admin istrator/Downloads/Chapter22-master/redex-test/strip_output.apk C:/Users/Administrator/Downloads/Chapter22-master/ReDexS ample/build/outputs/apk/debug/ReDexSample-debug.apk --android-sdk-path C:/Users/Administrator/AppData/Local/Android/Sdk/ build-tools/29.0.3 WARNING:root:No embedded files, please add manually! Trace settings: TRACEFILE= SHOW_TIMESTAMPS= SHOW_TRACEMODULE= TRACE_METHOD_FILTER= TRACE_CLASS_FILE= TRACE_CLASS_NAME= Unimplemented command (skipping): -ignorewarnings at line 27 Parsed ProGuard config file completed in 0.0 seconds Load classes from dexes completed in 0.3 seconds Load library jars completed in 0.4 seconds Deobfuscating dex elements completed in 0.1 seconds Process keep for whyareyoukeeping completed in 0.0 seconds Process keep for classes and members completed in 0.0 seconds Process keep for assumenosideeffects completed in 0.0 seconds Processing proguard rules completed in 0.0 seconds No Optimizations Rules completed in 0.0 seconds Mark keep-methods completed in 0.0 seconds Computing XML reachability completed in 0.0 seconds Computing native reachability completed in 0.0 seconds Analyzing reflection completed in 0.0 seconds Analyzing Serializable completed in 0.0 seconds Initializing for json serde completed in 0.0 seconds Initializing reachable classes completed in 0.1 seconds Redex_frontend completed in 0.9 seconds terminate called after throwing an instance of 'Json::LogicError' what(): Value is not convertible to bool. Traceback (most recent call last): File "redex.py", line 1262, in with_temp_cleanup(lambda: run_redex(args), args.always_clean_up) File "C:\msys64\home\pengsihai\redex\pyredex\utils.py", line 62, in with_temp_cleanup fn() File "redex.py", line 1262, in with_temp_cleanup(lambda: run_redex(args), args.always_clean_up) File "redex.py", line 1241, in run_redex run_redex_binary(state, exception_formatter, output_line_handler) File "redex.py", line 374, in run_redex_binary run() File "redex.py", line 356, in run raise RuntimeError(default_error_msg) RuntimeError: redex-all crashed with exit code 3!
> 
> C:\msys64\home\pengsihai\redex>

Hi, 请问你解决了这个问题吗?
