### ISSUE TITLE
Unexpected token error when supplying -P Proguard config 

### ISSUE THREAD

**Issue by polycoder** [facebook/redex#68]
When trying to supply a proguard config file I am receiving an almost immediate error during the redex-all step. The output is as follows:

```
redex -P "../app/config/proguard/proguard-release.cfg" 5.1.0.849.apk
Unexpected token - on line 1
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /var/folders/wq/wy9t8kns70sc8kvdhm5tqbvc0000gn/T/tmpwjzgwh9g.redex_extracted_apk --outdir /var/folders/wq/wy9t8kns70sc8kvdhm5tqbvc0000gn/T/tmpzsuhi0v6.redex_dexen --proguard-config ../app/config/proguard/proguard-release.cfg /var/folders/wq/wy9t8kns70sc8kvdhm5tqbvc0000gn/T/tmpzsuhi0v6.redex_dexen/dex0/classes.dex /var/folders/wq/wy9t8kns70sc8kvdhm5tqbvc0000gn/T/tmpzsuhi0v6.redex_dexen/dex1/classes2.dex' returned non-zero exit status 1
```

It seems to be complaining about an unexpected token on line 1. If this means line 1 of the proguard file, then the line for reference is:

```
-include proguard-generic-base.cfg
```

Perhaps a limited subset of proguard is supported...

Also, I'm wondering if there is any benefit to supplying the proguard file. I'd like to understand how is it used in the processing of the dex. Questions around usage of `-P` I can't seem to find answers to include:

* Should I supply the proguard mapping for an apk that is NOT proguarded. Will redex use the file to peform optimizations in this case that I describe in the proguard config
* Should I supply the proguard mapping for an apk that is proguarded. How does it help redex.

**Comment by polycoder** [comment]
Similar to #24 and #32

**Comment by bertmaher** [comment]
Parsing the proguard config is sort of an experimental feature.  I would say there's no benefit to it at this time.

**Comment by satnam6502** [comment]
Hello @polycoder and apologies for coming late to the party. The ProGuard parsing capabilities of Redex are very limited and designed for a very specific scenario (and I am about to totally change the lexer and parser in the coming days). 

Do you think you could have solved your problem by running ProGuard on your existing configuration files with the `-printconfiguraiton configuration.txt` option and then given the generated `configuration.txt` file to Redex with the -P flag? That will produce a flat merged total configuration for Redex which does not have any `-include` directives and it will include other information (like library jars) which will help Redex do a better job.

Perhaps you could try that and let me know how you get on?

**Comment by satnam6502** [comment]
Another option is to used the `-printseeds` flag and the provide that output to the seeds flag for Redex. I shall prepare some documentation about these two approaches with a small sample app.
