### ISSUE TITLE
opt/bridge/Bridge.cpp:61 DexMethod*{anonymous}::match_pattern(DexMethod*):assertion 'it==end' failed

### ISSUE THREAD

**Issue by chenlongkk** [facebook/redex#69]
i got a problem when i try redex like this 

`redex a.apk -o b.apk`

This is the outputs:

opt/bridge/Bridge.cpp:61: DexMethod* {anonymous}::match_pattern(DexMethod*): assertion `it == end' failed.
In public final bridge com.facebook.common.references.b.a(Ljava/lang/Object;)V
redex-all[0x415257]
/lib64/libc.so.6(+0x35670)[0x7f7dda8b9670]
/lib64/libc.so.6(gsignal+0x37)[0x7f7dda8b95f7]
/lib64/libc.so.6(abort+0x148)[0x7f7dda8bace8]
redex-all[0x41523a]
redex-all[0x4a07c8]
redex-all[0x440b25]
redex-all[0x40afd0]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f7dda8a5b15]
redex-all[0x40c0e9]
Traceback (most recent call last):
  File "/usr/local/bin/redex", line 779, in <module>
    run_redex(args)
  File "/usr/local/bin/redex", line 735, in run_redex
    dexen)
  File "/usr/local/bin/redex", line 110, in run_pass
    subprocess.check_call(args, shell=True)
  File "/usr/local/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'redex-all --apkdir /tmp/tmpu3o1k6o1.redex_extracted_apk --outdir /tmp/tmpmyofhr4u.redex_dexen /tmp/tmpmyofhr4u.redex_dexen/dex0/classes.dex' returned non-zero exit status -6

**Comment by Gavin1989** [comment]
same problem

**Comment by bertmaher** [comment]
Thanks for reporting, I'll take a look when I get a chance.

**Comment by bertmaher** [comment]
In the meantime you can unblock yourself by creating a config file as specified in docs/Config.md, and removing BridgePass.
