### ISSUE TITLE
ObjectEscapeAnalysisPass adds too many method refs

### ISSUE THREAD

**Issue by ufarooq** [facebook/redex#693]
Hi There,

When I enable ObjectEscapeAnalysisPass, it tries to add too many methods to a dex file. Please note that I have enabled InterDexPass and redex works well if ObjectEscapeAnalysisPass is not enabled in the configuration. 

The error appears as follows when I run with the option ``-J ir_type_checker.check_num_of_refs=true``.

```
dex classes.dex: method refs 65535, filed refs 26612, type refs 16063
dex classes2.dex: method refs 65543, filed refs 33349, type refs 17510

libc++abi: terminating with uncaught exception of type boost::exception_detail::error_info_injector<RedexException>: libredex/PassManager.cpp:197: auto (anonymous namespace)::CheckerConfig::ref_validation(const DexStoresVector &, const std::string &)::(anonymous class)::operator()(const DexClasses &, const DexStore &, size_t) const: assertion `total_method_refs.size() <= limit' failed.

ObjectEscapeAnalysisPass adds too many method refs 
```
Any possible work around it?

Bests,
Umar

**Comment by NTillmann** [comment]
The ObjectEscapeAnalysisPass can only run before the InterDexPass. (And you need the InterDexPass.) Also, you probably want to run the RemoveUnreachablePass right after the ObjectEscapeAnalysisPass, as that pass (intentionally) leaves behind some newly unreachable code.

**Comment by ufarooq** [comment]
Thanks, @NTillmann. I am able to run successfully when I use ObjectEscapeAnalysisPass with LocalDcePass. Still works when InterDexPass is before ObjectEscapeAnalysisPass. Closing this issue for now.

**Comment by NTillmann** [comment]
You really don't want to run ObjectEscapeAnalysisPass after the (last) InterDexPass. As it's written right now, ObjectEscapeAnalysisPass does not respect dex boundaries. Even if it works on some input, it will not work for all inputs.
