### ISSUE TITLE
Please install boost >= 1.71

### ISSUE THREAD

**Issue by android-jian** [facebook/redex#697]
my boost version is 1.78.0, when I execute "autoreconf -ivf && ./configure && make -j4", it notice me "configure: error: Please install boost >= 1.71 (including filesystem)", Can you help me?
<img width="1058" alt="WeChat81ce50654318898998419ca90e3b2278" src="https://user-images.githubusercontent.com/20474291/172820419-7f4a2059-4441-472b-bbc6-d685cc9c6622.png">

<img width="1128" alt="WeChat8422071410e9bf922562d4f58354f3e1" src="https://user-images.githubusercontent.com/20474291/172820508-6afe4265-ce16-4775-b515-084779217dda.png">

**Comment by jianjunhuang** [comment]
You can try this solution，it worked for me：
https://github.com/facebook/redex/issues/694#issuecomment-1110041679

**Comment by NTillmann** [comment]
The problem seems to have been solved.
