### ISSUE TITLE
README should require brew install openssl

### ISSUE THREAD

**Issue by benjamin-bader** [facebook/redex#7]
On OS X El Capitan, following the steps listed in README.md, I get the following error:

```
./../folly/io/async/ssl/OpenSSLPtrTypes.h:20:10: fatal error: 'openssl/evp.h' file not found
```

I have Homebrew's OpenSSL package installed, at version 1.0.2g.  I have only ever dabbled in C/C++, so am not sure how to proceed; apologies if there is an obvious fix.

**Comment by benjamin-bader** [comment]
Turns out that, using Homebrew openssl, one must `brew link openssl --force` in order for headers to be seen by make.

**Comment by bertmaher** [comment]
Thanks for the PR!  Apparently folly sprouted an openssl dependence and I didn't notice since it was already on my machine :-).

**Comment by benjamin-bader** [comment]
You're welcome!  I was surprised, I thought I already had those headers in place, too.

I guess a "better" solution than `brew link` might be to provide some path to `./configure`, but it's beyond my experience to say positively.  What do you think is the right way to handle the openssl dependency on OS X?

**Comment by bertmaher** [comment]
You're probably right that a ./configure parameter would be ideal here.  I'm inclined to simply recommend brew link, just for simplicity's sake.  But if someone wanted to figure out how to make configure work, I'd be happy!

**Comment by holoduke** [comment]
After  brew link openssl --force i get another error

./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);

**Comment by cesarferreira** [comment]
Yep, same as @holoduke here
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/local/include -std=gnu++0x -g -O2 -MT portability/Malloc.lo -MD -MP -MF portability/.deps/Malloc.Tpo -c portability/Malloc.cpp  -fno-common -DPIC -o portability/.libs/Malloc.o
In file included from portability/Malloc.cpp:17:
./../folly/portability/Malloc.h:27:12: error: unknown type name 'size_t'
extern "C" size_t malloc_usable_size(void* ptr);
           ^
1 error generated.
make[4]: *** [portability/Malloc.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by sealskej** [comment]
@cesarferreira the solution is mentioned in #8
