### ISSUE TITLE
JarLoader.cpp error when processing CONSTANT_MethodHandle_info

### ISSUE THREAD

**Issue by fengruisd** [facebook/redex#700]
JarLoader.parse_cp_entry read `u2` when parsing CONSTANT_MethodHandle_info, but it should be `u1` according https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.4.8. this will cause redex crash.

```
CONSTANT_MethodHandle_info {
    u1 tag;
    u1 reference_kind;  // it's u1
    u2 reference_index;
}
```

```
static bool parse_cp_entry(uint8_t*& buffer, cp_entry& cpe) {
  switch (cpe.tag) {
  ...
  case CP_CONST_METHHANDLE:
    cpe.s0 = read16(buffer); // but read u2
    cpe.s1 = read16(buffer);
    return true;
  ...
  }
}
```

**Comment by thezhangwei** [comment]
Thanks for reporting the bug. Would you be interested in submitting a fixing patch?
