### ISSUE TITLE
How to resolve v37 not support error.

### ISSUE THREAD

**Issue by 123zhangmiao** [facebook/redex#702]
> Thank you for being patient. It's out of our regular work hours.
> 
> We are sorry if the error messages didn't make sense to you. It's finding dex v37 format magic number while it's expecting v35.
> 
> I have checked it for you and v37 support is not enabled in redex-all at this moment.

thanks, I know how to solve this problem

_Originally posted by @JuneLeo in https://github.com/facebook/redex/issues/398#issuecomment-487435425_

**Comment by NTillmann** [comment]
See #707.
