### ISSUE TITLE
Annotations instead of JSON. Would this feature be feasible?

### ISSUE THREAD

**Issue by bytehala** [facebook/redex#71]
Would annotations work for the leave-me-alone feature instead of having to feed a JSON file?

e.g.
`@CantTouchThis`

**Comment by bertmaher** [comment]
Great question!  In fact this feature already exists, we just haven't documented it yet ;-).  Create a config file as described in docs/Config.md, and add "keep_annotations" : [ "Lyour/annotations/CantTouchThis;" ] to the top level object, and anything in your project annotated with CantTouchThis will be left alone.  Hope that helps!  (Feel free to reopen if I've misunderstood what you're going for.)

I'll document this formally once I have a few minutes to update the configuration docs.
