### ISSUE TITLE
Questions on localDcePass

### ISSUE THREAD

**Issue by ufarooq** [facebook/redex#710]
Hi there,

I have a couple of questions/concerns about ``LocalDcePass``. 

1. As documented [here](https://github.com/facebook/redex/blob/main/service/local-dce/LocalDce.h#L50), liveness is a backward dataflow analysis, however, implementation is processing a CFG instead of a reversed CFG. Why is that?
2. This pass [documents](https://github.com/facebook/redex/blob/main/service/local-dce/LocalDce.h#L56) and also implements block traversal in post-order, which is not aligned with "Engineering a compiler" and several others, where authors recommend to perform reversed-post-order on reversed CFG. 

I am curious to know what are the assumptions/rationale here. 

Bests,
Umar

**Comment by NTillmann** [comment]
1. Our CFG has forward and backwards edges, and we can visit instructions in reverse order. I am not sure what else a "reversed CFG" would give you?
2. The fix point computation in LocalDce.cpp is indeed a bit simplistic. It's a left-over from an earlier time, before the Sparta framework brought us state-of-the-art data structures and fix point algorithms. There is a newer version of the LocalDce analysis (https://github.com/facebook/redex/blob/main/opt/object-sensitive-dce/UsedVarsAnalysis.cpp) build on top of Sparta, but it has never been augmented with the various special considerations have been added on to LocalDce.cpp over time. Maybe unifying that would bring some performance (and other wins), not entirely clear.

Overall, the performance of the LocalDce pass is quite reasonable, and we've found bigger offending performance fish elsewhere. But we do welcome code improvements if they bring benefits :-)
