### ISSUE TITLE
NPE error on WhatsApp

### ISSUE THREAD

**Issue by rushkii** [facebook/redex#711]
Hello, I found this error while opening a WhatsApp, [see image](https://i.ibb.co/3vQ95qY/image.png)

**Comment by beicy** [comment]
Thanks for reaching out. Can I ask how to reproduce the error? e.g. the version of WhatsApp, the device you are working on?

**Comment by rushkii** [comment]
> Thanks for reaching out. Can I ask how to reproduce the error? e.g. the version of WhatsApp, the device you are working on?

Never mind, it solved now after the new version of WhatsApp released.
