### ISSUE TITLE
Mac os Run autoreconf -ivf && ./configure && make error

### ISSUE THREAD

**Issue by qingguoguo** [facebook/redex#723]
please help me :

HOMEBREW_VERSION: 3.6.3
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: d5b6b068c15a8df60f0f5e34a4ca80dcf82c48e3
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4595d1e34786b57138517b1e69a40f5665cf0ec5
Core tap last commit: 83 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A

run :autoreconf -ivf && ./configure && make

In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:141:5: error: unknown type name 'locale'
    locale pubimbue(const locale& __loc) {
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:141:27: error: unknown type name 'locale'
    locale pubimbue(const locale& __loc) {
                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:149:5: error: unknown type name 'locale'
    locale getloc() const { return __loc_; }
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:153:48: error: unknown type name 'streamsize'
    basic_streambuf* pubsetbuf(char_type* __s, streamsize __n)
                                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:157:41: error: incomplete type 'std::ios_base' named in nested name specifier
    pos_type pubseekoff(off_type __off, ios_base::seekdir __way,
                                        ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:158:25: error: incomplete type 'std::ios_base' named in nested name specifier
                        ios_base::openmode __which = ios_base::in | ios_base::out)
                        ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:163:25: error: incomplete type 'std::ios_base' named in nested name specifier
                        ios_base::openmode __which = ios_base::in | ios_base::out)
                        ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:172:5: error: unknown type name 'streamsize'
    streamsize in_avail() {
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:200:5: error: unknown type name 'streamsize'
    streamsize sgetn(char_type* __s, streamsize __n)
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:200:38: error: unknown type name 'streamsize'
    streamsize sgetn(char_type* __s, streamsize __n)
                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:228:5: error: unknown type name 'streamsize'
    streamsize sputn(const char_type* __s, streamsize __n)
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:228:44: error: unknown type name 'streamsize'
    streamsize sputn(const char_type* __s, streamsize __n)
                                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:261:18: error: unknown type name 'streamsize'
    void __pbump(streamsize __n) { __nout_ += __n; }
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:271:30: error: unknown type name 'locale'
    virtual void imbue(const locale& __loc);
                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:274:53: error: unknown type name 'streamsize'
    virtual basic_streambuf* setbuf(char_type* __s, streamsize __n);
                                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:275:46: error: incomplete type 'std::ios_base' named in nested name specifier
    virtual pos_type seekoff(off_type __off, ios_base::seekdir __way,
                                             ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:276:30: error: incomplete type 'std::ios_base' named in nested name specifier
                             ios_base::openmode __which = ios_base::in | ios_base::out);
                             ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:278:30: error: incomplete type 'std::ios_base' named in nested name specifier
                             ios_base::openmode __which = ios_base::in | ios_base::out);
                             ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iosfwd:106:24: note: forward declaration of 'std::ios_base'
class _LIBCPP_TYPE_VIS ios_base;
                       ^
In file included from tools/redexdump/DumpTables.cpp:8:
In file included from ./libredex/DexDebugInstruction.h:14:
In file included from ./libresource/androidfw/Util.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/sstream:184:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/istream:163:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ostream:138:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:214:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:21:
In file included from ./libresource/androidfw/locale.h:23:
In file included from ./libresource/androidfw/ResourceTypes.h:25:
In file included from ./libresource/utils/String16.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:40:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/streambuf:282:13: error: unknown type name 'streamsize'
    virtual streamsize showmanyc();
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [tools/redexdump/DumpTables.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by dbueno** [comment]
I believe this is a conflict between redex and the standard library, caused by redex having a file named `Locale.h` in the include path (the file lives in `./libresource/androidfw`). In the stack trace the file is referred to by its lowercase name `./libresource/androidfw/locale.h`. Some C++ libraries look to include C's `locale.h`, but instead they're picking up the redex version.

This is due to Mac OS's case-insensitive filesystem.

**Comment by wsanville** [comment]
Thanks for the hint on this issue. We can rename the file.
