### ISSUE TITLE
AnonymousClassMergingPass build time error

### ISSUE THREAD

**Issue by fengruisd** [facebook/redex#724]
I am testing `AnonymousClassMergingPass` and IRTypeChecker report an issue
```
Lcom/demo/AnonMTestShape0S0000000; is not assignable to Lcom/demo/AnonymousClassMergingTest$1;
```
I tried to write a test class to reproduce the issue and print the IRCode
```
public abstract class AnonymousClassMergingTest {
    protected String m_str;
    abstract String method_a();
    abstract void method_b();

    public static AnonymousClassMergingTest create(int type) {
        if (type > 0) {
            return new AnonymousClassMergingTest() {
                @Override
                String method_a() {
                    return m_str + "test1";
                }
                @Override
                void method_b() {
                    System.out.println(method_a());
                }
            };
        } else {
            return new AnonymousClassMergingTest() {
                @Override
                String method_a() {
                    return m_str + "test2";
                }
                @Override
                void method_b() {
                    Log.d("tag", method_a());
                }
            };
        }
    }
}
```
IRCode
```
Lcom/demo/AnonMTestShape0S0000000;.method_a:(Lcom/demo/AnonMTestShape0S0000000;)Ljava/lang/String;
[0x7fb819ebd100] OPCODE: IOPCODE_LOAD_PARAM_OBJECT v2
[0x7fb819ebdd80] POSITION: Lcom/demo/AnonymousClassMergingTest$1;.method_a:()Ljava/lang/String;(AnonymousClassMergingTest.java:18)
[0x7fb819ebde40] OPCODE: NEW_INSTANCE Ljava/lang/StringBuilder;
[0x7fb819ebdaa0] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v0
[0x7fb819ebde60] OPCODE: INVOKE_DIRECT v0, Ljava/lang/StringBuilder;.<init>:()V
[0x7fb819ebd260] OPCODE: IGET_OBJECT v2, Lcom/demo/AnonymousClassMergingTest$1;.m_str:Ljava/lang/String;
[0x7fb819ebdb60] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7fb819ebd280] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
[0x7fb819ebd720] OPCODE: CONST_STRING "test1"
[0x7fb819ebdc20] OPCODE: IOPCODE_MOVE_RESULT_PSEUDO_OBJECT v1
[0x7fb819ebd740] OPCODE: INVOKE_VIRTUAL v0, v1, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
[0x7fb819ebd840] OPCODE: INVOKE_VIRTUAL v0, Ljava/lang/StringBuilder;.toString:()Ljava/lang/String;
[0x7fb819ebd860] OPCODE: MOVE_RESULT_OBJECT v0
[0x7fb819ebd960] OPCODE: RETURN_OBJECT v0
```
I think ReDex does not replace the protected field correctly at [0x7fb819ebd260], the similar situation also happens with protected method

**Comment by thezhangwei** [comment]
Can you try running `ResolveRefsPass` before AnonCM?

**Comment by thezhangwei** [comment]
FYI this will be announced on fbredex.com soon.

!!! Redex Public Office Hour Coming on Tue. 10/11/2022 @2PM PST !!!
[Zoom Meeting id: 998 3966 9035; passcode: 456804](https://fb.zoom.us/j/99839669035?pwd=NHJIMjFUc2NXbnVuTk5rR1VXUkozUT09)
Please dial in to chat! We would love to learn how do you use Redex, what challenges are
you facing, and how can we better help. We would like keep the 1st office hour to be more
high level. If you have very specific questions, like how to build Redex, Github issue is still
the best way to resolve it.

**Comment by fengruisd** [comment]
@thezhangwei , I only enabled AnonymousCM before and `ResolveRefsPass` can solve part of the problem, but `ResolveRefsPass` does not resolve refs which the definition is external, so if the parent of the anonymous class is an external class, the problem still exits
```
    public static void test(View view1, View view2) {
        view1.setAnimation(new Animation() { /// <----- external class
            public void annoTest(int i) {
                this.setDuration(i);
                this.setFillAfter(i > 10);
            }
        });
        view2.setAnimation(new Animation() {
            public void annoTest(int i) {
                this.setDuration(i + 20);
                this.setFillAfter(i > 100);
            }
        });
    }
```

**Comment by thezhangwei** [comment]
Can you be a bit more explicit about which reference in your above example is a problem?

If a method ref can only be resolved to an external method definition at runtime, `ResolveRefsPass` will resolve it to the more specific external ref based on local type information. You might have to enable the `refine_to_external` option. I'm not entirely sure about that. But I don't see how your example will become invalid after AnonCM.

**Comment by fengruisd** [comment]
I successfully build the package after enabling `refine_to_external`, thanks !
