### ISSUE TITLE
how to insert log or some code to methods

### ISSUE THREAD

**Issue by javaeryang** [facebook/redex#729]
somtimes we need find method call process, if we can insert code to all method(before or end of method),that is good

**Comment by NTillmann** [comment]
While there's no existing generic pass to do arbitrary instrumentation, we do have some passes that do targeted instrumentation at the beginning and end of methods. Take a look here, and see if you can tweak it for your needs: https://github.com/facebook/redex/blob/main/opt/instrument/Instrument.cpp#L95

**Comment by javaeryang** [comment]
@NTillmann thank you
