### ISSUE TITLE
Is there a pass to solve the following dead code？

### ISSUE THREAD

**Issue by fa1conn** [facebook/redex#730]
for example
```
      if (Integer.parseInt("0") != 0) {
          i8 = 0;
          i7 = 0;
          columnName = null;
      } else {
          i7 = 28;
          i8 = 93;
      }
```

**Comment by ssj933** [comment]
We don't have a pass currently do this. Seems like something that can be added to constant propagation.

**Comment by NTillmann** [comment]
This commit can serve as a template for how you could plug logic for `Integer.parseInt`: https://github.com/facebook/redex/commit/25593e1f25cdaddf56b7e00d9b9b085415043029

**Comment by fa1conn** [comment]
> This commit can serve as a template for how you could plug logic for `Integer.parseInt`: [25593e1](https://github.com/facebook/redex/commit/25593e1f25cdaddf56b7e00d9b9b085415043029)

Thanks，I used newest redex to test the String.equals by using ConstantPropagationPass, but it doesn't work. How to make it work?

**Comment by fa1conn** [comment]
> This commit can serve as a template for how you could plug logic for `Integer.parseInt`: [25593e1](https://github.com/facebook/redex/commit/25593e1f25cdaddf56b7e00d9b9b085415043029)

For Boolean.valueOf, It is Effective by using CommonSubexpressionEliminationPass. 
For String.equals, It maybe Effective by using peepholePass. It depond on bytecode order matching. If there is some bytecode that interferes with the order it will not be recognized.
And I used ConstantPropagationPass, I found it It doesn't call StringAnalyzer::analyze_invoke function. Does it require additional configuration, or what conditions need to be met to trigger it?

**Comment by NTillmann** [comment]
> ConstantPropagationPass, but it doesn't work

Right, good observation. The `ConstantPropagationPass` only uses the `PrimitiveAnalyzer` by default. Other more sophisticated passes use multiple analyzers include the `StringAnalyzer`, e.g. the `InterproceduralConstantPropagationPass`, and `ShrinkerPass` (which basically runs several local optimizations concurrently, which is faster than running individual local optimizations sequentially), and many other passes that (can) use shrinking as part of their operations, e.g. the `MethodInlinePass`, the `IntraDexInlinePass`.

I'll look into upgrading `ConstantPropagationPass` and will report back on that.

**Comment by NTillmann** [comment]
This would upgrade ConstantPropagationPass to also use the StringAnalyzer (and various other analyzers): https://github.com/facebook/redex/pull/733 

However, by itself, it doesn't seem to add much value, just makes the build a bit slower, and by changing some local decisions it may regress the final size a bit. So I am not planning on merging that right now. But you could use it locally if it helps you.

**Comment by fa1conn** [comment]
> This would upgrade ConstantPropagationPass to also use the StringAnalyzer (and various other analyzers): #733
> 
> However, by itself, it doesn't seem to add much value, just makes the build a bit slower, and by changing some local decisions it may regress the final size a bit. So I am not planning on merging that right now. But you could use it locally if it helps you.

Thank you very much!
