### ISSUE TITLE
Is this normal for MethodInlinePass?

### ISSUE THREAD

**Issue by fa1conn** [facebook/redex#737]
For example, I have two class
MainActivity.java
```
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Utils utils = new Utils();
        System.out.println(utils.get_str());
        System.out.println(utils.get_str2("aaa"));
    }
}
```
Utils.java
```
public class Utils {
    public String get_str(){
        return "kkk";
    }
    public String get_str2(String str){
        return "kkk"+str;
    }
}
```
I thought MethodInlinePass would inline the get_str and get_str2 methods, but the MainActivity class didn't change after running redex. I don't know if this is normal because the documentation is not detailed enough. I used config/default.config, does it require additional configuration?

**Comment by NTillmann** [comment]
I dropped your code into a local test environment, and Redex did inline both methods for me, with no particular configuration. 
Some reasons why it's not inlining them for you:
- the inliner gives up if you have no (ProGuard) keep rules set up.
- `get_str2` is a rather large method. If there are more callosities, then the inliner's cost function would like determine that it's not a good trade-off to inline.

**Comment by fa1conn** [comment]
> I dropped your code into a local test environment, and Redex did inline both methods for me, with no particular configuration. Some reasons why it's not inlining them for you:
> 
> * the inliner gives up if you have no (ProGuard) keep rules set up.
> * `get_str2` is a rather large method. If there are more callosities, then the inliner's cost function would like determine that it's not a good trade-off to inline.

I configure the proguard-android-optimize.txt and successfully make it. Thank you very much! But I still feel that the documentation is not detailed enough that I need to look at the source code frequently. It is undeniable that redex is a good product!
