### ISSUE TITLE
zip align config in my-zsh

### ISSUE THREAD

**Issue by githubchen001** [facebook/redex#74]
hello,in my .zshrc file I declared the path:ANDROID_SDK=/path/to/android/sdk redex [... arguments ...]

but the command show .zshrc: bad pattern: [...        how to solve it   

the

**Comment by arifnadeem7** [comment]
Add build-tools to your PATH  in .zshrc like so "export PATH=$ANDROID_HOME/build-tools/23.0.2:$PATH"

**Comment by VenomVendor** [comment]
#28

**Comment by githubchen001** [comment]
it works fine   ths
