### ISSUE TITLE
How to merge/inject classes to a dex?

### ISSUE THREAD

**Issue by DavidFaermanPendo** [facebook/redex#741]
Hello,
I did my best to find a forum o another way to ask...
Can I use redex to inject classes or merge 2 dex files? 
If yes can you please point me to some documentation or link?
if there is a better forum to ask please point me there.
Thanks!!!!!!

**Comment by agampe** [comment]
It is unclear what you mean by "inject or merge classes." You can always just add a dex file to an APK and the classes become available. Will Redex help then shrinking the APK, possibly moving the classes? Yes.

**Comment by DavidFaermanPendo** [comment]
ok, I am moving forward to generate the dex file and I am getting 100K errors that it is not finding some libs that are in the Gradle file but I am not setting it in the command line. 
Any ideas on how to make this easier are super welcome.
Thanks

**Comment by DavidFaermanPendo** [comment]
@agampe hey, thanks!!! 
Your answer really helps me.
Will close this and ask a new question!
How to remove a specific class from dex files...
