### ISSUE TITLE
remove specific package or classes from dex files

### ISSUE THREAD

**Issue by DavidFaermanPendo** [facebook/redex#756]
Hello, I have a bunch of dex files, and I need to remove a specific package (and all the classes inside) or a list of classes.
Is there any way to achieve this?
If there is no out-of-the-box, can you point me to some material where I can read about this?
Or if this can be achieved by creating a new pass can you point me to where should I start? I have some CPP knowledge (basic) and I am not afraid to try. 

Maybe is there a way to tell to one of the passes that some class is not used? 

or... if I get the smali code and eliminate the calls to a class then redex will remove it from the dex? 
Thanks!!!

**Comment by agampe** [comment]
There is no existing pass to do that, but it isn't hard to do.

When you write your pass, you override [`run_pass`](https://github.com/facebook/redex/blob/54d6ee7147d221b8c6cdc40a4a00f8cd0ea3b4d0/libredex/Pass.h#L58). A `DexStoresVector` is passed in that contains the currently "active" classes. If you remove a class from this, it will no longer be tracked (and emitted at the end).
