### ISSUE TITLE
why resource was deleted some files after redex?

### ISSUE THREAD

**Issue by fdh19979** [facebook/redex#770]
config is below：
{
"redex" : {
  "passes" : [
    "ReBindRefsPass",
    "BridgeSynthInlinePass",
    "FinalInlinePassV2",
    "DelSuperPass",
    "SingleImplPass",
    "MethodInlinePass",
    "StaticReloPassV2",
    "RemoveEmptyClassesPass",
    "ShortenSrcStringsPass",
    "RegAllocPass"
  ]
}
}

after redex , output.apk's resource was deleted about 3mb , output.apk can install , but can not start.

how can I keep all resource files？

![image](https://user-images.githubusercontent.com/25642829/223312781-f4c42ee4-9190-4af5-b916-94343b55840d.png)

**Comment by wsanville** [comment]
With that config I wouldn't expect anything in res to get removed intentionally, unless something unusual like files with the same name but different casing is getting messed up by unpacking/repacking the apk on a case sensitive filesystem. That's just a guess of course but if you are willing to share details on which files have gone missing that could help sort this out sooner.

**Comment by thezhangwei** [comment]
Hi @fdh19979 do you need more assistance on this question pls?
