### ISSUE TITLE
run autoreconf -ivf && ./configure && make failed

### ISSUE THREAD

**Issue by ffdsss** [facebook/redex#790]
In file included from analysis/max-depth/MaxDepthAnalysis.cpp:8:0:
analysis/max-depth/MaxDepthAnalysis.h: In member function ‘virtual redex_properties::PropertyInteractions MaxDepthAnalysisPass::get_property_interactions() const’:
analysis/max-depth/MaxDepthAnalysis.h:22:51: sorry, unimplemented: non-trivial designated initializers not supported
     return {{HasSourceBlocks, {.preserves = true}}};
                                                   ^
Makefile:6649: recipe for target 'analysis/max-depth/MaxDepthAnalysis.lo' failed
make[2]: *** [analysis/max-depth/MaxDepthAnalysis.lo] Error 1
make[2]: 离开目录“/home/abc/桌面/redex-main”
Makefile:6798: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: 离开目录“/home/abc/桌面/redex-main”
Makefile:7095: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by agampe** [comment]
What version of Linux and compiler toolchain are you using? The minimum requirements are able to compile just fine, according to CircleCI continuous builds.

**Comment by ffdsss** [comment]
Ubuntu 18.04.6 LTS

**Comment by ffdsss** [comment]
> What version of Linux and compiler toolchain are you using? The minimum requirements are able to compile just fine, according to CircleCI continuous builds.

Ubuntu 18.04.6 LTS

**Comment by agampe** [comment]
Is this still happening? Our CircleCI bot for 18.04 does not have this issue.

**Comment by ffdsss** [comment]
> Is this still happening? Our CircleCI bot for 18.04 does not have this issue.

Yes, I reinstalled ubuntu in the virtual machine, and this error is still prompted. Where can I see the log

**Comment by agampe** [comment]
> Yes, I reinstalled ubuntu in the virtual machine, and this error is still prompted. Where can I see the log

[CircleCI pipeline](https://app.circleci.com/pipelines/github/facebook/redex)

Actively compiles for 18.04.My guess is that your Ubuntu isn't installing the right `g++`. I might misremember, but I think 18.04 supported two GCC versions over its lifetime.

We will remove 18.04 soon-ish (it's no longer supported upstream). Please move to a supported Ubuntu or Debian version (or a docker container).
