### ISSUE TITLE
make failed.

### ISSUE THREAD

**Issue by wys619** [facebook/redex#819]
* final log like this:

```
7 errors generated.
make[2]: *** [tools/common/redex_all-ToolsCommon.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

```

* details in attached file.

[log.txt](https://github.com/facebook/redex/files/12181319/log.txt)

* my os version.
macOS 13.4.1

**Comment by flashch** [comment]
I got the same error

**Comment by maiwenchang** [comment]
+1, how to resove it

**Comment by maiwenchang** [comment]
same error, how to resolve it?

**Comment by sunzhibindev** [comment]
same error, how to resolve it?

**Comment by sunzhibindev** [comment]
**maybe :**
# Assume you are in redex directory
mkdir build-cmake
cd build-cmake
# .. is the root source directory of Redex
cmake ..

make
