### ISSUE TITLE
ZipManager did not unpack expected number of files; is this a case insensitive file system? Potentially conflicting files

### ISSUE THREAD

**Issue by larryyli** [facebook/redex#831]
![微信图片_20231205204117](https://github.com/facebook/redex/assets/152982736/df82f3f9-697b-45a4-893f-5246bfa7e419)
System:Windows

**Comment by wsanville** [comment]
This message is here to tell you that you are running on a case insensitive file system, and the unpacking logic does not today handle the case of an apk that has many files that vary in case. Please see the suggestions at https://github.com/facebook/redex/issues/822#issuecomment-1684471499 for workarounds.
