### ISSUE TITLE
037 for support_dex_version 35

### ISSUE THREAD

**Issue by zhangruidongs** [facebook/redex#837]
How should I solve this problem？
][2024-01-17 14:49:39,426][root                     ] expected str, bytes or os.PathLike object, not NoneType
TRACE_CLASS_FILE=
TRACE_CLASS_NAME=
Trace settings:
TRACEFILE=
SHOW_TIMESTAMPS=
SHOW_TRACEMODULE=
TRACE_METHOD_FILTER=
        Parsed ProGuard config file completed in 0.0 seconds
terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
  what():  libredex/DexLoader.cpp:60: void validate_dex_header(const dex_header*, size_t, int): assertion `supported' failed.
Bad dex magic dex
037 for support_dex_version 35

/home/ruidong/redex/redex-all(_Z23crash_backtrace_handleri+0x44)[0x55a518b1d4d4]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fed91042520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fed910969fc]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fed91042476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7fed910287f3]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2b9e)[0x7fed914a2b9e]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c)[0x7fed914ae20c]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277)[0x7fed914ae277]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xae4d8)[0x7fed914ae4d8]
/home/ruidong/redex/redex-all(+0x4263cc)[0x55a51836d3cc]
/home/ruidong/redex/redex-all(_ZN9DexLoader8load_dexEPKcP11dex_stats_ti+0x1ec)[0x55a518b766cc]
/home/ruidong/redex/redex-all(_Z21load_classes_from_dexPK11DexLocationP11dex_stats_tbbi+0x71)[0x55a518b785b1]
/home/ruidong/redex/redex-all(_ZN5redex36load_classes_from_dexes_and_metadataERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERS0_I8DexStoreSaISB_EER11dex_stats_tRS0_ISF_SaISF_EE+0xc64)[0x55a518a8b0d4]
/home/ruidong/redex/redex-all(+0xb4dd21)[0x55a518a94d21]
/home/ruidong/redex/redex-all(_Z27run_rethrow_first_aggregateRKSt8functionIFvvEE+0x2c)[0x55a518ab2c9c]
/home/ruidong/redex/redex-all(+0xb53f90)[0x55a518a9af90]
/home/ruidong/redex/redex-all(main+0x8d6)[0x55a5184396c6]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fed91029d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fed91029e40]
/home/ruidong/redex/redex-all(_start+0x25)[0x55a518467ab5]

/home/ruidong/redex/redex-all(_Z23crash_backtrace_handleri+0x44)[0x55a518b1d4d4]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7fed910969fc]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7fed91042476]
/home/ruidong/redex/redex-all(+0x4263cc)[0x55a51836d3cc]
/home/ruidong/redex/redex-all(_ZN9DexLoader8load_dexEPKcP11dex_stats_ti+0x1ec)[0x55a518b766cc]
/home/ruidong/redex/redex-all(_Z21load_classes_from_dexPK11DexLocationP11dex_stats_tbbi+0x71)[0x55a518b785b1]
/home/ruidong/redex/redex-all(_ZN5redex36load_classes_from_dexes_and_metadataERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERS0_I8DexStoreSaISB_EER11dex_stats_tRS0_ISF_SaISF_EE+0xc64)[0x55a518a8b0d4]
/home/ruidong/redex/redex-all(+0xb4dd21)[0x55a518a94d21]
/home/ruidong/redex/redex-all(_Z27run_rethrow_first_aggregateRKSt8functionIFvvEE+0x2c)[0x55a518ab2c9c]
/home/ruidong/redex/redex-all(+0xb53f90)[0x55a518a9af90]
/home/ruidong/redex/redex-all(main+0x8d6)[0x55a5184396c6]
/home/ruidong/redex/redex-all(_start+0x25)[0x55a518467ab5]
Traceback (most recent call last):
  File "/home/ruidong/redex/redex.py", line 1499, in <module>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/home/ruidong/redex/pyredex/utils.py", line 65, in with_temp_cleanup
    fn()
  File "/home/ruidong/redex/redex.py", line 1499, in <lambda>
    with_temp_cleanup(lambda: run_redex(args), args.always_clean_up)
  File "/home/ruidong/redex/redex.py", line 1465, in run_redex
    run_redex_binary(state, exception_formatter, output_line_handler)
  File "/home/ruidong/redex/redex.py", line 408, in run_redex_binary
    run()
  File "/home/ruidong/redex/redex.py", line 401, in run
    raise RedexRunException(msg, returncode, abort_error, symbolized)
__main__.RedexRunException: redex-all crashed with exit code -6!
 terminate called after throwing an instance of 'boost::exception_detail::error_info_injector<RedexException>'
   what():  libredex/DexLoader.cpp:60: void validate_dex_header(const dex_header*, size_t, int): assertion `supported' failed.
 Bad dex magic dex
 037 for support_dex_version 35 You can re-run it under gdb by running /tmp/redex-gdb-5lu0_qbf.sh or under lldb by running /tmp/redex-lldb-thhrnxgv.sh

**Comment by wsanville** [comment]
We have an open issue for the enhancement for supporting dex 037 https://github.com/facebook/redex/issues/401. We do not have an ETA for this, but you can search around the other issues for some more context.
