### ISSUE TITLE
i had remove the config tag ""BridgePass",but the app Process has died after the attachBaseContext

### ISSUE THREAD

**Issue by dssljt** [facebook/redex#85]
I used the command "sudo redex -c config/default.config -o ~/Mytest.apk ~/test.apk" , creat a new apk and app structure is no problem,but the Process has died after the attachBaseContext

Log:
V/uitechno.launcher( 1015): C://intent == Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=Mytest/.MainActivity bnds=[8,554][178,794] }
I/ActivityManager( 917): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=Mytest/.MainActivity bnds=[8,554][178,794]} from pid 1015
I/ActivityManager( 917): Start proc Mytest for activity Mytest/.MainActivity: pid=12398 uid=10082 gids={50082, 3003, 1015, 3002, 3001, 1028}
I/Environment(12398): getPrimaryVolume info:ApplicationInfo{4216f6c8 Mytest},packagename:Mytest,UserId:0
E/AndroidRuntime(12398): at com.Mytest.common.BaseApplication.attachBaseContext
E/AndroidRuntime(12398): at Mytest.MyApplication.attachBaseContext
W/ActivityManager( 917): Force finishing activity Mytest/.MainActivity
I/WindowManager( 917): Screenshot max retries 4 of Token{434397e0 ActivityRecord{43439690 u0 Mytest/.MainActivity}} appWin=Window{423054f0 u0 Starting Mytest} drawState=4
W/ActivityManager( 917): Activity pause timeout for ActivityRecord{43439690 u0 Mytest/.MainActivity}
I/ActivityManager( 917): Process Mytest (pid 12398) has died.

**Comment by bertmaher** [comment]
It's not obvious to me why redex would have caused this problem.  Can you upload your test APK (before and after redex would be ideal)?

**Comment by justinjhendrick** [comment]
closing due to age
