### ISSUE TITLE
redex-all is not found or is not executable

### ISSUE THREAD

**Issue by figofuture** [facebook/redex#88]
after exec redex xxx.apk -o redex.apk, it tells me "redex-all is not found or is not executable", but the redex-all is in the PATH, I can exec it separately. My device is MacPro

**Comment by w4lle** [comment]
I have this issue becuase I run this `` redex ***.apk redex.apk``
exec this ``redex xxx.apk -o redex.apk`` it`s ok.

**Comment by john990** [comment]
@w4lle  It's work!!    thx.

**Comment by figofuture** [comment]
yes, worked, thx.
