### ISSUE TITLE
run autoreconf -ivf && ./configure && make failed

### ISSUE THREAD

**Issue by LiuFreedom** [facebook/redex#898]
MacOs 12.7.6 intel 
autoconf: 2.72 
automake: 1.17 
xcode-select version 2395

libredex/ClassUtil.cpp:78:52: error: constexpr variable cannot have non-literal type 'const std::array<std::string_view, 2>' (aka 'const array<basic_string_view<char>, 2>')
  static constexpr std::array<std::string_view, 2> patterns = {
                                                   ^
libredex/ClassUtil.cpp:78:52: error: implicit instantiation of undefined template 'std::array<std::string_view, 2>'
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;

2 errors generated.
make[2]: *** [libredex/ClassUtil.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

details in attached file.

[log.txt](https://github.com/user-attachments/files/16958929/log.txt)

**Comment by itang00** [comment]
Could you try adding `#include <array>` to ClassUtil.cpp ?

**Comment by LiuFreedom** [comment]
> Could you try adding `#include <array>` to ClassUtil.cpp ?

add `#include <array>` will be ok, Many cpp files do not add this

Do you know why `make[5]: /build-tools/29.0.3/aapt2: No such file or directory`
I checked that this path exists and I have configured the android_home environment variable

**Comment by chejdj** [comment]
> > Could you try adding `#include <array>` to ClassUtil.cpp ?
> 
> add `#include <array>` will be ok, Many cpp files do not add this
> 
> Do you know why `make[5]: /build-tools/29.0.3/aapt2: No such file or directory` I checked that this path exists and I have configured the android_home environment variable

How to resolve "aapt2" not found

**Comment by chejdj** [comment]
GET IT

test/samples/strings/Makefile
```
AAPT2 = $(ANDROID_SDK)/build-tools/29.0.2/aapt2
```

check the  path whether exists
