### ISSUE TITLE
after using redex, ouput is bigger than origin apk file.

### ISSUE THREAD

**Issue by figofuture** [facebook/redex#92]
after using redex, ouput is bigger than origin apk file.

**Comment by visualfanatic** [comment]
From [CONTRIBUTING.md](https://github.com/facebook/redex/blob/49f9e3446d7c68b4a29f16fd14fc334bd4bb4b86/CONTRIBUTING.md#issues):
> Please ensure your description is clear and has sufficient instructions to be able to reproduce the issue.

**Comment by bertmaher** [comment]
It's possible, depending on the exact nature of your APK.  You might want to look at the size of the dexes contained in the APK:
```
aapt list -v YOUR_INPUT.apk | grep ".dex"
```
Those will almost always be smaller after redex, but I can't guarantee it.

**Comment by zjinpeng** [comment]
Me too.
63.5m->63.7m
