### ISSUE TITLE
check test fail

### ISSUE THREAD

**Issue by Grown** [facebook/redex#94]
DevdeiMac:test dev$ make check
Making check in .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  libgtest_main.la
make[2]: *** No rule to make target `gtest-1.7.0/src/gtest-all.cc', needed by `gtest-1.7.0/src/libgtest_main_la-gtest-all.lo'.  Stop.
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

That's my problem!Does any one have some problem?

**Comment by bertmaher** [comment]
To run the tests properly, you need to do: `./test/setup.sh && cd test && make check`.  This is in the README.
